# A1+A2: свип данных × моделей (ROADMAP A; гипотеза: CRL-Prompt —
# low-resource метод, его вклад виден при малых данных/малой модели)

Дизайн: {MLE, mask, RL} × размеры {250/500/1000/[6000]} × 3 сида,
**без probe** — общий СЛУЧАЙНЫЙ старт на (модель, сид) переиспользуется
всеми конфигами и размерами (парность 2 уровней). Протокол/код — копии
experiment.ipynb (D1-классификация; датасет статьи). 6000-точка для 3B
берётся из готового D1.6 (n=7 сидов) — не перезапускается.

Время: 3B ~5.5 ч + 0.5B ~2.5 ч. Resume-safe (results.json на прогон).
Сетка/hипотезы зафиксированы априори; все ячейки в отчёт (не p-hacking).

Порядок: сверху вниз (инфраструктура = копии ячеек experiment.ipynb,
дальше свип-блок).

In [2]:
import time, os, gc

os.environ["PYTORCH_CUDA_ALLOC_CONF"] = "expandable_segments:True"
# CUBLAS_WORKSPACE_CONFIG НЕ включаем: окружение новых сидов должно
# совпадать с завершёнными прогонами (смешивать числовые среды между
# сидами таблицы не хотим); детерминизм уже показан эмпирически
# (каузальный тест, §5.5: бит-в-бит воспроизведение)

# ============================================================
# CELL 1: Imports
# ============================================================
import torch
import torch.nn.functional as F
from torch.distributions import Normal
from torch.utils.data import DataLoader

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    TrainerCallback,
    get_cosine_schedule_with_warmup,
    set_seed,
)
from peft import PrefixTuningConfig, TaskType, get_peft_model
from datasets import load_dataset

import numpy as np
import evaluate

print(f"torch: {torch.__version__}")
print(f"CUDA available: {torch.cuda.is_available()}")
if torch.cuda.is_available():
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    vram_gb = torch.cuda.get_device_properties(0).total_memory / (1024**3)
    print(f"VRAM: {vram_gb:.1f} GB")

<VENV>/lib/python3.14/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

torch: 2.11.0+cu128
CUDA available: True
GPU: NVIDIA GeForce RTX 5060 Ti
VRAM: 15.5 GB

In [3]:
# ============================================================
# CELL 2: Config — исследование-2, итерация D1.6
# Апгрейд по итогам внешней критики:
#   1) модель 1.5B -> 3B (реально крупнее статьи);
#   2) настоящий батч 8x1 вместо 1x8 (последовательности ~100 токенов);
#   3) ЧИСТЫЙ eval: вход больше НЕ содержит золотую метку (баг D1.x:
#      generate() продолжал ЗОЛОТУЮ метку — «предсказание» было эхом);
#   4) вербализатор-скоринг (протокол статьи: top-scoring output token);
#   5) per-example корректности -> парный бутстреп (стат. мощность);
#   6) жёсткие негативы для wrong_label (путаемые группы эмоций);
#   7) значения статьи β=0.3, τ=0.1 отдельным конфигом.
# ============================================================
class CFG:
    # ---- 1. Core
    seed = 42
    output_dir = "./gen_dialogue_ed_full"

    gradient_checkpointing = False
    use_cache = True
    bf16 = True
    fp16 = False

    # ---- 2. Model / PEFT
    # D1.6: Qwen2.5-3B (~6.2 ГБ bf16) — заметно крупнее Falcon-rw-1b
    # из статьи (критика: 1.5B был тем же классом). Влезает в 16 ГБ
    # с батчем 8 при seq ~110.
    model_name = "Qwen/Qwen2.5-3B"
    trust_remote_code = True
    peft_kind = "prefix_tuning"
    peft_method = "prefix_tuning"
    num_virtual_tokens = 20
    prefix_projection = True

    # Probe = ГЕНЕРАТОР общего старта
    init_selection_inits = 4
    init_selection_probe_steps = 200

    # ---- 3. Task / Dataset
    task_kind = "emotion_cls"
    dataset_repo = "empathetic_dialogues"
    dataset_revision = "refs/convert/parquet"
    dataset_name = None  # легаси XSum удалено (критика-2: техдолг);
                         # ветка не-cls сейчас не используется

    text_column = "text"
    target_column = "label"

    train_size = 6000
    val_size = 200
    test_size = 500

    max_source_len = 96
    max_target_len = 8
    max_total_len = max_source_len + max_target_len

    prompt_template = "Situation: {source}\nEmotion:"
    padding_side = "left"

    eval_max_new_tokens = 6
    gen_max_new_tokens = 6

    if task_kind == "emotion_cls":
        eval_metrics = ["accuracy", "verb_accuracy"]
    else:
        eval_metrics = ["rouge1", "rouge2", "rougeL"]

    # ---- 4. Schedule
    # D1.6: настоящий батч 8 x accum 1 (та же эффективная партия 8,
    # но GPU-утилизация вместо цикла микробатчей — прогоны в разы
    # быстрее; статистика градиента та же, аккумулирование == батчингу).
    # Эпох 4: 3B сходится быстрее, best-эпохи в D1.5 были 1-3.
    phase1_epochs = 4
    total_epochs = 4
    batch_size = 8
    eval_batch_size = 8
    gradient_accumulation_steps = 1

    learning_rate = 5e-4
    phase2_lr = 1e-4
    weight_decay = 0.0
    warmup_steps = 200

    lr_scheduler = "cosine"
    max_grad_norm = 1.0
    logging_steps = 10
    eval_strategy = "epoch"
    save_strategy = "epoch"
    save_total_limit = 1
    load_best_model_at_end = False
    remove_unused_columns = False
    dataloader_pin_memory = True
    report_to = "none"

    # ---- 5. Reward
    gen_do_sample = False
    gen_temperature = 0.7
    gen_top_p = 0.9
    reward_metric = "accuracy"

    # ---- 6. Contrast
    alpha = 1.0
    beta = 0.1
    contrast_mode = "mask"
    contrast_from_start = True
    contrastive_dropout = 0.1
    contrastive_tau = 0.5
    k_negatives = 1

    gamma = 2e-5
    gamma_auto = True
    gamma_target_frac = 0.3
    sigma = 0.02
    rl_interval = 50
    rl_num_batches = 16
    rl_subset_size = max(16, int(train_size * 0.1))
    use_reward_baseline = True

    divergence_ce_threshold = 8.0
    guard_start_step = 100

    # D1.6: отбор лучшей эпохи по ВСЕМ 200 val-примерам (было 64)
    val_rouge_examples = 200


cfg = CFG()

assert cfg.peft_method == "prefix_tuning"
assert cfg.gradient_checkpointing is False

print("Config OK (D1.6)")
print(f"Model: {cfg.model_name}  <-- апгрейд 1.5B -> 3B")
print(f"Task: {cfg.task_kind} | metrics: {cfg.eval_metrics}")
print(f"PEFT: {cfg.peft_kind} (prefix_projection={cfg.prefix_projection})")
print(f"Dataset: {cfg.dataset_repo} @ {cfg.dataset_revision}")
print(f"Train {cfg.train_size} | val {cfg.val_size} (полная, отбор эпохи) | test {cfg.test_size}")
print(f"Batch: {cfg.batch_size} x accum {cfg.gradient_accumulation_steps} (настоящий батч)")
print(f"Epochs: {cfg.total_epochs} (одна фаза, контраст с 1-й эпохи)")
print(f"LR: {cfg.learning_rate}, warmup: {cfg.warmup_steps}")
print(f"Contrast: mode={cfg.contrast_mode}, beta={cfg.beta}, tau={cfg.contrastive_tau}")
print(f"Eval: ЧИСТЫЙ (без золотой метки во входе) + вербализатор")

Config OK (D1.6)
Model: Qwen/Qwen2.5-3B  <-- апгрейд 1.5B -> 3B
Task: emotion_cls | metrics: ['accuracy', 'verb_accuracy']
PEFT: prefix_tuning (prefix_projection=True)
Dataset: empathetic_dialogues @ refs/convert/parquet
Train 6000 | val 200 (полная, отбор эпохи) | test 500
Batch: 8 x accum 1 (настоящий батч)
Epochs: 4 (одна фаза, контраст с 1-й эпохи)
LR: 0.0005, warmup: 200
Contrast: mode=mask, beta=0.1, tau=0.5
Eval: ЧИСТЫЙ (без золотой метки во входе) + вербализатор

In [4]:
# ============================================================
# CELL 3: Data loading & tokenization
# D1.6: жёсткие негативы wrong_label из групп путаемых эмоций
# (критика D1.5: случайная чужая метка слишком легка) + первые
# токены меток для вербализатор-скоринга
# ============================================================
import re
import random
from huggingface_hub import hf_hub_download, list_repo_files
from datasets import Dataset as HFDataset

tok = AutoTokenizer.from_pretrained(cfg.model_name, trust_remote_code=True)
tok.padding_side = cfg.padding_side

if tok.pad_token is None:
    tok.pad_token = tok.eos_token
    tok.pad_token_id = tok.eos_token_id

if cfg.task_kind == "emotion_cls":
    def load_ed_episodes(split):
        """ED — script-датасет, новыми datasets не грузится; читаем
        parquet-конвертацию с Hub. Эпизоды = уникальные conv_id."""
        files = list_repo_files(cfg.dataset_repo, repo_type="dataset",
                                revision=cfg.dataset_revision)
        names = sorted(f for f in files
                       if f.startswith(f"default/{split}/") and f.endswith(".parquet"))
        assert names, f"нет parquet-шардов для split={split}"
        paths = [hf_hub_download(cfg.dataset_repo, n, repo_type="dataset",
                                 revision=cfg.dataset_revision) for n in names]
        ds = load_dataset("parquet", data_files=paths, split="train")
        episodes, seen = [], set()
        for r in ds:
            cid = r["conv_id"]
            if cid in seen:
                continue
            seen.add(cid)
            text, label = r["prompt"].strip(), r["context"].strip()
            if text and label:
                episodes.append({"text": text, "label": label})
        return episodes

    ed_train_full = load_ed_episodes("train")
    ed_val_full = load_ed_episodes("validation")
    ed_test_full = load_ed_episodes("test")
    print(f"ED episodes: train {len(ed_train_full)} | "
          f"val {len(ed_val_full)} | test {len(ed_test_full)}")

    emotion_labels = sorted({e["label"] for e in ed_train_full})
    assert len(emotion_labels) == 32, f"ожидалось 32 эмоции, есть {len(emotion_labels)}"

    def _norm(s):
        return re.sub(r"[^a-z ]", "", s.lower()).strip()

    EMOTION_BY_NORM = {_norm(l): l for l in emotion_labels}

    def match_emotion(text):
        g = _norm(text)
        if not g:
            return None
        first = g.split()[0]
        if first in EMOTION_BY_NORM:
            return EMOTION_BY_NORM[first]
        if g in EMOTION_BY_NORM:
            return EMOTION_BY_NORM[g]
        for nl, l in EMOTION_BY_NORM.items():
            if g.startswith(nl):
                return l
        for nl, l in EMOTION_BY_NORM.items():
            if nl in g:
                return l
        return None

    LABEL_TOK_IDS = {
        lab: tok(" " + lab, add_special_tokens=False,
                 truncation=True, max_length=cfg.max_target_len)["input_ids"]
        for lab in emotion_labels
    }

    # D1.6: первые токены меток — для вербализатор-скоринга
    # (протокол статьи: top-scoring output token). Проверяем
    # единственность: две метки с одним первым токеном неразличимы.
    LABEL_FIRST_TOKEN = {lab: ids[0] for lab, ids in LABEL_TOK_IDS.items()}
    _firsts = list(LABEL_FIRST_TOKEN.values())
    assert len(set(_firsts)) == len(_firsts), (
        "коллизия первых токенов меток — вербализатор неразличим: " +
        str([l for l in LABEL_FIRST_TOKEN
             if list(LABEL_FIRST_TOKEN.values()).count(LABEL_FIRST_TOKEN[l]) > 1])
    )
    _multi = [l for l in emotion_labels if len(LABEL_TOK_IDS[l]) > 1]
    print(f"Вербализатор: все 32 первых токена уникальны; "
          f"мультитокенных меток: {len(_multi)} {_multi}")

    # D1.6: ЖЁСТКИЕ негативы — группы путаемых эмоций (критика D1.5:
    # случайная чужая метка из 31 слишком легка; негатив должен быть
    # реальной конкурирующей альтернативой)
    CONFUSION_GROUPS = [
        {"afraid", "terrified", "anxious", "apprehensive"},
        {"sad", "disappointed", "devastated", "lonely"},
        {"angry", "furious", "annoyed", "disgusted"},
        {"surprised", "anticipating", "excited", "joyful"},
        {"guilty", "ashamed", "embarrassed"},
        {"hopeful", "faithful", "trusting", "prepared", "confident", "proud"},
        {"caring", "grateful", "impressed"},
        {"sentimental", "nostalgic", "content"},
        {"jealous"},
    ]
    LABEL_GROUP = {}
    for g in CONFUSION_GROUPS:
        for lab in g:
            if lab in emotion_labels:
                LABEL_GROUP[lab] = g
    print(f"Группы путаемости покрывают {len(LABEL_GROUP)}/32 меток")

    _neg_rng = random.Random(1234)

    def sample_wrong_label(true_label):
        """Жёсткий негатив: предпочтительно из группы путаемости."""
        group = LABEL_GROUP.get(true_label)
        if group and len(group) > 1:
            pool = [l for l in group if l != true_label]
            return _neg_rng.choice(pool)
        pool = [l for l in emotion_labels if l != true_label]
        return _neg_rng.choice(pool)

    raw_rl    = HFDataset.from_list(ed_train_full[:cfg.rl_subset_size])
    raw_train = HFDataset.from_list(ed_train_full[cfg.rl_subset_size:
                                                  cfg.rl_subset_size + cfg.train_size])
    raw_val   = HFDataset.from_list(ed_val_full[:cfg.val_size])
    raw_test  = HFDataset.from_list(ed_test_full[:cfg.test_size])

    assert cfg.rl_subset_size + cfg.train_size <= len(ed_train_full), \
        "hold-out + train не помещаются в датасет"

    print(f"Эмоции (32): {emotion_labels}")
else:
    raw = load_dataset(cfg.dataset_name)
    print("Splits:", list(raw.keys()))
    raw_rl    = raw["train"].select(range(0, cfg.rl_subset_size))
    raw_train = raw["train"].select(range(cfg.rl_subset_size,
                                          cfg.rl_subset_size + cfg.train_size))
    raw_val   = raw["validation"].select(range(cfg.val_size))
    raw_test  = raw["test"].select(range(cfg.test_size))
    assert cfg.rl_subset_size + cfg.train_size <= len(raw["train"])

def tokenize_gen(examples):
    all_input_ids = []
    all_attention_mask = []
    all_labels = []
    all_neg_input_ids = []
    all_neg_attention_mask = []
    all_neg_labels = []

    max_total = cfg.max_total_len
    tgt_prefix = " " if cfg.task_kind == "emotion_cls" else ""
    add_eos = cfg.task_kind != "emotion_cls"  # D1.1b: без EOS в cls

    for s, t in zip(examples[cfg.text_column], examples[cfg.target_column]):
        src = cfg.prompt_template.format(source=s)

        src_ids = tok(
            src,
            add_special_tokens=False,
            truncation=True,
            max_length=cfg.max_source_len,
        )["input_ids"]

        tgt_max = max(1, cfg.max_target_len - 1) if add_eos else cfg.max_target_len
        tgt_ids = tok(
            tgt_prefix + t,
            add_special_tokens=False,
            truncation=True,
            max_length=tgt_max,
        )["input_ids"]
        if add_eos:
            tgt_ids = tgt_ids + [tok.eos_token_id]

        if len(src_ids) == 0:
            src_ids = [tok.pad_token_id]

        if len(src_ids) + len(tgt_ids) > max_total:
            src_ids = src_ids[:max(1, max_total - len(tgt_ids))]

        input_ids = src_ids + tgt_ids
        labels = [-100] * len(src_ids) + tgt_ids

        all_input_ids.append(input_ids)
        all_attention_mask.append([1] * len(input_ids))
        all_labels.append(labels)

        # D1.6: ЖЁСТКИЙ негатив wrong-label — (ситуация, путаемая эмоция)
        if cfg.task_kind == "emotion_cls":
            wrong_ids = list(LABEL_TOK_IDS[sample_wrong_label(t)])
            neg_ids = src_ids + wrong_ids
            all_neg_input_ids.append(neg_ids)
            all_neg_attention_mask.append([1] * len(neg_ids))
            all_neg_labels.append([-100] * len(src_ids) + wrong_ids)

    out = {
        "input_ids": all_input_ids,
        "attention_mask": all_attention_mask,
        "labels": all_labels,
    }
    if cfg.task_kind == "emotion_cls":
        out.update({
            "neg_input_ids": all_neg_input_ids,
            "neg_attention_mask": all_neg_attention_mask,
            "neg_labels": all_neg_labels,
        })
    return out

train_ds = raw_train.map(tokenize_gen, batched=True, remove_columns=raw_train.column_names)
val_ds = raw_val.map(tokenize_gen, batched=True, remove_columns=raw_val.column_names)
test_ds = raw_test.map(tokenize_gen, batched=True, remove_columns=raw_test.column_names)
rl_ds = raw_rl.map(tokenize_gen, batched=True, remove_columns=raw_rl.column_names)

rl_ds = rl_ds.add_column("ref_idx", list(range(len(rl_ds))))

rl_references = raw_rl[cfg.target_column]
val_references = raw_val[cfg.target_column]
test_references = raw_test[cfg.target_column]

train_ds.set_format("torch")
val_ds.set_format("torch")
test_ds.set_format("torch")
rl_ds.set_format("torch")

print(f"Train: {len(train_ds)} | Val: {len(val_ds)} | Test: {len(test_ds)} | "
      f"RL hold-out: {len(rl_ds)} (не входит в train)")
assert (train_ds[0]["labels"] != -100).sum() > 0, "нет супервизируемых токенов"
if cfg.task_kind == "emotion_cls":
    print("Sample NEG (последние 10 токенов):", train_ds[0]["neg_labels"][-10:])

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

ED episodes: train 17844 | val 2763 | test 2542
Вербализатор: все 32 первых токена уникальны; мультитокенных меток: 1 ['apprehensive']
Группы путаемости покрывают 32/32 меток
Эмоции (32): ['afraid', 'angry', 'annoyed', 'anticipating', 'anxious', 'apprehensive', 'ashamed', 'caring', 'confident', 'content', 'devastated', 'disappointed', 'disgusted', 'embarrassed', 'excited', 'faithful', 'furious', 'grateful', 'guilty', 'hopeful', 'impressed', 'jealous', 'joyful', 'lonely', 'nostalgic', 'prepared', 'proud', 'sad', 'sentimental', 'surprised', 'terrified', 'trusting']

Map: 100%|██████████| 6000/6000 [00:00<00:00, 10068.22 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 8140.64 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 8036.51 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8655.63 examples/s]

Train: 6000 | Val: 200 | Test: 500 | RL hold-out: 600 (не входит в train)
Sample NEG (последние 10 токенов): tensor([ -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100,  -100, 68244])

In [5]:
# ============================================================
# CELL 5: Reward function
# D1 (emotion_cls): accuracy матчинга сгенерированного слова к 32 меткам
# summarization (наследие): ROUGE-L против референса
# ============================================================
rouge_metric = evaluate.load("rouge")

@torch.no_grad()
def compute_generation_reward(model, input_ids, attention_mask, references, tokenizer,
                              task_cfg=None):
    """Reward на ДАННОМ примере против его референса. Greedy ->
    детерминированный reward (аналог accuracy в статье).

    Для task_kind="emotion_cls": references = строки-эмоции,
    reward = доля примеров, где match_emotion(генерация) == метка.
    Для "summarization": reward = ROUGE-L.
    """
    # D2.2: task_cfg — конфиг ЗАДАЧИ (глобальный cfg может быть чужим,
    # например D1-классификацией); по умолчанию прежнее поведение
    c = task_cfg if task_cfg is not None else cfg
    model.eval()

    old_use_cache = getattr(model.config, "use_cache", True)
    model.config.use_cache = True

    try:
        gen_kwargs = dict(
            input_ids=input_ids,
            attention_mask=attention_mask,
            max_new_tokens=c.gen_max_new_tokens,
            do_sample=c.gen_do_sample,
            pad_token_id=tokenizer.pad_token_id,
            eos_token_id=tokenizer.eos_token_id,
        )
        if c.gen_do_sample:
            gen_kwargs.update(temperature=c.gen_temperature, top_p=c.gen_top_p)

        gen_ids = model.generate(**gen_kwargs)
    finally:
        model.config.use_cache = old_use_cache

    new_tokens = gen_ids[:, input_ids.shape[1]:]
    generated_texts = tokenizer.batch_decode(new_tokens, skip_special_tokens=True)
    generated_texts = [x.strip() if x.strip() else " " for x in generated_texts]

    assert len(generated_texts) == len(references), \
        f"predictions/references mismatch: {len(generated_texts)} vs {len(references)}"

    if c.task_kind == "emotion_cls":
        reward = float(np.mean([
            match_emotion(g) == r
            for g, r in zip(generated_texts, references)
        ]))
    else:
        results = rouge_metric.compute(
            predictions=generated_texts,
            references=references,
            rouge_types=["rougeL"],
        )
        reward = float(results["rougeL"])

    model.train()
    return reward, generated_texts

print("Reward function defined: accuracy (emotion_cls) / ROUGE-L (summarization).")

Reward function defined: accuracy (emotion_cls) / ROUGE-L (summarization).

In [6]:
# ============================================================
# CELL 6: TwoPhaseTrainerGen — адаптация Algorithm 1
# D1.5: contrast_mode = "mask" | "wrong_label"; contrast_from_start
# D1.6: RL reward на ЧИСТОМ входе (strip золотой метки — баг эха)
# ============================================================
class TwoPhaseTrainerGen(Trainer):
    def __init__(
        self,
        model=None,
        args=None,
        phase1_epochs: int = 3,
        alpha: float = 1.0,
        beta: float = 0.1,
        gamma: float = 2e-5,
        gamma_auto: bool = True,
        gamma_target_frac: float = 0.3,
        sigma: float = 0.02,
        contrast_mode: str = "mask",
        contrast_from_start: bool = False,
        contrastive_dropout: float = 0.1,
        contrastive_tau: float = 0.5,
        k_negatives: int = 1,
        rl_interval: int = 50,
        rl_num_batches: int = 16,
        rl_subset_size: int = 200,
        use_reward_baseline: bool = True,
        phase2_lr: float = 2e-4,
        divergence_ce_threshold: float = 6.0,
        guard_start_step: int = 200,
        rl_dataset=None,
        rl_references=None,
        tokenizer=None,
        task_cfg=None,
        contrast_neg_in_graph: bool = False,
        reward_baseline_beta: float = 0.9,
        **kwargs
    ):
        self.phase1_epochs = phase1_epochs
        self.alpha = alpha
        self.beta = beta
        self.gamma = gamma
        self.gamma_auto = gamma_auto
        self.gamma_target_frac = gamma_target_frac
        self.sigma = sigma
        self.contrast_mode = contrast_mode
        self.contrast_from_start = contrast_from_start
        self.contrastive_dropout = contrastive_dropout
        self.contrastive_tau = contrastive_tau
        self.k_negatives = k_negatives
        self.rl_interval = rl_interval
        self.rl_num_batches = rl_num_batches
        self.rl_subset_size = rl_subset_size
        self.use_reward_baseline = use_reward_baseline
        self.phase2_lr = phase2_lr
        self.divergence_ce_threshold = divergence_ce_threshold
        self.guard_start_step = guard_start_step
        self.rl_dataset = rl_dataset
        self.rl_references = rl_references
        self.tokenizer = tokenizer
        self.task_cfg = task_cfg          # D2.2: конфиг задачи для reward
        self.rl_reward_history = []       # D2.2: трекинг наград по шагам
        self.contrast_neg_in_graph = contrast_neg_in_graph  # D2.3
        self.reward_baseline_beta = reward_baseline_beta    # D2.2b

        # Флаги состояний
        self._phase2_lr_reset_done = False
        self._gamma_calibrated = False
        self._last_rl_step = -1
        self._last_log_step = -1
        self._reward_baseline = 0.0
        self._ce_ema = None
        self._divergence_reported = False

        super().__init__(model=model, args=args, **kwargs)

        # Параметры префикса собираем ПОСЛЕ super().__init__
        self.prefix_params = [
            (n, p) for n, p in self.model.named_parameters()
            if "prompt_encoder" in n and p.requires_grad
        ]
        print(f"[Trainer] Prefix params collected: {len(self.prefix_params)}")

        # Цели контраста (для mode="mask") — ТОЛЬКО embedding-слой
        self.contrast_params = [
            (n, p) for n, p in self.prefix_params if "embedding" in n
        ] or self.prefix_params
        print(f"[Trainer] Contrast: mode={self.contrast_mode}, "
              f"from_start={self.contrast_from_start}, beta={self.beta}")

        if self.rl_dataset is not None:
            self._rl_loader = DataLoader(
                self.rl_dataset,
                batch_size=self.args.per_device_train_batch_size,
                collate_fn=self.data_collator,
            )
            self._rl_iter = iter(self._rl_loader)

    # ----------------------------------------------------------
    # Утилиты
    # ----------------------------------------------------------
    @staticmethod
    def _model_inputs(inputs):
        """Только те ключи, которые понимает model.forward. Коллатор
        дополнительно кладёт neg_*/ref_idx — их в модель нельзя."""
        return {k: v for k, v in inputs.items()
                if k in ("input_ids", "attention_mask", "labels")}

    def _next_rl_batch(self):
        try:
            return next(self._rl_iter)
        except StopIteration:
            self._rl_iter = iter(self._rl_loader)
            return next(self._rl_iter)

    def _restore_params(self, params, snapshot):
        with torch.no_grad():
            for n, p in params:
                p.data.copy_(snapshot[n])

    def _custom_scale(self):
        """ЕДИНЫЙ множитель для ВСЕГО лосса, включая CE (урок ит. 2
        исследования-1: иначе эффективный LR x gradient_accumulation)."""
        trainer_divides = not getattr(self, "model_accepts_loss_kwargs", False)
        return 1.0 if trainer_divides else 1.0 / self.args.gradient_accumulation_steps

    def _reset_lr_for_phase2(self):
        if self.optimizer is None or self.lr_scheduler is None:
            return
        remaining = max(1, self.state.max_steps - self.state.global_step)
        for pg in self.optimizer.param_groups:
            pg["lr"] = self.phase2_lr
            pg["initial_lr"] = self.phase2_lr
        self.lr_scheduler = get_cosine_schedule_with_warmup(
            self.optimizer, num_warmup_steps=0, num_training_steps=remaining,
        )
        print(f"\n[Phase 2] LR reset to {self.phase2_lr}, "
              f"new cosine over remaining {remaining} steps\n")

    def _pool_hidden(self, hidden, labels):
        """Пуллинг по токенам таргета (labels != -100): для позитива —
        токены верной метки, для негатива — токены чужой метки."""
        if hidden.size(1) != labels.size(1):
            hidden = hidden[:, -labels.size(1):, :]
        tgt_mask = (labels != -100).unsqueeze(-1).to(hidden.dtype)
        pooled = (hidden * tgt_mask).sum(1) / tgt_mask.sum(1).clamp(min=1)
        return F.normalize(pooled.float(), dim=-1)

    # ----------------------------------------------------------
    # Contrastive loss — два режима негативов
    # ----------------------------------------------------------
    def _contrastive_loss(self, model, inputs, h_pos):
        """L = log1 + sum_j exp((sim(h_i, h_j^-) - 1) / tau))

        mode="mask" (рецепт статьи): h_j^- — представление ТОГО ЖЕ входа
        под замаскированным embedding-слоем промпта. Позитив тривиален
        (sim(h,h)=1 — вырожденность Eq. 3, см. FINAL_ANALYSIS §4).

        mode="wrong_label" (ядро темы): негатив — (ситуация, ЖЁСТКАЯ
        чужая эмоция из группы путаемости) — реальная конкурирующая
        альтернатива."""
        if self.k_negatives <= 0:
            return h_pos.new_zeros(())

        h_negs = []

        # D2: негативы из neg-колонок, собранных при токенизации
        # (neg = wrong-label для cls; negoff*/neginc для response_gen).
        # D2.3: offtopic4 = k=4 негативов (Σ_j как в Eq.3 статьи);
        # oftopic_grad = градиент и через негатив (симметричный апдейт)
        COLUMN_MODES = {
            "wrong_label": ["neg"],
            "offtopic": ["negoff"],
            "offtopic_grad": ["negoff"],
            "offtopic4": ["negoff", "negoff2", "negoff3", "negoff4"],
            "incoherent": ["neginc"],
        }
        if self.contrast_mode in COLUMN_MODES:
            for pfx in COLUMN_MODES[self.contrast_mode]:
                neg_fwd = {
                    "input_ids": inputs[f"{pfx}_input_ids"],
                    "attention_mask": inputs[f"{pfx}_attention_mask"],
                }
                if getattr(self, "contrast_neg_in_graph", False):
                    out_neg = model(**neg_fwd, output_hidden_states=True)
                else:
                    with torch.no_grad():
                        out_neg = model(**neg_fwd, output_hidden_states=True)
                h_negs.append(self._pool_hidden(
                    out_neg.hidden_states[-1], inputs[f"{pfx}_labels"]))
                del out_neg
        else:
            neg_inputs = {k: v for k, v in self._model_inputs(inputs).items()
                          if k != "labels"}
            labels = inputs["labels"]
            original_data = {n: p.data.clone() for n, p in self.contrast_params}
            try:
                for _ in range(self.k_negatives):
                    for n, p in self.contrast_params:
                        mask = (torch.rand_like(p.float()) > self.contrastive_dropout).to(p.dtype)
                        p.data.copy_((original_data[n] * mask).to(p.dtype))
                    with torch.no_grad():
                        out_neg = model(**neg_inputs, output_hidden_states=True)
                    h_neg = self._pool_hidden(out_neg.hidden_states[-1], labels)
                    h_negs.append(h_neg)
                    del out_neg
                    self._restore_params(self.contrast_params, original_data)
            finally:
                self._restore_params(self.contrast_params, original_data)

        h_negs = torch.stack(h_negs, dim=1)  # (B, K, D)

        tau = self.contrastive_tau
        neg_scores = torch.einsum("bd,bkd->bk", h_pos, h_negs) / tau
        loss = torch.log1p(torch.exp(neg_scores - 1.0 / tau).sum(dim=1)).mean()
        return loss

    # ----------------------------------------------------------
    # RL loss (REINFORCE, Eq. 4 статьи)
    # ----------------------------------------------------------
    def _rl_loss(self, model):
        log_probs = []
        noisy_values = {}
        for n, p in self.prefix_params:
            p32 = p.float()
            eps = torch.randn_like(p32) * self.sigma
            noisy = (p32.detach() + eps).detach()
            log_probs.append(
                Normal(loc=p32, scale=self.sigma).log_prob(noisy).sum()
            )
            noisy_values[n] = noisy

        original_data = {n: p.data.clone() for n, p in self.prefix_params}
        rewards = []
        last_texts, last_refs = None, None
        try:
            for n, p in self.prefix_params:
                p.data.copy_(noisy_values[n].to(p.dtype))

            for _ in range(self.rl_num_batches):
                rl_batch = self._next_rl_batch()
                idx = rl_batch.pop("ref_idx", None)
                if idx is None:
                    raise RuntimeError(
                        "ref_idx потерян коллатором: causal_lm_collator обязан "
                        "пробрасывать ref_idx"
                    )
                # D1.6: ЧИСТЫЙ reward — отрезаем золотую метку до generate
                # (баг эха: иначе reward мерил повторение подсказанной метки)
                src_ids, src_mask = strip_label_tokens(rl_batch)
                batch = {
                    "input_ids": src_ids.to(model.device),
                    "attention_mask": src_mask.to(model.device),
                }
                refs = [self.rl_references[i] for i in idx.tolist()]
                r, texts = compute_generation_reward(
                    model, batch["input_ids"], batch["attention_mask"],
                    refs, self.tokenizer, task_cfg=self.task_cfg,
                )
                rewards.append(r)
                last_texts, last_refs = texts, refs
            reward = float(np.mean(rewards))
            self.rl_reward_history.append(
                {"step": int(self.state.global_step), "reward": reward})
        finally:
            self._restore_params(self.prefix_params, original_data)

        if self.use_reward_baseline:
            advantage = reward - self._reward_baseline
            _beta_b = self.reward_baseline_beta   # D2.2b: инерция EMA
            self._reward_baseline = (
                _beta_b * self._reward_baseline + (1 - _beta_b) * reward)
        else:
            advantage = reward

        raw_rl = -advantage * torch.stack(log_probs).sum()

        if self.gamma_auto and not self._gamma_calibrated:
            raw_abs = abs(float(raw_rl.detach()))
            if raw_abs < 1e-6 or self._ce_ema is None:
                print("[RL] gamma calibration postponed")
            else:
                accum = self.args.gradient_accumulation_steps
                self.gamma = float(np.clip(
                    self.gamma_target_frac * self._ce_ema * accum / raw_abs,
                    1e-8, 1.0,
                ))
                self._gamma_calibrated = True
                print(f"[RL] gamma auto-calibrated to {self.gamma:.3e}")

        loss_rl = self.gamma * raw_rl

        if last_texts is not None:
            print(f"[RL sample] REF: {last_refs[0][:110]!r}")
            print(f"[RL sample] GEN: {last_texts[0][:110]!r}")
        print(f"[RL step {self.state.global_step}] reward={reward:.4f} "
              f"adv={advantage:+.4f} gamma={self.gamma:.2e}")
        return loss_rl, reward

    # ----------------------------------------------------------
    # Основной лосс
    # ----------------------------------------------------------
    def compute_loss(self, model, inputs, return_outputs=False, **kwargs):
        current_epoch = int(self.state.epoch) if self.state.epoch else 0
        in_phase2 = current_epoch >= self.phase1_epochs

        if in_phase2 and not self._phase2_lr_reset_done:
            self._phase2_lr_reset_done = True
            self._reset_lr_for_phase2()

        use_contrast = self.beta != 0.0 and (in_phase2 or self.contrast_from_start)

        model_inputs = self._model_inputs(inputs)
        outputs = model(**model_inputs, output_hidden_states=use_contrast)
        loss_mle = outputs.loss

        ce_now = loss_mle.item()
        self._ce_ema = ce_now if self._ce_ema is None else 0.95 * self._ce_ema + 0.05 * ce_now

        if (self.state.global_step >= self.guard_start_step
                and self._ce_ema > self.divergence_ce_threshold
                and not self._divergence_reported):
            self._divergence_reported = True
            print(f"\n!!! CE/token EMA = {self._ce_ema:.2f} > "
                  f"{self.divergence_ce_threshold} — расходимость. "
                  f"Останавливаю обучение (шаг {self.state.global_step}).\n")
            self.control.should_training_stop = True

        scale = self._custom_scale()

        loss_contrast = loss_mle.new_zeros(())
        if use_contrast:
            h_pos = self._pool_hidden(outputs.hidden_states[-1],
                                      model_inputs["labels"])
            loss_contrast = self._contrastive_loss(model, inputs, h_pos)

        loss_rl = loss_mle.new_zeros(())
        reward_val = 0.0
        rl_enabled = (self.gamma != 0.0 or self.gamma_auto) and self.rl_dataset is not None
        if (
            rl_enabled
            and self.state.global_step % self.rl_interval == 0
            and self._last_rl_step != self.state.global_step
        ):
            self._last_rl_step = self.state.global_step
            loss_rl, reward_val = self._rl_loss(model)

        if (model.training and self.state.global_step % 10 == 0
                and self._last_log_step != self.state.global_step):
            self._last_log_step = self.state.global_step
            print(f"[Step {self.state.global_step}] CE/token (EMA): {self._ce_ema:.3f} | "
                  f"Contrast[{self.contrast_mode}]: {loss_contrast.item():.3f} | "
                  f"RL: {loss_rl.item():.3f} | Reward: {reward_val:.4f}")

        loss = scale * (self.alpha * loss_mle + self.beta * loss_contrast + loss_rl)
        return (loss, outputs) if return_outputs else loss

print("TwoPhaseTrainerGen defined ✓")

TwoPhaseTrainerGen defined ✓

In [7]:
# ============================================================
# CELL 7: collator + ЧИСТЫЙ eval (фикс бага эха) + коллбэки
#
# БАГ ПРОТОКОЛА D1.x (найден при разборе критики): вход для generate
# СОДЕРЖАЛ золотую метку в конце -> модель продолжала её, и
# «предсказанием» было ЭХО метки. Канарейка D1.5 это показывает
# буквально: «surprised surprised surprised…» — повтор золотой метки.
# Отсюда подозрительно высокие accuracy обученных моделей (0.45–0.65)
# при чистом zero-shot 0.18. Фикс: перед generate отрезаем токены
# метки (labels != -100 считаются от КОНЦА последовательности).
# ============================================================
import json as _json
import json
import torch.nn.functional as F  # ре-импорт: защита от затенения имени F
                                  # (баг: ячейка BERTScore писала P, R, F = ...)


def strip_label_tokens(batch):
    """Отрезает токены метки в конце каждого примера и заново
    лево-пэддит батч. Возвращает (input_ids, attention_mask)
    src-only — модель должна ПРЕДСКАЗАТЬ метку, а не прочитать."""
    labels = batch["labels"]
    n_lab = (labels != -100).sum(dim=1)
    L = batch["input_ids"].size(1)
    srcs = [batch["input_ids"][i, :L - int(n_lab[i])]
            for i in range(batch["input_ids"].size(0))]
    # Маску берём ТЕМ ЖЕ срезом из оригинала: в отрезанном куске
    # остаются исходные лево-паддинговые позиции с маской 0
    # (юнит-тест поймал баг: маска «все единицы» ломала позициями)
    ams = [batch["attention_mask"][i, :L - int(n_lab[i])]
           for i in range(batch["input_ids"].size(0))]
    max_len = max(s.size(0) for s in srcs)
    input_ids = torch.stack([
        s if s.size(0) == max_len
        else F.pad(s, (max_len - s.size(0), 0), value=tok.pad_token_id)
        for s in srcs
    ])
    attention_mask = torch.stack([
        m if m.size(0) == max_len
        else F.pad(m, (max_len - m.size(0), 0), value=0)
        for m in ams
    ])
    return input_ids, attention_mask


@torch.no_grad()
def verbalizer_eval(model, dataset, references, tokenizer, batch_size=16):
    """Вербализатор-скоринг (протокол статьи: top-scoring output token):
    ОДИН forward на src-only входе, argmax по первым токенам 32 меток
    в последней позиции. Детерминированно, без генерации.
    Возвращает (accuracy, correct_vec)."""
    if cfg.task_kind != "emotion_cls":
        return None, None
    model.eval()
    order_labels = sorted(LABEL_FIRST_TOKEN.keys())
    tok_ids = torch.tensor([LABEL_FIRST_TOKEN[l] for l in order_labels],
                           device=model.device)
    loader = DataLoader(dataset, batch_size=batch_size, collate_fn=causal_lm_collator)
    correct = []
    idx = 0
    for batch in loader:
        input_ids, attention_mask = strip_label_tokens(batch)
        input_ids = input_ids.to(model.device)
        attention_mask = attention_mask.to(model.device)
        logits = model(input_ids=input_ids,
                       attention_mask=attention_mask).logits[:, -1, :]
        pred_idx = logits[:, tok_ids].argmax(dim=-1).tolist()
        for pi in pred_idx:
            correct.append(int(order_labels[pi] == references[idx]))
            idx += 1
    return float(np.mean(correct)), correct


def causal_lm_collator(features):
    pad_token_id = tok.pad_token_id

    def to_1d_tensor(x, dtype=torch.long):
        if not isinstance(x, torch.Tensor):
            x = torch.tensor(x, dtype=dtype)
        if x.dim() > 1:
            x = x.squeeze(0)
        return x

    def pad_batch(seqs, value=0):
        max_len = max(s.size(0) for s in seqs)
        return torch.stack([
            s if s.size(0) == max_len
            else F.pad(s, (max_len - s.size(0), 0), value=value)
            for s in seqs
        ])

    # ПАДДИНГ = 0 ДЛЯ ОБОИХ (легаси всех завершённых прогонов).
    # Эмпирически доказано (журнал §6.3): в этом стеке значение пэда
    # input_ids ВЛИЯЕТ на логиты реальных позиций (max diff 6.2 даже
    # при нулевой маске) — «гигиена» pad_token_id НЕ числово-нейтральна,
    # а attention_mask с ненулевыми падами ломает маскирование вовсе.
    # Поэтому: (1) оставляем 0/0 как во всех проведённых экспериментах;
    # (2) замена на pad_token_id возможна ТОЛЬКО при полном перезапуске.
    # Известная историческая особенность: eval-пути (strip_label_tokens,
    # zero-shot через токенизатор) паддят pad_token_id — train/eval
    # рассогласование существовало ВСЕГДА, одинаково для всех конфигов
    # (парные выводы не затронуты), задокументировано в §6.3.
    out = {
        "input_ids": pad_batch([to_1d_tensor(f["input_ids"]) for f in features]),
        "attention_mask": pad_batch(
            [to_1d_tensor(f["attention_mask"]) for f in features]),
    }
    # labels: левый паддинг значением -100
    lab_list = []
    max_len = out["input_ids"].size(1)
    for f in features:
        labs = to_1d_tensor(f["labels"])
        pad_len = max_len - labs.size(0)
        lab_list.append(labs if pad_len == 0 else F.pad(labs, (pad_len, 0), value=-100))
    out["labels"] = torch.stack(lab_list)

    # Негативные последовательности: neg (wrong-label, cls),
    # negoff / negoff2..4 / neginc (D2; D2.3 — динамическое
    # обнаружение любых *_input_ids-колонок негативов)
    neg_pfxs = sorted({k[:-len("_input_ids")] for k in features[0]
                       if k.endswith("_input_ids") and k != "input_ids"})
    for pfx in neg_pfxs:
        if f"{pfx}_attention_mask" in features[0]:
            n_ids = [to_1d_tensor(f[f"{pfx}_input_ids"]) for f in features]
            n_mask = [to_1d_tensor(f[f"{pfx}_attention_mask"]) for f in features]
            n_labs = [to_1d_tensor(f[f"{pfx}_labels"]) for f in features]
            max_len = max(s.size(0) for s in n_ids)
            out[f"{pfx}_input_ids"] = torch.stack([
                s if s.size(0) == max_len
                else F.pad(s, (max_len - s.size(0), 0), value=pad_token_id)
                for s in n_ids])
            out[f"{pfx}_attention_mask"] = torch.stack([
                s if s.size(0) == max_len
                else F.pad(s, (max_len - s.size(0), 0), value=0)
                for s in n_mask])
            out[f"{pfx}_labels"] = torch.stack([
                s if s.size(0) == max_len
                else F.pad(s, (max_len - s.size(0), 0), value=-100)
                for s in n_labs])

    if "ref_idx" in features[0]:
        out["ref_idx"] = torch.tensor(
            [int(f["ref_idx"]) for f in features], dtype=torch.long
        )

    return out


class Phase1CanaryCallback(TrainerCallback):
    """Каждую эпоху печатает ЧИСТЫЕ генерации (src-only) на val;
    если ВСЕ пустые — останавливает обучение."""

    def __init__(self, canary_ds, tokenizer, collator, first_epoch=2,
                 num_examples=4, max_new_tokens=6):
        n = min(num_examples, len(canary_ds))
        self.loader = DataLoader(
            canary_ds.select(range(n)), batch_size=1, collate_fn=collator
        )
        self.tokenizer = tokenizer
        self.first_epoch = first_epoch
        self.max_new_tokens = max_new_tokens
        self.stopped = False

    @torch.no_grad()
    def on_epoch_end(self, args, state, control, model=None, **kwargs):
        if model is None or state.epoch < self.first_epoch or self.stopped:
            return

        was_training = model.training
        model.eval()
        old_use_cache = getattr(model.config, "use_cache", True)
        model.config.use_cache = True

        texts = []
        try:
            for batch in self.loader:
                input_ids, attention_mask = strip_label_tokens(batch)
                input_ids = input_ids.to(model.device)
                attention_mask = attention_mask.to(model.device)
                out = model.generate(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    max_new_tokens=self.max_new_tokens,
                    do_sample=False,
                    pad_token_id=self.tokenizer.pad_token_id,
                    eos_token_id=self.tokenizer.eos_token_id,
                )
                gen = self.tokenizer.decode(
                    out[0, input_ids.shape[1]:], skip_special_tokens=True
                ).strip()
                texts.append(gen if gen else "<EMPTY>")
        finally:
            model.config.use_cache = old_use_cache
            if was_training:
                model.train()

        print(f"[Canary epoch {state.epoch:.0f}] " + " | ".join(t[:80] for t in texts))

        if all(t == "<EMPTY>" for t in texts):
            self.stopped = True
            print("!!! Canary: ВСЕ генерации пустые — модель не обучилась.\n"
                  "    Останавливаю обучение.")
            control.should_training_stop = True


class BestEpochValMetricCallback(TrainerCallback):
    """Раз в эпоху: ЧИСТАЯ метрика (src-only генерация + матчинг)
    на N val-примерах + сохранение ЛУЧШЕГО адаптера в best_prefix.pt."""

    def __init__(self, val_ds, val_references, tokenizer, collator,
                 output_dir, task_kind="emotion_cls",
                 num_examples=200, max_new_tokens=6):
        n = min(num_examples, len(val_ds), len(val_references))
        self.loader = DataLoader(
            val_ds.select(range(n)), batch_size=8, collate_fn=collator
        )
        self.references = list(val_references[:n])
        self.tokenizer = tokenizer
        self.output_dir = output_dir
        self.task_kind = task_kind
        self.metric_name = "accuracy" if task_kind == "emotion_cls" else "rougeL"
        self.max_new_tokens = max_new_tokens
        self.rouge = evaluate.load("rouge") if task_kind != "emotion_cls" else None
        self.best = -1.0
        self.best_epoch = None
        self.history = []
        self._collapse_reported = False

    @torch.no_grad()
    def on_epoch_end(self, args, state, control, model=None, **kwargs):
        if model is None:
            return

        was_training = model.training
        model.eval()
        old_use_cache = getattr(model.config, "use_cache", True)
        model.config.use_cache = True

        preds = []
        try:
            for batch in self.loader:
                input_ids, attention_mask = strip_label_tokens(batch)
                input_ids = input_ids.to(model.device)
                attention_mask = attention_mask.to(model.device)
                out = model.generate(
                    input_ids=input_ids,
                    attention_mask=attention_mask,
                    max_new_tokens=self.max_new_tokens,
                    do_sample=False,
                    pad_token_id=self.tokenizer.pad_token_id,
                    eos_token_id=self.tokenizer.eos_token_id,
                )
                for j in range(input_ids.size(0)):
                    pred = self.tokenizer.decode(
                        out[j, input_ids.shape[1]:], skip_special_tokens=True
                    ).strip()
                    preds.append(pred if pred else " ")
        finally:
            model.config.use_cache = old_use_cache
            if was_training:
                model.train()

        if self.task_kind == "emotion_cls":
            score = float(np.mean([
                match_emotion(p) == r for p, r in zip(preds, self.references)
            ]))
        else:
            score = float(self.rouge.compute(
                predictions=preds, references=self.references,
                rouge_types=["rougeL"],
            )["rougeL"])
        self.history.append({"epoch": round(state.epoch, 2), "value": score})

        if score > self.best:
            self.best = score
            self.best_epoch = round(state.epoch, 2)
            os.makedirs(self.output_dir, exist_ok=True)
            torch.save(
                {n: p.data.detach().cpu().clone()
                 for n, p in model.named_parameters() if p.requires_grad},
                os.path.join(self.output_dir, "best_prefix.pt"),
            )

        # D2: стоп коллапса генерации. Урок ARTICLE s44 (§4.16): CE-плато
        # скрывает деградацию генерации — guard по лоссу её не видит,
        # канарейка видит только ПУСТЫЕ генерации. Здесь: глубокое
        # падение val-метрики относительно лучшей = остановка.
        if (len(self.history) >= 3 and score < 0.5 * self.best
                and not self._collapse_reported):
            self._collapse_reported = True
            print(f"\n!!! Коллапс: val {self.metric_name}={score:.4f} < "
                  f"0.5 x best ({self.best:.4f}) на эпохе {state.epoch:.0f} "
                  f"— останавливаю обучение.\n")
            control.should_training_stop = True
        elif (len(self.history) >= 3 and score < 0.75 * self.best
                and not getattr(self, "_softdeg_warned", False)):
            # критика-2: мягкая деградация (0.5x < val < 0.75x best) —
            # только предупреждение: агрессивный стоп опасен (MLE s44
            # D2.1 восстановился с 0.026 на e1 до 0.176 на e2)
            self._softdeg_warned = True
            print(f"[SoftDegradation] val {self.metric_name}={score:.4f} < "
                  f"0.75 x best ({self.best:.4f}) — предупреждение, "
                  f"БЕЗ остановки")

        with open(os.path.join(self.output_dir, "val_metric_history.json"), "w") as f:
            _json.dump(
                {"metric": self.metric_name, "history": self.history,
                 "best": self.best, "best_epoch": self.best_epoch},
                f, indent=2,
            )

        print(f"[ValMetric epoch {state.epoch:.0f}] {self.metric_name}={score:.4f} | "
              f"best={self.best:.4f} @ epoch {self.best_epoch:.0f}")

    def on_train_end(self, args, state, control, **kwargs):
        print(f"[ValMetric] Итог: best {self.metric_name}={self.best:.4f} @ epoch "
              f"{self.best_epoch:.0f} -> best_prefix.pt")


def prepare_trainer(model, train_ds, val_ds, rl_ds, rl_references, tokenizer, cfg,
                    val_references=None):
    """Конфигурация тренера полностью из cfg — включая output_dir."""

    def compute_metrics(eval_pred):
        return {}

    training_args = TrainingArguments(
        output_dir=cfg.output_dir,
        num_train_epochs=cfg.total_epochs,
        per_device_train_batch_size=cfg.batch_size,
        per_device_eval_batch_size=cfg.eval_batch_size,
        gradient_accumulation_steps=cfg.gradient_accumulation_steps,
        learning_rate=cfg.learning_rate,
        lr_scheduler_type=cfg.lr_scheduler,
        warmup_steps=cfg.warmup_steps,
        logging_steps=cfg.logging_steps,
        eval_strategy=cfg.eval_strategy,
        save_strategy=cfg.save_strategy,
        save_total_limit=cfg.save_total_limit,
        load_best_model_at_end=cfg.load_best_model_at_end,
        bf16=cfg.bf16,
        fp16=cfg.fp16,
        gradient_checkpointing=cfg.gradient_checkpointing,
        report_to=cfg.report_to,
        remove_unused_columns=cfg.remove_unused_columns,
        dataloader_pin_memory=cfg.dataloader_pin_memory,
        seed=cfg.seed,
        prediction_loss_only=True,
        max_grad_norm=cfg.max_grad_norm,
    )

    canary = Phase1CanaryCallback(
        canary_ds=val_ds,
        tokenizer=tokenizer,
        collator=causal_lm_collator,
        first_epoch=2,
        max_new_tokens=cfg.eval_max_new_tokens,
    )

    callbacks = [canary]

    if val_references is not None:
        callbacks.append(BestEpochValMetricCallback(
            val_ds=val_ds,
            val_references=val_references,
            tokenizer=tokenizer,
            collator=causal_lm_collator,
            output_dir=cfg.output_dir,
            task_kind=cfg.task_kind,
            num_examples=cfg.val_rouge_examples,
            max_new_tokens=cfg.eval_max_new_tokens,
        ))

    trainer = TwoPhaseTrainerGen(
        model=model,
        args=training_args,
        phase1_epochs=cfg.phase1_epochs,
        alpha=cfg.alpha,
        beta=cfg.beta,
        gamma=cfg.gamma,
        gamma_auto=cfg.gamma_auto,
        gamma_target_frac=cfg.gamma_target_frac,
        sigma=cfg.sigma,
        contrast_mode=cfg.contrast_mode,
        contrast_from_start=cfg.contrast_from_start,
        contrastive_dropout=cfg.contrastive_dropout,
        contrastive_tau=cfg.contrastive_tau,
        k_negatives=cfg.k_negatives,
        rl_interval=cfg.rl_interval,
        rl_num_batches=cfg.rl_num_batches,
        rl_subset_size=cfg.rl_subset_size,
        use_reward_baseline=cfg.use_reward_baseline,
        phase2_lr=cfg.phase2_lr,
        divergence_ce_threshold=cfg.divergence_ce_threshold,
        guard_start_step=cfg.guard_start_step,
        rl_dataset=rl_ds,
        rl_references=rl_references,
        tokenizer=tokenizer,
        task_cfg=cfg,
        contrast_neg_in_graph=getattr(cfg, "contrast_neg_in_graph", False),
        reward_baseline_beta=getattr(cfg, "reward_baseline_beta", 0.9),
        train_dataset=train_ds,
        eval_dataset=val_ds,
        data_collator=causal_lm_collator,
        compute_metrics=compute_metrics,
        callbacks=callbacks,
    )

    return trainer

print("collator + strip_label_tokens + verbalizer_eval + коллбэры (чистый eval) ✓")

collator + strip_label_tokens + verbalizer_eval + коллбэры (чистый eval) ✓

In [8]:
def run_experiment(cfg, experiment_name, init_state=None, return_init_state=False):
    """init_state — общий старт пары; return_init_state=True возвращает
    (scores, snapshot). Сохраняет per-example корректности (для
    парного бутстрепа) и вербализатор-скоринг."""

    print(f"\n{'='*70}")
    print(f"STARTING EXPERIMENT: {experiment_name}")
    print(f"{'='*70}\n")

    gc.collect()
    torch.cuda.empty_cache()
    set_seed(cfg.seed)

    dtype = torch.bfloat16 if cfg.bf16 else torch.float32
    base = AutoModelForCausalLM.from_pretrained(
        cfg.model_name,
        dtype=dtype,
        trust_remote_code=cfg.trust_remote_code,
    )

    if cfg.gradient_checkpointing:
        base.gradient_checkpointing_enable()
    base.config.use_cache = cfg.use_cache

    peft_cfg = PrefixTuningConfig(
        task_type=TaskType.CAUSAL_LM,
        num_virtual_tokens=cfg.num_virtual_tokens,
        prefix_projection=cfg.prefix_projection,
        inference_mode=False,
    )

    model = get_peft_model(base, peft_cfg)
    del base

    for p in model.parameters():
        if p.requires_grad:
            p.data = p.data.float()

    model.enable_input_require_grads()
    model.to("cuda" if torch.cuda.is_available() else "cpu")

    prompt_param_list = [(n, p) for n, p in model.named_parameters()
                         if p.requires_grad and "prompt_encoder" in n]

    start_snapshot = None
    if init_state is not None:
        with torch.no_grad():
            for n, p in prompt_param_list:
                if n in init_state:
                    p.data.copy_(init_state[n].to(p.device))
        print(f"[PairedStart] загружен ОБЩИЙ старт ({len(init_state)} тензоров "
              f"префикса) — probe пропущен\n")
    elif getattr(cfg, "init_selection_inits", 0) > 0:
        select_best_prefix_init(
            model, train_ds, val_ds, tok, cfg,
            n_inits=cfg.init_selection_inits,
            probe_steps=cfg.init_selection_probe_steps,
        )
        if return_init_state:
            start_snapshot = {n: p.data.detach().cpu().clone()
                              for n, p in prompt_param_list}

    print("Trainable parameters:")
    model.print_trainable_parameters()

    trainer = prepare_trainer(
        model, train_ds, val_ds, rl_ds, rl_references, tok, cfg,
        val_references=val_references,
    )

    start_time = time.time()
    trainer.train()
    elapsed = time.time() - start_time
    rl_hist = list(getattr(trainer, "rl_reward_history", []) or [])

    print(f"\n{experiment_name} completed in {elapsed/60:.1f} min")

    # Подгружаем ЛУЧШИЙ по val-метрике адаптер
    val_metric_info = {}
    best_path = os.path.join(cfg.output_dir, "best_prefix.pt")
    hist_path = os.path.join(cfg.output_dir, "val_metric_history.json")
    if os.path.exists(best_path):
        best_state = torch.load(best_path, map_location="cpu")
        with torch.no_grad():
            for n, p in model.named_parameters():
                if n in best_state:
                    p.data.copy_(best_state[n].to(p.device))
        if os.path.exists(hist_path):
            with open(hist_path) as f:
                val_metric_info = json.load(f)
            print(f"Loaded best adapter: val {val_metric_info['metric']}"
                  f"={val_metric_info['best']:.4f} "
                  f"@ epoch {val_metric_info['best_epoch']:.0f} "
                  f"(история: {[round(h['value'], 4) for h in val_metric_info['history']]})")
        else:
            print("Loaded best adapter (best_prefix.pt)")
    else:
        print("best_prefix.pt не найден — оцениваю последнюю эпоху")

    # ---------- ЧИСТЫЙ тест (src-only generate, без золотой метки) ----------
    print(f"\nEvaluating {experiment_name} on test set (clean protocol)...")
    model.eval()

    test_loader = DataLoader(
        test_ds,
        batch_size=cfg.eval_batch_size,
        collate_fn=causal_lm_collator,
    )

    predictions = []
    references = []

    with torch.no_grad():
        for batch in test_loader:
            input_ids, attention_mask = strip_label_tokens(batch)
            input_ids = input_ids.to(model.device)
            attention_mask = attention_mask.to(model.device)

            gen_ids = model.generate(
                input_ids=input_ids,
                attention_mask=attention_mask,
                max_new_tokens=cfg.eval_max_new_tokens,
                do_sample=False,
                num_beams=1,
                pad_token_id=tok.pad_token_id,
                eos_token_id=tok.eos_token_id,
            )

            for j in range(input_ids.size(0)):
                pred = tok.decode(
                    gen_ids[j, input_ids.shape[1]:], skip_special_tokens=True
                ).strip()
                predictions.append(pred if pred else " ")

    references = list(test_references)

    per_ex = None
    if cfg.task_kind == "emotion_cls":
        pred_labels = [match_emotion(p) for p in predictions]
        correct_vec = [int(pl == r) for pl, r in zip(pred_labels, references)]
        scores = {"accuracy": float(np.mean(correct_vec))}

        # Вербализатор-скоринг (протокол статьи, детерминированный)
        verb_acc, verb_correct = verbalizer_eval(
            model, test_ds, references, tok)
        scores["verb_accuracy"] = verb_acc
    else:
        rouge = evaluate.load("rouge")
        scores = rouge.compute(
            predictions=predictions,
            references=references,
            rouge_types=["rouge1", "rouge2", "rougeL"],
        )
        # D2: per-example ROUGE-L (для парного бутстрепа) + Distinct-1/2
        per_ex = [float(x) for x in rouge.compute(
            predictions=predictions, references=references,
            rouge_types=["rougeL"], use_aggregator=False)["rougeL"]]
        scores["distinct1"], scores["distinct2"] = distinct_n(predictions)
        correct_vec = None
        verb_correct = None
        pred_labels = None

    print(f"\n{'='*70}")
    print(f"RESULTS: {experiment_name}")
    print(f"{'='*70}")
    for k, v in scores.items():
        print(f"{k}: {v:.4f}")
    print(f"{'='*70}\n")

    if pred_labels is not None:
        miss = [(r, pl, p) for r, pl, p in zip(references, pred_labels, predictions)
                if pl != r][:6]
        print("Примеры ошибок (ref -> pred | генерация):")
        for r, pl, p in miss:
            print(f"  {r:<14} -> {str(pl):<14} | {p[:30]!r}")
    else:
        print("Примеры генераций (test, чистый вход):")
        for r, p in list(zip(references, predictions))[:4]:
            print(f"  REF: {r[:90]!r}")
            print(f"  GEN: {p[:90]!r}")

    results = {
        "experiment": experiment_name,
        "config": {
            "task_kind": cfg.task_kind,
            "model": cfg.model_name,
            "beta": cfg.beta,
            "contrast_mode": getattr(cfg, "contrast_mode", None),
            "contrastive_tau": cfg.contrastive_tau,
            "contrast_from_start": getattr(cfg, "contrast_from_start", False),
            "epochs": cfg.total_epochs,
            "lr": cfg.learning_rate,
            "batch": cfg.batch_size,
            "seed": cfg.seed,
            "paired_common_start": init_state is not None,
            "clean_eval": True,
        },
        "test_scores": scores,
        "correct_vec": correct_vec,
        "verb_correct_vec": verb_correct,
        "per_example_rougeL": per_ex,
        "predictions": predictions,
        "rl_reward_history": rl_hist,
        "val_metric": val_metric_info,
        "training_time_min": elapsed / 60,
    }

    output_file = f"{cfg.output_dir}/results.json"
    os.makedirs(cfg.output_dir, exist_ok=True)
    with open(output_file, "w") as f:
        json.dump(results, f, indent=2)

    print(f"Results saved to {output_file}")

    del model, trainer
    gc.collect()
    torch.cuda.empty_cache()

    if return_init_state:
        return scores, start_snapshot
    return scores

In [10]:
# ============================================================
# СВИП: данные × модели × {MLE, mask, RL}
# ============================================================
import copy
import math

cfg_sweep_base = CFG()          # глобальный cfg уже есть; это база для копий
assert cfg_sweep_base.task_kind == "emotion_cls"

# сетка (зафиксирована до запуска; все ячейки в отчёт):
SWEEP_MODELS = [
    ("Qwen/Qwen2.5-3B",   "3B",  [250, 500, 1000]),   # + 6000 из D1.6 (n=7)
    ("Qwen/Qwen2.5-0.5B", "05B", [250, 1000, 6000]),
]
SWEEP_CONFIGS = ["MLE", "mask", "RL"]
SWEEP_SEEDS = [42, 43, 44]
# NB: токенизатор Qwen2.5 един для всех размеров модели — данные
# переиспользуются без перетокенизации


def rebuild_d1_datasets(train_size):
    """Хвост data-ячейки под новый размер train (val/test/RL фиксированы)."""
    global raw_rl, raw_train, raw_val, raw_test
    global train_ds, val_ds, test_ds, rl_ds
    global rl_references, val_references, test_references
    c = cfg_sweep_base
    assert c.rl_subset_size + train_size <= len(ed_train_full)
    raw_rl    = HFDataset.from_list(ed_train_full[:c.rl_subset_size])
    raw_train = HFDataset.from_list(ed_train_full[c.rl_subset_size:
                                                  c.rl_subset_size + train_size])
    raw_val   = HFDataset.from_list(ed_val_full[:c.val_size])
    raw_test  = HFDataset.from_list(ed_test_full[:c.test_size])
    train_ds = raw_train.map(tokenize_gen, batched=True,
                             remove_columns=raw_train.column_names)
    val_ds   = raw_val.map(tokenize_gen, batched=True,
                           remove_columns=raw_val.column_names)
    test_ds  = raw_test.map(tokenize_gen, batched=True,
                            remove_columns=raw_test.column_names)
    rl_ds    = raw_rl.map(tokenize_gen, batched=True,
                          remove_columns=raw_rl.column_names)
    rl_ds = rl_ds.add_column("ref_idx", list(range(len(rl_ds))))
    rl_references   = raw_rl[c.target_column]
    val_references  = raw_val[c.target_column]
    test_references = raw_test[c.target_column]
    for d in (train_ds, val_ds, test_ds, rl_ds):
        d.set_format("torch")


def make_shared_start(model_name, seed):
    """Случайный (сидированный) старт префикса — общий для всех размеров
    и конфигов данной (модель, сид): парность на двух уровнях."""
    set_seed(seed)
    b = AutoModelForCausalLM.from_pretrained(
        model_name, dtype=torch.bfloat16, trust_remote_code=True)
    m = get_peft_model(b, PrefixTuningConfig(
        task_type=TaskType.CAUSAL_LM, num_virtual_tokens=20,
        prefix_projection=True, inference_mode=False))
    snap = {n: p.data.detach().cpu().clone()
            for n, p in m.named_parameters()
            if p.requires_grad and "prompt_encoder" in n}
    del m, b
    gc.collect(); torch.cuda.empty_cache()
    return snap


os.makedirs("./sweep_ld", exist_ok=True)
_summary_ld = "./sweep_ld/summary_lowdata.json"
ld_rows = []
if os.path.exists(_summary_ld):
    with open(_summary_ld) as f:
        ld_rows = json.load(f).get("rows", [])

def _have(model_short, seed, size):
    return any(r["model"] == model_short and r["seed"] == seed
               and r["size"] == size and all(k in r for k in SWEEP_CONFIGS)
               for r in ld_rows)

for model_name, mshort, sizes in SWEEP_MODELS:
    for seed in SWEEP_SEEDS:
        done_sizes = [n for n in sizes if _have(mshort, seed, n)]
        todo_sizes = [n for n in sizes if n not in done_sizes]
        if not todo_sizes:
            print(f"[Resume] {mshort} s{seed}: все размеры готовы")
            continue
        shared = make_shared_start(model_name, seed)
        for size in todo_sizes:
            rebuild_d1_datasets(size)
            steps = math.ceil(size / cfg_sweep_base.batch_size) * \
                cfg_sweep_base.total_epochs
            row = {"model": mshort, "seed": seed, "size": size}
            for cname in SWEEP_CONFIGS:
                c = copy.copy(cfg_sweep_base)
                c.model_name = model_name
                c.seed = seed
                c.train_size = size
                c.init_selection_inits = 0
                c.warmup_steps = min(200, max(10, steps // 10))
                c.output_dir = f"./sweep_ld/{mshort}_{cname}_s{seed}_n{size}"
                if cname == "MLE":
                    c.beta = 0.0; c.gamma = 0.0; c.gamma_auto = False
                elif cname == "mask":
                    c.beta = 0.1; c.contrast_mode = "mask"
                    c.gamma = 0.0; c.gamma_auto = False
                else:  # RL
                    c.beta = 0.0; c.gamma = 2e-5; c.gamma_auto = True
                rj = os.path.join(c.output_dir, "results.json")
                if os.path.exists(rj):
                    with open(rj) as f:
                        sc = json.load(f)["test_scores"]
                else:
                    sc = run_experiment(
                        c, f"{cname} {mshort} n={size} (s{seed})",
                        init_state=shared)
                row[cname] = sc["accuracy"]
                row[f"{cname}-verb"] = sc["verb_accuracy"]
                gc.collect(); torch.cuda.empty_cache()
            ld_rows = [r for r in ld_rows
                       if not (r["model"] == mshort and r["seed"] == seed
                               and r["size"] == size)] + [row]
            with open(_summary_ld, "w") as f:
                json.dump({"rows": ld_rows}, f, indent=2)
            print(f">>> {mshort} s{seed} n={size}: "
                  f"{ {k: round(row[k], 4) for k in SWEEP_CONFIGS} }\n")
        del shared
        gc.collect(); torch.cuda.empty_cache()

print("Свип завершён:", len(ld_rows), "ячеек")

[Resume] 3B s42: все размеры готовы
[Resume] 3B s43: все размеры готовы
[Resume] 3B s44: все размеры готовы
[Resume] 05B s42: все размеры готовы
[Resume] 05B s43: все размеры готовы
[Resume] 05B s44: все размеры готовы
Свип завершён: 32 ячеек

In [9]:
# ============================================================
# АГРЕГАЦИЯ: кривые data-efficiency + пары к MLE на каждом размере
# (+ точка 3B n=6000 из готового D1.6, n=7 сидов)
# ============================================================
from math import sqrt

d16 = json.load(open("./gen_dialogue_ed_full/summary_d1_6.json"))["per_seed"]
ref6000 = {}
for cname, key in [("MLE", "MLE-only"), ("mask", "contrast-mask"),
                   ("RL", "RL-only")]:
    ref6000[cname] = [r[key] for r in d16]

for model_name, mshort, sizes in SWEEP_MODELS:
    print("\n" + "=" * 88)
    print(f"Кривая data-efficiency: {mshort} (генеративная accuracy, "
          f"mean±std по {len(SWEEP_SEEDS)} сидам)")
    print("=" * 88)
    print(f"{'size':<8}" + "".join(f"{c + ':':<16}" for c in SWEEP_CONFIGS)
          + f"{'mask−MLE':<12}{'RL−MLE':<12}")
    for size in sizes:
        rows_n = [r for r in ld_rows
                  if r["model"] == mshort and r["size"] == size]
        if not rows_n:
            continue
        means = {c: np.mean([r[c] for r in rows_n]) for c in SWEEP_CONFIGS}
        stds = {c: np.std([r[c] for r in rows_n]) for c in SWEEP_CONFIGS}
        dm = [r["mask"] - r["MLE"] for r in rows_n]
        dr = [r["RL"] - r["MLE"] for r in rows_n]
        sem = sqrt(len(dm))
        tm = np.mean(dm) / (np.std(dm, ddof=1) / sqrt(len(dm))) if len(dm) > 1 else float("nan")
        tr = np.mean(dr) / (np.std(dr, ddof=1) / sqrt(len(dr))) if len(dr) > 1 else float("nan")
        print(f"{size:<8}" + "".join(f"{means[c]:.3f}±{stds[c]:.3f}  "
              for c in SWEEP_CONFIGS)
              + f"{np.mean(dm):+.4f}(t={tm:+.1f}) {np.mean(dr):+.4f}(t={tr:+.1f})")
    if mshort == "3B":
        m6 = {c: (np.mean(ref6000[c]), np.std(ref6000[c])) for c in ref6000}
        print(f"6000*   " + "".join(f"{m6[c][0]:.3f}±{m6[c][1]:.3f}  "
              for c in SWEEP_CONFIGS)
              + "(*из D1.6, n=7 сидов)")
print("\nВопрос: растёт ли mask−MLE / RL−MLE при уменьшении данных?")
print("Гипотеза (а приори): вклад CRL максимален в low-resource зоне.")

with open(_summary_ld, "w") as f:
    json.dump({"rows": ld_rows}, f, indent=2)
print("Итог:", _summary_ld)

========================================================================================
Кривая data-efficiency: 3B (генеративная accuracy, mean±std по 3 сидам)
========================================================================================
size    MLE:            mask:           RL:             mask−MLE    RL−MLE
250     0.543±0.005  0.537±0.007  0.549±0.010  -0.0053(t=-0.8) +0.0060(t=+0.6)
500     0.567±0.008  0.573±0.018  0.579±0.009  +0.0060(t=+0.4) +0.0120(t=+1.0)
1000    0.586±0.013  0.583±0.012  0.577±0.007  -0.0027(t=-0.2) -0.0093(t=-1.6)
6000*   0.618±0.010  0.628±0.008  0.626±0.006  (*из D1.6, n=7 сидов)

========================================================================================
Кривая data-efficiency: 05B (генеративная accuracy, mean±std по 3 сидам)
========================================================================================
size    MLE:            mask:           RL:             mask−MLE    RL−MLE
250     0.377±0.020  0.390±0.016  0.395±0.008  +0.0127(t=+2.6) +0.0173(t=+1.3)
1000    0.513±0.018  0.501±0.032  0.510±0.015  -0.0127(t=-0.6) -0.0033(t=-1.2)
6000    0.541±0.005  0.551±0.012  0.557±0.009  +0.0093(t=+1.1) +0.0160(t=+3.8)

Вопрос: растёт ли mask−MLE / RL−MLE при уменьшении данных?
Гипотеза (а приори): вклад CRL максимален в low-resource зоне.
Итог: ./sweep_ld/summary_lowdata.json

In [10]:
# ============================================================
# РАСШИРЕНИЕ 0.5B-ячеек до n=7 (сиды 45-48), ПРЕДЗАЯВЛЕННО:
# обе ячейки (n=250 и n=6000), все 3 конфига, все сиды в отчёт,
# дальнейших расширений не будет. Мотивация: 0.5B×6000 RL−MLE =
# +0.016, 3/3 сида, каждый дифф ≥ +0.008 (t=3.8 при критe 4.303 —
# не хватило мощности). Время ~80 мин (0.5B: MLE ~3.3, mask ~6.5,
# RL ~5.3 мин).
# ============================================================
import copy
import math

EXT05B = [("05B", "Qwen/Qwen2.5-0.5B", 250), ("05B", "Qwen/Qwen2.5-0.5B", 6000)]
EXT_SEEDS = [45, 46, 47, 48]

for mshort, model_name, size in EXT05B:
    for seed in EXT_SEEDS:
        if any(r["model"] == mshort and r["seed"] == seed and r["size"] == size
               and all(k in r for k in SWEEP_CONFIGS) for r in ld_rows):
            print(f"[Resume] {mshort} s{seed} n={size} готов")
            continue
        shared = make_shared_start(model_name, seed)
        rebuild_d1_datasets(size)
        steps = math.ceil(size / cfg_sweep_base.batch_size) * \
            cfg_sweep_base.total_epochs
        row = {"model": mshort, "seed": seed, "size": size}
        for cname in SWEEP_CONFIGS:
            c = copy.copy(cfg_sweep_base)
            c.model_name = model_name
            c.seed = seed
            c.train_size = size
            c.init_selection_inits = 0
            c.warmup_steps = min(200, max(10, steps // 10))
            c.output_dir = f"./sweep_ld/{mshort}_{cname}_s{seed}_n{size}"
            if cname == "MLE":
                c.beta = 0.0; c.gamma = 0.0; c.gamma_auto = False
            elif cname == "mask":
                c.beta = 0.1; c.contrast_mode = "mask"
                c.gamma = 0.0; c.gamma_auto = False
            else:
                c.beta = 0.0; c.gamma = 2e-5; c.gamma_auto = True
            rj = os.path.join(c.output_dir, "results.json")
            if os.path.exists(rj):
                with open(rj) as f:
                    sc = json.load(f)["test_scores"]
            else:
                sc = run_experiment(
                    c, f"{cname} {mshort} n={size} (s{seed})", init_state=shared)
            row[cname] = sc["accuracy"]
            row[f"{cname}-verb"] = sc["verb_accuracy"]
            gc.collect(); torch.cuda.empty_cache()
        ld_rows = [r for r in ld_rows
                   if not (r["model"] == mshort and r["seed"] == seed
                           and r["size"] == size)] + [row]
        with open(_summary_ld, "w") as f:
            json.dump({"rows": ld_rows}, f, indent=2)
        print(f">>> {mshort} s{seed} n={size}: "
              f"{ {k: round(row[k], 4) for k in SWEEP_CONFIGS} }\n")
        del shared
        gc.collect(); torch.cuda.empty_cache()

# вердикт по расширенным ячейкам
from math import sqrt
for size in (250, 6000):
    rs = [r for r in ld_rows if r["model"] == "05B" and r["size"] == size]
    n = len(rs)
    if n < 4:
        continue
    print(f"\n0.5B n={size} (n_сидов={n}):")
    for a in ("mask", "RL"):
        dd = [r[a] - r["MLE"] for r in rs]
        se = np.std(dd, ddof=1) / sqrt(n)
        t = np.mean(dd) / se if se > 0 else float("nan")
        crit = {4: 3.182, 5: 2.776, 6: 2.571, 7: 2.447}[n]
        print(f"  {a}−MLE: {np.mean(dd):+.4f} ± {np.std(dd, ddof=1):.4f} | "
              f"t={t:+.2f} (крит {crit}) | per-seed "
              f"{[f'{x:+.4f}' for x in dd]} | "
              f"{'ЗНАЧИМО' if abs(t) > crit else 'н.з.'}")

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10518.22it/s]
Map: 100%|██████████| 250/250 [00:00<00:00, 7911.81 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 7933.24 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7972.23 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8345.27 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 05B n=250 (s45)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 8819.42it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 8.689 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 8.116 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 6.570 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.504 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.3100 | best=0.3100 @ epoch 1
[Step 40] CE/token (EMA): 3.619 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.253 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 2.948 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified

the author's fear | scared
describe the fear of | excited

regret: guilty | scared

filling her with
[ValMetric epoch 2] accuracy=0.3300 | best=0.3300 @ epoch 2
[Step 70] CE/token (EMA): 2.613 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.379 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.218 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified
fill in the blank | afraid
filling: afraid | excited

the author's emotions | surprised

what is the emotional
[ValMetric epoch 3] accuracy=0.3800 | best=0.3800 @ epoch 3
[Step 100] CE/token (EMA): 2.284 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.099 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.001 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified
fill in the blank | afraid
filling: afraid | excited

the author's emotions | surprised

how to respect a
[ValMetric epoch 4] accuracy=0.3850 | best=0.3850 @ epoch 4

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3850 @ epoch 4 -> best_prefix.pt

MLE 05B n=250 (s45) completed in 0.4 min
Loaded best adapter: val accuracy=0.3850 @ epoch 4 (история: [0.31, 0.33, 0.38, 0.385])

Evaluating MLE 05B n=250 (s45) on test set (clean protocol)...

======================================================================
RESULTS: MLE 05B n=250 (s45)
======================================================================
accuracy: 0.3920
verb_accuracy: 0.4140
======================================================================

Примеры ошибок (ref -> pred | генерация):
  guilty         -> annoyed        | 'annoyed, afraid, and angry'
  caring         -> None           | 'in the process of starving.'
  lonely         -> None           | 'empty\ndescribe the emotion the'
  excited        -> anticipating   | 'anticipating the anticipation '
  sad            -> guilty         | 'guilty\n 5.6'
  caring         -> None           | 'optimistic\ndesponding,'
Results saved to ./sweep_ld/05B_MLE_s45_n250/results.json

======================================================================
STARTING EXPERIMENT: mask 05B n=250 (s45)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9388.45it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 8.689 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 8.123 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 6.551 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.474 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.3100 | best=0.3100 @ epoch 1
[Step 40] CE/token (EMA): 3.646 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.259 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 2.975 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified

regretted, | scared
desperate

in | excited

regretful, | scared

filling her face
[ValMetric epoch 2] accuracy=0.3450 | best=0.3450 @ epoch 2
[Step 70] CE/token (EMA): 2.624 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.386 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.233 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified
desperate
f | afraid
desperate

in | excited

filling in the | surprised

filling her face
[ValMetric epoch 3] accuracy=0.3700 | best=0.3700 @ epoch 3
[Step 100] CE/token (EMA): 2.264 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.081 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.001 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified

regretted, | afraid
desperate

in | excited

filling in the | scared

filling her with
[ValMetric epoch 4] accuracy=0.3800 | best=0.3800 @ epoch 4

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3800 @ epoch 4 -> best_prefix.pt

mask 05B n=250 (s45) completed in 0.5 min
Loaded best adapter: val accuracy=0.3800 @ epoch 4 (история: [0.31, 0.345, 0.37, 0.38])

Evaluating mask 05B n=250 (s45) on test set (clean protocol)...

======================================================================
RESULTS: mask 05B n=250 (s45)
======================================================================
accuracy: 0.3940
verb_accuracy: 0.4160
======================================================================

Примеры ошибок (ref -> pred | генерация):
  guilty         -> angry          | 'angry\n\nhow the narrator feels'
  caring         -> None           | 'in the process of mourning the'
  lonely         -> None           | 'empty\ndesponding,'
  excited        -> anticipating   | 'anticipating Christmas.\n\nantic'
  sad            -> devastated     | 'devastated\ndesperate\nhope'
  caring         -> hopeful        | 'optimistic, hopeful, optimisti'
Results saved to ./sweep_ld/05B_mask_s45_n250/results.json

======================================================================
STARTING EXPERIMENT: RL 05B n=250 (s45)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10161.89it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma calibration postponed
[RL sample] REF: 'prepared'
[RL sample] GEN: 'Love & Relationships\n\n#'
[RL step 0] reward=0.0000 adv=+0.0000 gamma=2.00e-05
[Step 0] CE/token (EMA): 8.689 | Contrast[mask]: 0.000 | RL: -0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 8.116 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 6.578 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.501 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2900 | best=0.2900 @ epoch 1
[Step 40] CE/token (EMA): 3.639 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL] gamma auto-calibrated to 1.375e-06
[RL sample] REF: 'content'
[RL sample] GEN: 'anxious.\nnervous.'
[RL step 50] reward=0.3516 adv=+0.3516 gamma=1.38e-06
[Step 50] CE/token (EMA): 3.263 | Contrast[mask]: 0.000 | RL: -0.979 | Reward: 0.3516
[Step 60] CE/token (EMA): 2.977 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified

the author's fear | scared
describe the fear of | excited

the author's emotions | surprised

the surprise surprised the
[ValMetric epoch 2] accuracy=0.3550 | best=0.3550 @ epoch 2
[Step 70] CE/token (EMA): 2.626 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.398 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.241 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified, intimidated, and paralyzed | afraid

the fear of the | excited

the author's emotions | surprised surprised surprised surprised surprised surprised
[ValMetric epoch 3] accuracy=0.3700 | best=0.3700 @ epoch 3
[RL sample] REF: 'disappointed'
[RL sample] GEN: "sad.\n\nthe author's emotional"
[RL step 100] reward=0.4688 adv=+0.4336 gamma=1.38e-06
[Step 100] CE/token (EMA): 2.376 | Contrast[mask]: 0.000 | RL: -1.206 | Reward: 0.4688
[Step 110] CE/token (EMA): 2.154 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.046 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified, intimidated, and paralyzed | afraid

the fear of the | excited

the author's emotions | surprised, surprised

filling
[ValMetric epoch 4] accuracy=0.3650 | best=0.3700 @ epoch 3

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3700 @ epoch 3 -> best_prefix.pt

RL 05B n=250 (s45) completed in 0.5 min
Loaded best adapter: val accuracy=0.3700 @ epoch 3 (история: [0.29, 0.355, 0.37, 0.365])

Evaluating RL 05B n=250 (s45) on test set (clean protocol)...

======================================================================
RESULTS: RL 05B n=250 (s45)
======================================================================
accuracy: 0.4000
verb_accuracy: 0.4300
======================================================================

Примеры ошибок (ref -> pred | генерация):
  guilty         -> afraid         | 'afraid\n\nthe speaker is afraid'
  caring         -> None           | 'in the process of dying.'
  lonely         -> None           | 'empty\n\nthe speaker feels empty'
  excited        -> None           | 'expecting a present for a Chri'
  sad            -> guilty         | 'guilty.\nthoughts: guilty'
  caring         -> hopeful        | 'optimistic, hopeful, optimisti'
Results saved to ./sweep_ld/05B_RL_s45_n250/results.json
>>> 05B s45 n=250: {'MLE': 0.392, 'mask': 0.394, 'RL': 0.4}

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9807.76it/s]
Map: 100%|██████████| 250/250 [00:00<00:00, 7551.92 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 8061.24 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7921.22 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8523.74 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 05B n=250 (s46)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9746.85it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 8.633 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 8.034 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 6.531 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.352 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2250 | best=0.2250 @ epoch 1
[Step 40] CE/token (EMA): 3.446 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.249 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 2.998 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified
place: in the | curious
thoughts: afraid | excited
subject: I am | scared
place: home
[ValMetric epoch 2] accuracy=0.3450 | best=0.3450 @ epoch 2
[Step 70] CE/token (EMA): 2.646 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.422 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.254 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified
place: in the | surprised
and
embarrass | excited
subjecting: will | surprised
place: home
[ValMetric epoch 3] accuracy=0.3750 | best=0.3750 @ epoch 3
[Step 100] CE/token (EMA): 2.152 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.008 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 1.924 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified
place: in the | afraid
subjecting
to | excited
subjecting: will | terrified
place: home
[ValMetric epoch 4] accuracy=0.3750 | best=0.3750 @ epoch 3

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3750 @ epoch 3 -> best_prefix.pt

MLE 05B n=250 (s46) completed in 0.4 min
Loaded best adapter: val accuracy=0.3750 @ epoch 3 (история: [0.225, 0.345, 0.375, 0.375])

Evaluating MLE 05B n=250 (s46) on test set (clean protocol)...

======================================================================
RESULTS: MLE 05B n=250 (s46)
======================================================================
accuracy: 0.3940
verb_accuracy: 0.4160
======================================================================

Примеры ошибок (ref -> pred | генерация):
  guilty         -> embarrassed    | 'embarrassed\ndescription: embar'
  caring         -> None           | 'hungry. I was_ hungry'
  lonely         -> None           | 'emptying emptying emptying'
  excited        -> joyful         | 'joyful\nsubjecting\nsit'
  sad            -> afraid         | 'afraid\nAppearance: scared'
  caring         -> hopeful        | 'hopeful\nsubjecting\ncharacter'
Results saved to ./sweep_ld/05B_MLE_s46_n250/results.json

======================================================================
STARTING EXPERIMENT: mask 05B n=250 (s46)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9951.63it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 8.633 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 8.027 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 6.536 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.355 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2400 | best=0.2400 @ epoch 1
[Step 40] CE/token (EMA): 3.471 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.268 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.009 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified
place: in the | afraid
description: afraid | excited
subject: I am | surprised
place: home
[ValMetric epoch 2] accuracy=0.3250 | best=0.3250 @ epoch 2
[Step 70] CE/token (EMA): 2.647 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.438 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.243 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified
place: in the | afraid
subject: afraid | excited
subject: will be | terrified
place: home
[ValMetric epoch 3] accuracy=0.4000 | best=0.4000 @ epoch 3
[Step 100] CE/token (EMA): 2.152 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.036 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 1.949 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified
location: in the | afraid
subject: afraid | excited
subject: will be | terrified
location: home
[ValMetric epoch 4] accuracy=0.3950 | best=0.4000 @ epoch 3

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.4000 @ epoch 3 -> best_prefix.pt

mask 05B n=250 (s46) completed in 0.5 min
Loaded best adapter: val accuracy=0.4000 @ epoch 3 (история: [0.24, 0.325, 0.4, 0.395])

Evaluating mask 05B n=250 (s46) on test set (clean protocol)...

======================================================================
RESULTS: mask 05B n=250 (s46)
======================================================================
accuracy: 0.4120
verb_accuracy: 0.4280
======================================================================

Примеры ошибок (ref -> pred | генерация):
  guilty         -> embarrassed    | 'embarrassed\nsubjecting\nemb'
  caring         -> None           | 'hungry. I was so moved'
  lonely         -> None           | 'emptying my body\ncom'
  excited        -> joyful         | 'joyful\nsubject: I'
  sad            -> afraid         | 'afraid\nAppearance: scared'
  caring         -> None           | 'comforting\nsubjecting\nobject'
Results saved to ./sweep_ld/05B_mask_s46_n250/results.json

======================================================================
STARTING EXPERIMENT: RL 05B n=250 (s46)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10034.05it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 5.460e-05
[RL sample] REF: 'prepared'
[RL sample] GEN: 'love\nAction-verb:'
[RL step 0] reward=0.0234 adv=+0.0234 gamma=5.46e-05
[Step 0] CE/token (EMA): 8.633 | Contrast[mask]: 0.000 | RL: -2.590 | Reward: 0.0234

[Step 10] CE/token (EMA): 8.021 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 6.530 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.342 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2200 | best=0.2200 @ epoch 1
[Step 40] CE/token (EMA): 3.437 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'content\npersonas: content'
[RL step 50] reward=0.3672 adv=+0.3648 gamma=5.46e-05
[Step 50] CE/token (EMA): 3.227 | Contrast[mask]: 0.000 | RL: -40.315 | Reward: 0.3672
[Step 60] CE/token (EMA): 2.968 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified
place: home | afraid
place: home | excited
subject: I'm | surprised
place: home
[ValMetric epoch 2] accuracy=0.3300 | best=0.3300 @ epoch 2
[Step 70] CE/token (EMA): 2.632 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.424 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.249 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified
place: in the | afraid
subject: afraid | excited
subject: will be | terrified
place: home
[ValMetric epoch 3] accuracy=0.3650 | best=0.3650 @ epoch 3
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed\ncharacteristic: disappointed'
[RL step 100] reward=0.5469 adv=+0.5080 gamma=5.46e-05
[Step 100] CE/token (EMA): 2.164 | Contrast[mask]: 0.000 | RL: -56.131 | Reward: 0.5469
[Step 110] CE/token (EMA): 2.033 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 1.940 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified
place: in the | afraid
subject: afraid | excited
subject: will be | terrified
place: home
[ValMetric epoch 4] accuracy=0.3550 | best=0.3650 @ epoch 3

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3650 @ epoch 3 -> best_prefix.pt

RL 05B n=250 (s46) completed in 0.5 min
Loaded best adapter: val accuracy=0.3650 @ epoch 3 (история: [0.22, 0.33, 0.365, 0.355])

Evaluating RL 05B n=250 (s46) on test set (clean protocol)...

======================================================================
RESULTS: RL 05B n=250 (s46)
======================================================================
accuracy: 0.4020
verb_accuracy: 0.4320
======================================================================

Примеры ошибок (ref -> pred | генерация):
  guilty         -> embarrassed    | 'embarrassed\nsubjecting\nemb'
  caring         -> None           | 'hungry. I was_ hungry'
  lonely         -> None           | 'emptying emptying emptying'
  excited        -> joyful         | 'joyful\nsubject: I'
  sad            -> afraid         | 'afraid\nAppearance: scared'
  caring         -> hopeful        | 'hopeful\nsubjecting\ncharacter'
Results saved to ./sweep_ld/05B_RL_s46_n250/results.json
>>> 05B s46 n=250: {'MLE': 0.394, 'mask': 0.412, 'RL': 0.402}

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10484.77it/s]
Map: 100%|██████████| 250/250 [00:00<00:00, 7738.74 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 8106.35 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7966.72 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8473.26 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 05B n=250 (s47)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9777.09it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 9.329 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 8.679 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 7.053 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.754 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2650 | best=0.2650 @ epoch 1
[Step 40] CE/token (EMA): 3.708 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.359 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.032 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified
description: terrified | afraid
person: the child | excited.
gender: female. | surprised
person: a mother
[ValMetric epoch 2] accuracy=0.3300 | best=0.3300 @ epoch 2
[Step 70] CE/token (EMA): 2.619 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.415 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.279 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified
description: terrified | terrified
description: terrified | excited
description: feeling excited | terrified
description: terrified
[ValMetric epoch 3] accuracy=0.3700 | best=0.3700 @ epoch 3
[Step 100] CE/token (EMA): 2.294 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.036 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 1.991 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified, afraid, terrified | terrified
description: terrified | excited
description: feeling excited | surprised
description: surprised
[ValMetric epoch 4] accuracy=0.3800 | best=0.3800 @ epoch 4

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3800 @ epoch 4 -> best_prefix.pt

MLE 05B n=250 (s47) completed in 0.4 min
Loaded best adapter: val accuracy=0.3800 @ epoch 4 (история: [0.265, 0.33, 0.37, 0.38])

Evaluating MLE 05B n=250 (s47) on test set (clean protocol)...

======================================================================
RESULTS: MLE 05B n=250 (s47)
======================================================================
accuracy: 0.3920
verb_accuracy: 0.4160
======================================================================

Примеры ошибок (ref -> pred | генерация):
  guilty         -> afraid         | 'afraid\ngender: female'
  caring         -> None           | 'in a state of hunger_com'
  excited        -> surprised      | 'surprised, surprised, surprise'
  caring         -> None           | 'concerned, worried, concerned'
  angry          -> guilty         | 'guilty\nnarrating the'
  joyful         -> anxious        | 'anxious, fearful, and worried'
Results saved to ./sweep_ld/05B_MLE_s47_n250/results.json

======================================================================
STARTING EXPERIMENT: mask 05B n=250 (s47)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9664.76it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 9.329 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 8.677 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 7.026 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.748 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2700 | best=0.2700 @ epoch 1
[Step 40] CE/token (EMA): 3.725 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.384 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.072 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified
description: terrified | afraid
gender: female | excited.
gender: female. | disgusted
gender: female
[ValMetric epoch 2] accuracy=0.3400 | best=0.3400 @ epoch 2
[Step 70] CE/token (EMA): 2.598 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.426 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.333 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified, anxious, fearful, | terrified
description: terrified | excited
gender: female | disgusted
description: disgusted
[ValMetric epoch 3] accuracy=0.3850 | best=0.3850 @ epoch 3
[Step 100] CE/token (EMA): 2.321 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.075 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.048 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified, anxious, fearful, | terrified
description: terrified | excited.
gender: female. | disgusted
description: disgusted
[ValMetric epoch 4] accuracy=0.3900 | best=0.3900 @ epoch 4

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3900 @ epoch 4 -> best_prefix.pt

mask 05B n=250 (s47) completed in 0.5 min
Loaded best adapter: val accuracy=0.3900 @ epoch 4 (история: [0.27, 0.34, 0.385, 0.39])

Evaluating mask 05B n=250 (s47) on test set (clean protocol)...

======================================================================
RESULTS: mask 05B n=250 (s47)
======================================================================
accuracy: 0.3940
verb_accuracy: 0.4140
======================================================================

Примеры ошибок (ref -> pred | генерация):
  caring         -> None           | 'in a state of hunger.'
  excited        -> None           | 'expecting the unexpected.\nsubj'
  caring         -> None           | 'concerned, worried, worried'
  angry          -> guilty         | 'guilty\nrace: guilty'
  joyful         -> anxious        | 'anxious, fearful, and anxious'
  faithful       -> guilty         | 'guilty\ngender: female'
Results saved to ./sweep_ld/05B_mask_s47_n250/results.json

======================================================================
STARTING EXPERIMENT: RL 05B n=250 (s47)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10538.18it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 3.540e-05
[RL sample] REF: 'prepared'
[RL sample] GEN: 'Thinking\nEmotion: Happiness'
[RL step 0] reward=0.0391 adv=+0.0391 gamma=3.54e-05
[Step 0] CE/token (EMA): 9.329 | Contrast[mask]: 0.000 | RL: -2.799 | Reward: 0.0391

[Step 10] CE/token (EMA): 8.709 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 7.076 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.796 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2550 | best=0.2550 @ epoch 1
[Step 40] CE/token (EMA): 3.733 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'comfortable\nrace: american'
[RL step 50] reward=0.4141 adv=+0.4102 gamma=3.54e-05
[Step 50] CE/token (EMA): 3.395 | Contrast[mask]: 0.000 | RL: -29.390 | Reward: 0.4141
[Step 60] CE/token (EMA): 3.064 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified
gender: female | afraid
person: the child | excited
gender: female | surprised
person 1:
[ValMetric epoch 2] accuracy=0.3000 | best=0.3000 @ epoch 2
[Step 70] CE/token (EMA): 2.670 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.469 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.346 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified
gender: female | terrified
person: the mother | excited
gender: female | surprised
desires: surprised
[ValMetric epoch 3] accuracy=0.3450 | best=0.3450 @ epoch 3
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'sad\nAnswers checkup'
[RL step 100] reward=0.5078 adv=+0.4629 gamma=3.54e-05
[Step 100] CE/token (EMA): 2.380 | Contrast[mask]: 0.000 | RL: -33.149 | Reward: 0.5078
[Step 110] CE/token (EMA): 2.108 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.036 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified, afraid, or terrified | terrified
on the inside: | excited
gender: female | surprised
desires: surprised
[ValMetric epoch 4] accuracy=0.3500 | best=0.3500 @ epoch 4

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3500 @ epoch 4 -> best_prefix.pt

RL 05B n=250 (s47) completed in 0.5 min
Loaded best adapter: val accuracy=0.3500 @ epoch 4 (история: [0.255, 0.3, 0.345, 0.35])

Evaluating RL 05B n=250 (s47) on test set (clean protocol)...

======================================================================
RESULTS: RL 05B n=250 (s47)
======================================================================
accuracy: 0.3820
verb_accuracy: 0.4040
======================================================================

Примеры ошибок (ref -> pred | генерация):
  guilty         -> afraid         | 'afraid\ncolor: afraid'
  caring         -> None           | 'in a state of hunger.'
  excited        -> surprised      | 'surprised, surprised with the '
  sad            -> devastated     | 'devastated and grieving over t'
  caring         -> None           | 'concerned\ndesires: concerned'
  angry          -> afraid         | 'afraid, concerned, afraid'
Results saved to ./sweep_ld/05B_RL_s47_n250/results.json
>>> 05B s47 n=250: {'MLE': 0.392, 'mask': 0.394, 'RL': 0.382}

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9393.67it/s]
Map: 100%|██████████| 250/250 [00:00<00:00, 7283.60 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 7657.61 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7604.25 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8466.53 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 05B n=250 (s48)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10187.60it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 9.364 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 8.946 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 6.972 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.626 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2750 | best=0.2750 @ epoch 1
[Step 40] CE/token (EMA): 3.558 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.201 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.087 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified
Name: terrified | terrified.
description: terrified | excited
desires: to | terrified
description: terrified
[ValMetric epoch 2] accuracy=0.3800 | best=0.3800 @ epoch 2
[Step 70] CE/token (EMA): 2.585 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.347 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.341 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified
Name: terrified | terrified
Name: afraid | excited
I'm feeling excited | terrified
Name: child
[ValMetric epoch 3] accuracy=0.3650 | best=0.3800 @ epoch 2
[Step 100] CE/token (EMA): 2.263 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.014 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 1.813 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified
Name: terrified | terrified
Name: afraid | excited
I'm feeling excited | terrified
Name: child
[ValMetric epoch 4] accuracy=0.3500 | best=0.3800 @ epoch 2

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3800 @ epoch 2 -> best_prefix.pt

MLE 05B n=250 (s48) completed in 0.4 min
Loaded best adapter: val accuracy=0.3800 @ epoch 2 (история: [0.275, 0.38, 0.365, 0.35])

Evaluating MLE 05B n=250 (s48) on test set (clean protocol)...

======================================================================
RESULTS: MLE 05B n=250 (s48)
======================================================================
accuracy: 0.3740
verb_accuracy: 0.3960
======================================================================

Примеры ошибок (ref -> pred | генерация):
  caring         -> None           | 'in the process of starving_com'
  sad            -> afraid         | 'afraid\nIn the dark,'
  caring         -> None           | 'comforting\nConstance is comfor'
  angry          -> afraid         | 'afraid\nPlace of escape:'
  joyful         -> excited        | "excited\nI'm ready!"
  faithful       -> guilty         | 'guilty\ndescription: guilty'
Results saved to ./sweep_ld/05B_MLE_s48_n250/results.json

======================================================================
STARTING EXPERIMENT: mask 05B n=250 (s48)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9542.16it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 9.364 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 8.945 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 6.970 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.627 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2850 | best=0.2850 @ epoch 1
[Step 40] CE/token (EMA): 3.563 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.185 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.122 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified
Name: terrified | terrified.
Place: home | excited.
Describe the moment of | terrified
Place: the ground
[ValMetric epoch 2] accuracy=0.3300 | best=0.3300 @ epoch 2
[Step 70] CE/token (EMA): 2.583 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.344 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.326 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified
Name: terrified | terrified.
What's on my | excited.
I have a romantic | annoyed
Name: annoyed
[ValMetric epoch 3] accuracy=0.3600 | best=0.3600 @ epoch 3
[Step 100] CE/token (EMA): 2.242 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 1.972 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 1.772 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified
Name: terrified | terrified.
What's on my | excited
desires: excited | surprised
Name: surprised
[ValMetric epoch 4] accuracy=0.3500 | best=0.3600 @ epoch 3

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3600 @ epoch 3 -> best_prefix.pt

mask 05B n=250 (s48) completed in 0.5 min
Loaded best adapter: val accuracy=0.3600 @ epoch 3 (история: [0.285, 0.33, 0.36, 0.35])

Evaluating mask 05B n=250 (s48) on test set (clean protocol)...

======================================================================
RESULTS: mask 05B n=250 (s48)
======================================================================
accuracy: 0.4000
verb_accuracy: 0.4360
======================================================================

Примеры ошибок (ref -> pred | генерация):
  caring         -> None           | 'in the process_comma_'
  sad            -> afraid         | 'afraid\nConceptualizing the'
  caring         -> None           | 'concerned\nIn the situation,'
  angry          -> guilty         | 'guilty\nIn the situation,'
  joyful         -> excited        | 'excited\nContext: preparing for'
  disappointed   -> excited        | 'excited\ndefinitely excited'
Results saved to ./sweep_ld/05B_mask_s48_n250/results.json

======================================================================
STARTING EXPERIMENT: RL 05B n=250 (s48)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9698.43it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 1.777e-04
[RL sample] REF: 'prepared'
[RL sample] GEN: 'Happiness\nHypnaca'
[RL step 0] reward=0.0078 adv=+0.0078 gamma=1.78e-04
[Step 0] CE/token (EMA): 9.364 | Contrast[mask]: 0.000 | RL: -2.809 | Reward: 0.0078

[Step 10] CE/token (EMA): 8.948 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 6.978 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.622 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2750 | best=0.2750 @ epoch 1
[Step 40] CE/token (EMA): 3.535 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'indifferent.\nActivity: indifferent.'
[RL step 50] reward=0.4219 adv=+0.4211 gamma=1.78e-04
[Step 50] CE/token (EMA): 3.172 | Contrast[mask]: 0.000 | RL: -151.468 | Reward: 0.4219
[Step 60] CE/token (EMA): 3.105 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified
Name: terrified | terrified.
Describe the scene in | excited.
I'm ready to | terrified
description: terrified
[ValMetric epoch 2] accuracy=0.3350 | best=0.3350 @ epoch 2
[Step 70] CE/token (EMA): 2.592 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.391 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.405 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified
Name: terrified | terrified
I was afraid of | excited.
I have a cold | terrified
name: scared
[ValMetric epoch 3] accuracy=0.3650 | best=0.3650 @ epoch 3
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'sad\nDescribe the sad.'
[RL step 100] reward=0.5156 adv=+0.4727 gamma=1.78e-04
[Step 100] CE/token (EMA): 2.284 | Contrast[mask]: 0.000 | RL: -170.001 | Reward: 0.5156
[Step 110] CE/token (EMA): 2.055 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 1.845 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified
Name: terrified | terrified
Name: afraid | excited.
I have a cold | terrified
Name: terrified
[ValMetric epoch 4] accuracy=0.3450 | best=0.3650 @ epoch 3

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3650 @ epoch 3 -> best_prefix.pt

RL 05B n=250 (s48) completed in 0.5 min
Loaded best adapter: val accuracy=0.3650 @ epoch 3 (история: [0.275, 0.335, 0.365, 0.345])

Evaluating RL 05B n=250 (s48) on test set (clean protocol)...

======================================================================
RESULTS: RL 05B n=250 (s48)
======================================================================
accuracy: 0.3940
verb_accuracy: 0.4160
======================================================================

Примеры ошибок (ref -> pred | генерация):
  caring         -> None           | 'in the process of starving_com'
  lonely         -> None           | 'empty\nName: empty'
  excited        -> None           | "festive.\nI'm a festive"
  sad            -> afraid         | 'afraid\nIn the dark,'
  caring         -> None           | "comforting\nI'm comforting my"
  angry          -> guilty         | 'guilty\nimagining my neighbour'
Results saved to ./sweep_ld/05B_RL_s48_n250/results.json
>>> 05B s48 n=250: {'MLE': 0.374, 'mask': 0.4, 'RL': 0.394}

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10165.80it/s]
Map: 100%|██████████| 6000/6000 [00:00<00:00, 10095.79 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 8034.91 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7712.67 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8415.90 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 05B n=6000 (s45)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9342.58it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 9.710 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 9.477 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 8.759 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 8.071 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.075 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 5.902 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 5.066 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 4.473 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.169 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 4.070 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 3.829 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 3.500 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.366 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.951 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.825 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.848 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.670 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.570 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.578 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.360 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.464 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.262 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.309 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.290 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.174 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 2.120 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 2.127 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.062 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 2.085 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 2.019 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.948 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.988 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.900 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.841 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.999 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 2.013 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 2.020 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.853 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.916 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 2.062 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.931 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.777 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.716 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.677 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.780 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.908 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 2.118 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 2.037 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.857 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.666 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.726 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.710 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.702 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.672 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.668 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.702 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.712 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.715 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.803 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.747 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.661 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.698 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.541 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.529 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.639 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.693 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.597 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.493 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.470 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.560 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.498 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.481 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.453 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.569 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.757 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.4750 | best=0.4750 @ epoch 1
[Step 750] CE/token (EMA): 1.718 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.616 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.680 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.529 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.660 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.681 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.597 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.666 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.651 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.584 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.535 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.638 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.649 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.638 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.526 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.498 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.483 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.517 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.501 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.531 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.548 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.567 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.596 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.564 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.477 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.369 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.415 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.568 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.579 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.567 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.502 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.434 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.439 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.386 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.657 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.580 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.491 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.510 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.517 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.476 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.569 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.669 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.748 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.573 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.542 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.575 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.538 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.538 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.579 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.546 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.552 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.506 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.404 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.497 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.410 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.366 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.341 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.372 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.480 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.533 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.536 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.561 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.443 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.427 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.463 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.588 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.558 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.534 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.541 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.501 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.494 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.440 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.460 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.538 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified, terrified afraid, terrified | surprised surprised surprised surprised surprised surprised | excited excited excited excited excited excited | terrified, terrified, terrified,
[ValMetric epoch 2] accuracy=0.5250 | best=0.5250 @ epoch 2
[Step 1500] CE/token (EMA): 1.449 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.357 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.311 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.281 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.318 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.419 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.526 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.486 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.458 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.446 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.539 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.638 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.600 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.541 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.464 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.338 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.244 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.248 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.358 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.305 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.333 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.211 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.212 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.281 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.310 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.416 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.376 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.405 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.396 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.367 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.346 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.343 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.451 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.467 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.422 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.367 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.539 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.590 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.412 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.376 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.424 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.531 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.476 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.346 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.332 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.295 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.228 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.255 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.080 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.121 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.215 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.155 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.172 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.300 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.342 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.425 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.326 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.459 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.375 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.278 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.237 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.184 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.372 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.276 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.394 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.254 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.131 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.197 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.257 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.282 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.407 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified, terrified afraid of dangerous | surprised surprised surprised surprised surprised surprised | excited excited excited excited excited excited | terrified, terrified terrified terrified terrified
[ValMetric epoch 3] accuracy=0.5350 | best=0.5350 @ epoch 3

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9354.51it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 9.710 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 9.477 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 8.758 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 8.068 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.077 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 5.898 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 5.061 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 4.472 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.161 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 4.208 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 3.901 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 3.538 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.366 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 3.002 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.860 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.870 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.679 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.548 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.553 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.346 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.468 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.258 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.302 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.283 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.149 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 2.084 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 2.132 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.078 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 2.105 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 2.020 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.956 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 2.018 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.907 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.854 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.995 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 2.034 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 2.067 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.916 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.946 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 2.115 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.956 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.803 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.744 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.643 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.765 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.892 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 2.106 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 2.038 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.862 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.669 | Contrast[mask]: 0.669 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.725 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.713 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.723 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.713 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.710 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.721 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.726 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.742 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.844 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.759 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.650 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.690 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.520 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.512 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.626 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.698 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.591 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.521 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.490 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.581 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.505 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.479 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.463 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.607 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.782 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5350 | best=0.5350 @ epoch 1
[Step 750] CE/token (EMA): 1.702 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.629 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.706 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.526 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.671 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.720 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.621 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.681 | Contrast[mask]: 0.669 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.660 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.615 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.550 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.662 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.675 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.637 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.520 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.509 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.519 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.520 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.488 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.501 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.525 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.537 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.604 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.564 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.474 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.401 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.445 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.618 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.592 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.596 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.486 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.419 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.444 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.400 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.663 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.582 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.493 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.499 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.499 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.479 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.565 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.639 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.684 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.553 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.541 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.549 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.542 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.531 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.597 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.548 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.546 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.502 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.385 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.485 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.385 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.378 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.298 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.373 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.363 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.525 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.549 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.537 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.546 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.456 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.422 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.454 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.596 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.562 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.546 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.562 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.524 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.519 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.462 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.473 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.539 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified, terrified, terrified, | surprised surprised surprised surprised surprised surprised | excited excited excited excited excited excited | terrified terrified terrified terrified terrified terrified
[ValMetric epoch 2] accuracy=0.5450 | best=0.5450 @ epoch 2
[Step 1500] CE/token (EMA): 1.436 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.341 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.294 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.243 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.280 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.325 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.433 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.496 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.481 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.484 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.444 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.531 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.649 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.613 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.527 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.449 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.341 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.252 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.266 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.383 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.316 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.334 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.234 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.232 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.319 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.351 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.443 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.404 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.440 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.432 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.397 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.370 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.348 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.453 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.476 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.440 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.368 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.522 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.580 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.490 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.375 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.380 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.403 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.506 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.473 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.359 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.341 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.300 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.237 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.233 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.064 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.120 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.227 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.155 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.155 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.298 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.326 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.424 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.436 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.350 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.480 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.388 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.288 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.247 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.182 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.361 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.242 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.391 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.258 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.151 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.228 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.272 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.255 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.279 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.430 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified terrified terrified terrified terrified terrified | terrified angry with afraid angry with | excited excited excited excited excited excited | terrified terrified terrified terrified terrified terrified

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10077.03it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma calibration postponed
[RL sample] REF: 'prepared'
[RL sample] GEN: 'Love & Relationships\n\n#'
[RL step 0] reward=0.0000 adv=+0.0000 gamma=2.00e-05
[Step 0] CE/token (EMA): 9.710 | Contrast[mask]: 0.000 | RL: -0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 9.478 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 8.759 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 8.066 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.072 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL] gamma auto-calibrated to 3.388e-06
[RL sample] REF: 'content'
[RL sample] GEN: 'fat\nNarcotrema'
[RL step 50] reward=0.2578 adv=+0.2578 gamma=3.39e-06
[Step 50] CE/token (EMA): 5.896 | Contrast[mask]: 0.000 | RL: -1.769 | Reward: 0.2578
[Step 60] CE/token (EMA): 5.064 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 4.471 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.183 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 4.058 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'sad\nBased on the information'
[RL step 100] reward=0.3906 adv=+0.3648 gamma=3.39e-06
[Step 100] CE/token (EMA): 3.764 | Contrast[mask]: 0.000 | RL: -2.499 | Reward: 0.3906
[Step 110] CE/token (EMA): 3.427 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.248 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.887 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.769 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'sad\nReasoning: the'
[RL step 150] reward=0.4531 adv=+0.3909 gamma=3.39e-06
[Step 150] CE/token (EMA): 2.805 | Contrast[mask]: 0.000 | RL: -2.679 | Reward: 0.4531
[Step 160] CE/token (EMA): 2.620 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.505 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.538 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.316 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'disgusted disgusted disgusted disgusted disgusted disgusted'
[RL step 200] reward=0.3516 adv=+0.2502 gamma=3.39e-06
[Step 200] CE/token (EMA): 2.421 | Contrast[mask]: 0.000 | RL: -1.716 | Reward: 0.3516
[Step 210] CE/token (EMA): 2.203 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.267 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.273 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.164 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud and grateful\n\nI am'
[RL step 250] reward=0.3438 adv=+0.2174 gamma=3.39e-06
[Step 250] CE/token (EMA): 2.131 | Contrast[mask]: 0.000 | RL: -1.490 | Reward: 0.3438
[Step 260] CE/token (EMA): 2.121 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.058 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 2.081 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 2.004 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'terrified, terrified, terrified,'
[RL step 300] reward=0.5625 adv=+0.4144 gamma=3.39e-06
[Step 300] CE/token (EMA): 1.937 | Contrast[mask]: 0.000 | RL: -2.841 | Reward: 0.5625
[Step 310] CE/token (EMA): 1.982 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.879 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.847 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.997 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'surprised'
[RL sample] GEN: 'surprised and surprised.\n\nsurpr'
[RL step 350] reward=0.5781 adv=+0.3886 gamma=3.39e-06
[Step 350] CE/token (EMA): 2.011 | Contrast[mask]: 0.000 | RL: -2.664 | Reward: 0.5781
[Step 360] CE/token (EMA): 2.027 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.901 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.923 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 2.047 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'hopeful'
[RL sample] GEN: 'hopeful, anticipating the future,'
[RL step 400] reward=0.4375 adv=+0.2091 gamma=3.39e-06
[Step 400] CE/token (EMA): 1.904 | Contrast[mask]: 0.000 | RL: -1.433 | Reward: 0.4375
[Step 410] CE/token (EMA): 1.751 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.724 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.656 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.795 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'prepared'
[RL sample] GEN: 'prepared, confident, and prepared'
[RL step 450] reward=0.5156 adv=+0.2663 gamma=3.39e-06
[Step 450] CE/token (EMA): 1.887 | Contrast[mask]: 0.000 | RL: -1.825 | Reward: 0.5156
[Step 460] CE/token (EMA): 2.119 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 2.017 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.836 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.662 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'prepared for the anticipation.\n\nprepared'
[RL step 500] reward=0.4688 adv=+0.1928 gamma=3.39e-06
[Step 500] CE/token (EMA): 1.711 | Contrast[mask]: 0.000 | RL: -1.322 | Reward: 0.4688
[Step 510] CE/token (EMA): 1.694 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.704 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.689 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.682 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anticipating'
[RL sample] GEN: 'excited, excited, excited,'
[RL step 550] reward=0.5625 adv=+0.2673 gamma=3.39e-06
[Step 550] CE/token (EMA): 1.705 | Contrast[mask]: 0.000 | RL: -1.833 | Reward: 0.5625
[Step 560] CE/token (EMA): 1.725 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.775 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.844 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.758 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'lonely'
[RL sample] GEN: 'nostalgic, sentimental, sentimental,'
[RL step 600] reward=0.5625 adv=+0.2405 gamma=3.39e-06
[Step 600] CE/token (EMA): 1.668 | Contrast[mask]: 0.000 | RL: -1.650 | Reward: 0.5625
[Step 610] CE/token (EMA): 1.690 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.544 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.515 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.639 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anxious, prepared, prepared for'
[RL step 650] reward=0.3984 adv=+0.0524 gamma=3.39e-06
[Step 650] CE/token (EMA): 1.751 | Contrast[mask]: 0.000 | RL: -0.359 | Reward: 0.3984
[Step 660] CE/token (EMA): 1.619 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.549 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.523 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.591 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anticipating the anticipation for the new'
[RL step 700] reward=0.4375 adv=+0.0862 gamma=3.39e-06
[Step 700] CE/token (EMA): 1.507 | Contrast[mask]: 0.000 | RL: -0.591 | Reward: 0.4375
[Step 710] CE/token (EMA): 1.493 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.472 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.591 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.742 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.4850 | best=0.4850 @ epoch 1
[RL sample] REF: 'jealous'
[RL sample] GEN: 'annoyed with my sister in law'
[RL step 750] reward=0.4844 adv=+0.1245 gamma=3.39e-06
[Step 750] CE/token (EMA): 1.724 | Contrast[mask]: 0.000 | RL: -0.853 | Reward: 0.4844
[Step 760] CE/token (EMA): 1.588 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.676 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.507 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.653 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'anxious, anticipating the anticipation of'
[RL step 800] reward=0.6484 adv=+0.2761 gamma=3.39e-06
[Step 800] CE/token (EMA): 1.700 | Contrast[mask]: 0.000 | RL: -1.893 | Reward: 0.6484
[Step 810] CE/token (EMA): 1.609 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.699 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.672 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.630 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 850] reward=0.5312 adv=+0.1313 gamma=3.39e-06
[Step 850] CE/token (EMA): 1.564 | Contrast[mask]: 0.000 | RL: -0.900 | Reward: 0.5312
[Step 860] CE/token (EMA): 1.702 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.671 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.667 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.534 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'disgusted disgusted disgusted disgusted disgusted disgusted'
[RL step 900] reward=0.4219 adv=+0.0088 gamma=3.39e-06
[Step 900] CE/token (EMA): 1.513 | Contrast[mask]: 0.000 | RL: -0.060 | Reward: 0.4219
[Step 910] CE/token (EMA): 1.540 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.544 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.516 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.523 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'sad, sad, lonely'
[RL step 950] reward=0.4531 adv=+0.0392 gamma=3.39e-06
[Step 950] CE/token (EMA): 1.549 | Contrast[mask]: 0.000 | RL: -0.269 | Reward: 0.4531
[Step 960] CE/token (EMA): 1.579 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.611 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.551 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.487 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud that my dad stopped drinking'
[RL step 1000] reward=0.5859 adv=+0.1681 gamma=3.39e-06
[Step 1000] CE/token (EMA): 1.418 | Contrast[mask]: 0.000 | RL: -1.152 | Reward: 0.5859
[Step 1010] CE/token (EMA): 1.435 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.613 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.598 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.592 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disgusted'
[RL sample] GEN: 'disgusted, disgusted, disgusted,'
[RL step 1050] reward=0.6094 adv=+0.1747 gamma=3.39e-06
[Step 1050] CE/token (EMA): 1.494 | Contrast[mask]: 0.000 | RL: -1.197 | Reward: 0.6094
[Step 1060] CE/token (EMA): 1.444 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.449 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.384 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.674 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'nostalgic'
[RL sample] GEN: 'sentimental, sentimental, sentimental,'
[RL step 1100] reward=0.4297 adv=-0.0225 gamma=3.39e-06
[Step 1100] CE/token (EMA): 1.596 | Contrast[mask]: 0.000 | RL: 0.154 | Reward: 0.4297
[Step 1110] CE/token (EMA): 1.489 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.522 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.523 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.475 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sentimental'
[RL sample] GEN: 'sentimental, sentimental, sentimental,'
[RL step 1150] reward=0.4766 adv=+0.0267 gamma=3.39e-06
[Step 1150] CE/token (EMA): 1.555 | Contrast[mask]: 0.000 | RL: -0.183 | Reward: 0.4766
[Step 1160] CE/token (EMA): 1.662 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.695 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.545 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.549 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'confident'
[RL sample] GEN: 'prepared, prepared, anticipating the'
[RL step 1200] reward=0.5078 adv=+0.0552 gamma=3.39e-06
[Step 1200] CE/token (EMA): 1.547 | Contrast[mask]: 0.000 | RL: -0.379 | Reward: 0.5078
[Step 1210] CE/token (EMA): 1.561 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.548 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.611 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.562 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 1250] reward=0.5859 adv=+0.1278 gamma=3.39e-06
[Step 1250] CE/token (EMA): 1.544 | Contrast[mask]: 0.000 | RL: -0.877 | Reward: 0.5859
[Step 1260] CE/token (EMA): 1.509 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.384 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.389 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'jealous'
[RL sample] GEN: 'proud, confident, confident,'
[RL step 1300] reward=0.5781 adv=+0.1073 gamma=3.39e-06
[Step 1300] CE/token (EMA): 1.372 | Contrast[mask]: 0.000 | RL: -0.736 | Reward: 0.5781
[Step 1310] CE/token (EMA): 1.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.353 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.359 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.499 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited excited excited excited excited excited'
[RL step 1350] reward=0.4062 adv=-0.0753 gamma=3.39e-06
[Step 1350] CE/token (EMA): 1.558 | Contrast[mask]: 0.000 | RL: 0.517 | Reward: 0.4062
[Step 1360] CE/token (EMA): 1.555 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.559 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.470 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.453 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'caring, caring, caring,'
[RL step 1400] reward=0.5156 adv=+0.0416 gamma=3.39e-06
[Step 1400] CE/token (EMA): 1.491 | Contrast[mask]: 0.000 | RL: -0.285 | Reward: 0.5156
[Step 1410] CE/token (EMA): 1.616 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.579 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.558 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.596 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'afraid'
[RL sample] GEN: 'afraid, afraid of death.'
[RL step 1450] reward=0.5391 adv=+0.0608 gamma=3.39e-06
[Step 1450] CE/token (EMA): 1.542 | Contrast[mask]: 0.000 | RL: -0.417 | Reward: 0.5391
[Step 1460] CE/token (EMA): 1.533 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.494 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.466 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.523 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified, terrified, terrified, | surprised surprised surprised surprised surprised surprised | excited excited excited excited excited excited | disgusted disgusted disgusted disgusted disgusted disgusted
[ValMetric epoch 2] accuracy=0.5050 | best=0.5050 @ epoch 2
[RL sample] REF: 'annoyed'
[RL sample] GEN: 'annoyed, annoyed with the guilty'
[RL step 1500] reward=0.6484 adv=+0.1641 gamma=3.39e-06
[Step 1500] CE/token (EMA): 1.490 | Contrast[mask]: 0.000 | RL: -1.125 | Reward: 0.6484
[Step 1510] CE/token (EMA): 1.369 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.315 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.272 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.281 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'joyful'
[RL sample] GEN: 'joyful, joyful, joyful,'
[RL step 1550] reward=0.5469 adv=+0.0462 gamma=3.39e-06
[Step 1550] CE/token (EMA): 1.347 | Contrast[mask]: 0.000 | RL: -0.316 | Reward: 0.5469
[Step 1560] CE/token (EMA): 1.459 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.536 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.502 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.490 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'proud, joyful, excited,'
[RL step 1600] reward=0.4531 adv=-0.0522 gamma=3.39e-06
[Step 1600] CE/token (EMA): 1.460 | Contrast[mask]: 0.000 | RL: 0.358 | Reward: 0.4531
[Step 1610] CE/token (EMA): 1.551 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.633 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.599 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.520 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'caring'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 1650] reward=0.4609 adv=-0.0392 gamma=3.39e-06
[Step 1650] CE/token (EMA): 1.460 | Contrast[mask]: 0.000 | RL: 0.269 | Reward: 0.4609
[Step 1660] CE/token (EMA): 1.360 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.280 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.301 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.406 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'embarrassed'
[RL sample] GEN: 'embarrassed, ashamed, embarrassed,'
[RL step 1700] reward=0.5312 adv=+0.0351 gamma=3.39e-06
[Step 1700] CE/token (EMA): 1.337 | Contrast[mask]: 0.000 | RL: -0.240 | Reward: 0.5312
[Step 1710] CE/token (EMA): 1.364 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.255 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.241 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10230.01it/s]
Map: 100%|██████████| 6000/6000 [00:00<00:00, 10158.41 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 7951.44 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7648.06 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8345.41 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 05B n=6000 (s46)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9442.08it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 8.918 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 8.727 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 8.436 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 7.809 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 6.896 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 6.101 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 5.180 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 4.547 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.106 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.723 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 3.533 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 3.493 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.216 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.999 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.687 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.585 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.450 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.299 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.263 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.256 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.218 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.148 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.131 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.070 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 1.916 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 1.863 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 1.892 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.988 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 2.012 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 2.031 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.925 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.724 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.767 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.728 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 2.021 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.888 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.754 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.786 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.838 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.723 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.882 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.995 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 2.073 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.934 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.900 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.868 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.836 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.780 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.853 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.749 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.738 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.723 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.605 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.683 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.655 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.637 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.519 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.584 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.581 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.762 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.765 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.712 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.776 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.685 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.617 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.641 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.821 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.768 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.757 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.718 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.689 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.678 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.676 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.625 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.701 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.4950 | best=0.4950 @ epoch 1
[Step 750] CE/token (EMA): 1.618 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.505 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.506 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.463 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.482 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.546 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.625 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.697 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.653 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.653 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.609 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.738 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.844 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.844 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.766 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.694 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.581 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.445 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.480 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.604 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.514 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.577 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.469 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.427 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.499 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.526 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.643 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.618 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.657 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.647 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.577 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.524 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.521 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.616 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.596 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.568 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.506 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.684 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.715 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.664 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.598 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.577 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.565 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.684 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.641 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.525 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.490 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.480 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.395 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.383 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.196 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.290 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.432 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.311 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.315 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.515 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.546 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.634 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.568 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.522 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.649 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.581 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.462 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.412 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.323 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.535 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.557 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.434 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.335 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.397 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.495 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.491 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.497 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.637 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified, terrified, terrified, | terrified, afraid, terrified. | excited, anxious, excited for | disgusted disgusted disgusted disgusted disgusted disgusted
[ValMetric epoch 2] accuracy=0.5250 | best=0.5250 @ epoch 2
[Step 1500] CE/token (EMA): 1.589 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.521 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.381 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.422 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.460 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.330 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.347 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.385 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.380 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.360 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.356 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.374 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.261 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.346 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.309 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.259 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.252 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.343 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.505 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.471 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.404 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.424 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.468 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.486 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.466 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.379 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.355 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.470 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.373 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.410 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.359 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.327 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.370 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.456 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.557 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.486 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.395 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.374 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.341 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.362 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.450 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.361 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.350 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.349 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.262 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.293 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.276 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.343 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.280 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.259 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.300 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.323 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.263 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.272 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.355 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.353 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.321 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.280 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.243 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.292 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.219 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.135 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.158 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.270 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.359 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.465 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.357 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.343 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.344 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.348 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.338 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.364 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.342 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.305 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.489 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified, terrified, terrified, | embarrassed and embarrassed enough to admit | excited excited excited excited excited excited | embarrassed and embarrassed disgusted with guilty
[ValMetric epoch 3] accuracy=0.5550 | best=0.5550 @ epoch 3

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9719.36it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 8.918 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 8.730 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 8.439 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 7.810 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 6.897 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 6.098 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 5.169 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 4.538 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.089 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.699 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 3.530 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 3.477 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.209 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.977 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.664 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.550 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.437 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.273 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.215 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.247 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.207 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.163 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.124 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.065 | Contrast[mask]: 0.665 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 1.976 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 1.886 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 1.899 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.043 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.999 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.983 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.868 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.707 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.773 | Contrast[mask]: 0.660 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.713 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.985 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.861 | Contrast[mask]: 0.647 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.706 | Contrast[mask]: 0.650 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.762 | Contrast[mask]: 0.661 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.799 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.683 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.830 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.968 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 2.039 | Contrast[mask]: 0.666 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.879 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.873 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.854 | Contrast[mask]: 0.667 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.791 | Contrast[mask]: 0.662 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.771 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.823 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.728 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.713 | Contrast[mask]: 0.664 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.716 | Contrast[mask]: 0.668 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.603 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.694 | Contrast[mask]: 0.666 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.606 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.589 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.493 | Contrast[mask]: 0.669 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.541 | Contrast[mask]: 0.665 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.504 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.673 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.701 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.678 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.718 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.664 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.595 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.642 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.806 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.780 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.745 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.746 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.688 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.677 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.643 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.589 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.661 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5050 | best=0.5050 @ epoch 1
[Step 750] CE/token (EMA): 1.601 | Contrast[mask]: 0.668 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.496 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.461 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.406 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.464 | Contrast[mask]: 0.661 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.560 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.667 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.709 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.661 | Contrast[mask]: 0.669 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.624 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.586 | Contrast[mask]: 0.659 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.664 | Contrast[mask]: 0.664 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.794 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.796 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.735 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.679 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.572 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.415 | Contrast[mask]: 0.669 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.443 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.558 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.506 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.547 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.467 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.444 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.511 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.575 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.674 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.624 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.641 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.619 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.580 | Contrast[mask]: 0.661 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.501 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.530 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.574 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.593 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.583 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.517 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.675 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.734 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.648 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.525 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.541 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.522 | Contrast[mask]: 0.660 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.655 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.666 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.536 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.501 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.476 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.448 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.419 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.294 | Contrast[mask]: 0.667 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.339 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.427 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.311 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.327 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.500 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.541 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.610 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.558 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.547 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.667 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.603 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.461 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.427 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.334 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.549 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.428 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.573 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.432 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.300 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.360 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.458 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.449 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.475 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.621 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified afraid terrified terrified terrified terrified | embarrassed and ashamed.

| embarrassed | excited excited excited excited excited excited | disgusted disgusted disgusted disgusted disgusted disgusted
[ValMetric epoch 2] accuracy=0.5450 | best=0.5450 @ epoch 2
[Step 1500] CE/token (EMA): 1.570 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.501 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.426 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.442 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.464 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.325 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.344 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.406 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.397 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.373 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.371 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.379 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.309 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.388 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.356 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.322 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.265 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.362 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.448 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.435 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.373 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.419 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.438 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.487 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.463 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.397 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.361 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.450 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.362 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.417 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.345 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.317 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.384 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.506 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.573 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.486 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.387 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.367 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.367 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.394 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.433 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.345 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.322 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.377 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.285 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.301 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.261 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.370 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.301 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.287 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.355 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.391 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.330 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.343 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.403 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.379 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.328 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.265 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.238 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.339 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.256 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.159 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.196 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.291 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.367 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.479 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.334 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.353 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.363 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.391 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.378 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.364 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.325 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.303 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.497 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified afraid terrified terrified terrified terrified | embarrassed and embarrassed embarrassed embarrassed embarrassed | excited excited excited excited excited excited | disgusted disgusted disgusted disgusted disgusted disgusted

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10356.84it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 5.640e-05
[RL sample] REF: 'prepared'
[RL sample] GEN: 'love\nAction-verb:'
[RL step 0] reward=0.0234 adv=+0.0234 gamma=5.64e-05
[Step 0] CE/token (EMA): 8.918 | Contrast[mask]: 0.000 | RL: -2.675 | Reward: 0.0234

[Step 10] CE/token (EMA): 8.722 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 8.432 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 7.810 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 6.896 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'fat.\nAdjective: fat'
[RL step 50] reward=0.2266 adv=+0.2242 gamma=5.64e-05
[Step 50] CE/token (EMA): 6.094 | Contrast[mask]: 0.000 | RL: -25.594 | Reward: 0.2266
[Step 60] CE/token (EMA): 5.165 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 4.549 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.106 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.721 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'sad\nAction: cry'
[RL step 100] reward=0.3672 adv=+0.3424 gamma=5.64e-05
[Step 100] CE/token (EMA): 3.533 | Contrast[mask]: 0.000 | RL: -39.082 | Reward: 0.3672
[Step 110] CE/token (EMA): 3.481 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.220 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 3.004 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.704 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'sad.\nEmotion: sad'
[RL step 150] reward=0.4453 adv=+0.3863 gamma=5.64e-05
[Step 150] CE/token (EMA): 2.585 | Contrast[mask]: 0.000 | RL: -44.107 | Reward: 0.4453
[Step 160] CE/token (EMA): 2.467 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.316 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.231 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.237 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'lonely\nContext: I was'
[RL step 200] reward=0.3359 adv=+0.2383 gamma=5.64e-05
[Step 200] CE/token (EMA): 2.225 | Contrast[mask]: 0.000 | RL: -27.194 | Reward: 0.3359
[Step 210] CE/token (EMA): 2.178 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.137 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.039 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 1.883 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'relieved and grateful\nRelieved'
[RL step 250] reward=0.3672 adv=+0.2457 gamma=5.64e-05
[Step 250] CE/token (EMA): 1.866 | Contrast[mask]: 0.000 | RL: -28.055 | Reward: 0.3672
[Step 260] CE/token (EMA): 1.861 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.950 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.956 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 2.007 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'terrified\nEmotion: terrified'
[RL step 300] reward=0.5234 adv=+0.3774 gamma=5.64e-05
[Step 300] CE/token (EMA): 1.914 | Contrast[mask]: 0.000 | RL: -43.071 | Reward: 0.5234
[Step 310] CE/token (EMA): 1.721 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.790 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.743 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 2.028 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'surprised'
[RL sample] GEN: 'disappointed.\nDisappointed with the'
[RL step 350] reward=0.5469 adv=+0.3631 gamma=5.64e-05
[Step 350] CE/token (EMA): 1.875 | Contrast[mask]: 0.000 | RL: -41.448 | Reward: 0.5469
[Step 360] CE/token (EMA): 1.802 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.795 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.801 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.714 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'hopeful'
[RL sample] GEN: 'prepared for the real world'
[RL step 400] reward=0.3516 adv=+0.1315 gamma=5.64e-05
[Step 400] CE/token (EMA): 1.874 | Contrast[mask]: 0.000 | RL: -15.009 | Reward: 0.3516
[Step 410] CE/token (EMA): 1.988 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 2.058 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.908 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.879 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'prepared'
[RL sample] GEN: 'prepared, prepared for the trip'
[RL step 450] reward=0.4688 adv=+0.2355 gamma=5.64e-05
[Step 450] CE/token (EMA): 1.864 | Contrast[mask]: 0.000 | RL: -26.887 | Reward: 0.4688
[Step 460] CE/token (EMA): 1.813 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.795 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.865 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.769 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'anticipating the anticipation of the most'
[RL step 500] reward=0.4766 adv=+0.2198 gamma=5.64e-05
[Step 500] CE/token (EMA): 1.763 | Contrast[mask]: 0.000 | RL: -25.066 | Reward: 0.4766
[Step 510] CE/token (EMA): 1.702 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.606 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.698 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.639 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anticipating'
[RL sample] GEN: 'excited, hopeful, hopeful,'
[RL step 550] reward=0.5000 adv=+0.2212 gamma=5.64e-05
[Step 550] CE/token (EMA): 1.633 | Contrast[mask]: 0.000 | RL: -25.247 | Reward: 0.5000
[Step 560] CE/token (EMA): 1.537 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.582 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.565 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.777 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'lonely'
[RL sample] GEN: 'lonely and lonely.\n\nBelieving'
[RL step 600] reward=0.5312 adv=+0.2304 gamma=5.64e-05
[Step 600] CE/token (EMA): 1.758 | Contrast[mask]: 0.000 | RL: -26.293 | Reward: 0.5312
[Step 610] CE/token (EMA): 1.720 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.755 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.695 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.629 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anxious, anxious, anxious,'
[RL step 650] reward=0.4922 adv=+0.1683 gamma=5.64e-05
[Step 650] CE/token (EMA): 1.654 | Contrast[mask]: 0.000 | RL: -19.202 | Reward: 0.4922
[Step 660] CE/token (EMA): 1.828 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.765 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.746 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.709 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'excited, hopeful, hopeful,'
[RL step 700] reward=0.5000 adv=+0.1592 gamma=5.64e-05
[Step 700] CE/token (EMA): 1.665 | Contrast[mask]: 0.000 | RL: -18.170 | Reward: 0.5000
[Step 710] CE/token (EMA): 1.690 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.666 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.613 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.668 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.4900 | best=0.4900 @ epoch 1
[RL sample] REF: 'jealous'
[RL sample] GEN: 'annoyed.\n\n1. annoyed with'
[RL step 750] reward=0.4609 adv=+0.1043 gamma=5.64e-05
[Step 750] CE/token (EMA): 1.655 | Contrast[mask]: 0.000 | RL: -11.897 | Reward: 0.4609
[Step 760] CE/token (EMA): 1.534 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.493 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.436 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.471 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'anxious, worried, and afraid'
[RL step 800] reward=0.6016 adv=+0.2345 gamma=5.64e-05
[Step 800] CE/token (EMA): 1.534 | Contrast[mask]: 0.000 | RL: -26.763 | Reward: 0.6016
[Step 810] CE/token (EMA): 1.633 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.699 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.670 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.667 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty, guilty, guilty,'
[RL step 850] reward=0.5234 adv=+0.1329 gamma=5.64e-05
[Step 850] CE/token (EMA): 1.631 | Contrast[mask]: 0.000 | RL: -15.177 | Reward: 0.5234
[Step 860] CE/token (EMA): 1.725 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.820 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.828 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.758 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty, ashamed, guilty,'
[RL step 900] reward=0.4453 adv=+0.0415 gamma=5.64e-05
[Step 900] CE/token (EMA): 1.683 | Contrast[mask]: 0.000 | RL: -4.731 | Reward: 0.4453
[Step 910] CE/token (EMA): 1.585 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.431 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.470 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.570 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'sad, sad, sad,'
[RL step 950] reward=0.4453 adv=+0.0373 gamma=5.64e-05
[Step 950] CE/token (EMA): 1.490 | Contrast[mask]: 0.000 | RL: -4.258 | Reward: 0.4453
[Step 960] CE/token (EMA): 1.556 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.473 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.431 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.513 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud that my dad faithful to'
[RL step 1000] reward=0.5859 adv=+0.1742 gamma=5.64e-05
[Step 1000] CE/token (EMA): 1.528 | Contrast[mask]: 0.000 | RL: -19.882 | Reward: 0.5859
[Step 1010] CE/token (EMA): 1.657 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.612 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.637 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.623 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disgusted'
[RL sample] GEN: 'disgusted, disgusted, disgusted,'
[RL step 1050] reward=0.5938 adv=+0.1646 gamma=5.64e-05
[Step 1050] CE/token (EMA): 1.574 | Contrast[mask]: 0.000 | RL: -18.790 | Reward: 0.5938
[Step 1060] CE/token (EMA): 1.518 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.524 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.590 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.596 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'nostalgic'
[RL sample] GEN: 'nostalgic, sentimental, sentimental,'
[RL step 1100] reward=0.4609 adv=+0.0153 gamma=5.64e-05
[Step 1100] CE/token (EMA): 1.583 | Contrast[mask]: 0.000 | RL: -1.750 | Reward: 0.4609
[Step 1110] CE/token (EMA): 1.517 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.712 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.743 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.671 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sentimental'
[RL sample] GEN: 'sentimental, sentimental, sentimental,'
[RL step 1150] reward=0.5234 adv=+0.0763 gamma=5.64e-05
[Step 1150] CE/token (EMA): 1.580 | Contrast[mask]: 0.000 | RL: -8.702 | Reward: 0.5234
[Step 1160] CE/token (EMA): 1.561 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.543 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.685 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.668 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'confident'
[RL sample] GEN: 'anticipating the most joyful, anticipating'
[RL step 1200] reward=0.4609 adv=+0.0062 gamma=5.64e-05
[Step 1200] CE/token (EMA): 1.520 | Contrast[mask]: 0.000 | RL: -0.705 | Reward: 0.4609
[Step 1210] CE/token (EMA): 1.505 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.488 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.399 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.397 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty, ashamed, guilty,'
[RL step 1250] reward=0.5469 adv=+0.0915 gamma=5.64e-05
[Step 1250] CE/token (EMA): 1.221 | Contrast[mask]: 0.000 | RL: -10.443 | Reward: 0.5469
[Step 1260] CE/token (EMA): 1.319 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.405 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.301 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.323 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'jealous'
[RL sample] GEN: 'confident, proud, and confident'
[RL step 1300] reward=0.5859 adv=+0.1214 gamma=5.64e-05
[Step 1300] CE/token (EMA): 1.506 | Contrast[mask]: 0.000 | RL: -13.858 | Reward: 0.5859
[Step 1310] CE/token (EMA): 1.540 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.631 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.585 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.529 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited, excited, excited,'
[RL step 1350] reward=0.4609 adv=-0.0157 gamma=5.64e-05
[Step 1350] CE/token (EMA): 1.643 | Contrast[mask]: 0.000 | RL: 1.795 | Reward: 0.4609
[Step 1360] CE/token (EMA): 1.579 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.465 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.398 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.333 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'caring enough to save an elderly'
[RL step 1400] reward=0.5000 adv=+0.0249 gamma=5.64e-05
[Step 1400] CE/token (EMA): 1.551 | Contrast[mask]: 0.000 | RL: -2.842 | Reward: 0.5000
[Step 1410] CE/token (EMA): 1.418 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.580 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.450 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.351 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'afraid'
[RL sample] GEN: 'terrified, afraid, terrified.'
[RL step 1450] reward=0.5312 adv=+0.0537 gamma=5.64e-05
[Step 1450] CE/token (EMA): 1.362 | Contrast[mask]: 0.000 | RL: -6.128 | Reward: 0.5312
[Step 1460] CE/token (EMA): 1.467 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.466 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.475 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.626 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified, terrified, terrified, | surprised and embarrassed.

| surprised | excited, anxious, prepared, | disgusted disgusted disgusted disgusted disgusted disgusted
[ValMetric epoch 2] accuracy=0.5400 | best=0.5400 @ epoch 2
[RL sample] REF: 'annoyed'
[RL sample] GEN: 'annoyed and disgusted with jealous,'
[RL step 1500] reward=0.5938 adv=+0.1108 gamma=5.64e-05
[Step 1500] CE/token (EMA): 1.582 | Contrast[mask]: 0.000 | RL: -12.639 | Reward: 0.5938
[Step 1510] CE/token (EMA): 1.547 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.412 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.455 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.467 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'joyful'
[RL sample] GEN: 'joyful, excited, grateful,'
[RL step 1550] reward=0.5547 adv=+0.0607 gamma=5.64e-05
[Step 1550] CE/token (EMA): 1.333 | Contrast[mask]: 0.000 | RL: -6.924 | Reward: 0.5547
[Step 1560] CE/token (EMA): 1.362 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.423 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.425 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.369 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'impressed, impressed with the faithful'
[RL step 1600] reward=0.4531 adv=-0.0470 gamma=5.64e-05
[Step 1600] CE/token (EMA): 1.358 | Contrast[mask]: 0.000 | RL: 5.360 | Reward: 0.4531
[Step 1610] CE/token (EMA): 1.363 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.273 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.330 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.304 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'caring'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 1650] reward=0.4375 adv=-0.0579 gamma=5.64e-05
[Step 1650] CE/token (EMA): 1.230 | Contrast[mask]: 0.000 | RL: 6.608 | Reward: 0.4375
[Step 1660] CE/token (EMA): 1.214 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.334 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.459 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.471 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'embarrassed'
[RL sample] GEN: 'embarrassed and ashamed.\n\n embarrassed and'
[RL step 1700] reward=0.5469 adv=+0.0573 gamma=5.64e-05
[Step 1700] CE/token (EMA): 1.414 | Contrast[mask]: 0.000 | RL: -6.535 | Reward: 0.5469
[Step 1710] CE/token (EMA): 1.447 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.472 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.484 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.475 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9555.87it/s]
Map: 100%|██████████| 6000/6000 [00:00<00:00, 10098.03 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 7719.13 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7714.46 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8162.48 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 05B n=6000 (s47)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9698.12it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 10.073 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 9.834 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 9.508 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 8.679 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.525 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 6.632 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 5.838 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 5.135 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.322 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.840 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 3.433 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 3.289 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.326 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 3.187 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.988 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.701 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.491 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.285 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.189 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.278 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.165 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.341 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.156 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 1.975 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.125 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 2.056 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 2.141 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.062 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 2.090 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 2.049 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.976 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.884 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.856 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.927 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.922 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.917 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.830 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.949 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.942 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.942 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.923 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.869 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.899 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.969 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.900 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.796 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.775 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.754 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.651 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.600 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.450 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.521 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.620 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.549 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.660 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.826 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.784 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.903 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.809 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.758 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.878 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.809 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.666 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.639 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.551 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.764 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.632 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.794 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.650 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.542 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.577 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.668 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.715 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.700 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.795 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.4950 | best=0.4950 @ epoch 1
[Step 750] CE/token (EMA): 1.829 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.697 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.606 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.654 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.609 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.518 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.523 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.603 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.563 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.538 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.557 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.596 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.526 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.576 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.521 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.478 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.479 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.579 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.728 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.660 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.589 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.627 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.688 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.680 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.679 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.577 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.557 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.648 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.543 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.561 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.511 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.509 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.554 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.690 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.766 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.699 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.581 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.535 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.504 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.554 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.644 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.522 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.498 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.547 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.474 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.493 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.473 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.536 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.462 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.478 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.562 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.542 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.504 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.488 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.525 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.559 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.486 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.409 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.375 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.486 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.321 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.325 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.417 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.496 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.583 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.502 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.548 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.525 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.535 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.520 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.518 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.500 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.460 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.657 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified.

# terrified

# | embarrassed and embarrassed.

 embarrassed embarrassed | excited.

I prepared prepared prepared | terrified.

 embarrassed embarrassed embarrassed embarrassed
[ValMetric epoch 2] accuracy=0.5550 | best=0.5550 @ epoch 2
[Step 1500] CE/token (EMA): 1.522 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.388 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.374 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.440 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.511 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.423 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.371 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.383 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.424 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.389 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.408 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.274 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.330 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.480 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.443 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.472 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.614 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.366 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.344 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.457 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.380 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.329 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.378 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.378 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.365 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.329 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.344 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.343 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.303 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.329 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.353 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.353 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.314 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.242 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.374 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.412 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.409 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.500 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.407 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.386 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.286 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.213 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.300 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.286 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.346 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.446 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.285 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.335 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.386 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.408 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.462 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.375 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.355 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.282 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.273 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.340 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.338 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.372 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.247 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.255 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.175 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.116 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.157 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.244 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.320 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.385 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.462 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.384 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.323 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.329 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.429 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.415 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.416 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.373 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified.

# terrified afraid afraid | surprised.

 embarrassed.

 embarrassed. | excited excited excited excited excited excited | terrified.

 embarrassed.

 embarrassed.
[ValMetric epoch 3] accuracy=0.5750 | best=0.5750 @ epoch 3

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9820.11it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 10.073 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 9.836 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 9.505 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 8.673 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.516 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 6.620 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 5.828 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 5.126 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.324 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.839 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 3.421 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 3.277 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.308 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 3.187 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.999 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.710 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.492 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.293 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.192 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.288 | Contrast[mask]: 0.666 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.196 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.366 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.165 | Contrast[mask]: 0.669 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 1.994 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.148 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 2.075 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 2.126 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.051 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 2.093 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 2.025 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.992 | Contrast[mask]: 0.657 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.916 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.872 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.896 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.893 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.912 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.828 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.985 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.980 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.953 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.920 | Contrast[mask]: 0.669 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.844 | Contrast[mask]: 0.664 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.850 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.933 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.874 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.783 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.781 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.750 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.663 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.611 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.465 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.512 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.620 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.539 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.613 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.773 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.770 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.886 | Contrast[mask]: 0.666 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.776 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.726 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.873 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.798 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.652 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.651 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.546 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.781 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.620 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.792 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.635 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.512 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.554 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.645 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.700 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.706 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.803 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5250 | best=0.5250 @ epoch 1
[Step 750] CE/token (EMA): 1.791 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.667 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.613 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.657 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.614 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.495 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.522 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.613 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.568 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.528 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.526 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.589 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.517 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.580 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.529 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.490 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.487 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.560 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.686 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.657 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.586 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.640 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.682 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.702 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.684 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.588 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.552 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.653 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.544 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.576 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.529 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.502 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.529 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.636 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.731 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.675 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.598 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.543 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.524 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.538 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.633 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.546 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.540 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.576 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.495 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.504 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.501 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.537 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.498 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.494 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.582 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.543 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.500 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.497 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.491 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.514 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.458 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.380 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.352 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.492 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.422 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.345 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.341 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.462 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.562 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.628 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.535 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.569 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.543 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.530 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.511 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.522 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.527 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.488 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.650 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified afraid terrified afraid terrified afraid | terrified afraid afraid afraid afraid afraid | excited excited anticipating the exciting anticipation | terrified, terrified afraid of the
[ValMetric epoch 2] accuracy=0.5500 | best=0.5500 @ epoch 2
[Step 1500] CE/token (EMA): 1.480 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.367 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.367 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.436 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.528 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.417 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.354 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.370 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.423 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.378 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.413 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.286 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.340 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.490 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.457 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.492 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.630 | Contrast[mask]: 0.669 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.365 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.329 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.451 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.396 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.389 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.308 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.348 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.357 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.382 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.314 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.331 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.343 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.307 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.342 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.377 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.350 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.300 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.232 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.357 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.393 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.392 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.482 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.376 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.377 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.310 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.222 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.302 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.266 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.355 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.446 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.298 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.322 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.381 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.383 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.432 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.337 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.317 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.250 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.267 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.330 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.328 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.350 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.222 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.231 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.167 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.104 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.169 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.246 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.311 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.387 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.464 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.385 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.310 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.327 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.435 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.435 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.433 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.382 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified afraid terrified afraid afraid terrified | surprised surprised surprised surprised surprised surprised | excited excited excited excited excited excited | terrified angry angry angry angry angry
[ValMetric epoch 3] accuracy=0.5700 | best=0.5700 @ epoch 3

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9594.62it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 3.822e-05
[RL sample] REF: 'prepared'
[RL sample] GEN: 'Thinking\nEmotion: Happiness'
[RL step 0] reward=0.0391 adv=+0.0391 gamma=3.82e-05
[Step 0] CE/token (EMA): 10.073 | Contrast[mask]: 0.000 | RL: -3.022 | Reward: 0.0391

[Step 10] CE/token (EMA): 9.833 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 9.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 8.671 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.506 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'fat\n  (see the'
[RL step 50] reward=0.2031 adv=+0.1992 gamma=3.82e-05
[Step 50] CE/token (EMA): 6.613 | Contrast[mask]: 0.000 | RL: -15.414 | Reward: 0.2031
[Step 60] CE/token (EMA): 5.829 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 5.140 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.343 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.840 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed\n  • I am'
[RL step 100] reward=0.3750 adv=+0.3512 gamma=3.82e-05
[Step 100] CE/token (EMA): 3.439 | Contrast[mask]: 0.000 | RL: -27.154 | Reward: 0.3750
[Step 110] CE/token (EMA): 3.305 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.340 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 3.224 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 3.013 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'sad\nDescription: sad'
[RL step 150] reward=0.4141 adv=+0.3551 gamma=3.82e-05
[Step 150] CE/token (EMA): 2.726 | Contrast[mask]: 0.000 | RL: -27.474 | Reward: 0.4141
[Step 160] CE/token (EMA): 2.508 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.263 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.158 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.227 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'annoyed, annoyed, annoyed,'
[RL step 200] reward=0.4219 adv=+0.3274 gamma=3.82e-05
[Step 200] CE/token (EMA): 2.148 | Contrast[mask]: 0.000 | RL: -25.323 | Reward: 0.4219
[Step 210] CE/token (EMA): 2.378 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.132 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 1.952 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.117 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud\nEmotion: proud'
[RL step 250] reward=0.3906 adv=+0.2634 gamma=3.82e-05
[Step 250] CE/token (EMA): 2.059 | Contrast[mask]: 0.000 | RL: -20.373 | Reward: 0.3906
[Step 260] CE/token (EMA): 2.111 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.049 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 2.081 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 2.058 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'terrified\nContext: afraid'
[RL step 300] reward=0.4922 adv=+0.3386 gamma=3.82e-05
[Step 300] CE/token (EMA): 1.986 | Contrast[mask]: 0.000 | RL: -26.175 | Reward: 0.4922
[Step 310] CE/token (EMA): 1.947 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.898 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.940 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.922 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'surprised'
[RL sample] GEN: 'surprised, surprised\nContext:'
[RL step 350] reward=0.5234 adv=+0.3360 gamma=3.82e-05
[Step 350] CE/token (EMA): 1.917 | Contrast[mask]: 0.000 | RL: -25.989 | Reward: 0.5234
[Step 360] CE/token (EMA): 1.841 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.942 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.966 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.978 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'hopeful'
[RL sample] GEN: 'prepared, prepared for the returning'
[RL step 400] reward=0.4141 adv=+0.1931 gamma=3.82e-05
[Step 400] CE/token (EMA): 1.891 | Contrast[mask]: 0.000 | RL: -14.929 | Reward: 0.4141
[Step 410] CE/token (EMA): 1.886 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.866 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.966 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.919 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'prepared'
[RL sample] GEN: 'excited, anticipating the trip.'
[RL step 450] reward=0.4922 adv=+0.2519 gamma=3.82e-05
[Step 450] CE/token (EMA): 1.860 | Contrast[mask]: 0.000 | RL: -19.481 | Reward: 0.4922
[Step 460] CE/token (EMA): 1.793 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.773 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.702 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.640 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'prepared, prepared to go to'
[RL step 500] reward=0.3828 adv=+0.1173 gamma=3.82e-05
[Step 500] CE/token (EMA): 1.463 | Contrast[mask]: 0.000 | RL: -9.072 | Reward: 0.3828
[Step 510] CE/token (EMA): 1.528 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.626 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.562 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.645 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anticipating'
[RL sample] GEN: 'excited, hopeful, hopeful for'
[RL step 550] reward=0.5312 adv=+0.2540 gamma=3.82e-05
[Step 550] CE/token (EMA): 1.781 | Contrast[mask]: 0.000 | RL: -19.639 | Reward: 0.5312
[Step 560] CE/token (EMA): 1.789 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.911 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.815 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.758 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'lonely'
[RL sample] GEN: 'lonely lonely lonely lonely lonely lonely'
[RL step 600] reward=0.5781 adv=+0.2755 gamma=3.82e-05
[Step 600] CE/token (EMA): 1.897 | Contrast[mask]: 0.000 | RL: -21.311 | Reward: 0.5781
[Step 610] CE/token (EMA): 1.827 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.682 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.673 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.567 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anxious, nervous, anxious,'
[RL step 650] reward=0.4297 adv=+0.0995 gamma=3.82e-05
[Step 650] CE/token (EMA): 1.769 | Contrast[mask]: 0.000 | RL: -7.694 | Reward: 0.4297
[Step 660] CE/token (EMA): 1.643 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.816 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.653 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.526 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'excited.\n\nI want to move'
[RL step 700] reward=0.4766 adv=+0.1364 gamma=3.82e-05
[Step 700] CE/token (EMA): 1.567 | Contrast[mask]: 0.000 | RL: -10.553 | Reward: 0.4766
[Step 710] CE/token (EMA): 1.656 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.703 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.718 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.815 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5300 | best=0.5300 @ epoch 1
[RL sample] REF: 'jealous'
[RL sample] GEN: 'annoyed.\n\nI annoyed my sister'
[RL step 750] reward=0.4609 adv=+0.1072 gamma=3.82e-05
[Step 750] CE/token (EMA): 1.787 | Contrast[mask]: 0.000 | RL: -8.285 | Reward: 0.4609
[Step 760] CE/token (EMA): 1.651 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.599 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.649 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.611 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'disappointed.\n\nI disappointed because I'
[RL step 800] reward=0.6172 adv=+0.2527 gamma=3.82e-05
[Step 800] CE/token (EMA): 1.533 | Contrast[mask]: 0.000 | RL: -19.545 | Reward: 0.6172
[Step 810] CE/token (EMA): 1.536 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.602 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.556 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.535 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 850] reward=0.5391 adv=+0.1493 gamma=3.82e-05
[Step 850] CE/token (EMA): 1.559 | Contrast[mask]: 0.000 | RL: -11.551 | Reward: 0.5391
[Step 860] CE/token (EMA): 1.604 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.522 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.567 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.514 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'angry with angry with angry angry'
[RL step 900] reward=0.4922 adv=+0.0875 gamma=3.82e-05
[Step 900] CE/token (EMA): 1.477 | Contrast[mask]: 0.000 | RL: -6.767 | Reward: 0.4922
[Step 910] CE/token (EMA): 1.510 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.587 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.723 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.666 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'sad and sad.\n\nSad and'
[RL step 950] reward=0.4062 adv=-0.0072 gamma=3.82e-05
[Step 950] CE/token (EMA): 1.597 | Contrast[mask]: 0.000 | RL: 0.556 | Reward: 0.4062
[Step 960] CE/token (EMA): 1.643 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.695 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.699 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.697 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud.\n\n caring for caring for'
[RL step 1000] reward=0.6016 adv=+0.1888 gamma=3.82e-05
[Step 1000] CE/token (EMA): 1.570 | Contrast[mask]: 0.000 | RL: -14.599 | Reward: 0.6016
[Step 1010] CE/token (EMA): 1.527 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.662 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.562 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.607 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disgusted'
[RL sample] GEN: 'disgusted disgusted disgusted disgusted disgusted disgusted'
[RL step 1050] reward=0.6406 adv=+0.2090 gamma=3.82e-05
[Step 1050] CE/token (EMA): 1.537 | Contrast[mask]: 0.000 | RL: -16.164 | Reward: 0.6406
[Step 1060] CE/token (EMA): 1.477 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.565 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.652 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.729 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'nostalgic'
[RL sample] GEN: 'sentimental sentimental sentimental sentimental sentimental sentimental'
[RL step 1100] reward=0.3984 adv=-0.0541 gamma=3.82e-05
[Step 1100] CE/token (EMA): 1.679 | Contrast[mask]: 0.000 | RL: 4.182 | Reward: 0.3984
[Step 1110] CE/token (EMA): 1.581 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.515 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.494 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.547 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sentimental'
[RL sample] GEN: 'sentimental.\n\nContext: sentimental.'
[RL step 1150] reward=0.4766 adv=+0.0295 gamma=3.82e-05
[Step 1150] CE/token (EMA): 1.600 | Contrast[mask]: 0.000 | RL: -2.278 | Reward: 0.4766
[Step 1160] CE/token (EMA): 1.507 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.493 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.544 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.489 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'confident'
[RL sample] GEN: 'prepared, prepared for the event'
[RL step 1200] reward=0.4922 adv=+0.0421 gamma=3.82e-05
[Step 1200] CE/token (EMA): 1.508 | Contrast[mask]: 0.000 | RL: -3.258 | Reward: 0.4922
[Step 1210] CE/token (EMA): 1.508 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.561 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.492 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.480 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty.\n\nI guilty guilty guilty'
[RL step 1250] reward=0.5781 adv=+0.1239 gamma=3.82e-05
[Step 1250] CE/token (EMA): 1.548 | Contrast[mask]: 0.000 | RL: -9.575 | Reward: 0.5781
[Step 1260] CE/token (EMA): 1.528 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.484 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.484 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.526 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'jealous'
[RL sample] GEN: 'proud.\n\nI caring about my'
[RL step 1300] reward=0.5781 adv=+0.1115 gamma=3.82e-05
[Step 1300] CE/token (EMA): 1.553 | Contrast[mask]: 0.000 | RL: -8.620 | Reward: 0.5781
[Step 1310] CE/token (EMA): 1.504 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.422 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.378 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.511 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited for the trip excited for'
[RL step 1350] reward=0.4375 adv=-0.0403 gamma=3.82e-05
[Step 1350] CE/token (EMA): 1.437 | Contrast[mask]: 0.000 | RL: 3.117 | Reward: 0.4375
[Step 1360] CE/token (EMA): 1.339 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.346 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.462 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.528 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'surprised and surprised with caring for'
[RL step 1400] reward=0.4922 adv=+0.0184 gamma=3.82e-05
[Step 1400] CE/token (EMA): 1.599 | Contrast[mask]: 0.000 | RL: -1.424 | Reward: 0.4922
[Step 1410] CE/token (EMA): 1.489 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.534 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.512 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.519 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'afraid'
[RL sample] GEN: 'afraid of death.\n\nBecause afraid'
[RL step 1450] reward=0.4609 adv=-0.0147 gamma=3.82e-05
[Step 1450] CE/token (EMA): 1.517 | Contrast[mask]: 0.000 | RL: 1.135 | Reward: 0.4609
[Step 1460] CE/token (EMA): 1.538 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.526 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.472 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.642 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified.

# terrified.

# | embarrassed.

 embarrassed embarrassed embarrassed embarrassed | excited.

Considering the anticipation, | terrified.

 embarrassed

 embarrassed
[ValMetric epoch 2] accuracy=0.5450 | best=0.5450 @ epoch 2
[RL sample] REF: 'annoyed'
[RL sample] GEN: 'annoyed jealous jealous jealous jealous jealous'
[RL step 1500] reward=0.6562 adv=+0.1821 gamma=3.82e-05
[Step 1500] CE/token (EMA): 1.460 | Contrast[mask]: 0.000 | RL: -14.082 | Reward: 0.6562
[Step 1510] CE/token (EMA): 1.380 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.380 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.445 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.504 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'joyful'
[RL sample] GEN: 'joyful.\n\n| joyful joyful joyful'
[RL step 1550] reward=0.6016 adv=+0.1092 gamma=3.82e-05
[Step 1550] CE/token (EMA): 1.415 | Contrast[mask]: 0.000 | RL: -8.443 | Reward: 0.6016
[Step 1560] CE/token (EMA): 1.353 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.384 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.432 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.405 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'impressed with the faithful.\n\nI'
[RL step 1600] reward=0.4453 adv=-0.0580 gamma=3.82e-05
[Step 1600] CE/token (EMA): 1.437 | Contrast[mask]: 0.000 | RL: 4.483 | Reward: 0.4453
[Step 1610] CE/token (EMA): 1.290 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.368 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.508 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.452 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'caring'
[RL sample] GEN: 'faithful, faithful.\n\n caring faithful'
[RL step 1650] reward=0.4375 adv=-0.0600 gamma=3.82e-05
[Step 1650] CE/token (EMA): 1.494 | Contrast[mask]: 0.000 | RL: 4.642 | Reward: 0.4375
[Step 1660] CE/token (EMA): 1.632 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.361 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.332 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.441 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'embarrassed'
[RL sample] GEN: 'embarrassed.\n\n embarrassed embarrassed embarrassed embarrassed'
[RL step 1700] reward=0.5469 adv=+0.0554 gamma=3.82e-05
[Step 1700] CE/token (EMA): 1.407 | Contrast[mask]: 0.000 | RL: -4.285 | Reward: 0.5469
[Step 1710] CE/token (EMA): 1.387 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.320 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.372 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9653.25it/s]
Map: 100%|██████████| 6000/6000 [00:00<00:00, 10075.68 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 7889.22 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7670.22 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8352.16 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 05B n=6000 (s48)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9687.00it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 11.617 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 11.150 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 10.270 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 9.116 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.704 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 6.438 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 5.505 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 4.916 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.545 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 4.006 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 3.739 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 3.463 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.198 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 3.089 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.886 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.695 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.487 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.512 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.339 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.256 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.202 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.279 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.200 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.209 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 2.049 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 1.987 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.063 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.943 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 2.013 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.856 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.861 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.879 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.989 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 2.083 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 2.047 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.911 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.836 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.791 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.863 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.959 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.834 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.807 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.859 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.730 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.728 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.718 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.759 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.709 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.657 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.746 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.732 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.709 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.718 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.734 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.775 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.745 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.679 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.581 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.687 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.595 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.488 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.513 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.648 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.777 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.831 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.697 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.732 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.679 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.713 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.707 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.725 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.720 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.702 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.819 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.4950 | best=0.4950 @ epoch 1
[Step 750] CE/token (EMA): 1.654 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.545 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.573 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.605 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.694 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.599 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.538 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.566 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.606 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.575 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.610 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.471 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.589 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.664 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.641 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.677 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.867 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.605 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.566 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.643 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.577 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.558 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.519 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.554 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.550 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.549 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.473 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.476 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.489 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.492 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.519 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.539 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.594 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.547 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.492 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.555 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.598 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.584 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.669 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.631 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.597 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.524 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.437 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.500 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.451 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.535 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.606 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.478 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.473 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.521 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.585 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.619 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.536 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.519 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.462 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.479 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.530 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.500 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.565 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.438 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.418 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.297 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.223 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.341 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.390 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.451 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.505 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.552 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.526 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.459 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.487 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.604 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.600 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.599 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.542 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified, terrified, terrified, | furious, furious, furious, | excited, anticipating the exciting and | terrified, afraid, terrified,
[ValMetric epoch 2] accuracy=0.5350 | best=0.5350 @ epoch 2
[Step 1500] CE/token (EMA): 1.505 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.379 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.301 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.309 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.469 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.379 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.336 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.233 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.273 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.292 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.270 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.305 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.321 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.422 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.410 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.448 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.386 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.356 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.406 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.337 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.281 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.370 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.406 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.370 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.336 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.297 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.338 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.375 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.295 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.288 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.304 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.282 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.364 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.425 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.256 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.343 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.379 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.316 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.267 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.185 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.276 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.419 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.389 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.355 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.427 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.509 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.434 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.413 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.354 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.434 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.441 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.386 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.422 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.343 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.336 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.369 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.315 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.401 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.413 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.217 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.326 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.316 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.306 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.250 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.403 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.291 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.362 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.262 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.328 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.306 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.329 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.232 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.296 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified, terrified, terrified, | surprised and surprised with surprised surprised | excited, anticipating the lonely and | sad and embarrassed.

Sad and
[ValMetric epoch 3] accuracy=0.5650 | best=0.5650 @ epoch 3
[Step 2250] CE/token (EMA): 1.333 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9926.21it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 11.617 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 11.145 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 10.271 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 9.120 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.706 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 6.438 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 5.491 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 4.906 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.530 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.990 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 3.716 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 3.435 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.166 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 3.073 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.841 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.657 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.459 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.493 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.497 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.334 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.258 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.184 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.293 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.200 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.211 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 2.068 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 1.991 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.071 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.919 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.999 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.882 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.899 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.898 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 2.015 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 2.104 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 2.043 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.932 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.880 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.833 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.935 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.993 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.824 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.829 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.861 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.734 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.733 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.740 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.779 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.747 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.707 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.757 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.766 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.712 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.696 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.719 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.766 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.717 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.645 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.582 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.682 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.605 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.493 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.523 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.705 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.793 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.862 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.704 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.761 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.729 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.748 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.748 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.751 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.749 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.701 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.811 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5000 | best=0.5000 @ epoch 1
[Step 750] CE/token (EMA): 1.646 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.547 | Contrast[mask]: 0.667 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.569 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.601 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.681 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.588 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.498 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.551 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.612 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.579 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.622 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.489 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.575 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.701 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.663 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.690 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.867 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.616 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.553 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.650 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.576 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.557 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.538 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.574 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.571 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.563 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.506 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.517 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.538 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.512 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.524 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.542 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.594 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.535 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.492 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.546 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.571 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.561 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.661 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.575 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.568 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.511 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.425 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.484 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.455 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.539 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.594 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.469 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.500 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.520 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.586 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.607 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.525 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.509 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.446 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.486 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.545 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.491 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.582 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.440 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.420 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.339 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.253 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.375 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.438 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.515 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.550 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.575 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.544 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.472 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.496 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.592 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.583 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.584 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.523 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified, terrified, terrified, | surprised and surprised surprised surprised surprised | excited, anticipating the exciting, | embarrassed and embarrassed.
 embarrassed and
[ValMetric epoch 2] accuracy=0.5300 | best=0.5300 @ epoch 2
[Step 1500] CE/token (EMA): 1.470 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.368 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.290 | Contrast[mask]: 0.667 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.304 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.455 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.365 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.404 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.344 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.257 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.288 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.294 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.264 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.308 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.319 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.400 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.415 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.441 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.365 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.365 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.404 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.315 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.299 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.388 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.392 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.393 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.339 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.315 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.336 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.361 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.316 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.283 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.336 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.294 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.365 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.427 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.259 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.276 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.338 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.383 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.343 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.286 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.182 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.249 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.367 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.350 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.310 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.388 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.473 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.415 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.372 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.314 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.429 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.439 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.385 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.426 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.327 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.331 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.338 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.292 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.396 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.407 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.223 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.345 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.352 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.345 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.272 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.419 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.326 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.394 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.280 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.310 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.305 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.313 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.211 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.288 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified, terrified, terrified, | terrified, afraid, and surprised | excited, anticipating joyful, joyful | embarrassed and ashamed.
 embarrassed and
[ValMetric epoch 3] accuracy=0.5650 | best=0.5650 @ epoch 3

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9625.52it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 2.205e-04
[RL sample] REF: 'prepared'
[RL sample] GEN: 'Happiness\nHypnaca'
[RL step 0] reward=0.0078 adv=+0.0078 gamma=2.20e-04
[Step 0] CE/token (EMA): 11.617 | Contrast[mask]: 0.000 | RL: -3.485 | Reward: 0.0078

[Step 10] CE/token (EMA): 11.150 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 10.271 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 9.118 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.707 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'fat.\n$\\end1$:'
[RL step 50] reward=0.2188 adv=+0.2180 gamma=2.20e-04
[Step 50] CE/token (EMA): 6.425 | Contrast[mask]: 0.000 | RL: -97.259 | Reward: 0.2188
[Step 60] CE/token (EMA): 5.483 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 4.895 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.511 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.978 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'sad.\nBased on the text'
[RL step 100] reward=0.4062 adv=+0.3837 gamma=2.20e-04
[Step 100] CE/token (EMA): 3.715 | Contrast[mask]: 0.000 | RL: -171.155 | Reward: 0.4062
[Step 110] CE/token (EMA): 3.446 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.190 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 3.084 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.848 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'sad\nThoughts: sad'
[RL step 150] reward=0.3984 adv=+0.3375 gamma=2.20e-04
[Step 150] CE/token (EMA): 2.658 | Contrast[mask]: 0.000 | RL: -150.623 | Reward: 0.3984
[Step 160] CE/token (EMA): 2.467 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.509 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.513 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.357 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'surprised\nContext: I was'
[RL step 200] reward=0.4219 adv=+0.3272 gamma=2.20e-04
[Step 200] CE/token (EMA): 2.247 | Contrast[mask]: 0.000 | RL: -146.055 | Reward: 0.4219
[Step 210] CE/token (EMA): 2.184 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.280 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.186 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.208 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud and grateful\nIn the'
[RL step 250] reward=0.4062 adv=+0.2788 gamma=2.20e-04
[Step 250] CE/token (EMA): 2.052 | Contrast[mask]: 0.000 | RL: -124.350 | Reward: 0.4062
[Step 260] CE/token (EMA): 1.956 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.049 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.922 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.991 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'terrified.\nIn the storming'
[RL step 300] reward=0.4766 adv=+0.3213 gamma=2.20e-04
[Step 300] CE/token (EMA): 1.877 | Contrast[mask]: 0.000 | RL: -143.332 | Reward: 0.4766
[Step 310] CE/token (EMA): 1.856 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.865 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.997 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 2.089 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'surprised'
[RL sample] GEN: 'proud and grateful.\nIn the'
[RL step 350] reward=0.5781 adv=+0.3907 gamma=2.20e-04
[Step 350] CE/token (EMA): 2.019 | Contrast[mask]: 0.000 | RL: -174.330 | Reward: 0.5781
[Step 360] CE/token (EMA): 1.904 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.877 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.816 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.890 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'hopeful'
[RL sample] GEN: 'anticipating the graduate-ready for the'
[RL step 400] reward=0.3984 adv=+0.1719 gamma=2.20e-04
[Step 400] CE/token (EMA): 1.980 | Contrast[mask]: 0.000 | RL: -76.669 | Reward: 0.3984
[Step 410] CE/token (EMA): 1.841 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.832 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.874 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.747 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'prepared'
[RL sample] GEN: 'prepared, prepared, prepared,'
[RL step 450] reward=0.4766 adv=+0.2329 gamma=2.20e-04
[Step 450] CE/token (EMA): 1.740 | Contrast[mask]: 0.000 | RL: -103.879 | Reward: 0.4766
[Step 460] CE/token (EMA): 1.729 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.773 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.745 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.715 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited, prepared, and prepared'
[RL step 500] reward=0.4609 adv=+0.1940 gamma=2.20e-04
[Step 500] CE/token (EMA): 1.802 | Contrast[mask]: 0.000 | RL: -86.514 | Reward: 0.4609
[Step 510] CE/token (EMA): 1.767 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.711 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.693 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.711 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anticipating'
[RL sample] GEN: 'excited, excited, excited,'
[RL step 550] reward=0.5859 adv=+0.2996 gamma=2.20e-04
[Step 550] CE/token (EMA): 1.769 | Contrast[mask]: 0.000 | RL: -133.712 | Reward: 0.5859
[Step 560] CE/token (EMA): 1.744 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.669 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.615 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.714 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'lonely'
[RL sample] GEN: 'lonely and lonely.\nDesires'
[RL step 600] reward=0.6016 adv=+0.2852 gamma=2.20e-04
[Step 600] CE/token (EMA): 1.609 | Contrast[mask]: 0.000 | RL: -127.242 | Reward: 0.6016
[Step 610] CE/token (EMA): 1.499 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.513 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.666 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.766 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anxious, anxious, anxious,'
[RL step 650] reward=0.4141 adv=+0.0692 gamma=2.20e-04
[Step 650] CE/token (EMA): 1.819 | Contrast[mask]: 0.000 | RL: -30.887 | Reward: 0.4141
[Step 660] CE/token (EMA): 1.684 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.728 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.691 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.729 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anticipating the future, anticipating the'
[RL step 700] reward=0.4609 adv=+0.1092 gamma=2.20e-04
[Step 700] CE/token (EMA): 1.749 | Contrast[mask]: 0.000 | RL: -48.702 | Reward: 0.4609
[Step 710] CE/token (EMA): 1.743 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.722 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.705 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.826 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5050 | best=0.5050 @ epoch 1
[RL sample] REF: 'jealous'
[RL sample] GEN: 'annoyed, jealous, jealous,'
[RL step 750] reward=0.4688 adv=+0.1061 gamma=2.20e-04
[Step 750] CE/token (EMA): 1.669 | Contrast[mask]: 0.000 | RL: -47.314 | Reward: 0.4688
[Step 760] CE/token (EMA): 1.539 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.571 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.617 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.716 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'disappointed, sad, lonely,'
[RL step 800] reward=0.5781 adv=+0.2048 gamma=2.20e-04
[Step 800] CE/token (EMA): 1.620 | Contrast[mask]: 0.000 | RL: -91.348 | Reward: 0.5781
[Step 810] CE/token (EMA): 1.546 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.580 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.627 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.589 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty, guilty, guilty guilty'
[RL step 850] reward=0.5312 adv=+0.1375 gamma=2.20e-04
[Step 850] CE/token (EMA): 1.620 | Contrast[mask]: 0.000 | RL: -61.326 | Reward: 0.5312
[Step 860] CE/token (EMA): 1.465 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.599 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.699 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.662 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'angry and jealous.\ncaring'
[RL step 900] reward=0.4922 adv=+0.0847 gamma=2.20e-04
[Step 900] CE/token (EMA): 1.671 | Contrast[mask]: 0.000 | RL: -37.765 | Reward: 0.4922
[Step 910] CE/token (EMA): 1.843 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.590 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.569 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.665 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'devastated, devastated, devastated,'
[RL step 950] reward=0.4062 adv=-0.0097 gamma=2.20e-04
[Step 950] CE/token (EMA): 1.589 | Contrast[mask]: 0.000 | RL: 4.344 | Reward: 0.4062
[Step 960] CE/token (EMA): 1.581 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.532 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.568 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.545 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud, proud, proud.'
[RL step 1000] reward=0.5781 adv=+0.1631 gamma=2.20e-04
[Step 1000] CE/token (EMA): 1.553 | Contrast[mask]: 0.000 | RL: -72.784 | Reward: 0.5781
[Step 1010] CE/token (EMA): 1.468 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.494 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.482 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.470 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disgusted'
[RL sample] GEN: 'disgusted, disgusted, disgusted,'
[RL step 1050] reward=0.6094 adv=+0.1780 gamma=2.20e-04
[Step 1050] CE/token (EMA): 1.494 | Contrast[mask]: 0.000 | RL: -79.413 | Reward: 0.6094
[Step 1060] CE/token (EMA): 1.513 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.569 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.523 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.496 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'nostalgic'
[RL sample] GEN: 'nostalgic, sentimental, sentimental,'
[RL step 1100] reward=0.4453 adv=-0.0038 gamma=2.20e-04
[Step 1100] CE/token (EMA): 1.549 | Contrast[mask]: 0.000 | RL: 1.704 | Reward: 0.4453
[Step 1110] CE/token (EMA): 1.591 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.583 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.696 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.590 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sentimental'
[RL sample] GEN: 'grateful, sentimental, sentimental,'
[RL step 1150] reward=0.5156 adv=+0.0669 gamma=2.20e-04
[Step 1150] CE/token (EMA): 1.547 | Contrast[mask]: 0.000 | RL: -29.837 | Reward: 0.5156
[Step 1160] CE/token (EMA): 1.526 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.437 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.488 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.442 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'confident'
[RL sample] GEN: 'prepared for the occasion, prepared'
[RL step 1200] reward=0.5156 adv=+0.0602 gamma=2.20e-04
[Step 1200] CE/token (EMA): 1.515 | Contrast[mask]: 0.000 | RL: -26.845 | Reward: 0.5156
[Step 1210] CE/token (EMA): 1.621 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.490 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.507 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.537 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty, guilty, guilty,'
[RL step 1250] reward=0.6250 adv=+0.1635 gamma=2.20e-04
[Step 1250] CE/token (EMA): 1.599 | Contrast[mask]: 0.000 | RL: -73.004 | Reward: 0.6250
[Step 1260] CE/token (EMA): 1.616 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.556 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.521 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.454 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'jealous'
[RL sample] GEN: 'proud, proud, proud,'
[RL step 1300] reward=0.5781 adv=+0.1003 gamma=2.20e-04
[Step 1300] CE/token (EMA): 1.459 | Contrast[mask]: 0.000 | RL: -44.717 | Reward: 0.5781
[Step 1310] CE/token (EMA): 1.529 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.482 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.555 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.441 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited, anticipating the ride,'
[RL step 1350] reward=0.4062 adv=-0.0816 gamma=2.20e-04
[Step 1350] CE/token (EMA): 1.431 | Contrast[mask]: 0.000 | RL: 36.416 | Reward: 0.4062
[Step 1360] CE/token (EMA): 1.321 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.244 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.372 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.429 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'caring, caring, caring enough'
[RL step 1400] reward=0.5078 adv=+0.0281 gamma=2.20e-04
[Step 1400] CE/token (EMA): 1.487 | Contrast[mask]: 0.000 | RL: -12.551 | Reward: 0.5078
[Step 1410] CE/token (EMA): 1.539 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.573 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.520 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.461 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'afraid'
[RL sample] GEN: 'apprehensive, anxious, and'
[RL step 1450] reward=0.4219 adv=-0.0606 gamma=2.20e-04
[Step 1450] CE/token (EMA): 1.489 | Contrast[mask]: 0.000 | RL: 27.046 | Reward: 0.4219
[Step 1460] CE/token (EMA): 1.618 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.597 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.586 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.531 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified, terrified, terrified, | surprised and surprised surprised surprised surprised | excited, anticipating the exciting, | terrified, terrified, terrified,
[ValMetric epoch 2] accuracy=0.5600 | best=0.5600 @ epoch 2
[RL sample] REF: 'annoyed'
[RL sample] GEN: 'annoyed, annoyed, annoyed,'
[RL step 1500] reward=0.6641 adv=+0.1876 gamma=2.20e-04
[Step 1500] CE/token (EMA): 1.450 | Contrast[mask]: 0.000 | RL: -83.750 | Reward: 0.6641
[Step 1510] CE/token (EMA): 1.355 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.277 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.282 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.454 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'joyful'
[RL sample] GEN: 'joyful, content, grateful for'
[RL step 1550] reward=0.5938 adv=+0.0986 gamma=2.20e-04
[Step 1550] CE/token (EMA): 1.363 | Contrast[mask]: 0.000 | RL: -43.942 | Reward: 0.5938
[Step 1560] CE/token (EMA): 1.423 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.359 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.268 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.284 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'impressed with the game faithful in'
[RL step 1600] reward=0.4062 adv=-0.0988 gamma=2.20e-04
[Step 1600] CE/token (EMA): 1.291 | Contrast[mask]: 0.000 | RL: 44.111 | Reward: 0.4062
[Step 1610] CE/token (EMA): 1.290 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.328 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.322 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.425 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'caring'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 1650] reward=0.4453 adv=-0.0499 gamma=2.20e-04
[Step 1650] CE/token (EMA): 1.433 | Contrast[mask]: 0.000 | RL: 22.241 | Reward: 0.4453
[Step 1660] CE/token (EMA): 1.449 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.382 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.359 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.402 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'embarrassed'
[RL sample] GEN: 'embarrassed and ashamed.\n\n| embarrassed'
[RL step 1700] reward=0.4922 adv=+0.0020 gamma=2.20e-04
[Step 1700] CE/token (EMA): 1.343 | Contrast[mask]: 0.000 | RL: -0.893 | Reward: 0.4922
[Step 1710] CE/token (EMA): 1.295 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.379 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.414 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.407 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed and sad disappointed.\n\n|'

In [10]:
# ============================================================
# КОНТРОЛЬНЫЕ CAPACITY-ТОЧКИ (критика-3 §22): 1.5B и 3B при n=6000
# ПО ЕДИНОМУ sweep-ПРОТОКОЛЮ (без probe, общий случайный старт на
# (модель,сид)) — уравнивает init-протокол с 0.5B и даёт трёхточечную
# dose-response кривую: 0.5B (n=7) -> 1.5B (n=3) -> 3B (n=3).
# Отдельная сверка: 3B probe-протокол из D1.6 (RL−MLE +0.0043, n=10).
# Время: 3B ~37 мин/сид, 1.5B ~22 мин/сид -> ~3 ч суммарно. Resume-safe.
# ============================================================
import copy
import math

CAP_POINTS = [("15B", "Qwen/Qwen2.5-1.5B"), ("3B", "Qwen/Qwen2.5-3B")]
CAP_SIZE, CAP_SEEDS = 6000, [42, 43, 44]

for mshort, model_name in CAP_POINTS:
    for seed in CAP_SEEDS:
        if any(r["model"] == mshort and r["seed"] == seed and r["size"] == CAP_SIZE
               and all(k in r for k in SWEEP_CONFIGS) for r in ld_rows):
            print(f"[Resume] {mshort} s{seed} n={CAP_SIZE} готов")
            continue
        shared = make_shared_start(model_name, seed)
        rebuild_d1_datasets(CAP_SIZE)
        steps = math.ceil(CAP_SIZE / cfg_sweep_base.batch_size) * \
            cfg_sweep_base.total_epochs
        row = {"model": mshort, "seed": seed, "size": CAP_SIZE}
        for cname in SWEEP_CONFIGS:
            c = copy.copy(cfg_sweep_base)
            c.model_name = model_name
            c.seed = seed
            c.train_size = CAP_SIZE
            c.init_selection_inits = 0
            c.warmup_steps = min(200, max(10, steps // 10))
            c.output_dir = f"./sweep_ld/{mshort}_{cname}_s{seed}_n{CAP_SIZE}"
            if cname == "MLE":
                c.beta = 0.0; c.gamma = 0.0; c.gamma_auto = False
            elif cname == "mask":
                c.beta = 0.1; c.contrast_mode = "mask"
                c.gamma = 0.0; c.gamma_auto = False
            else:
                c.beta = 0.0; c.gamma = 2e-5; c.gamma_auto = True
            rj = os.path.join(c.output_dir, "results.json")
            if os.path.exists(rj):
                with open(rj) as f:
                    sc = json.load(f)["test_scores"]
            else:
                sc = run_experiment(c, f"{cname} {mshort} n={CAP_SIZE} (s{seed})",
                                    init_state=shared)
            row[cname] = sc["accuracy"]
            row[f"{cname}-verb"] = sc["verb_accuracy"]
            gc.collect(); torch.cuda.empty_cache()
        ld_rows = [r for r in ld_rows
                   if not (r["model"] == mshort and r["seed"] == seed
                           and r["size"] == CAP_SIZE)] + [row]
        with open(_summary_ld, "w") as f:
            json.dump({"rows": ld_rows}, f, indent=2)
        print(f">>> {mshort} s{seed} n={CAP_SIZE}: "
              f"{ {k: round(row[k], 4) for k in SWEEP_CONFIGS} }\n")
        del shared
        gc.collect(); torch.cuda.empty_cache()

# ---------- вердикт: dose-response по ёмкости ----------
from math import sqrt

tc = {3: 4.303, 4: 3.182, 5: 2.776, 6: 2.571, 7: 2.447}
print("\n" + "=" * 92)
print("DOSE-RESPONSE ПО ЁМКОСТИ (единый sweep-протокол: без probe,")
print("общий случайный старт на (модель,сид), n=6000)")
print("=" * 92)
print(f"{'модель':<8}{'MLE':<10}{'mask−MLE':<28}{'RL−MLE':<28}")
for mshort in ("05B", "15B", "3B"):
    rs = [r for r in ld_rows if r["model"] == mshort and r["size"] == 6000]
    if not rs:
        continue
    line = f"{mshort:<8}{np.mean([r['MLE'] for r in rs]):<10.3f}"
    for a in ("mask", "RL"):
        dd = [r[a] - r["MLE"] for r in rs]
        n = len(dd)
        se = np.std(dd, ddof=1) / sqrt(n)
        t = np.mean(dd) / se if se > 0 else float("nan")
        sig = abs(t) > tc.get(n, 2.447)
        line += (f"{np.mean(dd):+.4f} (t={t:+.1f}"
                 f"{' ЗНАЧ' if sig else ''}, n={n})   ")
    print(line)
print("\nСверка с probe-протоколом (D1.6, 3B): RL−MLE +0.0043 (n=10, 8/10,")
print("бутстреп p=0.023); mask −0.0002 (n=7, большой тест). Если sweep-3B")
print("воспроизводит порядок эффектов — capacity-заявка протокольно чиста.")
print("\nГипотеза (предзаявлена, ROADMAP A): эффект RL убывает с ростом")
print("ёмкости модели; кривая 0.5B > 1.5B > 3B monotone по mean-разности.")

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 1427.79it/s]
Map: 100%|██████████| 6000/6000 [00:00<00:00, 10551.55 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 7586.97 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 8006.96 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8223.67 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 15B n=6000 (s42)
======================================================================

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 9058.34it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 3,755,264 || all params: 1,547,469,568 || trainable%: 0.2427
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 5.905 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 5.979 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 5.479 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 4.937 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 4.181 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.784 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.497 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.413 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 3.023 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.722 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 2.609 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.603 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.403 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.371 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.205 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.107 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.044 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 1.883 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 1.781 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 1.812 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 1.911 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 1.847 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 1.768 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.064 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.019 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 1.923 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 1.907 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.902 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 2.020 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 2.180 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.891 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.815 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.662 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.527 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.641 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.636 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.674 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.654 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.812 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.813 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.723 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.764 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.707 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.720 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.682 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.790 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.646 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.579 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.712 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.658 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.732 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.631 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.534 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.477 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.436 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.364 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.617 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.725 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.746 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.707 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.649 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.665 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.617 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.543 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.471 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.655 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.709 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.660 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.590 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.524 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.509 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.490 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.535 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.598 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.519 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5300 | best=0.5300 @ epoch 1
[Step 750] CE/token (EMA): 1.481 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.595 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.465 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.451 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.418 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.454 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.492 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.526 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.506 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.455 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.500 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.416 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.516 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.362 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.491 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.510 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.557 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.458 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.437 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.501 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.547 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.557 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.616 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.454 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.480 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.435 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.454 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.451 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.414 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.435 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.548 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.498 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.584 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.513 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.521 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.413 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.483 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.537 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.507 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.382 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.496 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.510 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.403 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.457 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.420 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.378 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.505 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.506 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.427 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.290 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.200 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.228 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.219 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.177 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.304 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.268 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.257 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.343 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.320 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.282 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.513 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.421 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.443 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.409 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.291 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.251 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.259 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.282 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.205 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.222 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified surprised surprised terrified terrified terrified | angry surprised angry angry angry angry | excited and excited excited joyful joyful | disgusted surprised surprised angry surprised angry
[ValMetric epoch 2] accuracy=0.6150 | best=0.6150 @ epoch 2
[Step 1500] CE/token (EMA): 1.216 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.191 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.224 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.245 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.249 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.295 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.332 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.260 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.220 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.290 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.221 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.251 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.215 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.138 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.207 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.354 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.359 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.256 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.344 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.260 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.146 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.257 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.290 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.252 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.186 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.145 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.127 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.131 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.202 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.212 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.118 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.199 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.165 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.318 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.253 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.198 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.158 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.200 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.127 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.194 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.138 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.229 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.241 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.209 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.282 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.292 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.269 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.173 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.276 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.246 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.107 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.120 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.180 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.215 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.241 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.233 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.080 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.056 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.049 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.115 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.097 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.210 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.298 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.199 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.203 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.208 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.166 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.091 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.069 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.042 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 0.983 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.044 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.082 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.046 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.025 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified terrified terrified terrified terrified terrified | surprised surprised surprised surprised surprised surprised | excited anticipating excited anticipating excited anticipating | disgusted disgusted disgusted disgusted disgusted disgusted

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 9664.95it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 3,755,264 || all params: 1,547,469,568 || trainable%: 0.2427
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 5.905 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 5.981 | Contrast[mask]: 0.644 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 5.481 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 4.942 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 4.171 | Contrast[mask]: 0.665 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.769 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.481 | Contrast[mask]: 0.526 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.431 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.966 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.713 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 2.612 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.540 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.373 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.326 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.197 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.014 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.003 | Contrast[mask]: 0.635 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 1.924 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 1.878 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 1.994 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.052 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 1.954 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 1.835 | Contrast[mask]: 0.651 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.128 | Contrast[mask]: 0.667 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.015 | Contrast[mask]: 0.664 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 1.833 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 1.791 | Contrast[mask]: 0.651 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.796 | Contrast[mask]: 0.646 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.879 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 2.125 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.884 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.855 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.661 | Contrast[mask]: 0.664 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.464 | Contrast[mask]: 0.668 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.595 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.619 | Contrast[mask]: 0.665 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.637 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.691 | Contrast[mask]: 0.665 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.758 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.832 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.869 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.868 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.776 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.704 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.624 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.741 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.583 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.549 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.714 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.642 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.720 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.652 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.581 | Contrast[mask]: 0.656 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.556 | Contrast[mask]: 0.661 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.470 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.395 | Contrast[mask]: 0.669 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.575 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.603 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.678 | Contrast[mask]: 0.636 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.673 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.612 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.658 | Contrast[mask]: 0.634 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.600 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.557 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.517 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.610 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.728 | Contrast[mask]: 0.665 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.682 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.565 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.505 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.468 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.441 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.497 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.512 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.500 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5400 | best=0.5400 @ epoch 1
[Step 750] CE/token (EMA): 1.403 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.509 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.377 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.413 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.348 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.340 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.373 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.530 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.504 | Contrast[mask]: 0.667 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.518 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.440 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.461 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.495 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.437 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.490 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.372 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.519 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.510 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.545 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.459 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.415 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.461 | Contrast[mask]: 0.655 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.449 | Contrast[mask]: 0.666 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.386 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.497 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.556 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.464 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.444 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.467 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.512 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.518 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.495 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.470 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.408 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.546 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.458 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.527 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.482 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.352 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.311 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.395 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.527 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.437 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.327 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.482 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.518 | Contrast[mask]: 0.653 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.442 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.415 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.417 | Contrast[mask]: 0.629 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.384 | Contrast[mask]: 0.663 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.470 | Contrast[mask]: 0.660 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.501 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.407 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.266 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.179 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.205 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.183 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.166 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.278 | Contrast[mask]: 0.638 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.322 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.305 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.385 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.347 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.319 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.559 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.430 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.452 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.421 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.334 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.295 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.277 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.287 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.233 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.211 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.250 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified surprised surprised surprised surprised surprised | angry angry angry angry angry angry | excited anticipating excited anticipating excited anticipating | surprised surprised surprised surprised surprised surprised
[ValMetric epoch 2] accuracy=0.5550 | best=0.5550 @ epoch 2
[Step 1500] CE/token (EMA): 1.251 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.225 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.225 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.250 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.227 | Contrast[mask]: 0.657 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.227 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.308 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.238 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.220 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.266 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.262 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.254 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.227 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.127 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.205 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.359 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.330 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.230 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.297 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.216 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.117 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.237 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.283 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.290 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.173 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.143 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.162 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.142 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.205 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.167 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.055 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.153 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.121 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.248 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.219 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.199 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.160 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.171 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.106 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.203 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.166 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.209 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.202 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.186 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.267 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.297 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.261 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.196 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.272 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.216 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.091 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.145 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.246 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.214 | Contrast[mask]: 0.662 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.261 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.239 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.089 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.049 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.073 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.111 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.082 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.207 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.304 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.208 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.195 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.200 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.177 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.080 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.052 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.067 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.070 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.064 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.137 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.118 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.050 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified afraidensive terrified afraidensive | surprised surprised surprised surprised surprised surprised | excited anticipating excited anticipating excited anticipating | surprised surprised surprised surprised surprised surprised

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 9932.22it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 3,755,264 || all params: 1,547,469,568 || trainable%: 0.2427
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 1.101e-06
[RL sample] REF: 'prepared'
[RL sample] GEN: 'N/A\nContext: The'
[RL step 0] reward=0.1719 adv=+0.1719 gamma=1.10e-06
[Step 0] CE/token (EMA): 5.905 | Contrast[mask]: 0.000 | RL: -1.771 | Reward: 0.1719

[Step 10] CE/token (EMA): 5.982 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 5.478 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 4.936 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 4.186 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'disgusted\nYou are an AI'
[RL step 50] reward=0.3047 adv=+0.2875 gamma=1.10e-06
[Step 50] CE/token (EMA): 3.772 | Contrast[mask]: 0.000 | RL: -2.964 | Reward: 0.3047
[Step 60] CE/token (EMA): 3.472 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.410 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.958 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.681 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed\nYou are a language'
[RL step 100] reward=0.4844 adv=+0.4384 gamma=1.10e-06
[Step 100] CE/token (EMA): 2.597 | Contrast[mask]: 0.000 | RL: -4.518 | Reward: 0.4844
[Step 110] CE/token (EMA): 2.581 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.380 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.343 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.221 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'sad\nYou are an only'
[RL step 150] reward=0.5000 adv=+0.4102 gamma=1.10e-06
[Step 150] CE/token (EMA): 2.027 | Contrast[mask]: 0.000 | RL: -4.229 | Reward: 0.5000
[Step 160] CE/token (EMA): 2.033 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 1.872 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 1.742 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 1.813 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'surprised\nYou are now imagining'
[RL step 200] reward=0.3906 adv=+0.2598 gamma=1.10e-06
[Step 200] CE/token (EMA): 1.882 | Contrast[mask]: 0.000 | RL: -2.678 | Reward: 0.3906
[Step 210] CE/token (EMA): 2.034 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 1.912 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.224 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.183 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proudant\nYou might also'
[RL step 250] reward=0.4062 adv=+0.2495 gamma=1.10e-06
[Step 250] CE/token (EMA): 2.067 | Contrast[mask]: 0.000 | RL: -2.571 | Reward: 0.4062
[Step 260] CE/token (EMA): 1.890 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.893 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.926 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.982 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'terrified and afraid for my parents'
[RL step 300] reward=0.5625 adv=+0.3808 gamma=1.10e-06
[Step 300] CE/token (EMA): 1.807 | Contrast[mask]: 0.000 | RL: -3.925 | Reward: 0.5625
[Step 310] CE/token (EMA): 1.846 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.731 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.572 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 2.254 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'surprised'
[RL sample] GEN: 'surprised and surprised that he was'
[RL step 350] reward=0.5938 adv=+0.3739 gamma=1.10e-06
[Step 350] CE/token (EMA): 2.039 | Contrast[mask]: 0.000 | RL: -3.855 | Reward: 0.5938
[Step 360] CE/token (EMA): 1.906 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.863 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.870 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.911 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'hopeful'
[RL sample] GEN: 'prepared\nconfident\nprepared'
[RL step 400] reward=0.4297 adv=+0.1725 gamma=1.10e-06
[Step 400] CE/token (EMA): 1.768 | Contrast[mask]: 0.000 | RL: -1.778 | Reward: 0.4297
[Step 410] CE/token (EMA): 1.759 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.719 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.738 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.659 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'prepared'
[RL sample] GEN: 'prepared for the adventure</code'
[RL step 450] reward=0.4922 adv=+0.2177 gamma=1.10e-06
[Step 450] CE/token (EMA): 1.756 | Contrast[mask]: 0.000 | RL: -2.244 | Reward: 0.4922
[Step 460] CE/token (EMA): 1.606 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.615 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.728 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.679 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'prepared and prepared for the occasion'
[RL step 500] reward=0.4375 adv=+0.1413 gamma=1.10e-06
[Step 500] CE/token (EMA): 1.695 | Contrast[mask]: 0.000 | RL: -1.456 | Reward: 0.4375
[Step 510] CE/token (EMA): 1.621 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.558 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.561 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.508 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anticipating'
[RL sample] GEN: 'excited anticipating excited anticipating excited anticipating'
[RL step 550] reward=0.5312 adv=+0.2209 gamma=1.10e-06
[Step 550] CE/token (EMA): 1.408 | Contrast[mask]: 0.000 | RL: -2.277 | Reward: 0.5312
[Step 560] CE/token (EMA): 1.544 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.639 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.711 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.666 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'lonely'
[RL sample] GEN: 'lonely lonely lonely lonely lonely lonely'
[RL step 600] reward=0.5859 adv=+0.2535 gamma=1.10e-06
[Step 600] CE/token (EMA): 1.653 | Contrast[mask]: 0.000 | RL: -2.613 | Reward: 0.5859
[Step 610] CE/token (EMA): 1.635 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.692 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 2.203 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 2.475 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anxious anxious anxious anxious anxious anxious'
[RL step 650] reward=0.3984 adv=+0.0406 gamma=1.10e-06
[Step 650] CE/token (EMA): 2.253 | Contrast[mask]: 0.000 | RL: -0.419 | Reward: 0.3984
[Step 660] CE/token (EMA): 2.019 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.924 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.772 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.596 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anticipating anticipating anticipating anticipating anticipating anticipating'
[RL step 700] reward=0.4609 adv=+0.0991 gamma=1.10e-06
[Step 700] CE/token (EMA): 1.535 | Contrast[mask]: 0.000 | RL: -1.021 | Reward: 0.4609
[Step 710] CE/token (EMA): 1.506 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.510 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.524 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.544 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5200 | best=0.5200 @ epoch 1
[RL sample] REF: 'jealous'
[RL sample] GEN: 'annoyed and annoyed with my mother'
[RL step 750] reward=0.4453 adv=+0.0735 gamma=1.10e-06
[Step 750] CE/token (EMA): 1.475 | Contrast[mask]: 0.000 | RL: -0.758 | Reward: 0.4453
[Step 760] CE/token (EMA): 1.574 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.393 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.461 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.355 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'disappointed guilty guilty guilty guilty guilty'
[RL step 800] reward=0.5781 adv=+0.1990 gamma=1.10e-06
[Step 800] CE/token (EMA): 1.353 | Contrast[mask]: 0.000 | RL: -2.052 | Reward: 0.5781
[Step 810] CE/token (EMA): 1.391 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.471 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.477 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.418 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty and ashamedensive.\nAnswer'
[RL step 850] reward=0.5703 adv=+0.1713 gamma=1.10e-06
[Step 850] CE/token (EMA): 1.423 | Contrast[mask]: 0.000 | RL: -1.766 | Reward: 0.5703
[Step 860] CE/token (EMA): 1.413 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.417 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.345 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.461 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'furious, devastated furious furious furious'
[RL step 900] reward=0.4375 adv=+0.0214 gamma=1.10e-06
[Step 900] CE/token (EMA): 1.342 | Contrast[mask]: 0.000 | RL: -0.220 | Reward: 0.4375
[Step 910] CE/token (EMA): 1.497 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.553 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.562 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.425 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'afraid afraid afraid afraid afraid afraid'
[RL step 950] reward=0.4297 adv=+0.0114 gamma=1.10e-06
[Step 950] CE/token (EMA): 1.418 | Contrast[mask]: 0.000 | RL: -0.118 | Reward: 0.4297
[Step 960] CE/token (EMA): 1.509 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.522 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.430 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.537 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud proud proud proud proud proud'
[RL step 1000] reward=0.5625 adv=+0.1431 gamma=1.10e-06
[Step 1000] CE/token (EMA): 1.654 | Contrast[mask]: 0.000 | RL: -1.475 | Reward: 0.5625
[Step 1010] CE/token (EMA): 1.469 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.424 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.489 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.512 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disgusted'
[RL sample] GEN: 'disgusted and disgusted disgusted disgusted disgusted'
[RL step 1050] reward=0.6328 adv=+0.1991 gamma=1.10e-06
[Step 1050] CE/token (EMA): 1.491 | Contrast[mask]: 0.000 | RL: -2.052 | Reward: 0.6328
[Step 1060] CE/token (EMA): 1.493 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.419 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.374 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.509 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'nostalgic'
[RL sample] GEN: 'nostalgic joyful joyful nostalgic nostalgic nostalgic'
[RL step 1100] reward=0.5547 adv=+0.1010 gamma=1.10e-06
[Step 1100] CE/token (EMA): 1.456 | Contrast[mask]: 0.000 | RL: -1.041 | Reward: 0.5547
[Step 1110] CE/token (EMA): 1.543 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.532 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.394 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.336 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sentimental'
[RL sample] GEN: 'sentimental sentimental surprised surprised sentimental sentimental'
[RL step 1150] reward=0.5703 adv=+0.1066 gamma=1.10e-06
[Step 1150] CE/token (EMA): 1.358 | Contrast[mask]: 0.000 | RL: -1.098 | Reward: 0.5703
[Step 1160] CE/token (EMA): 1.470 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.432 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.356 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.508 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'confident'
[RL sample] GEN: 'prepared and prepared caring faithful faithful'
[RL step 1200] reward=0.5156 adv=+0.0412 gamma=1.10e-06
[Step 1200] CE/token (EMA): 1.538 | Contrast[mask]: 0.000 | RL: -0.425 | Reward: 0.5156
[Step 1210] CE/token (EMA): 1.435 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.431 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.375 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.366 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 1250] reward=0.5938 adv=+0.1152 gamma=1.10e-06
[Step 1250] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: -1.188 | Reward: 0.5938
[Step 1260] CE/token (EMA): 1.481 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.383 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.278 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.188 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'jealous'
[RL sample] GEN: 'confident with confident with confident with'
[RL step 1300] reward=0.5859 adv=+0.0959 gamma=1.10e-06
[Step 1300] CE/token (EMA): 1.235 | Contrast[mask]: 0.000 | RL: -0.988 | Reward: 0.5859
[Step 1310] CE/token (EMA): 1.205 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.167 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.307 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.336 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited anticipating anticipation anticipating anticipation anticipating'
[RL step 1350] reward=0.4141 adv=-0.0856 gamma=1.10e-06
[Step 1350] CE/token (EMA): 1.301 | Contrast[mask]: 0.000 | RL: 0.882 | Reward: 0.4141
[Step 1360] CE/token (EMA): 1.375 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.367 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.343 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.546 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'grateful caring caring caring caring caring'
[RL step 1400] reward=0.5547 adv=+0.0636 gamma=1.10e-06
[Step 1400] CE/token (EMA): 1.463 | Contrast[mask]: 0.000 | RL: -0.656 | Reward: 0.5547
[Step 1410] CE/token (EMA): 1.513 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.447 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.303 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.244 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'afraid'
[RL sample] GEN: 'terrified anticipating death terrified anxious anxious'
[RL step 1450] reward=0.4297 adv=-0.0678 gamma=1.10e-06
[Step 1450] CE/token (EMA): 1.314 | Contrast[mask]: 0.000 | RL: 0.698 | Reward: 0.4297
[Step 1460] CE/token (EMA): 1.313 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.327 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.208 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.250 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified surprised terrified terrified terrified terrified | embarrassed angry angry angry angry angry | excited excited excited excited excited excited | disgusted disgusted disgusted disgusted disgusted disgusted
[ValMetric epoch 2] accuracy=0.5450 | best=0.5450 @ epoch 2
[RL sample] REF: 'annoyed'
[RL sample] GEN: 'angry angry angry angry angry angry'
[RL step 1500] reward=0.6641 adv=+0.1734 gamma=1.10e-06
[Step 1500] CE/token (EMA): 1.268 | Contrast[mask]: 0.000 | RL: -1.787 | Reward: 0.6641
[Step 1510] CE/token (EMA): 1.238 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.224 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.231 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.222 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'joyful'
[RL sample] GEN: 'joyful joyful joyful joyful joyful joyful'
[RL step 1550] reward=0.6250 adv=+0.1170 gamma=1.10e-06
[Step 1550] CE/token (EMA): 1.187 | Contrast[mask]: 0.000 | RL: -1.206 | Reward: 0.6250
[Step 1560] CE/token (EMA): 1.261 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.248 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.256 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.329 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'impressed impressed impressed impressed impressed impressed'
[RL step 1600] reward=0.4766 adv=-0.0431 gamma=1.10e-06
[Step 1600] CE/token (EMA): 1.263 | Contrast[mask]: 0.000 | RL: 0.445 | Reward: 0.4766
[Step 1610] CE/token (EMA): 1.297 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.246 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.164 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.207 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'caring'
[RL sample] GEN: 'grateful grateful grateful grateful grateful grateful'
[RL step 1650] reward=0.4531 adv=-0.0623 gamma=1.10e-06
[Step 1650] CE/token (EMA): 1.354 | Contrast[mask]: 0.000 | RL: 0.642 | Reward: 0.4531
[Step 1660] CE/token (EMA): 1.372 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.266 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.328 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.268 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'embarrassed'
[RL sample] GEN: 'embarrassed surprised and embarrassed guilty guilty'
[RL step 1700] reward=0.4531 adv=-0.0560 gamma=1.10e-06

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 10102.65it/s]
Map: 100%|██████████| 6000/6000 [00:00<00:00, 10408.46 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 8084.24 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7323.99 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8318.48 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 15B n=6000 (s43)
======================================================================

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 10009.92it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 3,755,264 || all params: 1,547,469,568 || trainable%: 0.2427
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 6.177 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 6.431 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 5.897 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.348 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 4.588 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 4.039 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.598 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.402 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 3.204 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.874 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 2.725 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.527 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.360 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.186 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.138 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.065 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.136 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.044 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.096 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 1.944 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 1.993 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.010 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 1.961 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 1.874 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 1.898 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 2.092 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 1.873 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.836 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.917 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.828 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.789 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.737 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.670 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.733 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.759 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.753 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.946 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.854 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.722 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.620 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.689 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.773 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.705 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.583 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.765 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.779 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.639 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.621 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.556 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.575 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.718 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.702 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.649 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.499 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.491 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.433 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.367 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.401 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.511 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.621 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.478 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.552 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.570 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.508 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.655 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.555 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.627 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.597 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.478 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.487 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.494 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.393 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.423 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.334 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.430 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5550 | best=0.5550 @ epoch 1
[Step 750] CE/token (EMA): 1.423 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.388 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.359 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.392 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.365 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.452 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.533 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.468 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.456 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.556 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.480 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.517 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.479 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.390 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.432 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.563 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.573 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.500 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.563 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.368 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.444 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 5.617 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 4.178 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 3.176 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 2.473 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 2.072 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.698 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.595 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.508 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.320 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.388 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.366 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.541 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.466 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.392 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.385 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.344 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.338 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.417 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.344 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.403 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.420 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.373 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.485 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.559 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.500 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.401 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.436 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.407 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.295 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.321 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.424 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.464 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.473 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.429 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.277 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.226 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.205 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.307 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.276 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.423 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.525 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.418 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.419 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.444 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.407 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.307 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.229 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.233 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.242 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.254 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.274 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.295 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.253 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified. terrified terrified terrified terrified | surprised and surprised surprised surprised surprised | excited anticipating anticipating anticipating anticipating anticipating | surprised surprised surprised surprised surprised surprised
[ValMetric epoch 2] accuracy=0.5750 | best=0.5750 @ epoch 2
[Step 1500] CE/token (EMA): 1.237 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.222 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.175 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.287 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.242 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.259 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.282 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.245 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.293 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.296 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.338 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.218 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.226 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.144 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.268 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.244 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.178 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.187 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.312 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.193 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.277 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.233 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.169 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.216 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.190 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.228 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.285 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.354 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.300 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.281 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.347 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.322 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.268 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.209 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.336 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.388 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.350 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.226 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.267 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.275 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.176 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.118 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.096 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.034 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.128 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.186 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.387 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.269 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.164 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.057 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.124 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.170 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.165 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.102 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.120 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.244 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.273 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.170 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.182 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.212 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.167 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.169 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.057 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.031 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.060 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.216 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.101 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.091 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.016 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.043 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.087 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.077 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.039 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.081 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.157 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 10238.43it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 3,755,264 || all params: 1,547,469,568 || trainable%: 0.2427
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 6.177 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 6.432 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 5.900 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.344 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 4.583 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 4.034 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.600 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.408 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 3.215 | Contrast[mask]: 0.668 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.898 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 2.724 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.532 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.376 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.225 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.157 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.052 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.082 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.014 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.044 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 1.920 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.056 | Contrast[mask]: 0.652 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.033 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.011 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 1.969 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 1.963 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 2.202 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 2.084 | Contrast[mask]: 0.655 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.030 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 2.067 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.936 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.883 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.828 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.713 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.708 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.864 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.754 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.929 | Contrast[mask]: 0.665 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.897 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.717 | Contrast[mask]: 0.665 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.638 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.679 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.776 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.773 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.646 | Contrast[mask]: 0.613 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.796 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.767 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.622 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.646 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.656 | Contrast[mask]: 0.649 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.566 | Contrast[mask]: 0.647 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.644 | Contrast[mask]: 0.669 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.734 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.651 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.510 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.464 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.484 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.437 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.476 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.549 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.580 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.496 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.507 | Contrast[mask]: 0.645 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.587 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.560 | Contrast[mask]: 0.520 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.641 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.531 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.587 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.547 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.495 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.436 | Contrast[mask]: 0.666 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.438 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.362 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.370 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.352 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.411 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5750 | best=0.5750 @ epoch 1
[Step 750] CE/token (EMA): 1.381 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.413 | Contrast[mask]: 0.669 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.389 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.417 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.455 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.483 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.592 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.521 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.466 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.559 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.445 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.464 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.441 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.338 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.376 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.509 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.506 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.442 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.535 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.480 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.362 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.474 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.433 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.438 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.389 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.306 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.316 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.332 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.386 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.348 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.213 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.351 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.358 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.481 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.423 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.348 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.359 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.334 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.279 | Contrast[mask]: 0.664 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.313 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.291 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.404 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.417 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.358 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.466 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.482 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.444 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.353 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.437 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.465 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.337 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.374 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.425 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.447 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.480 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.479 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.337 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.309 | Contrast[mask]: 0.646 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.254 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.337 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.274 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.373 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.508 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.424 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.404 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.375 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.346 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.249 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.242 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.233 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.255 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.259 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.299 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.333 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.264 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified anticipating the worst anticipating the | surprised surprised surprised surprised surprised surprised | excited anticipating anticipating anticipating anticipating anticipating | surprised surprised surprised surprised surprised surprised
[ValMetric epoch 2] accuracy=0.6350 | best=0.6350 @ epoch 2
[Step 1500] CE/token (EMA): 1.219 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.221 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.180 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.313 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.257 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.257 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.268 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.227 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.293 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.319 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.329 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.250 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.264 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.170 | Contrast[mask]: 0.661 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.295 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.222 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.188 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.228 | Contrast[mask]: 0.659 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.337 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.234 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.372 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.318 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.235 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.251 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.218 | Contrast[mask]: 0.650 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.262 | Contrast[mask]: 0.667 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.281 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.311 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.281 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.263 | Contrast[mask]: 0.658 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.367 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.395 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.314 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.257 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.341 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.336 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.357 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.211 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.262 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.304 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.188 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.119 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.097 | Contrast[mask]: 0.644 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.094 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.160 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.198 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.438 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.313 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.197 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.075 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.120 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.164 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.104 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.069 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.090 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.224 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.258 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.146 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.181 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.230 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.192 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.233 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.112 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.096 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.100 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.190 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.071 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.042 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.024 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.095 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.073 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.059 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.072 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.094 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.150 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 9410.45it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 3,755,264 || all params: 1,547,469,568 || trainable%: 0.2427
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 2.303e-06
[RL sample] REF: 'prepared'
[RL sample] GEN: 'N/A\nContext: The'
[RL step 0] reward=0.0859 adv=+0.0859 gamma=2.30e-06
[Step 0] CE/token (EMA): 6.177 | Contrast[mask]: 0.000 | RL: -1.853 | Reward: 0.0859

[Step 10] CE/token (EMA): 6.430 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 5.893 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.346 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 4.584 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'accepting\nYou are a doctor'
[RL step 50] reward=0.3047 adv=+0.2961 gamma=2.30e-06
[Step 50] CE/token (EMA): 4.046 | Contrast[mask]: 0.000 | RL: -6.385 | Reward: 0.3047
[Step 60] CE/token (EMA): 3.604 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.411 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 3.202 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.878 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed\nNext sentence: i'
[RL step 100] reward=0.4062 adv=+0.3680 gamma=2.30e-06
[Step 100] CE/token (EMA): 2.712 | Contrast[mask]: 0.000 | RL: -7.936 | Reward: 0.4062
[Step 110] CE/token (EMA): 2.528 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.394 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.210 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.162 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: "devastated\nMe: I'm"
[RL step 150] reward=0.3906 adv=+0.3156 gamma=2.30e-06
[Step 150] CE/token (EMA): 2.031 | Contrast[mask]: 0.000 | RL: -6.808 | Reward: 0.3906
[Step 160] CE/token (EMA): 2.133 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.069 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.036 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 1.902 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'surprised\nWho would be surprised'
[RL step 200] reward=0.4219 adv=+0.3153 gamma=2.30e-06
[Step 200] CE/token (EMA): 1.895 | Contrast[mask]: 0.000 | RL: -6.799 | Reward: 0.4219
[Step 210] CE/token (EMA): 2.002 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.128 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.205 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.314 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'content\nFeeling: content'
[RL step 250] reward=0.3750 adv=+0.2369 gamma=2.30e-06
[Step 250] CE/token (EMA): 2.519 | Contrast[mask]: 0.000 | RL: -5.110 | Reward: 0.3750
[Step 260] CE/token (EMA): 2.172 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.062 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 2.027 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.917 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'terrified\nGiven that the car'
[RL step 300] reward=0.4844 adv=+0.3226 gamma=2.30e-06
[Step 300] CE/token (EMA): 1.868 | Contrast[mask]: 0.000 | RL: -6.957 | Reward: 0.4844
[Step 310] CE/token (EMA): 1.804 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.729 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.743 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.905 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'surprised'
[RL sample] GEN: 'impressed\nsurprised'
[RL step 350] reward=0.5859 adv=+0.3919 gamma=2.30e-06
[Step 350] CE/token (EMA): 1.759 | Contrast[mask]: 0.000 | RL: -8.452 | Reward: 0.5859
[Step 360] CE/token (EMA): 1.901 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.834 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.698 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.656 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'hopeful'
[RL sample] GEN: 'prepared\nsurprised'
[RL step 400] reward=0.4688 adv=+0.2355 gamma=2.30e-06
[Step 400] CE/token (EMA): 1.635 | Contrast[mask]: 0.000 | RL: -5.078 | Reward: 0.4688
[Step 410] CE/token (EMA): 1.850 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.818 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.718 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.863 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'prepared'
[RL sample] GEN: 'prepared\nsurprised'
[RL step 450] reward=0.5000 adv=+0.2432 gamma=2.30e-06
[Step 450] CE/token (EMA): 1.858 | Contrast[mask]: 0.000 | RL: -5.245 | Reward: 0.5000
[Step 460] CE/token (EMA): 1.667 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.694 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.599 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.614 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited and excited with anticipation.'
[RL step 500] reward=0.4297 adv=+0.1486 gamma=2.30e-06
[Step 500] CE/token (EMA): 1.712 | Contrast[mask]: 0.000 | RL: -3.204 | Reward: 0.4297
[Step 510] CE/token (EMA): 1.712 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.634 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.470 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.485 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anticipating'
[RL sample] GEN: 'excited, excited\nsurr'
[RL step 550] reward=0.5781 adv=+0.2822 gamma=2.30e-06
[Step 550] CE/token (EMA): 1.557 | Contrast[mask]: 0.000 | RL: -6.084 | Reward: 0.5781
[Step 560] CE/token (EMA): 1.655 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 2.131 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 5.369 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 5.903 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'lonely'
[RL sample] GEN: 'angry surprised surprised surprised surprised surprised'
[RL step 600] reward=0.0625 adv=-0.2617 gamma=2.30e-06
[Step 600] CE/token (EMA): 5.375 | Contrast[mask]: 0.000 | RL: 5.642 | Reward: 0.0625
[Step 610] CE/token (EMA): 4.781 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 4.385 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 4.169 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 3.822 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'confident surprised surprised surprised lonely lonely'
[RL step 650] reward=0.1406 adv=-0.1574 gamma=2.30e-06
[Step 650] CE/token (EMA): 3.505 | Contrast[mask]: 0.000 | RL: 3.393 | Reward: 0.1406
[Step 660] CE/token (EMA): 3.450 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 3.571 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 3.278 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 3.124 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'furious anticipating terrifiedly anticipating terrified'
[RL step 700] reward=0.1094 adv=-0.1729 gamma=2.30e-06
[Step 700] CE/token (EMA): 3.228 | Contrast[mask]: 0.000 | RL: 3.729 | Reward: 0.1094
[Step 710] CE/token (EMA): 3.313 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 3.243 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 3.106 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 3.025 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2350 | best=0.2350 @ epoch 1
[RL sample] REF: 'jealous'
[RL sample] GEN: 'angry annoyed angry annoyed annoyed annoyed'
[RL step 750] reward=0.2266 adv=-0.0384 gamma=2.30e-06
[Step 750] CE/token (EMA): 2.890 | Contrast[mask]: 0.000 | RL: 0.829 | Reward: 0.2266
[Step 760] CE/token (EMA): 2.596 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 2.618 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 2.585 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 2.685 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'bored lonely lonely alone alone alone'
[RL step 800] reward=0.4141 adv=+0.1529 gamma=2.30e-06
[Step 800] CE/token (EMA): 2.507 | Contrast[mask]: 0.000 | RL: -3.297 | Reward: 0.4141
[Step 810] CE/token (EMA): 2.731 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 2.553 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 2.458 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 2.467 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 850] reward=0.4375 adv=+0.1611 gamma=2.30e-06
[Step 850] CE/token (EMA): 2.339 | Contrast[mask]: 0.000 | RL: -3.473 | Reward: 0.4375
[Step 860] CE/token (EMA): 2.327 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 2.297 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 2.103 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 2.070 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 900] reward=0.3203 adv=+0.0278 gamma=2.30e-06
[Step 900] CE/token (EMA): 2.072 | Contrast[mask]: 0.000 | RL: -0.599 | Reward: 0.3203
[Step 910] CE/token (EMA): 2.193 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 2.113 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 2.101 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 2.023 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'devastatedensive devastatedensive devastated devastated'
[RL step 950] reward=0.3047 adv=+0.0094 gamma=2.30e-06
[Step 950] CE/token (EMA): 2.027 | Contrast[mask]: 0.000 | RL: -0.202 | Reward: 0.3047
[Step 960] CE/token (EMA): 2.020 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 2.097 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 2.109 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 2.161 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proudensive of impressed. sentimental'
[RL step 1000] reward=0.4141 adv=+0.1178 gamma=2.30e-06
[Step 1000] CE/token (EMA): 2.033 | Contrast[mask]: 0.000 | RL: -2.541 | Reward: 0.4141
[Step 1010] CE/token (EMA): 2.065 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 2.026 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 2.094 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 2.451 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disgusted'
[RL sample] GEN: 'sad sad sad sad sad sad'
[RL step 1050] reward=0.3828 adv=+0.0748 gamma=2.30e-06
[Step 1050] CE/token (EMA): 2.665 | Contrast[mask]: 0.000 | RL: -1.613 | Reward: 0.3828
[Step 1060] CE/token (EMA): 2.645 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 2.461 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 2.508 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 2.451 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'nostalgic'
[RL sample] GEN: 'sentimentalensive. caring sentimentalensive'
[RL step 1100] reward=0.3125 adv=-0.0030 gamma=2.30e-06
[Step 1100] CE/token (EMA): 2.236 | Contrast[mask]: 0.000 | RL: 0.065 | Reward: 0.3125
[Step 1110] CE/token (EMA): 2.199 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 2.260 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 2.178 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 2.073 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sentimental'
[RL sample] GEN: 'nostalgicensive sentimentalensive sentimentalensive'
[RL step 1150] reward=0.3984 adv=+0.0832 gamma=2.30e-06
[Step 1150] CE/token (EMA): 1.960 | Contrast[mask]: 0.000 | RL: -1.794 | Reward: 0.3984
[Step 1160] CE/token (EMA): 1.944 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.861 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.897 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 2.000 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'confident'
[RL sample] GEN: 'surprised surprised surprised surprised surprised surprised'
[RL step 1200] reward=0.3984 adv=+0.0749 gamma=2.30e-06
[Step 1200] CE/token (EMA): 1.999 | Contrast[mask]: 0.000 | RL: -1.616 | Reward: 0.3984
[Step 1210] CE/token (EMA): 1.922 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.945 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.969 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 2.024 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'disgustedensive guilty guilty guilty guilty'
[RL step 1250] reward=0.5156 adv=+0.1846 gamma=2.30e-06
[Step 1250] CE/token (EMA): 1.945 | Contrast[mask]: 0.000 | RL: -3.982 | Reward: 0.5156
[Step 1260] CE/token (EMA): 1.975 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.962 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.937 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.975 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'jealous'
[RL sample] GEN: 'surprised impressed impressed surprised surprised surprised'
[RL step 1300] reward=0.3438 adv=-0.0057 gamma=2.30e-06
[Step 1300] CE/token (EMA): 2.045 | Contrast[mask]: 0.000 | RL: 0.124 | Reward: 0.3438
[Step 1310] CE/token (EMA): 2.110 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 2.195 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 2.314 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 2.271 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited content excited. excited excited'
[RL step 1350] reward=0.3516 adv=+0.0027 gamma=2.30e-06
[Step 1350] CE/token (EMA): 2.248 | Contrast[mask]: 0.000 | RL: -0.057 | Reward: 0.3516
[Step 1360] CE/token (EMA): 2.250 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 2.369 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 2.337 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 2.463 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'courageous and proud impressed proud impressed'
[RL step 1400] reward=0.3984 adv=+0.0493 gamma=2.30e-06
[Step 1400] CE/token (EMA): 2.762 | Contrast[mask]: 0.000 | RL: -1.062 | Reward: 0.3984
[Step 1410] CE/token (EMA): 2.570 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 2.282 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 2.046 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.928 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'afraid'
[RL sample] GEN: 'afraidant of afraidant of'
[RL step 1450] reward=0.4297 adv=+0.0756 gamma=2.30e-06
[Step 1450] CE/token (EMA): 1.790 | Contrast[mask]: 0.000 | RL: -1.630 | Reward: 0.4297
[Step 1460] CE/token (EMA): 1.749 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.673 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.782 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.653 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified anticipating anticipating anticipating anticipating anticipating | surprised surprised surprised surprised surprised surprised | excited anticipating anticipating anticipating anticipating anticipating | surprised surprised surprised surprised surprised surprised
[ValMetric epoch 2] accuracy=0.5100 | best=0.5100 @ epoch 2
[RL sample] REF: 'annoyed'
[RL sample] GEN: 'angry angry furious angry furious angry'
[RL step 1500] reward=0.5859 adv=+0.2243 gamma=2.30e-06
[Step 1500] CE/token (EMA): 1.587 | Contrast[mask]: 0.000 | RL: -4.837 | Reward: 0.5859
[Step 1510] CE/token (EMA): 1.619 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.505 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.607 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.491 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'joyful'
[RL sample] GEN: 'joyful joyful joyful joyful joyful joyful'
[RL step 1550] reward=0.4922 adv=+0.1081 gamma=2.30e-06
[Step 1550] CE/token (EMA): 1.466 | Contrast[mask]: 0.000 | RL: -2.331 | Reward: 0.4922
[Step 1560] CE/token (EMA): 1.479 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.460 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.475 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.497 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'impressed impressed impressed impressed impressed impressed'
[RL step 1600] reward=0.4375 adv=+0.0426 gamma=2.30e-06
[Step 1600] CE/token (EMA): 1.562 | Contrast[mask]: 0.000 | RL: -0.919 | Reward: 0.4375
[Step 1610] CE/token (EMA): 1.489 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.471 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.383 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.433 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'caring'
[RL sample] GEN: 'grateful grateful grateful grateful grateful grateful'
[RL step 1650] reward=0.4844 adv=+0.0852 gamma=2.30e-06
[Step 1650] CE/token (EMA): 1.423 | Contrast[mask]: 0.000 | RL: -1.838 | Reward: 0.4844
[Step 1660] CE/token (EMA): 1.446 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.456 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.501 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.383 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'embarrassed'
[RL sample] GEN: 'embarrassed guilty guilty guilty guilty guilty'
[RL step 1700] reward=0.5625 adv=+0.1548 gamma=2.30e-06
[Step 1700] CE/token (EMA): 1.505 | Contrast[mask]: 0.000 | RL: -3.339 | Reward: 0.5625

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 9353.27it/s]
Map: 100%|██████████| 6000/6000 [00:00<00:00, 10058.78 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 7905.95 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7833.29 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8563.74 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 15B n=6000 (s44)
======================================================================

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 9823.95it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 3,755,264 || all params: 1,547,469,568 || trainable%: 0.2427
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 6.337 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 6.385 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 6.122 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.572 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 4.928 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 4.300 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.908 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.485 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 3.215 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.924 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 2.683 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.551 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.308 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.139 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.052 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.321 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.276 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.189 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.287 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.578 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.583 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.360 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.249 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.447 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.224 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 1.965 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 1.882 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.857 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.936 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.764 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.688 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.868 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.827 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.933 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.809 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.761 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.768 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.827 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.713 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.740 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.722 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.785 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.791 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.666 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.742 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.784 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.720 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.656 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.645 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.630 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.532 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.600 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.695 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.722 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.777 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.754 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.600 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.538 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.556 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.642 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.621 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.722 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.814 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.701 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.688 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.745 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.630 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.505 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.499 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.461 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.431 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.501 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.529 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.524 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.460 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5750 | best=0.5750 @ epoch 1
[Step 750] CE/token (EMA): 1.455 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.412 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.354 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.604 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.521 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.463 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.524 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.517 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.543 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.568 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.583 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.496 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.495 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.410 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.531 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.631 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.581 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.585 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.573 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.429 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.510 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.450 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.397 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.432 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.362 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.358 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.398 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.447 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.502 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.520 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.610 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.611 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.523 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.476 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.537 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.579 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.591 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.470 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.515 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.508 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.363 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.282 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.347 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.300 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.366 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.429 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.621 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.514 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.402 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.349 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.394 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.350 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.348 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.339 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.316 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.469 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.457 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.332 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.394 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.339 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.372 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.251 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.272 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.398 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.265 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.300 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.221 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.250 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.245 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.241 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.184 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.281 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.352 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified and terrified of being lonely | terrified and terrified of trusting trusting | excited and excited anticipating the adventure | surprised and surprised surprised surprised surprised
[ValMetric epoch 2] accuracy=0.5350 | best=0.5750 @ epoch 1
[Step 1500] CE/token (EMA): 1.314 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.215 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.308 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.262 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.325 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.400 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.339 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.319 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.281 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.225 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.211 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.245 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.233 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.229 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.165 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.123 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.133 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.202 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.141 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.075 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.176 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.214 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.248 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.222 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.133 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.102 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.070 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.249 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.222 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.206 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.177 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.117 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.022 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 0.994 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.253 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.209 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.158 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.111 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.114 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.072 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.179 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.262 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.262 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.248 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.231 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.194 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.333 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.227 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.182 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.212 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.185 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.177 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.154 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.143 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.035 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 0.966 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 0.907 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 0.931 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 0.998 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.147 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.280 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.256 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.277 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.121 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.045 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.134 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.226 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.196 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.200 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.247 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.174 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.249 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.228 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.125 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.193 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified and terrified with fear terrified | surprised and surprised surprised surprised surprised | excited anticipating traveling abroad with my | disgusted surprised surprised surprised surprised surprised
[ValMetric epoch 3] accuracy=0.5850 | best=0.5850 @ epoch 3

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 9265.48it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 3,755,264 || all params: 1,547,469,568 || trainable%: 0.2427
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 6.337 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 6.388 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 6.117 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.537 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 4.893 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 4.284 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.900 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.473 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 3.170 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.904 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 2.643 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.546 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.322 | Contrast[mask]: 0.615 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.036 | Contrast[mask]: 0.631 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.054 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.265 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.206 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 1.974 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.089 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.097 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 1.969 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 1.887 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 1.958 | Contrast[mask]: 0.669 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 3.036 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 3.032 | Contrast[mask]: 0.658 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 2.435 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 2.163 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.852 | Contrast[mask]: 0.666 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.950 | Contrast[mask]: 0.667 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.783 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.629 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.701 | Contrast[mask]: 0.669 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.738 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.869 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.778 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.681 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.670 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.662 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.577 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.661 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.754 | Contrast[mask]: 0.667 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.859 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.825 | Contrast[mask]: 0.669 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.758 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.851 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.807 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.732 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.657 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.652 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.636 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.581 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.569 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.638 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.689 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.729 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.680 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.509 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.458 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.436 | Contrast[mask]: 0.660 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.686 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.664 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.678 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.820 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.731 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.769 | Contrast[mask]: 0.654 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.797 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.632 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.527 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.488 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.481 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.567 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.535 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.484 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.482 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.487 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5200 | best=0.5200 @ epoch 1
[Step 750] CE/token (EMA): 1.513 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.560 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.598 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.669 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.587 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.569 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.494 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.515 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.523 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.562 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.577 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.535 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.563 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.423 | Contrast[mask]: 0.667 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.544 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.514 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.498 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.588 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.605 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.493 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.574 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.540 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.512 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.500 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.493 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.455 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.482 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.539 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.534 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.444 | Contrast[mask]: 0.666 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.507 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.596 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.527 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.467 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.509 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.532 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.556 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.462 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.509 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.578 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.426 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.340 | Contrast[mask]: 0.663 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.300 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.277 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.312 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.357 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.563 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.469 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.418 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.423 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.422 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.399 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.351 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.307 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.313 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.467 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.452 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.360 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.415 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.429 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.348 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.323 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.222 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.220 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.247 | Contrast[mask]: 0.655 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.360 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.262 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.241 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.183 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.260 | Contrast[mask]: 0.664 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.282 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.285 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.247 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.302 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.328 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified terrified terrified terrified terrified terrified | terrified terrified terrified terrified terrified terrified | excited excited excited anticipating excited anticipating | terrified terrified terrified terrified terrified terrified
[ValMetric epoch 2] accuracy=0.5600 | best=0.5600 @ epoch 2
[Step 1500] CE/token (EMA): 1.371 | Contrast[mask]: 0.669 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.280 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.346 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.289 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.417 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.496 | Contrast[mask]: 0.664 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.405 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.360 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.322 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.262 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.240 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.266 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.227 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.230 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.204 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.131 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.134 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.206 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.167 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.140 | Contrast[mask]: 0.663 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.247 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.331 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.329 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.246 | Contrast[mask]: 0.664 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.221 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.170 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.148 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.407 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.324 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.261 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.215 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.174 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.079 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.024 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.298 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.269 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.160 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.155 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.168 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.093 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.183 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.251 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.294 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.210 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.229 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.163 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.308 | Contrast[mask]: 0.653 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.265 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.246 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.261 | Contrast[mask]: 0.656 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.249 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.247 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.193 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.165 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.074 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.046 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 0.979 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 0.972 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.052 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.146 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.256 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.268 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.268 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.152 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.085 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.131 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.206 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.198 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.172 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.252 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.208 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.244 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.143 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.066 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.124 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000

Loading weights: 100%|██████████| 338/338 [00:00<00:00, 9879.61it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 3,755,264 || all params: 1,547,469,568 || trainable%: 0.2427
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 2.166e-06
[RL sample] REF: 'prepared'
[RL sample] GEN: 'Excitement\nText:'
[RL step 0] reward=0.0938 adv=+0.0938 gamma=2.17e-06
[Step 0] CE/token (EMA): 6.337 | Contrast[mask]: 0.000 | RL: -1.901 | Reward: 0.0938

[Step 10] CE/token (EMA): 6.384 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 6.123 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.565 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 4.921 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'happy\nYou are a helpful'
[RL step 50] reward=0.2891 adv=+0.2797 gamma=2.17e-06
[Step 50] CE/token (EMA): 4.305 | Contrast[mask]: 0.000 | RL: -5.671 | Reward: 0.2891
[Step 60] CE/token (EMA): 3.907 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.495 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 3.225 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.940 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed\nYou are a lif'
[RL step 100] reward=0.5000 adv=+0.4627 gamma=2.17e-06
[Step 100] CE/token (EMA): 2.683 | Contrast[mask]: 0.000 | RL: -9.381 | Reward: 0.5000
[Step 110] CE/token (EMA): 2.569 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.305 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.101 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.045 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'sad\nQuestion: How did'
[RL step 150] reward=0.5391 adv=+0.4555 gamma=2.17e-06
[Step 150] CE/token (EMA): 2.182 | Contrast[mask]: 0.000 | RL: -9.234 | Reward: 0.5391
[Step 160] CE/token (EMA): 2.196 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.107 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.140 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.098 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'disgusted\nPredictor: lonely'
[RL step 200] reward=0.3672 adv=+0.2380 gamma=2.17e-06
[Step 200] CE/token (EMA): 1.988 | Contrast[mask]: 0.000 | RL: -4.826 | Reward: 0.3672
[Step 210] CE/token (EMA): 1.941 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 1.998 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.115 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.040 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'annoyed\nEmotion: annoyed'
[RL step 250] reward=0.3984 adv=+0.2455 gamma=2.17e-06
[Step 250] CE/token (EMA): 1.960 | Contrast[mask]: 0.000 | RL: -4.977 | Reward: 0.3984
[Step 260] CE/token (EMA): 1.895 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.770 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.836 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.652 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'terrified\nsurprised'
[RL step 300] reward=0.5078 adv=+0.3303 gamma=2.17e-06
[Step 300] CE/token (EMA): 1.584 | Contrast[mask]: 0.000 | RL: -6.698 | Reward: 0.5078
[Step 310] CE/token (EMA): 1.762 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.732 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.840 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.792 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'surprised'
[RL sample] GEN: 'surprised\nsurprised'
[RL step 350] reward=0.5938 adv=+0.3832 gamma=2.17e-06
[Step 350] CE/token (EMA): 1.709 | Contrast[mask]: 0.000 | RL: -7.770 | Reward: 0.5938
[Step 360] CE/token (EMA): 1.657 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.646 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.608 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.647 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'hopeful'
[RL sample] GEN: 'anticipating the anticipation of returning to'
[RL step 400] reward=0.4453 adv=+0.1965 gamma=2.17e-06
[Step 400] CE/token (EMA): 1.634 | Contrast[mask]: 0.000 | RL: -3.983 | Reward: 0.4453
[Step 410] CE/token (EMA): 1.696 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.686 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.572 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.708 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'prepared'
[RL sample] GEN: 'prepared\nsurive\n prepared'
[RL step 450] reward=0.4688 adv=+0.2002 gamma=2.17e-06
[Step 450] CE/token (EMA): 1.714 | Contrast[mask]: 0.000 | RL: -4.061 | Reward: 0.4688
[Step 460] CE/token (EMA): 1.690 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.653 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.608 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.657 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited\ncontentensive\n confident'
[RL step 500] reward=0.4141 adv=+0.1255 gamma=2.17e-06
[Step 500] CE/token (EMA): 1.577 | Contrast[mask]: 0.000 | RL: -2.546 | Reward: 0.4141
[Step 510] CE/token (EMA): 1.571 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.637 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.661 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.697 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anticipating'
[RL sample] GEN: 'anticipating anticipating anticipating anticipating anticipating anticipating'
[RL step 550] reward=0.5391 adv=+0.2380 gamma=2.17e-06
[Step 550] CE/token (EMA): 1.701 | Contrast[mask]: 0.000 | RL: -4.826 | Reward: 0.5391
[Step 560] CE/token (EMA): 1.510 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.504 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.434 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.546 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'lonely'
[RL sample] GEN: 'lonely\nsurjoying'
[RL step 600] reward=0.6562 adv=+0.3314 gamma=2.17e-06
[Step 600] CE/token (EMA): 1.551 | Contrast[mask]: 0.000 | RL: -6.718 | Reward: 0.6562
[Step 610] CE/token (EMA): 1.630 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.790 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.691 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.702 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anxious\nDesensive\nprepared'
[RL step 650] reward=0.4453 adv=+0.0873 gamma=2.17e-06
[Step 650] CE/token (EMA): 1.738 | Contrast[mask]: 0.000 | RL: -1.770 | Reward: 0.4453
[Step 660] CE/token (EMA): 1.599 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.489 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.487 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.468 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anticipating anticipating anticipating anticipating anticipating anticipating'
[RL step 700] reward=0.5000 adv=+0.1333 gamma=2.17e-06
[Step 700] CE/token (EMA): 1.438 | Contrast[mask]: 0.000 | RL: -2.703 | Reward: 0.5000
[Step 710] CE/token (EMA): 1.459 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.491 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.539 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.484 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5700 | best=0.5700 @ epoch 1
[RL sample] REF: 'jealous'
[RL sample] GEN: 'jealous and jealous\nangr'
[RL step 750] reward=0.4844 adv=+0.1043 gamma=2.17e-06
[Step 750] CE/token (EMA): 1.463 | Contrast[mask]: 0.000 | RL: -2.114 | Reward: 0.4844
[Step 760] CE/token (EMA): 1.405 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.459 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.589 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.466 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'disappointed disappointeded\ndisappointed'
[RL step 800] reward=0.5703 adv=+0.1798 gamma=2.17e-06
[Step 800] CE/token (EMA): 1.403 | Contrast[mask]: 0.000 | RL: -3.646 | Reward: 0.5703
[Step 810] CE/token (EMA): 1.370 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.401 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.468 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.522 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty\nconflictedusing'
[RL step 850] reward=0.5391 adv=+0.1306 gamma=2.17e-06
[Step 850] CE/token (EMA): 1.522 | Contrast[mask]: 0.000 | RL: -2.648 | Reward: 0.5391
[Step 860] CE/token (EMA): 1.435 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.463 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.361 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.485 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'ashamed and ashamed ashamed angry angry'
[RL step 900] reward=0.5000 adv=+0.0785 gamma=2.17e-06
[Step 900] CE/token (EMA): 1.425 | Contrast[mask]: 0.000 | RL: -1.591 | Reward: 0.5000
[Step 910] CE/token (EMA): 1.423 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.476 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.500 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.346 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'devastatedanged and devastatedavaged'
[RL step 950] reward=0.4297 adv=+0.0003 gamma=2.17e-06
[Step 950] CE/token (EMA): 1.468 | Contrast[mask]: 0.000 | RL: -0.006 | Reward: 0.4297
[Step 960] CE/token (EMA): 1.412 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.361 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.394 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.384 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud proud proud proud proud proud'
[RL step 1000] reward=0.5312 adv=+0.1018 gamma=2.17e-06
[Step 1000] CE/token (EMA): 1.405 | Contrast[mask]: 0.000 | RL: -2.065 | Reward: 0.5312
[Step 1010] CE/token (EMA): 1.466 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.514 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.506 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.452 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disgusted'
[RL sample] GEN: 'disgustedved\nsurprised'
[RL step 1050] reward=0.6797 adv=+0.2401 gamma=2.17e-06
[Step 1050] CE/token (EMA): 1.586 | Contrast[mask]: 0.000 | RL: -4.867 | Reward: 0.6797
[Step 1060] CE/token (EMA): 1.624 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.497 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.486 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.568 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'nostalgic'
[RL sample] GEN: 'nostalgicious lonely lonely lonely lonely'
[RL step 1100] reward=0.4844 adv=+0.0208 gamma=2.17e-06
[Step 1100] CE/token (EMA): 1.563 | Contrast[mask]: 0.000 | RL: -0.421 | Reward: 0.4844
[Step 1110] CE/token (EMA): 1.567 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.453 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.512 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.505 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sentimental'
[RL sample] GEN: 'nostalgic nostalgicies nostalgicensive nostalgic'
[RL step 1150] reward=0.4922 adv=+0.0265 gamma=2.17e-06
[Step 1150] CE/token (EMA): 1.405 | Contrast[mask]: 0.000 | RL: -0.537 | Reward: 0.4922
[Step 1160] CE/token (EMA): 1.300 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.289 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.284 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.392 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'confident'
[RL sample] GEN: 'apprehensive anticipating anticipating anticipating anticipating'
[RL step 1200] reward=0.5156 adv=+0.0473 gamma=2.17e-06
[Step 1200] CE/token (EMA): 1.419 | Contrast[mask]: 0.000 | RL: -0.959 | Reward: 0.5156
[Step 1210] CE/token (EMA): 1.653 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.496 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.415 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.309 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 1250] reward=0.5703 adv=+0.0972 gamma=2.17e-06
[Step 1250] CE/token (EMA): 1.358 | Contrast[mask]: 0.000 | RL: -1.972 | Reward: 0.5703
[Step 1260] CE/token (EMA): 1.369 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.328 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.247 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.263 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'jealous'
[RL sample] GEN: 'confident and confident with confident with'
[RL step 1300] reward=0.5781 adv=+0.0953 gamma=2.17e-06
[Step 1300] CE/token (EMA): 1.472 | Contrast[mask]: 0.000 | RL: -1.933 | Reward: 0.5781
[Step 1310] CE/token (EMA): 1.464 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.382 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.425 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.414 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited anticipating the trip to college'
[RL step 1350] reward=0.4766 adv=-0.0158 gamma=2.17e-06
[Step 1350] CE/token (EMA): 1.320 | Contrast[mask]: 0.000 | RL: 0.319 | Reward: 0.4766
[Step 1360] CE/token (EMA): 1.358 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.211 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.241 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.246 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proudaced proud caring caring caring'
[RL step 1400] reward=0.4688 adv=-0.0220 gamma=2.17e-06
[Step 1400] CE/token (EMA): 1.375 | Contrast[mask]: 0.000 | RL: 0.446 | Reward: 0.4688
[Step 1410] CE/token (EMA): 1.256 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.284 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.219 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'afraid'
[RL sample] GEN: 'afraideful of death terrified of'
[RL step 1450] reward=0.5234 adv=+0.0349 gamma=2.17e-06
[Step 1450] CE/token (EMA): 1.247 | Contrast[mask]: 0.000 | RL: -0.707 | Reward: 0.5234
[Step 1460] CE/token (EMA): 1.182 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.206 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.298 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.316 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified terrified terrified terrified terrified terrified | terrified terrified terrified terrified terrified terrified | excited anticipating excited anticipating excited anticipating | terrified terrified terrified terrified terrified terrified
[ValMetric epoch 2] accuracy=0.5950 | best=0.5950 @ epoch 2
[RL sample] REF: 'annoyed'
[RL sample] GEN: 'grateful grateful grateful grateful grateful grateful'
[RL step 1500] reward=0.6484 adv=+0.1564 gamma=2.17e-06
[Step 1500] CE/token (EMA): 1.319 | Contrast[mask]: 0.000 | RL: -3.171 | Reward: 0.6484
[Step 1510] CE/token (EMA): 1.244 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.300 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.222 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.341 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'joyful'
[RL sample] GEN: 'joyful joyful joyful joyful joyful joyful'
[RL step 1550] reward=0.6484 adv=+0.1408 gamma=2.17e-06
[Step 1550] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: -2.854 | Reward: 0.6484
[Step 1560] CE/token (EMA): 1.319 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.295 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.254 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.221 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'proudound impressed surprised surprised surprised'
[RL step 1600] reward=0.4844 adv=-0.0374 gamma=2.17e-06
[Step 1600] CE/token (EMA): 1.227 | Contrast[mask]: 0.000 | RL: 0.758 | Reward: 0.4844
[Step 1610] CE/token (EMA): 1.264 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.229 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.227 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.190 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'caring'
[RL sample] GEN: 'grateful grateful grateful grateful grateful grateful'
[RL step 1650] reward=0.5234 adv=+0.0054 gamma=2.17e-06
[Step 1650] CE/token (EMA): 1.187 | Contrast[mask]: 0.000 | RL: -0.110 | Reward: 0.5234
[Step 1660] CE/token (EMA): 1.179 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.194 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.138 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.137 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'embarrassed'
[RL sample] GEN: 'embarrassed guilty guilty guilty guilty guilty'
[RL step 1700] reward=0.4922 adv=-0.0264 gamma=2.17e-06
[Step 1700] CE/token (EMA): 1.201 | Contrast[mask]: 0.000 | RL: 0.535 | Reward: 0.4922
[Step 1710] CE/token (EMA): 1.205 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 9381.88it/s]
Map: 100%|██████████| 6000/6000 [00:00<00:00, 10137.26 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 8075.21 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7855.33 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8124.85 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 3B n=6000 (s42)
======================================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 9631.77it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 4,807,936 || all params: 3,090,746,624 || trainable%: 0.1556
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 5.220 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 5.279 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 5.003 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 4.676 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 4.041 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.656 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.361 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.330 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 3.053 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.831 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 2.802 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.740 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.584 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.398 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.152 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 1.891 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 1.782 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 1.717 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 1.571 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 1.634 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 1.712 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 1.681 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 1.648 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 1.903 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 1.756 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 1.549 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 1.609 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.565 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.502 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.641 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.593 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.570 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.401 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.271 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.337 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.333 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.389 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.476 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.535 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.576 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.428 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.548 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.521 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.396 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.319 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.443 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.393 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.328 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.408 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.417 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.508 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.447 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.385 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.312 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.240 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.205 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.238 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.390 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.475 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.426 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.383 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.428 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.362 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.341 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.260 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.417 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.385 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.282 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.268 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.225 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.289 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.293 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.345 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.264 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.6000 | best=0.6000 @ epoch 1
[Step 750] CE/token (EMA): 1.242 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.313 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.178 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.216 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.180 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.201 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.222 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.307 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.304 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.281 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.255 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.209 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.198 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.125 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.227 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.146 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.286 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.259 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.306 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.220 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.312 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.433 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.368 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.289 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.356 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.438 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.240 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.243 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.281 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.205 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.246 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.294 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.210 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.217 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.335 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.333 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.355 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.348 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.234 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.174 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.279 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.385 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.326 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.251 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.354 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.323 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.277 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.261 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.246 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.218 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.299 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.334 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.210 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.136 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.139 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.150 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.101 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.028 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.085 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.124 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.180 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.223 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.238 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.162 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.381 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.238 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.254 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.211 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.085 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.061 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.168 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.158 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.158 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.151 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.138 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified and terrified terrified terrified terrified | surprised and afraid

susp | excited

s content joyful joyful | disgusted and disgusted and disgusted with
[ValMetric epoch 2] accuracy=0.6250 | best=0.6250 @ epoch 2
[Step 1500] CE/token (EMA): 1.141 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.087 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.052 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.130 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.138 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.081 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.092 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.094 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.139 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.065 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.066 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.087 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.067 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 0.999 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.063 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.152 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.127 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.086 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.178 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.141 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.026 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.131 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.149 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.155 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.093 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.062 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.025 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.015 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.619 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 2.315 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 3.296 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 3.696 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 2.963 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 2.287 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.785 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.522 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.310 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.256 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.122 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.185 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.149 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.200 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.200 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.161 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.210 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.195 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.148 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.102 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.225 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.201 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.044 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.047 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.102 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.095 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.156 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.133 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 0.985 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 0.971 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 0.950 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.004 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 0.972 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.134 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.212 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.152 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.143 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.099 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.063 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.013 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.009 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 0.996 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 0.961 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 0.994 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.045 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.024 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 0.989 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified terrified terrified terrified terrified terrified | surprised and surprised at surprised | excited anticipating excited anticipating anticipating anticipating | disgusted and disgusted by surprised and
[ValMetric epoch 3] accuracy=0.6400 | best=0.6400 @ epoch 3

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 9570.15it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 4,807,936 || all params: 3,090,746,624 || trainable%: 0.1556
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 5.220 | Contrast[mask]: 0.693 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 5.279 | Contrast[mask]: 0.693 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 5.000 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 4.675 | Contrast[mask]: 0.692 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 4.044 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.660 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.363 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.323 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 3.046 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.818 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 2.797 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.732 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.558 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.404 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.167 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 1.871 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 1.789 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 1.743 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 1.612 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 1.665 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 1.758 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 1.686 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 1.637 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 1.926 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 1.791 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 1.575 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 1.603 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.550 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.522 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.613 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.532 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.546 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.468 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 4.761 | Contrast[mask]: 0.567 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 6.336 | Contrast[mask]: 0.656 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 6.383 | Contrast[mask]: 0.653 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 5.574 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 4.279 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 3.226 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 2.598 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 2.086 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.915 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.776 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.692 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.523 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.603 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.472 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.391 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.613 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.562 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.609 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.499 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.421 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.365 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 2.003 | Contrast[mask]: 0.658 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.925 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.931 | Contrast[mask]: 0.660 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.918 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.820 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.847 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.738 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.600 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.512 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.456 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.397 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.508 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.485 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.430 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.296 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.284 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.262 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.310 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.322 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.371 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.302 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5850 | best=0.5850 @ epoch 1
[Step 750] CE/token (EMA): 1.305 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.386 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.264 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.292 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.217 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.280 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.313 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.383 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.348 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.336 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.280 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.242 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.254 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.176 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.282 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.175 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.300 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.294 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.316 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.211 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.228 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.308 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.293 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.272 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.336 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.450 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.279 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.301 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.349 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.243 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.291 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.328 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.229 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.254 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.381 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.369 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.364 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.391 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.283 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.189 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.258 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.388 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.314 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.245 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.355 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.324 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.282 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.270 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.207 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.207 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.308 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.385 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.247 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.160 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.164 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.174 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.161 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.318 | Contrast[mask]: 0.664 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.495 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.357 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.308 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.308 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.296 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.200 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.384 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.247 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.282 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.258 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.114 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.106 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.193 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.198 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.219 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.199 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.191 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified afraid terrified terrified terrified terrified | surprised surprised surprised surprised surprised surprised | excited anticipating anticipating anticipating anticipating anticipating | disgusted surprised disgusted disgusted surprised disgusted
[ValMetric epoch 2] accuracy=0.5900 | best=0.5900 @ epoch 2
[Step 1500] CE/token (EMA): 1.154 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.095 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.072 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.140 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.141 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.083 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.094 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.116 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.152 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.135 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.087 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.141 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.096 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 0.997 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.047 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.187 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.162 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.101 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.176 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.150 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.024 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.119 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.135 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.162 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.084 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.058 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.025 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.020 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.113 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.073 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 0.968 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.089 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.054 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.144 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.144 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.079 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.086 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.097 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.053 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.162 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.157 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.207 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.183 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.162 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.207 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.212 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.212 | Contrast[mask]: 0.692 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.147 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.223 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.175 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.016 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.044 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.077 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.086 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.154 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.140 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.010 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 0.980 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 0.986 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.027 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.002 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.175 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.238 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.149 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.150 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.119 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.091 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.044 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.010 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.027 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 0.998 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.019 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.033 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 0.975 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 0.970 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 9985.40it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 4,807,936 || all params: 3,090,746,624 || trainable%: 0.1556
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 7.964e-07
[RL sample] REF: 'prepared'
[RL sample] GEN: 'anxious\nAction: feeling nervous'
[RL step 0] reward=0.1641 adv=+0.1641 gamma=7.96e-07
[Step 0] CE/token (EMA): 5.220 | Contrast[mask]: 0.000 | RL: -1.566 | Reward: 0.1641

[Step 10] CE/token (EMA): 5.278 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 5.002 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 4.674 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 4.041 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'happy\nNot applicable\n\nIn'
[RL step 50] reward=0.3438 adv=+0.3273 gamma=7.96e-07
[Step 50] CE/token (EMA): 3.655 | Contrast[mask]: 0.000 | RL: -3.125 | Reward: 0.3438
[Step 60] CE/token (EMA): 3.363 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.326 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 3.048 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.836 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed\nDefinition: feeling sad'
[RL step 100] reward=0.4688 adv=+0.4196 gamma=7.96e-07
[Step 100] CE/token (EMA): 2.832 | Contrast[mask]: 0.000 | RL: -4.006 | Reward: 0.4688
[Step 110] CE/token (EMA): 2.752 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.579 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.415 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.167 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'sad\nYou are describing a'
[RL step 150] reward=0.5234 adv=+0.4323 gamma=7.96e-07
[Step 150] CE/token (EMA): 1.880 | Contrast[mask]: 0.000 | RL: -4.128 | Reward: 0.5234
[Step 160] CE/token (EMA): 1.794 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 1.735 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 1.600 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 1.668 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'annoyed\n\nExplanation: I was'
[RL step 200] reward=0.4844 adv=+0.3500 gamma=7.96e-07
[Step 200] CE/token (EMA): 1.763 | Contrast[mask]: 0.000 | RL: -3.342 | Reward: 0.4844
[Step 210] CE/token (EMA): 1.753 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 1.691 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 1.948 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 1.808 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'excited\nExplanation: I was'
[RL step 250] reward=0.4375 adv=+0.2682 gamma=7.96e-07
[Step 250] CE/token (EMA): 1.564 | Contrast[mask]: 0.000 | RL: -2.560 | Reward: 0.4375
[Step 260] CE/token (EMA): 1.572 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.543 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.509 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.676 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'terrified\n\nIn that situation,'
[RL step 300] reward=0.5703 adv=+0.3742 gamma=7.96e-07
[Step 300] CE/token (EMA): 1.573 | Contrast[mask]: 0.000 | RL: -3.572 | Reward: 0.5703
[Step 310] CE/token (EMA): 1.621 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.414 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.276 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.421 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'surprised'
[RL sample] GEN: 'surprised\nPredictably, I'
[RL step 350] reward=0.6641 adv=+0.4305 gamma=7.96e-07
[Step 350] CE/token (EMA): 1.383 | Contrast[mask]: 0.000 | RL: -4.110 | Reward: 0.6641
[Step 360] CE/token (EMA): 1.440 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.522 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.571 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.628 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'hopeful'
[RL sample] GEN: "prepared\n\nI'm prepared for"
[RL step 400] reward=0.5078 adv=+0.2312 gamma=7.96e-07
[Step 400] CE/token (EMA): 1.805 | Contrast[mask]: 0.000 | RL: -2.207 | Reward: 0.5078
[Step 410] CE/token (EMA): 1.715 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.639 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.475 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.367 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'prepared'
[RL sample] GEN: 'prepared\n\nAssistant: faithful'
[RL step 450] reward=0.5234 adv=+0.2237 gamma=7.96e-07
[Step 450] CE/token (EMA): 1.465 | Contrast[mask]: 0.000 | RL: -2.135 | Reward: 0.5234
[Step 460] CE/token (EMA): 1.395 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.337 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.412 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.436 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'prepared\nprepared'
[RL step 500] reward=0.4844 adv=+0.1623 gamma=7.96e-07
[Step 500] CE/token (EMA): 1.506 | Contrast[mask]: 0.000 | RL: -1.549 | Reward: 0.4844
[Step 510] CE/token (EMA): 1.444 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.393 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.344 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.272 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anticipating'
[RL sample] GEN: 'excited'
[RL step 550] reward=0.6328 adv=+0.2945 gamma=7.96e-07
[Step 550] CE/token (EMA): 1.217 | Contrast[mask]: 0.000 | RL: -2.811 | Reward: 0.6328
[Step 560] CE/token (EMA): 1.253 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.375 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.485 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.467 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'lonely'
[RL sample] GEN: 'lonely\n\n\n\n\nn'
[RL step 600] reward=0.6406 adv=+0.2728 gamma=7.96e-07
[Step 600] CE/token (EMA): 1.425 | Contrast[mask]: 0.000 | RL: -2.604 | Reward: 0.6406
[Step 610] CE/token (EMA): 1.461 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.850 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.660 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.452 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anxious\n\n\n\nn anxious'
[RL step 650] reward=0.5000 adv=+0.1049 gamma=7.96e-07
[Step 650] CE/token (EMA): 1.530 | Contrast[mask]: 0.000 | RL: -1.002 | Reward: 0.5000
[Step 660] CE/token (EMA): 1.528 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.459 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.318 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.285 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anticipating\n\n anticipating'
[RL step 700] reward=0.5234 adv=+0.1179 gamma=7.96e-07
[Step 700] CE/token (EMA): 1.456 | Contrast[mask]: 0.000 | RL: -1.125 | Reward: 0.5234
[Step 710] CE/token (EMA): 1.435 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.393 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.384 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.313 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.6000 | best=0.6000 @ epoch 1
[RL sample] REF: 'jealous'
[RL sample] GEN: 'jealous\n\nJust because she has'
[RL step 750] reward=0.5859 adv=+0.1686 gamma=7.96e-07
[Step 750] CE/token (EMA): 1.235 | Contrast[mask]: 0.000 | RL: -1.609 | Reward: 0.5859
[Step 760] CE/token (EMA): 1.380 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.704 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.556 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.399 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'disappointed\nprepared for a day'
[RL step 800] reward=0.6953 adv=+0.2611 gamma=7.96e-07
[Step 800] CE/token (EMA): 1.343 | Contrast[mask]: 0.000 | RL: -2.493 | Reward: 0.6953
[Step 810] CE/token (EMA): 1.337 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.433 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.385 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.357 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty\n\nAccording to the sentiment'
[RL step 850] reward=0.6406 adv=+0.1803 gamma=7.96e-07
[Step 850] CE/token (EMA): 1.287 | Contrast[mask]: 0.000 | RL: -1.721 | Reward: 0.6406
[Step 860] CE/token (EMA): 1.247 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.232 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.153 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.243 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'furious\nchained\n\nAssistant'
[RL step 900] reward=0.5312 adv=+0.0529 gamma=7.96e-07
[Step 900] CE/token (EMA): 1.159 | Contrast[mask]: 0.000 | RL: -0.505 | Reward: 0.5312
[Step 910] CE/token (EMA): 1.293 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.278 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.332 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.217 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'sad\n\nAccording to the sentiment'
[RL step 950] reward=0.5000 adv=+0.0164 gamma=7.96e-07
[Step 950] CE/token (EMA): 1.205 | Contrast[mask]: 0.000 | RL: -0.156 | Reward: 0.5000
[Step 960] CE/token (EMA): 1.538 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.444 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.361 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.372 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud\n\nAccording to the sentiment'
[RL step 1000] reward=0.6094 adv=+0.1241 gamma=7.96e-07
[Step 1000] CE/token (EMA): 1.464 | Contrast[mask]: 0.000 | RL: -1.185 | Reward: 0.6094
[Step 1010] CE/token (EMA): 1.273 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.286 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.355 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.279 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disgusted'
[RL sample] GEN: 'disgusted\n\nAccording not surprised,'
[RL step 1050] reward=0.6562 adv=+0.1586 gamma=7.96e-07
[Step 1050] CE/token (EMA): 1.296 | Contrast[mask]: 0.000 | RL: -1.514 | Reward: 0.6562
[Step 1060] CE/token (EMA): 1.341 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.231 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.226 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.367 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'nostalgic'
[RL sample] GEN: 'nostalgic\n anticipating\n nostalgic'
[RL step 1100] reward=0.5703 adv=+0.0568 gamma=7.96e-07
[Step 1100] CE/token (EMA): 1.339 | Contrast[mask]: 0.000 | RL: -0.542 | Reward: 0.5703
[Step 1110] CE/token (EMA): 1.359 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.362 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.175 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sentimental'
[RL sample] GEN: 'sentimental\n\nChained, afraid'
[RL step 1150] reward=0.5781 adv=+0.0589 gamma=7.96e-07
[Step 1150] CE/token (EMA): 1.244 | Contrast[mask]: 0.000 | RL: -0.562 | Reward: 0.5781
[Step 1160] CE/token (EMA): 1.361 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.318 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.255 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.351 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'confident'
[RL sample] GEN: 'prepared\n\nChained, prepared'
[RL step 1200] reward=0.5625 adv=+0.0374 gamma=7.96e-07
[Step 1200] CE/token (EMA): 1.342 | Contrast[mask]: 0.000 | RL: -0.357 | Reward: 0.5625
[Step 1210] CE/token (EMA): 1.271 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.255 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.230 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.206 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty\nChained, guilty'
[RL step 1250] reward=0.6953 adv=+0.1665 gamma=7.96e-07
[Step 1250] CE/token (EMA): 1.313 | Contrast[mask]: 0.000 | RL: -1.589 | Reward: 0.6953
[Step 1260] CE/token (EMA): 1.335 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.222 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.148 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.136 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'jealous'
[RL sample] GEN: 'jealous\nCrazy, right'
[RL step 1300] reward=0.6641 adv=+0.1186 gamma=7.96e-07
[Step 1300] CE/token (EMA): 1.167 | Contrast[mask]: 0.000 | RL: -1.132 | Reward: 0.6641
[Step 1310] CE/token (EMA): 1.117 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.059 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.095 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.128 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited\n anticipating\n anticipating'
[RL step 1350] reward=0.5000 adv=-0.0574 gamma=7.96e-07
[Step 1350] CE/token (EMA): 1.159 | Contrast[mask]: 0.000 | RL: 0.547 | Reward: 0.5000
[Step 1360] CE/token (EMA): 1.211 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.217 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.160 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.358 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud\nJustified, because'
[RL step 1400] reward=0.5781 adv=+0.0265 gamma=7.96e-07
[Step 1400] CE/token (EMA): 1.228 | Contrast[mask]: 0.000 | RL: -0.253 | Reward: 0.5781
[Step 1410] CE/token (EMA): 1.244 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.218 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.088 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.070 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'afraid'
[RL sample] GEN: 'terrified\n\nAccording to the sentiment'
[RL step 1450] reward=0.5547 adv=+0.0004 gamma=7.96e-07
[Step 1450] CE/token (EMA): 1.172 | Contrast[mask]: 0.000 | RL: -0.004 | Reward: 0.5547
[Step 1460] CE/token (EMA): 1.166 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.193 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.173 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.141 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified

 anticipating

 anticipating | surprised and afraid.

Assistant: | excited

According to the sentiment | disgusted and disgusted with herself for
[ValMetric epoch 2] accuracy=0.6150 | best=0.6150 @ epoch 2
[RL sample] REF: 'annoyed'
[RL sample] GEN: 'annoyed\n\nAccording to the sentiment'
[RL step 1500] reward=0.6797 adv=+0.1254 gamma=7.96e-07
[Step 1500] CE/token (EMA): 1.140 | Contrast[mask]: 0.000 | RL: -1.197 | Reward: 0.6797
[Step 1510] CE/token (EMA): 1.057 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.074 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.132 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.145 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'joyful'
[RL sample] GEN: 'joyful\nContent grateful\nContent'
[RL step 1550] reward=0.7109 adv=+0.1441 gamma=7.96e-07
[Step 1550] CE/token (EMA): 1.077 | Contrast[mask]: 0.000 | RL: -1.376 | Reward: 0.7109
[Step 1560] CE/token (EMA): 1.094 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.122 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.158 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.103 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'impressed\n\nChained, impressed'
[RL step 1600] reward=0.5391 adv=-0.0422 gamma=7.96e-07
[Step 1600] CE/token (EMA): 1.061 | Contrast[mask]: 0.000 | RL: 0.403 | Reward: 0.5391
[Step 1610] CE/token (EMA): 1.114 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.094 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 0.994 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.057 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'caring'
[RL sample] GEN: 'caring\npredicting faithful'
[RL step 1650] reward=0.5078 adv=-0.0692 gamma=7.96e-07
[Step 1650] CE/token (EMA): 1.207 | Contrast[mask]: 0.000 | RL: 0.661 | Reward: 0.5078
[Step 1660] CE/token (EMA): 1.118 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.061 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.169 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.179 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'embarrassed'
[RL sample] GEN: 'embarrassed and ashamed of myself for'
[RL step 1700] reward=0.5547 adv=-0.0154 gamma=7.96e-07
[Step 1700] CE/token (EMA): 1.062 | Contrast[mask]: 0.000 | RL: 0.147 | Reward: 0.5547
[Step 1710] CE/token (EMA): 1.144 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.162 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.156 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.083 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed\n\nAccording disappointed,'
[RL step 1750] reward=0.6562 adv=+0.0877 gamma=7.96e-07

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 9926.75it/s]
Map: 100%|██████████| 6000/6000 [00:00<00:00, 9899.53 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 7980.94 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7789.59 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8344.02 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 3B n=6000 (s43)
======================================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 9567.63it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 4,807,936 || all params: 3,090,746,624 || trainable%: 0.1556
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 5.342 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 5.546 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 5.142 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 4.833 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 4.219 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.682 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.358 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.248 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 3.068 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.880 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 2.749 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.497 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.302 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.106 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.064 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 1.862 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 1.940 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 1.866 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 1.840 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 1.623 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.209 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.105 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 1.977 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 1.764 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 1.735 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 1.863 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 1.599 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.523 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.644 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.527 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.546 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.540 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.482 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.530 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.677 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 3.603 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 2.866 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 2.354 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.918 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.728 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.673 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.705 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.636 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.528 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.625 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.554 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.498 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.542 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.465 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.400 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.477 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.547 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.382 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.276 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.313 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.362 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.285 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.264 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.326 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.343 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.358 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.415 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.370 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.292 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.371 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.434 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.416 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.268 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.225 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.357 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.306 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.349 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.333 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.293 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.6050 | best=0.6050 @ epoch 1
[Step 750] CE/token (EMA): 1.193 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.176 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.172 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.246 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.246 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.249 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.246 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.279 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.274 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.296 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.249 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.280 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.246 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.135 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.187 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.364 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.323 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.243 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.333 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.305 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.171 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.271 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.345 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.338 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.259 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.205 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.164 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.177 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.265 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.243 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.116 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.224 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.210 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.337 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.628 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 3.564 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 3.359 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 3.037 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 2.339 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 2.023 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.813 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.621 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.517 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.399 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.400 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.386 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.343 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.245 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.376 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.344 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.180 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.206 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.259 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.308 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.301 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.293 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.151 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.117 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.099 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.184 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.153 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.336 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.388 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.299 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.300 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.266 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.277 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.189 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.169 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.251 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.205 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.181 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.212 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.135 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.093 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified

 afraid terrified terrified terrified | surprised and surprised.
 proud of | excited anticipating anticipating anticipating anticipating anticipating | disgusted and disgusted.
 disgusted and
[ValMetric epoch 2] accuracy=0.6350 | best=0.6350 @ epoch 2
[Step 1500] CE/token (EMA): 1.141 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.126 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.108 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.257 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.139 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.142 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.190 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.171 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.205 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.236 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.125 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.174 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.050 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.195 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.146 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.079 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.048 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.192 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.096 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.174 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.157 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.106 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.135 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.145 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.161 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.140 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.120 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.130 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.164 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.244 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.276 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.188 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.179 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.256 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.253 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.254 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.127 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.152 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.136 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.092 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.012 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.006 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 0.968 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.037 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.024 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.301 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.202 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.047 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 0.963 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.016 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.048 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.033 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 0.957 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 0.965 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.063 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.086 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.024 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.078 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.120 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.043 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.064 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 0.941 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 0.974 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 0.961 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.097 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 0.986 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 0.905 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 0.912 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 0.944 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 0.978 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 0.976 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 0.961 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 0.977 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.067 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified terrified terrified terrified terrified terrified | surprised and surprised.

 content surprised | excited anticipating anticipating anticipating anticipating anticipating | disgusted and disgusted.

 I hated

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 9548.66it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 4,807,936 || all params: 3,090,746,624 || trainable%: 0.1556
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 5.342 | Contrast[mask]: 0.693 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 5.548 | Contrast[mask]: 0.692 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 5.147 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 4.836 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 4.224 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.680 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.358 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.253 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 3.078 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.898 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 2.753 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.495 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.299 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.103 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.070 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 1.867 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 1.917 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 1.867 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 1.832 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 1.701 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 1.950 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 1.893 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 1.816 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 1.660 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 1.709 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 1.823 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 1.567 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.548 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.630 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.503 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.553 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.545 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.478 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.575 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.692 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.628 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.782 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.720 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.550 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.503 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.506 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.624 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.565 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.465 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.586 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.532 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.453 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.471 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.403 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.383 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.460 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.539 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.401 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.309 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.320 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.364 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.309 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.264 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.332 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.376 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.350 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.399 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.404 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.278 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.542 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.435 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.407 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.463 | Contrast[mask]: 0.666 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.306 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.237 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.340 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.302 | Contrast[mask]: 0.666 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.322 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.308 | Contrast[mask]: 0.617 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.280 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5950 | best=0.5950 @ epoch 1
[Step 750] CE/token (EMA): 1.220 | Contrast[mask]: 0.668 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.195 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.206 | Contrast[mask]: 0.668 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.280 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.308 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.293 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.296 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.303 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.282 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.337 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.254 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.274 | Contrast[mask]: 0.658 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.249 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.148 | Contrast[mask]: 0.666 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.182 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.364 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.299 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.217 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.277 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.429 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.299 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.299 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.342 | Contrast[mask]: 0.667 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.473 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.292 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.253 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.201 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.215 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.335 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.269 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.177 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.285 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.257 | Contrast[mask]: 0.659 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.333 | Contrast[mask]: 0.652 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.294 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.217 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.234 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.249 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.198 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.292 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.244 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.320 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.347 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.298 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.307 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.330 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.291 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.220 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.336 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.317 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.165 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.173 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.226 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.261 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.288 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.273 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.131 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.098 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.091 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.172 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.148 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.342 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.366 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.291 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.308 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.283 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.229 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.165 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.135 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.136 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.107 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.124 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.184 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.122 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.102 | Contrast[mask]: 0.662 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified terrified terrified terrified terrified terrified | surprised surprised surprised surprised surprised surprised | excited… anticipating… anticipating… | disgusted disgusted… disgusted… disgusted
[ValMetric epoch 2] accuracy=0.6400 | best=0.6400 @ epoch 2
[Step 1500] CE/token (EMA): 1.115 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.142 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.128 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.245 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.133 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.117 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.201 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.186 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.223 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.237 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.255 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.125 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.143 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.047 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.185 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.120 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.063 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.032 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.171 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.082 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.179 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.150 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.115 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.137 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.148 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.146 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.120 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.093 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.079 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.117 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.157 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.206 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.170 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.172 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.248 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.234 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.252 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.121 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.165 | Contrast[mask]: 0.667 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.178 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.138 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.002 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.010 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 0.953 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.035 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.036 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.336 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.219 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.055 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 0.959 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.002 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.029 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.002 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 0.927 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 0.966 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.083 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.083 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.024 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.052 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.141 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.044 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.050 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 0.954 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 0.980 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 0.982 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.126 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.002 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 0.932 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 0.950 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 0.962 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 0.959 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 0.978 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 0.978 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 0.988 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.086 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified… terrified… terrified… | terrified terrified… terrified… terrified | excited… anticipating… anxious… | disgusted… surprised… disgusted…
[ValMetric epoch 3] accuracy=0.6350 | best=0.6400 @ epoch 2

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 9690.89it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 4,807,936 || all params: 3,090,746,624 || trainable%: 0.1556
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 9.007e-07
[RL sample] REF: 'prepared'
[RL sample] GEN: "fear\nI'm sorry,"
[RL step 0] reward=0.1484 adv=+0.1484 gamma=9.01e-07
[Step 0] CE/token (EMA): 5.342 | Contrast[mask]: 0.000 | RL: -1.602 | Reward: 0.1484

[Step 10] CE/token (EMA): 5.548 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 5.145 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 4.832 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 4.223 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'content\nHow would you describe'
[RL step 50] reward=0.2656 adv=+0.2508 gamma=9.01e-07
[Step 50] CE/token (EMA): 3.685 | Contrast[mask]: 0.000 | RL: -2.707 | Reward: 0.2656
[Step 60] CE/token (EMA): 3.356 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.256 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 3.073 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.896 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed.\n\nNow, provide a'
[RL step 100] reward=0.4844 adv=+0.4445 gamma=9.01e-07
[Step 100] CE/token (EMA): 2.750 | Contrast[mask]: 0.000 | RL: -4.799 | Reward: 0.4844
[Step 110] CE/token (EMA): 2.488 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.308 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.115 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.087 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'sad\nMy thoughts: I'
[RL step 150] reward=0.4375 adv=+0.3531 gamma=9.01e-07
[Step 150] CE/token (EMA): 1.871 | Contrast[mask]: 0.000 | RL: -3.813 | Reward: 0.4375
[Step 160] CE/token (EMA): 1.940 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 1.874 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 1.838 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 1.668 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'disgusted\nBelief: I'
[RL step 200] reward=0.4375 adv=+0.3178 gamma=9.01e-07
[Step 200] CE/token (EMA): 1.729 | Contrast[mask]: 0.000 | RL: -3.432 | Reward: 0.4375
[Step 210] CE/token (EMA): 1.744 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 1.722 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 1.652 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 1.662 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'content\nNarrative: I'
[RL step 250] reward=0.4219 adv=+0.2704 gamma=9.01e-07
[Step 250] CE/token (EMA): 1.854 | Contrast[mask]: 0.000 | RL: -2.920 | Reward: 0.4219
[Step 260] CE/token (EMA): 1.603 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.584 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.657 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.544 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'terrified\nImagine a child sitting'
[RL step 300] reward=0.6016 adv=+0.4231 gamma=9.01e-07
[Step 300] CE/token (EMA): 1.571 | Contrast[mask]: 0.000 | RL: -4.567 | Reward: 0.6016
[Step 310] CE/token (EMA): 1.549 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.568 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.718 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'surprised'
[RL sample] GEN: 'surprised\ncomplimented'
[RL step 350] reward=0.6094 adv=+0.3886 gamma=9.01e-07
[Step 350] CE/token (EMA): 1.675 | Contrast[mask]: 0.000 | RL: -4.196 | Reward: 0.6094
[Step 360] CE/token (EMA): 1.718 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.685 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.550 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.468 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'hopeful'
[RL sample] GEN: 'anxious\nPredictably, I'
[RL step 400] reward=0.4609 adv=+0.2013 gamma=9.01e-07
[Step 400] CE/token (EMA): 1.505 | Contrast[mask]: 0.000 | RL: -2.173 | Reward: 0.4609
[Step 410] CE/token (EMA): 1.632 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.575 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.489 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.601 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'prepared'
[RL sample] GEN: 'excited\nPredictable actions:'
[RL step 450] reward=0.5859 adv=+0.3061 gamma=9.01e-07
[Step 450] CE/token (EMA): 1.613 | Contrast[mask]: 0.000 | RL: -3.306 | Reward: 0.5859
[Step 460] CE/token (EMA): 1.527 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.496 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.403 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.402 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'prepared\nprepared\nprepared'
[RL step 500] reward=0.5391 adv=+0.2287 gamma=9.01e-07
[Step 500] CE/token (EMA): 1.499 | Contrast[mask]: 0.000 | RL: -2.468 | Reward: 0.5391
[Step 510] CE/token (EMA): 1.537 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.388 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.287 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.323 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anticipating'
[RL sample] GEN: 'excited\nAwwww,'
[RL step 550] reward=0.6250 adv=+0.2917 gamma=9.01e-07
[Step 550] CE/token (EMA): 1.404 | Contrast[mask]: 0.000 | RL: -3.149 | Reward: 0.6250
[Step 560] CE/token (EMA): 1.372 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.300 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.339 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.345 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'lonely'
[RL sample] GEN: 'lonely\nChainsaw:'
[RL step 600] reward=0.5781 adv=+0.2157 gamma=9.01e-07
[Step 600] CE/token (EMA): 1.401 | Contrast[mask]: 0.000 | RL: -2.328 | Reward: 0.5781
[Step 610] CE/token (EMA): 1.465 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.414 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.309 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.498 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anxious\nA feeling of anxious'
[RL step 650] reward=0.5078 adv=+0.1238 gamma=9.01e-07
[Step 650] CE/token (EMA): 1.412 | Contrast[mask]: 0.000 | RL: -1.336 | Reward: 0.5078
[Step 660] CE/token (EMA): 1.414 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.430 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.271 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.248 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anticipating\n anticipating\n anticipating'
[RL step 700] reward=0.5469 adv=+0.1505 gamma=9.01e-07
[Step 700] CE/token (EMA): 1.355 | Contrast[mask]: 0.000 | RL: -1.625 | Reward: 0.5469
[Step 710] CE/token (EMA): 1.298 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.335 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.326 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.314 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.6150 | best=0.6150 @ epoch 1
[RL sample] REF: 'jealous'
[RL sample] GEN: 'jealous\nA feeling of angry'
[RL step 750] reward=0.5547 adv=+0.1432 gamma=9.01e-07
[Step 750] CE/token (EMA): 1.289 | Contrast[mask]: 0.000 | RL: -1.547 | Reward: 0.5547
[Step 760] CE/token (EMA): 1.199 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.177 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.247 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.247 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'disappointed\nI was disappointed because'
[RL step 800] reward=0.6719 adv=+0.2461 gamma=9.01e-07
[Step 800] CE/token (EMA): 1.224 | Contrast[mask]: 0.000 | RL: -2.657 | Reward: 0.6719
[Step 810] CE/token (EMA): 1.242 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.310 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.306 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.317 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty\nA guilty feeling is'
[RL step 850] reward=0.6406 adv=+0.1902 gamma=9.01e-07
[Step 850] CE/token (EMA): 1.240 | Contrast[mask]: 0.000 | RL: -2.054 | Reward: 0.6406
[Step 860] CE/token (EMA): 1.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.246 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.119 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.206 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty\nA guilty conscience is'
[RL step 900] reward=0.5391 adv=+0.0697 gamma=9.01e-07
[Step 900] CE/token (EMA): 1.377 | Contrast[mask]: 0.000 | RL: -0.752 | Reward: 0.5391
[Step 910] CE/token (EMA): 1.309 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.252 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.287 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.299 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'devastated\nCompanion: devastated'
[RL step 950] reward=0.4922 adv=+0.0158 gamma=9.01e-07
[Step 950] CE/token (EMA): 1.200 | Contrast[mask]: 0.000 | RL: -0.171 | Reward: 0.4922
[Step 960] CE/token (EMA): 1.298 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.338 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.374 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.289 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud\nCompassion'
[RL step 1000] reward=0.5859 adv=+0.1080 gamma=9.01e-07
[Step 1000] CE/token (EMA): 1.224 | Contrast[mask]: 0.000 | RL: -1.166 | Reward: 0.5859
[Step 1010] CE/token (EMA): 1.168 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.173 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.301 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.247 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disgusted'
[RL sample] GEN: 'disgusted\nJesse felt disgusted'
[RL step 1050] reward=0.6797 adv=+0.1909 gamma=9.01e-07
[Step 1050] CE/token (EMA): 1.122 | Contrast[mask]: 0.000 | RL: -2.062 | Reward: 0.6797
[Step 1060] CE/token (EMA): 1.235 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.147 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.211 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.225 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'nostalgic'
[RL sample] GEN: 'nostalgic\nA lot of times'
[RL step 1100] reward=0.6250 adv=+0.1172 gamma=9.01e-07
[Step 1100] CE/token (EMA): 1.164 | Contrast[mask]: 0.000 | RL: -1.265 | Reward: 0.6250
[Step 1110] CE/token (EMA): 1.176 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.180 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.147 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.270 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sentimental'
[RL sample] GEN: 'sentimental.\n  \n  sentimental'
[RL step 1150] reward=0.5938 adv=+0.0742 gamma=9.01e-07
[Step 1150] CE/token (EMA): 1.265 | Contrast[mask]: 0.000 | RL: -0.801 | Reward: 0.5938
[Step 1160] CE/token (EMA): 1.344 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.385 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.304 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.338 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'confident'
[RL sample] GEN: 'confident\nI was confident in'
[RL step 1200] reward=0.5234 adv=-0.0035 gamma=9.01e-07
[Step 1200] CE/token (EMA): 1.354 | Contrast[mask]: 0.000 | RL: 0.038 | Reward: 0.5234
[Step 1210] CE/token (EMA): 1.311 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.221 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.331 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.302 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 1250] reward=0.6250 adv=+0.0984 gamma=9.01e-07
[Step 1250] CE/token (EMA): 1.170 | Contrast[mask]: 0.000 | RL: -1.062 | Reward: 0.6250
[Step 1260] CE/token (EMA): 1.188 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.240 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.255 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.287 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'jealous'
[RL sample] GEN: 'competitive\nI was competitive because'
[RL step 1300] reward=0.6562 adv=+0.1198 gamma=9.01e-07
[Step 1300] CE/token (EMA): 1.265 | Contrast[mask]: 0.000 | RL: -1.293 | Reward: 0.6562
[Step 1310] CE/token (EMA): 1.133 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.100 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.063 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.181 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited\nI was excited about'
[RL step 1350] reward=0.5234 adv=-0.0250 gamma=9.01e-07
[Step 1350] CE/token (EMA): 1.143 | Contrast[mask]: 0.000 | RL: 0.270 | Reward: 0.5234
[Step 1360] CE/token (EMA): 1.315 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.355 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.301 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.310 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud\nI was proud of'
[RL step 1400] reward=0.5078 adv=-0.0381 gamma=9.01e-07
[Step 1400] CE/token (EMA): 1.273 | Contrast[mask]: 0.000 | RL: 0.412 | Reward: 0.5078
[Step 1410] CE/token (EMA): 1.210 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.132 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.115 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.108 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'afraid'
[RL sample] GEN: 'afraid\n  \n  terrified'
[RL step 1450] reward=0.5547 adv=+0.0126 gamma=9.01e-07
[Step 1450] CE/token (EMA): 1.088 | Contrast[mask]: 0.000 | RL: -0.136 | Reward: 0.5547
[Step 1460] CE/token (EMA): 1.109 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.172 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.100 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.080 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified terrified terrified terrified terrified terrified | surprised.
Jesse surprised me | excited anticipating anticipating anticipating anticipating anticipating | disgusted.



I was
[ValMetric epoch 2] accuracy=0.6500 | best=0.6500 @ epoch 2
[RL sample] REF: 'annoyed'
[RL sample] GEN: 'annoyed\nI tried to be'
[RL step 1500] reward=0.7109 adv=+0.1676 gamma=9.01e-07
[Step 1500] CE/token (EMA): 1.040 | Contrast[mask]: 0.000 | RL: -1.809 | Reward: 0.7109
[Step 1510] CE/token (EMA): 1.089 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.069 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.207 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.086 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'joyful'
[RL sample] GEN: 'joyful\nCompared to the'
[RL step 1550] reward=0.6250 adv=+0.0649 gamma=9.01e-07
[Step 1550] CE/token (EMA): 1.106 | Contrast[mask]: 0.000 | RL: -0.700 | Reward: 0.6250
[Step 1560] CE/token (EMA): 1.173 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.144 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.178 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.208 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'impressed\nGenerations past,'
[RL step 1600] reward=0.5391 adv=-0.0276 gamma=9.01e-07
[Step 1600] CE/token (EMA): 1.227 | Contrast[mask]: 0.000 | RL: 0.298 | Reward: 0.5391
[Step 1610] CE/token (EMA): 1.103 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.135 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.040 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.173 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'caring'
[RL sample] GEN: 'caring\nCompassionate'
[RL step 1650] reward=0.5703 adv=+0.0064 gamma=9.01e-07
[Step 1650] CE/token (EMA): 1.115 | Contrast[mask]: 0.000 | RL: -0.070 | Reward: 0.5703
[Step 1660] CE/token (EMA): 1.049 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.043 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.150 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.045 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'embarrassed'
[RL sample] GEN: 'embarrassed\nI was embarrassed because'
[RL step 1700] reward=0.5938 adv=+0.0292 gamma=9.01e-07
[Step 1700] CE/token (EMA): 1.129 | Contrast[mask]: 0.000 | RL: -0.316 | Reward: 0.5938
[Step 1710] CE/token (EMA): 1.104 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.089 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.146 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.153 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed\nI was devastated.'
[RL step 1750] reward=0.6797 adv=+0.1123 gamma=9.01e-07

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 9408.21it/s]
Map: 100%|██████████| 6000/6000 [00:00<00:00, 10230.75 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 8041.15 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7864.31 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8338.94 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 3B n=6000 (s44)
======================================================================

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 9952.80it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 4,807,936 || all params: 3,090,746,624 || trainable%: 0.1556
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 3.903 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 4.435 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 4.385 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 4.215 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 3.967 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.507 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.310 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.206 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 3.012 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.838 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 2.660 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.577 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.309 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 1.950 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 1.986 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 1.955 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 1.876 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 1.788 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 1.863 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 1.823 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 1.774 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 1.710 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 1.778 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 1.743 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 1.663 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 1.598 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 1.521 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.462 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.602 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.541 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.456 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.568 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.515 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.619 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.478 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.354 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.405 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.415 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.400 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.471 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.426 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.481 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.574 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.487 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.532 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.598 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.493 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.421 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.487 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.488 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.356 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.359 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.425 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.490 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.505 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.459 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.328 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.284 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.254 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.301 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.301 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.470 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.573 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.483 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.529 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.484 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.415 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.314 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.291 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.266 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.278 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.330 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.248 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.218 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5800 | best=0.5800 @ epoch 1
[Step 750] CE/token (EMA): 1.282 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.285 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.247 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.386 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.330 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.317 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.310 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.291 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.384 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.448 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.469 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.325 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.353 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.195 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.369 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.315 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.252 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.252 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.385 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.268 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 3.334 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 3.638 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 2.700 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 2.175 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.842 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.640 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.510 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.399 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.369 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.361 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.396 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.425 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.336 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.337 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.364 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.368 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.415 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.252 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.322 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.328 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.240 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.150 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.148 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.084 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.151 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.152 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.404 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.312 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.196 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.077 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.149 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.177 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.154 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.072 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.111 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.202 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.203 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.146 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.227 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.264 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.200 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.190 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.075 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.106 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.090 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.220 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.137 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.040 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.046 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.070 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.067 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.101 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.068 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.116 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.220 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified and terrified terrified terrified terrified | surprised and terrified. | excited and excited.
    anticipating | disgusted and disgusted.
[ValMetric epoch 2] accuracy=0.6150 | best=0.6150 @ epoch 2
[Step 1500] CE/token (EMA): 1.177 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.112 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.143 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.231 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.314 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.236 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.205 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.215 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.108 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.086 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.139 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.163 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.133 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.050 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 0.965 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 0.974 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.083 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.088 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.034 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.101 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.151 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.116 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.022 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 0.980 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 0.960 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 0.948 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.052 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.035 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.039 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.046 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.041 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 0.952 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 0.882 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.130 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.082 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 0.990 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.025 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.062 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 0.986 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.046 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.097 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.123 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.027 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.030 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.003 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.147 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.083 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.044 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.065 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.104 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.051 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.066 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.118 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 0.965 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 0.911 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 0.841 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 0.855 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 0.917 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 0.982 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.081 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.106 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.105 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.049 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 0.983 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 0.970 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.087 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.031 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.043 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.103 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.104 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.115 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.109 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.070 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.173 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified terrified terrified terrified terrified terrified | surprised and afraid surprised and afraid | excited and excited anticipating the experience | disgusted and disgusted surprised and disgusted
[ValMetric epoch 3] accuracy=0.6300 | best=0.6300 @ epoch 3

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 9364.74it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 4,807,936 || all params: 3,090,746,624 || trainable%: 0.1556
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 3.903 | Contrast[mask]: 0.693 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 4.432 | Contrast[mask]: 0.693 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 4.376 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 4.211 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 3.964 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.501 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.299 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.212 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.988 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.805 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 2.655 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.570 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.270 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 1.917 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 1.971 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 1.998 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 1.886 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 1.767 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 1.829 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 1.818 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 1.757 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 1.712 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 1.791 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 1.736 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 1.706 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 1.644 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 1.529 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.484 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.563 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.481 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.396 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.511 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.807 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.781 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.615 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.394 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.476 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.434 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.369 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.450 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.465 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.479 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.574 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.486 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.527 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.510 | Contrast[mask]: 0.692 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.446 | Contrast[mask]: 0.692 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.396 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.457 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.475 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.364 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.362 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.397 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.446 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.499 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.459 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.281 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.278 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.230 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.582 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.452 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.529 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.581 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.461 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.517 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.451 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.384 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.302 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.292 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.261 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.272 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.288 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.352 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.255 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.237 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.6050 | best=0.6050 @ epoch 1
[Step 750] CE/token (EMA): 1.260 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.277 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.242 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.425 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.296 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.264 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.337 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.265 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.324 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.392 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.429 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.256 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.287 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.179 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.311 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.289 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.281 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.272 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.373 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.233 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.359 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.300 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.283 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.315 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.340 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.327 | Contrast[mask]: 0.663 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.307 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 2.312 | Contrast[mask]: 0.668 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 2.933 | Contrast[mask]: 0.651 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 3.670 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 4.075 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 2.981 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 2.255 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.845 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.673 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.529 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.490 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.302 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.330 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.336 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.260 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.144 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.127 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.078 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.154 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.157 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.416 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.312 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.188 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.066 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.138 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.188 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.161 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.105 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.139 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.239 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.200 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.160 | Contrast[mask]: 0.667 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.228 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.233 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.157 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.171 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.060 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.092 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.084 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.202 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.124 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.024 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.033 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.049 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.069 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.102 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.062 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.108 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.222 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified terrified terrified terrified terrified terrified | surprised surprised surprised surprised surprised surprised | excited excited excited excited excited excited | disgusted disgusted disgusted disgusted disgusted disgusted
[ValMetric epoch 2] accuracy=0.6000 | best=0.6050 @ epoch 1
[Step 1500] CE/token (EMA): 1.196 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.131 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.236 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.132 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.203 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.310 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.232 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.235 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.223 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.130 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.073 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.131 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.167 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.162 | Contrast[mask]: 0.660 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.082 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.008 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 0.985 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.056 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.058 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.015 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.064 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.127 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.085 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.021 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.014 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 0.975 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 0.940 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.064 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.048 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.085 | Contrast[mask]: 0.646 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.058 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.058 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 0.980 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 0.900 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.157 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.084 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 0.983 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 0.983 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.053 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 0.999 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.078 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.100 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.100 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.024 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.041 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.023 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.186 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.122 | Contrast[mask]: 0.663 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.093 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.116 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.134 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.060 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.039 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.073 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 0.940 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 0.906 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 0.823 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 0.837 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 0.873 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 0.949 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.029 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.063 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.095 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.037 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 0.976 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 0.982 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.074 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.014 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.027 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.082 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.087 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.117 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.097 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.055 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.172 | Contrast[mask]: 0.692 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified terrified terrified terrified terrified terrified | surprised surprised surprised surprised surprised surprised | excited期待 anticipating期待期待 anticipating | disgusted disgusted disgusted disgusted terrified terrified

Loading weights: 100%|██████████| 434/434 [00:00<00:00, 9480.13it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 4,807,936 || all params: 3,090,746,624 || trainable%: 0.1556
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 5.002e-07
[RL sample] REF: 'prepared'
[RL sample] GEN: "anxious\nI'm sorry to"
[RL step 0] reward=0.1953 adv=+0.1953 gamma=5.00e-07
[Step 0] CE/token (EMA): 3.903 | Contrast[mask]: 0.000 | RL: -1.171 | Reward: 0.1953

[Step 10] CE/token (EMA): 4.432 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 4.379 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 4.213 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 3.967 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'happy\nRelationship: friend'
[RL step 50] reward=0.3281 adv=+0.3086 gamma=5.00e-07
[Step 50] CE/token (EMA): 3.507 | Contrast[mask]: 0.000 | RL: -1.850 | Reward: 0.3281
[Step 60] CE/token (EMA): 3.308 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 3.207 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 3.018 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.848 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed, sad\n\nWhat is'
[RL step 100] reward=0.5156 adv=+0.4652 gamma=5.00e-07
[Step 100] CE/token (EMA): 2.671 | Contrast[mask]: 0.000 | RL: -2.789 | Reward: 0.5156
[Step 110] CE/token (EMA): 2.600 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.355 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.018 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.061 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'sad\nTherapist:'
[RL step 150] reward=0.5547 adv=+0.4578 gamma=5.00e-07
[Step 150] CE/token (EMA): 2.010 | Contrast[mask]: 0.000 | RL: -2.744 | Reward: 0.5547
[Step 160] CE/token (EMA): 1.925 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 1.819 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 1.862 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 1.856 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'disgusted\n\nExplanation: I was'
[RL step 200] reward=0.4688 adv=+0.3261 gamma=5.00e-07
[Step 200] CE/token (EMA): 1.833 | Contrast[mask]: 0.000 | RL: -1.955 | Reward: 0.4688
[Step 210] CE/token (EMA): 1.760 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 1.799 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 1.776 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 1.699 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'organized\nPredict the sentiment of'
[RL step 250] reward=0.4297 adv=+0.2544 gamma=5.00e-07
[Step 250] CE/token (EMA): 1.672 | Contrast[mask]: 0.000 | RL: -1.525 | Reward: 0.4297
[Step 260] CE/token (EMA): 1.592 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.532 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.669 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.573 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'terrified\n\nExplanation: The terrified'
[RL step 300] reward=0.5625 adv=+0.3618 gamma=5.00e-07
[Step 300] CE/token (EMA): 1.470 | Contrast[mask]: 0.000 | RL: -2.169 | Reward: 0.5625
[Step 310] CE/token (EMA): 1.574 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.487 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.589 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.487 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'surprised'
[RL sample] GEN: 'surprised\n\nAssistant: surprised'
[RL step 350] reward=0.6797 adv=+0.4428 gamma=5.00e-07
[Step 350] CE/token (EMA): 1.325 | Contrast[mask]: 0.000 | RL: -2.655 | Reward: 0.6797
[Step 360] CE/token (EMA): 1.406 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 2.157 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.833 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.745 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'hopeful'
[RL sample] GEN: 'prepared\nYou are trusting in'
[RL step 400] reward=0.5391 adv=+0.2579 gamma=5.00e-07
[Step 400] CE/token (EMA): 1.590 | Contrast[mask]: 0.000 | RL: -1.546 | Reward: 0.5391
[Step 410] CE/token (EMA): 1.613 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.634 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.523 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.565 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'prepared'
[RL sample] GEN: 'excited\nI was so excited'
[RL step 450] reward=0.5156 adv=+0.2086 gamma=5.00e-07
[Step 450] CE/token (EMA): 1.538 | Contrast[mask]: 0.000 | RL: -1.251 | Reward: 0.5156
[Step 460] CE/token (EMA): 1.473 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.429 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.447 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.443 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'prepared\nI am prepared for'
[RL step 500] reward=0.5078 adv=+0.1800 gamma=5.00e-07
[Step 500] CE/token (EMA): 1.329 | Contrast[mask]: 0.000 | RL: -1.079 | Reward: 0.5078
[Step 510] CE/token (EMA): 1.345 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.412 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.454 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.506 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anticipating'
[RL sample] GEN: 'anticipating the joy of anticipating the'
[RL step 550] reward=0.6719 adv=+0.3260 gamma=5.00e-07
[Step 550] CE/token (EMA): 1.473 | Contrast[mask]: 0.000 | RL: -1.955 | Reward: 0.6719
[Step 560] CE/token (EMA): 1.293 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.298 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.270 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.325 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'lonely'
[RL sample] GEN: 'lonely.\nI feel lonely because'
[RL step 600] reward=0.6719 adv=+0.2934 gamma=5.00e-07
[Step 600] CE/token (EMA): 1.308 | Contrast[mask]: 0.000 | RL: -1.759 | Reward: 0.6719
[Step 610] CE/token (EMA): 1.478 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.556 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.487 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.522 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anxious\nPredicted outcome:'
[RL step 650] reward=0.5156 adv=+0.1078 gamma=5.00e-07
[Step 650] CE/token (EMA): 1.459 | Contrast[mask]: 0.000 | RL: -0.647 | Reward: 0.5156
[Step 660] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.315 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.309 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.294 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'excited\n\nAssistant: joyful'
[RL step 700] reward=0.5234 adv=+0.1049 gamma=5.00e-07
[Step 700] CE/token (EMA): 1.275 | Contrast[mask]: 0.000 | RL: -0.629 | Reward: 0.5234
[Step 710] CE/token (EMA): 1.296 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.364 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.274 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.259 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5850 | best=0.5850 @ epoch 1
[RL sample] REF: 'jealous'
[RL sample] GEN: 'jealous.\nI feel jealous because'
[RL step 750] reward=0.5703 adv=+0.1413 gamma=5.00e-07
[Step 750] CE/token (EMA): 1.233 | Contrast[mask]: 0.000 | RL: -0.847 | Reward: 0.5703
[Step 760] CE/token (EMA): 1.273 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.263 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.403 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.294 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'disappointed\n\nI was anticipating spending'
[RL step 800] reward=0.6719 adv=+0.2287 gamma=5.00e-07
[Step 800] CE/token (EMA): 1.270 | Contrast[mask]: 0.000 | RL: -1.371 | Reward: 0.6719
[Step 810] CE/token (EMA): 1.335 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.274 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.330 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.409 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty\n\nAssistant: guilty'
[RL step 850] reward=0.6250 adv=+0.1589 gamma=5.00e-07
[Step 850] CE/token (EMA): 1.449 | Contrast[mask]: 0.000 | RL: -0.953 | Reward: 0.6250
[Step 860] CE/token (EMA): 1.295 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.306 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.184 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.344 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'angry and furious.\nContent:'
[RL step 900] reward=0.5234 adv=+0.0415 gamma=5.00e-07
[Step 900] CE/token (EMA): 1.283 | Contrast[mask]: 0.000 | RL: -0.249 | Reward: 0.5234
[Step 910] CE/token (EMA): 1.220 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.221 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.386 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.275 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'devastated\n\nAssistant: devastated'
[RL step 950] reward=0.4688 adv=-0.0173 gamma=5.00e-07
[Step 950] CE/token (EMA): 1.391 | Contrast[mask]: 0.000 | RL: 0.104 | Reward: 0.4688
[Step 960] CE/token (EMA): 1.307 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.297 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.307 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.326 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud\n\nAssistant: proud'
[RL step 1000] reward=0.6250 adv=+0.1406 gamma=5.00e-07
[Step 1000] CE/token (EMA): 1.311 | Contrast[mask]: 0.000 | RL: -0.843 | Reward: 0.6250
[Step 1010] CE/token (EMA): 1.281 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.268 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.260 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.285 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disgusted'
[RL sample] GEN: 'disgusted and disgusted with her.'
[RL step 1050] reward=0.6484 adv=+0.1500 gamma=5.00e-07
[Step 1050] CE/token (EMA): 1.342 | Contrast[mask]: 0.000 | RL: -0.899 | Reward: 0.6484
[Step 1060] CE/token (EMA): 1.409 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.334 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.321 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.387 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'nostalgic'
[RL sample] GEN: 'nostalgic.\nI was nostalgic because'
[RL step 1100] reward=0.5859 adv=+0.0725 gamma=5.00e-07
[Step 1100] CE/token (EMA): 1.360 | Contrast[mask]: 0.000 | RL: -0.435 | Reward: 0.5859
[Step 1110] CE/token (EMA): 1.360 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.225 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.292 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.300 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sentimental'
[RL sample] GEN: 'sentimental\n\nAssistant: sentimental'
[RL step 1150] reward=0.5938 adv=+0.0731 gamma=5.00e-07
[Step 1150] CE/token (EMA): 1.214 | Contrast[mask]: 0.000 | RL: -0.438 | Reward: 0.5938
[Step 1160] CE/token (EMA): 1.119 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.116 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.074 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.151 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'confident'
[RL sample] GEN: 'prepared\n\nAssistant: prepared'
[RL step 1200] reward=0.5391 adv=+0.0111 gamma=5.00e-07
[Step 1200] CE/token (EMA): 1.171 | Contrast[mask]: 0.000 | RL: -0.066 | Reward: 0.5391
[Step 1210] CE/token (EMA): 1.439 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.343 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.219 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.099 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 1250] reward=0.6641 adv=+0.1350 gamma=5.00e-07
[Step 1250] CE/token (EMA): 1.168 | Contrast[mask]: 0.000 | RL: -0.809 | Reward: 0.6641
[Step 1260] CE/token (EMA): 1.196 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.185 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.101 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.118 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'jealous'
[RL sample] GEN: 'competitive\n\nAssistant: competitive'
[RL step 1300] reward=0.6797 adv=+0.1371 gamma=5.00e-07
[Step 1300] CE/token (EMA): 1.244 | Contrast[mask]: 0.000 | RL: -0.822 | Reward: 0.6797
[Step 1310] CE/token (EMA): 1.212 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.167 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.219 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.242 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited\n\nAssistant: excited'
[RL step 1350] reward=0.5625 adv=+0.0062 gamma=5.00e-07
[Step 1350] CE/token (EMA): 1.174 | Contrast[mask]: 0.000 | RL: -0.037 | Reward: 0.5625
[Step 1360] CE/token (EMA): 1.186 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.076 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.116 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.129 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'grateful for my sight\n\nAssistant'
[RL step 1400] reward=0.5078 adv=-0.0491 gamma=5.00e-07
[Step 1400] CE/token (EMA): 1.227 | Contrast[mask]: 0.000 | RL: 0.294 | Reward: 0.5078
[Step 1410] CE/token (EMA): 1.138 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.064 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.088 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.103 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'afraid'
[RL sample] GEN: 'terrified\n\nAssistant: terrified'
[RL step 1450] reward=0.5391 adv=-0.0129 gamma=5.00e-07
[Step 1450] CE/token (EMA): 1.086 | Contrast[mask]: 0.000 | RL: 0.078 | Reward: 0.5391
[Step 1460] CE/token (EMA): 1.119 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.079 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.106 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.234 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified terrified terrified terrified terrified terrified | surprised and terrified terrified terrified terrified | excited

Assistant: anticipating the | disgusted and disgusted at the same
[ValMetric epoch 2] accuracy=0.6250 | best=0.6250 @ epoch 2
[RL sample] REF: 'annoyed'
[RL sample] GEN: 'annoyed\n\nAssistant: 1'
[RL step 1500] reward=0.6719 adv=+0.1212 gamma=5.00e-07
[Step 1500] CE/token (EMA): 1.164 | Contrast[mask]: 0.000 | RL: -0.726 | Reward: 0.6719
[Step 1510] CE/token (EMA): 1.150 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.286 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.153 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.229 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'joyful'
[RL sample] GEN: 'joyful\n\nAssistant: joyful'
[RL step 1550] reward=0.6641 adv=+0.1012 gamma=5.00e-07
[Step 1550] CE/token (EMA): 1.316 | Contrast[mask]: 0.000 | RL: -0.607 | Reward: 0.6641
[Step 1560] CE/token (EMA): 1.231 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.227 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.249 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.143 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'surprised and impressed\n\nAssistant:'
[RL step 1600] reward=0.5234 adv=-0.0495 gamma=5.00e-07
[Step 1600] CE/token (EMA): 1.103 | Contrast[mask]: 0.000 | RL: 0.297 | Reward: 0.5234
[Step 1610] CE/token (EMA): 1.147 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.148 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.126 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.061 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'caring'
[RL sample] GEN: 'caring\n\nAssistant: caring'
[RL step 1650] reward=0.5703 adv=+0.0023 gamma=5.00e-07
[Step 1650] CE/token (EMA): 0.998 | Contrast[mask]: 0.000 | RL: -0.014 | Reward: 0.5703
[Step 1660] CE/token (EMA): 0.982 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.068 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.063 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.032 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'embarrassed'
[RL sample] GEN: 'embarrassed\n\nAssistant: embarrassed'
[RL step 1700] reward=0.5625 adv=-0.0057 gamma=5.00e-07
[Step 1700] CE/token (EMA): 1.089 | Contrast[mask]: 0.000 | RL: 0.034 | Reward: 0.5625
[Step 1710] CE/token (EMA): 1.132 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.119 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.020 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 0.984 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'

In [11]:
# ============================================================
# НЕЗАВИСИМАЯ РЕПЛИКАЦИЯ 0.5B×6000, сиды 52–54 (критика-4 §17)
# Протокол заморожен заранее (§8.1/§10 журнала): те же
# гиперпараметры, общий случайный старт на сид, {MLE, mask, CE+RL}.
# Все сиды включаются без отбора. ~45 мин (0.5B).
# ============================================================
import copy
import math

REPL_SEEDS = [52, 53, 54]
REPL_SIZE = 6000

for seed in REPL_SEEDS:
    if any(r["model"] == "05B" and r["seed"] == seed and r["size"] == REPL_SIZE
           and all(k in r for k in SWEEP_CONFIGS) for r in ld_rows):
        print(f"[Resume] 05B s{seed} готов")
        continue
    shared = make_shared_start("Qwen/Qwen2.5-0.5B", seed)
    rebuild_d1_datasets(REPL_SIZE)
    steps = math.ceil(REPL_SIZE / cfg_sweep_base.batch_size) * \
        cfg_sweep_base.total_epochs
    row = {"model": "05B", "seed": seed, "size": REPL_SIZE, "replication": True}
    for cname in SWEEP_CONFIGS:
        c = copy.copy(cfg_sweep_base)
        c.model_name = "Qwen/Qwen2.5-0.5B"
        c.seed = seed
        c.train_size = REPL_SIZE
        c.init_selection_inits = 0
        c.warmup_steps = min(200, max(10, steps // 10))
        c.output_dir = f"./sweep_ld/05B_{cname}_s{seed}_n{REPL_SIZE}"
        if cname == "MLE":
            c.beta = 0.0; c.gamma = 0.0; c.gamma_auto = False
        elif cname == "mask":
            c.beta = 0.1; c.contrast_mode = "mask"
            c.gamma = 0.0; c.gamma_auto = False
        else:
            c.beta = 0.0; c.gamma = 2e-5; c.gamma_auto = True
        rj = os.path.join(c.output_dir, "results.json")
        if os.path.exists(rj):
            with open(rj) as f:
                sc = json.load(f)["test_scores"]
        else:
            sc = run_experiment(c, f"{cname} 05B repl n={REPL_SIZE} (s{seed})",
                                init_state=shared)
        row[cname] = sc["accuracy"]
        row[f"{cname}-verb"] = sc["verb_accuracy"]
        gc.collect(); torch.cuda.empty_cache()
    ld_rows = [r for r in ld_rows
               if not (r["model"] == "05B" and r["seed"] == seed
                       and r["size"] == REPL_SIZE)] + [row]
    with open(_summary_ld, "w") as f:
        json.dump({"rows": ld_rows}, f, indent=2)
    print(f">>> repl 05B s{seed}: "
          f"{ {k: round(row[k], 4) for k in SWEEP_CONFIGS} }\n")
    del shared
    gc.collect(); torch.cuda.empty_cache()

# ---------- агрегация: n=10 (исходные 42-48 + репликация 52-54) ----------
from math import sqrt, comb

rs = [r for r in ld_rows if r["model"] == "05B" and r["size"] == 6000]
rs = sorted(rs, key=lambda r: r["seed"])
print("\n" + "=" * 90)
print(f"ГЛАВНЫЙ РЕЗУЛЬТАТ, РЕПЛИКАЦИЯ: 0.5B x 6000, n={len(rs)} сидов "
      f"(42-48 исходные + 52-54 репликация)")
print("=" * 90)
for a in ("RL", "mask"):
    d = [r[a] - r["MLE"] for r in rs]
    n = len(d); se = np.std(d, ddof=1) / sqrt(n)
    t = np.mean(d) / se
    crit = {10: 2.262, 9: 2.262, 8: 2.306, 7: 2.447}[n]
    k = sum(1 for x in d if x > 0)
    psign = 2 * sum(comb(n, i) for i in range(k, n + 1)) / 2**n
    orig = [x for x, r in zip(d, rs) if r["seed"] <= 48]
    repl = [x for x, r in zip(d, rs) if r["seed"] >= 52]
    print(f"{a}-MLE: {np.mean(d):+.4f} ± {np.std(d, ddof=1):.4f} | "
          f"t={t:+.2f} (крит {crit}) | {k}/{n} в плюс, знак. p={psign:.4f}")
    print(f"   исходные (n={len(orig)}): mean {np.mean(orig):+.4f} | "
          f"репликация (n={len(repl)}): mean "
          f"{np.mean(repl):+.4f} {[f'{x:+.4f}' for x in repl]}")
print("\nКритерий согласованности: среднее репликации внутри CI исходных?")
print("Гипотеза (предзаявлена): направление и порядок величины сохраняются.")

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10110.87it/s]
Map: 100%|██████████| 6000/6000 [00:00<00:00, 10349.07 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 7859.65 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7902.27 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8702.15 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 05B repl n=6000 (s52)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9746.30it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 10.018 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 9.728 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 9.179 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 8.399 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.304 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 6.196 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 5.277 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 4.890 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.417 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.845 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 3.669 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 3.377 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.199 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 3.167 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 3.016 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.876 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.696 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.691 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.596 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.379 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.426 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.368 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.309 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.176 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 2.092 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 2.123 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.048 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.932 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.911 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.923 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.890 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.939 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.871 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.816 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.734 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.877 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.746 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.690 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.672 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.585 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.669 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.815 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.900 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 2.052 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.982 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.907 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.831 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.859 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.736 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.881 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.815 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.725 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.857 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.838 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.744 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.980 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.892 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.787 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.711 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.738 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.719 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.786 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.703 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.799 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.696 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.587 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.473 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.602 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.651 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.754 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.624 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.757 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.726 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.661 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5300 | best=0.5300 @ epoch 1
[Step 750] CE/token (EMA): 1.634 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.496 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.431 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.540 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.533 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.580 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.564 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.441 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.373 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.286 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.317 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.435 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.490 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.558 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.592 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.596 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.605 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.474 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.358 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.482 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.487 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.554 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.548 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.567 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.582 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.601 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.612 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.486 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.408 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.477 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.577 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.622 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.513 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.549 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.581 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.589 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.485 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.602 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.515 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.486 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.498 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.499 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.554 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.589 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.419 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.601 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.592 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.624 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.565 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.576 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.549 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.478 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.506 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.573 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.539 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.599 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.649 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.544 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.561 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.536 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.357 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.573 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.721 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.563 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.623 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.604 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.524 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.558 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.424 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.398 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.352 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.388 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.329 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.464 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified, afraid, and terrified | angry and angry with angry and | excited, anticipating the exciting and | furious and angry with angry and
[ValMetric epoch 2] accuracy=0.5100 | best=0.5300 @ epoch 1
[Step 1500] CE/token (EMA): 1.472 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.325 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.417 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.434 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.410 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.537 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.458 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.430 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.471 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.472 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.513 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.459 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.404 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.329 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.349 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.443 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.393 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.505 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.434 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.434 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.392 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.350 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.292 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.303 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.349 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.465 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.382 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.347 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.307 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.278 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.219 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.367 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.355 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.402 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.386 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.358 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.335 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.180 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.195 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.222 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.186 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.160 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.230 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.269 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.235 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.210 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.238 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.251 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.209 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.225 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.295 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.352 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.405 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.334 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.266 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.257 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.219 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.220 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.155 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.383 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.322 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.386 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.293 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.331 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.317 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.256 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.444 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.506 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.403 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.320 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.221 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.278 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.372 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.272 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified and terrified.

The terrified | terrified and afraid.

| afraid | excited, anticipating the exciting journey | disgusted with disgusted disgusted disgusted disgusted
[ValMetric epoch 3] accuracy=0.5900 | best=0.5900 @ epoch 3
[Step 2250] CE/token (EMA): 1.317 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9927.35it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 10.018 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 9.733 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 9.184 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 8.407 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.293 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 6.170 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 5.235 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 4.855 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.379 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.827 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 3.656 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 3.343 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.170 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 3.144 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.991 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.865 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.674 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.662 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.557 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.355 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.410 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.347 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.281 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.224 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.117 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 2.027 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 2.056 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.988 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.895 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.890 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.881 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.864 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.951 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.908 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.860 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.769 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.891 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.740 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.685 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.689 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.566 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.661 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.804 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.871 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 2.057 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.995 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.912 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.814 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.858 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.751 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.865 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.808 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.686 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.833 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.815 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.724 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.955 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.878 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.744 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.684 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.684 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.678 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.710 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.685 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.788 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.710 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.626 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.496 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.592 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.664 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.736 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.604 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.756 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.753 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.659 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5300 | best=0.5300 @ epoch 1
[Step 750] CE/token (EMA): 1.613 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.487 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.441 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.525 | Contrast[mask]: 0.668 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.519 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.592 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.547 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.436 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.371 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.294 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.330 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.454 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.524 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.592 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.624 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.618 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.609 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.484 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.374 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.527 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.491 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.497 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.550 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.551 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.573 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.587 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.574 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.567 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.442 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.380 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.464 | Contrast[mask]: 0.665 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.537 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.583 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.499 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.530 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.584 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.592 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.498 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.600 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.507 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.485 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.504 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.486 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.536 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.584 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.404 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.582 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.559 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.589 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.573 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.598 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.553 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.468 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.477 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.514 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.506 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.593 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.654 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.538 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.573 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.549 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.385 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.569 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.711 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.545 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.625 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.602 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.501 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.537 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.390 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.369 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.321 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.370 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.345 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.486 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified, afraid, terrified, | angry and angry with my angry | excited anticipating the exciting and anxious | disgusted and disgusted with the contents
[ValMetric epoch 2] accuracy=0.5200 | best=0.5300 @ epoch 1
[Step 1500] CE/token (EMA): 1.530 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.354 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.440 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.434 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.403 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.542 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.439 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.434 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.479 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.461 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.490 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.451 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.394 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.316 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.364 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.452 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.402 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.511 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.435 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.415 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.335 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.304 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.267 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.269 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.336 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.438 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.481 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.390 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.323 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.276 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.249 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.197 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.365 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.358 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.397 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.382 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.340 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.329 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.198 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.239 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.236 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.190 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.174 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.233 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.291 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.231 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.211 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.235 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.251 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.213 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.248 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.309 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.340 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.393 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.328 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.283 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.282 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.229 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.234 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.146 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.371 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.320 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.363 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.290 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.333 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.318 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.259 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.432 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.496 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.385 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.285 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.196 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.267 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.377 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.261 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified, terrified, terrified, | furious angry angry angry angry angry | excited excited excited excited excited excited | disgusted disgusted disgusted disgusted disgusted disgusted
[ValMetric epoch 3] accuracy=0.5800 | best=0.5800 @ epoch 3

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10341.51it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 1.901e-04
[RL sample] REF: 'prepared'
[RL sample] GEN: 'Happiness\nSobibof'
[RL step 0] reward=0.0078 adv=+0.0078 gamma=1.90e-04
[Step 0] CE/token (EMA): 10.018 | Contrast[mask]: 0.000 | RL: -3.005 | Reward: 0.0078

[Step 10] CE/token (EMA): 9.731 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 9.172 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 8.408 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.321 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'I am feeling very, very'
[RL step 50] reward=0.1484 adv=+0.1477 gamma=1.90e-04
[Step 50] CE/token (EMA): 6.214 | Contrast[mask]: 0.000 | RL: -56.786 | Reward: 0.1484
[Step 60] CE/token (EMA): 5.288 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 4.897 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.419 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.836 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed\nPlanteen:'
[RL step 100] reward=0.3984 adv=+0.3829 gamma=1.90e-04
[Step 100] CE/token (EMA): 3.656 | Contrast[mask]: 0.000 | RL: -147.349 | Reward: 0.3984
[Step 110] CE/token (EMA): 3.343 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.173 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 3.137 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.991 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'sad\nNamer: the'
[RL step 150] reward=0.3828 adv=+0.3290 gamma=1.90e-04
[Step 150] CE/token (EMA): 2.855 | Contrast[mask]: 0.000 | RL: -126.513 | Reward: 0.3828
[Step 160] CE/token (EMA): 2.673 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.654 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.598 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.371 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'lonely\nInclude the details of'
[RL step 200] reward=0.3906 adv=+0.3039 gamma=1.90e-04
[Step 200] CE/token (EMA): 2.446 | Contrast[mask]: 0.000 | RL: -116.868 | Reward: 0.3906
[Step 210] CE/token (EMA): 2.365 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.306 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.240 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.133 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud and satisfied with the current'
[RL step 250] reward=0.3047 adv=+0.1876 gamma=1.90e-04
[Step 250] CE/token (EMA): 2.045 | Contrast[mask]: 0.000 | RL: -72.129 | Reward: 0.3047
[Step 260] CE/token (EMA): 2.084 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.009 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.921 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.899 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'anxious and prepared for the storm'
[RL step 300] reward=0.5312 adv=+0.3954 gamma=1.90e-04
[Step 300] CE/token (EMA): 1.960 | Contrast[mask]: 0.000 | RL: -151.944 | Reward: 0.5312
[Step 310] CE/token (EMA): 1.907 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.946 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.916 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.838 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'surprised'
[RL sample] GEN: 'surprised and impressed with the surprise'
[RL step 350] reward=0.5859 adv=+0.4105 gamma=1.90e-04
[Step 350] CE/token (EMA): 1.760 | Contrast[mask]: 0.000 | RL: -157.955 | Reward: 0.5859
[Step 360] CE/token (EMA): 1.896 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.756 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.698 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.693 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'hopeful'
[RL sample] GEN: 'hopeful and hopeful for the future'
[RL step 400] reward=0.4844 adv=+0.2679 gamma=1.90e-04
[Step 400] CE/token (EMA): 1.598 | Contrast[mask]: 0.000 | RL: -103.039 | Reward: 0.4844
[Step 410] CE/token (EMA): 1.694 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.824 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.899 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 2.049 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'prepared'
[RL sample] GEN: 'anticipating the anticipation of the trip'
[RL step 450] reward=0.4609 adv=+0.2177 gamma=1.90e-04
[Step 450] CE/token (EMA): 1.987 | Contrast[mask]: 0.000 | RL: -83.724 | Reward: 0.4609
[Step 460] CE/token (EMA): 1.912 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.829 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.912 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.795 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited and anticipating the exciting and'
[RL step 500] reward=0.5000 adv=+0.2350 gamma=1.90e-04
[Step 500] CE/token (EMA): 1.883 | Contrast[mask]: 0.000 | RL: -90.402 | Reward: 0.5000
[Step 510] CE/token (EMA): 1.815 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.708 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.859 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.844 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anticipating'
[RL sample] GEN: 'excited and hopeful\n\nI can'
[RL step 550] reward=0.5703 adv=+0.2818 gamma=1.90e-04
[Step 550] CE/token (EMA): 1.772 | Contrast[mask]: 0.000 | RL: -108.391 | Reward: 0.5703
[Step 560] CE/token (EMA): 1.996 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.945 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.830 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.731 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'lonely'
[RL sample] GEN: 'lonely and lonely\nI wish'
[RL step 600] reward=0.5781 adv=+0.2614 gamma=1.90e-04
[Step 600] CE/token (EMA): 1.747 | Contrast[mask]: 0.000 | RL: -100.490 | Reward: 0.5781
[Step 610] CE/token (EMA): 1.728 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.786 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.714 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.817 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anxious and nervous\nContent:'
[RL step 650] reward=0.4062 adv=+0.0634 gamma=1.90e-04
[Step 650] CE/token (EMA): 1.733 | Contrast[mask]: 0.000 | RL: -24.388 | Reward: 0.4062
[Step 660] CE/token (EMA): 1.626 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.489 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.630 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.697 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'excitedly anticipating the new,'
[RL step 700] reward=0.4531 adv=+0.1039 gamma=1.90e-04
[Step 700] CE/token (EMA): 1.796 | Contrast[mask]: 0.000 | RL: -39.975 | Reward: 0.4531
[Step 710] CE/token (EMA): 1.651 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.766 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.708 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.647 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5300 | best=0.5300 @ epoch 1
[RL sample] REF: 'jealous'
[RL sample] GEN: 'annoyed and disappointed with my mother'
[RL step 750] reward=0.5000 adv=+0.1404 gamma=1.90e-04
[Step 750] CE/token (EMA): 1.655 | Contrast[mask]: 0.000 | RL: -54.064 | Reward: 0.5000
[Step 760] CE/token (EMA): 1.481 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.440 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.544 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.539 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 800] reward=0.6016 adv=+0.2279 gamma=1.90e-04
[Step 800] CE/token (EMA): 1.600 | Contrast[mask]: 0.000 | RL: -87.697 | Reward: 0.6016
[Step 810] CE/token (EMA): 1.569 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.450 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.388 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.315 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 850] reward=0.5312 adv=+0.1348 gamma=1.90e-04
[Step 850] CE/token (EMA): 1.354 | Contrast[mask]: 0.000 | RL: -51.829 | Reward: 0.5312
[Step 860] CE/token (EMA): 1.448 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.517 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.576 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.600 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'angry and disgusted with my guilty'
[RL step 900] reward=0.4609 adv=+0.0510 gamma=1.90e-04
[Step 900] CE/token (EMA): 1.616 | Contrast[mask]: 0.000 | RL: -19.619 | Reward: 0.4609
[Step 910] CE/token (EMA): 1.620 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.483 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.364 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.514 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'devastated and devastated.\n\n| devastated'
[RL step 950] reward=0.4141 adv=-0.0009 gamma=1.90e-04
[Step 950] CE/token (EMA): 1.477 | Contrast[mask]: 0.000 | RL: 0.362 | Reward: 0.4141
[Step 960] CE/token (EMA): 1.493 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.524 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.534 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.565 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud because my dad stopped drinking'
[RL step 1000] reward=0.5547 adv=+0.1398 gamma=1.90e-04
[Step 1000] CE/token (EMA): 1.577 | Contrast[mask]: 0.000 | RL: -53.767 | Reward: 0.5547
[Step 1010] CE/token (EMA): 1.601 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.614 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.481 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.410 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disgusted'
[RL sample] GEN: 'disgusted disgusted disgusted disgusted disgusted disgusted'
[RL step 1050] reward=0.6328 adv=+0.2039 gamma=1.90e-04
[Step 1050] CE/token (EMA): 1.476 | Contrast[mask]: 0.000 | RL: -78.434 | Reward: 0.6328
[Step 1060] CE/token (EMA): 1.554 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.622 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.509 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.558 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'nostalgic'
[RL sample] GEN: 'nostalgic and sentimental.\n\nThe nostalgic'
[RL step 1100] reward=0.4766 adv=+0.0273 gamma=1.90e-04
[Step 1100] CE/token (EMA): 1.579 | Contrast[mask]: 0.000 | RL: -10.496 | Reward: 0.4766
[Step 1110] CE/token (EMA): 1.583 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.478 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.594 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.510 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sentimental'
[RL sample] GEN: 'sentimental and sentimental.\n\nSad and'
[RL step 1150] reward=0.5156 adv=+0.0636 gamma=1.90e-04
[Step 1150] CE/token (EMA): 1.488 | Contrast[mask]: 0.000 | RL: -24.479 | Reward: 0.5156
[Step 1160] CE/token (EMA): 1.502 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.502 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.562 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.583 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'confident'
[RL sample] GEN: 'prepared, prepared, prepared,'
[RL step 1200] reward=0.4531 adv=-0.0052 gamma=1.90e-04
[Step 1200] CE/token (EMA): 1.404 | Contrast[mask]: 0.000 | RL: 2.018 | Reward: 0.4531
[Step 1210] CE/token (EMA): 1.575 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.573 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.595 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.562 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty and ashamed.\n\nSad and'
[RL step 1250] reward=0.5703 adv=+0.1125 gamma=1.90e-04
[Step 1250] CE/token (EMA): 1.603 | Contrast[mask]: 0.000 | RL: -43.266 | Reward: 0.5703
[Step 1260] CE/token (EMA): 1.555 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.474 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.463 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.526 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'jealous'
[RL sample] GEN: 'confident and proud\n\nI feel'
[RL step 1300] reward=0.5781 adv=+0.1090 gamma=1.90e-04
[Step 1300] CE/token (EMA): 1.516 | Contrast[mask]: 0.000 | RL: -41.939 | Reward: 0.5781
[Step 1310] CE/token (EMA): 1.613 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.647 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.541 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.568 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited and excited for the exciting'
[RL step 1350] reward=0.4609 adv=-0.0191 gamma=1.90e-04
[Step 1350] CE/token (EMA): 1.544 | Contrast[mask]: 0.000 | RL: 7.333 | Reward: 0.4609
[Step 1360] CE/token (EMA): 1.394 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.573 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.740 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.566 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'grateful and caring, caring for'
[RL step 1400] reward=0.4688 adv=-0.0093 gamma=1.90e-04
[Step 1400] CE/token (EMA): 1.632 | Contrast[mask]: 0.000 | RL: 3.594 | Reward: 0.4688
[Step 1410] CE/token (EMA): 1.631 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.560 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.578 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.427 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'afraid'
[RL sample] GEN: 'terrified, terrified, terrified,'
[RL step 1450] reward=0.4375 adv=-0.0397 gamma=1.90e-04
[Step 1450] CE/token (EMA): 1.404 | Contrast[mask]: 0.000 | RL: 15.252 | Reward: 0.4375
[Step 1460] CE/token (EMA): 1.372 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.397 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.341 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.465 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified, terrified, afraid, | angry and angry with my son | excited, anticipating the exciting and | furious and angry with my son
[ValMetric epoch 2] accuracy=0.4950 | best=0.5300 @ epoch 1
[RL sample] REF: 'annoyed'
[RL sample] GEN: 'annoyed and annoyed with my boyfriend'
[RL step 1500] reward=0.6328 adv=+0.1596 gamma=1.90e-04
[Step 1500] CE/token (EMA): 1.519 | Contrast[mask]: 0.000 | RL: -61.370 | Reward: 0.6328
[Step 1510] CE/token (EMA): 1.348 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.428 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.422 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.421 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'joyful'
[RL sample] GEN: 'joyful and joyful.\n\nSad and'
[RL step 1550] reward=0.5938 adv=+0.1046 gamma=1.90e-04
[Step 1550] CE/token (EMA): 1.554 | Contrast[mask]: 0.000 | RL: -40.222 | Reward: 0.5938
[Step 1560] CE/token (EMA): 1.481 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.438 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.501 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.500 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'proud and impressed with the beautiful'
[RL step 1600] reward=0.4297 adv=-0.0699 gamma=1.90e-04
[Step 1600] CE/token (EMA): 1.530 | Contrast[mask]: 0.000 | RL: 26.889 | Reward: 0.4297
[Step 1610] CE/token (EMA): 1.473 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.427 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.346 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.388 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'caring'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 1650] reward=0.4219 adv=-0.0707 gamma=1.90e-04
[Step 1650] CE/token (EMA): 1.465 | Contrast[mask]: 0.000 | RL: 27.221 | Reward: 0.4219
[Step 1660] CE/token (EMA): 1.403 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.491 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.416 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.423 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'embarrassed'
[RL sample] GEN: 'embarrassed and ashamed.\n\n embarrassed and'
[RL step 1700] reward=0.5781 adv=+0.0926 gamma=1.90e-04
[Step 1700] CE/token (EMA): 1.360 | Contrast[mask]: 0.000 | RL: -35.594 | Reward: 0.5781
[Step 1710] CE/token (EMA): 1.323 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.281 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.274 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10874.04it/s]
Map: 100%|██████████| 6000/6000 [00:00<00:00, 10122.09 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 8105.72 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7640.59 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8482.25 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 05B repl n=6000 (s53)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10493.63it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 10.206 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 9.947 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 9.376 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 8.295 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.342 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 6.405 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 5.445 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 4.750 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.221 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.629 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 3.350 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 3.211 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.154 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 3.074 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.912 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.862 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.706 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.493 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.218 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.261 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.193 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.138 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.229 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.157 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.099 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 2.065 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 2.046 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.011 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.846 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.776 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.916 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.998 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 2.101 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.929 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.954 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.932 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.958 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.815 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.932 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.862 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.772 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.795 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.797 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.919 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.936 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.759 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.895 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.817 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.897 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.791 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.823 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.840 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.722 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.738 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.781 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.771 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.825 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.822 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.752 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.816 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.773 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.600 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.812 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.949 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.780 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.836 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.761 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.726 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.809 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.653 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.626 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.585 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.579 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.536 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.676 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.4950 | best=0.4950 @ epoch 1
[Step 750] CE/token (EMA): 1.686 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.562 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.624 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.673 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.645 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.763 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.676 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.662 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.699 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.716 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.717 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.648 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.570 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.513 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.562 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.667 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.602 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.661 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.614 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.622 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.563 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.560 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.544 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.563 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.627 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.685 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.534 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.513 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.470 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.464 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.405 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.566 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.589 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.639 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.561 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.555 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.539 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.400 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.393 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.429 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.395 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.329 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.384 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.433 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.418 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.428 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.496 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.510 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.443 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.475 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.494 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.499 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.612 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.526 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.447 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.476 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.400 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.446 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.366 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.625 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.576 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.577 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.478 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.502 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.502 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.454 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.635 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.643 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.547 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.485 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.387 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.483 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.601 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.539 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified, terrified, terrified, | terrified, afraid, terrified, | excited, anticipating the exciting adventure | embarrassed and ashamed.

| embarrassed
[ValMetric epoch 2] accuracy=0.5450 | best=0.5450 @ epoch 2
[Step 1500] CE/token (EMA): 1.454 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.439 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.508 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.530 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.495 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.381 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.203 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.285 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.291 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.297 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.188 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.384 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.402 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.401 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.423 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.355 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.378 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.401 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.376 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.464 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.515 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.450 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.426 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.301 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.385 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.400 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.357 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.312 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.323 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.422 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.353 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.384 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.430 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.433 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.462 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.403 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.279 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.159 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.216 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.208 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.285 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.382 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.316 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.277 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.382 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.402 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.512 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.486 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.370 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.323 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.268 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.399 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.420 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.433 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.487 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.433 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.326 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.447 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.421 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.455 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.349 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.258 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.349 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.267 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.266 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.286 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.413 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.325 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.283 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.277 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.212 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.140 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.140 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.189 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified, terrified, terrified, | angry, furious, furious, | excited, anticipating the exciting journey | embarrassed and ashamed.

| embarrassed
[ValMetric epoch 3] accuracy=0.5200 | best=0.5450 @ epoch 2
[Step 2250] CE/token (EMA): 1.319 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9945.85it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 10.206 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 9.951 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 9.376 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 8.295 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.359 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 6.429 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 5.472 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 4.779 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.245 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.649 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 3.374 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 3.243 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.181 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 3.098 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.921 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.892 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.724 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.558 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.285 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.318 | Contrast[mask]: 0.667 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.212 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.164 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.255 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.153 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.098 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 2.090 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 2.080 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.033 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.867 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.763 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.883 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.974 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 2.063 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.926 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.958 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.961 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.981 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.861 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.955 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.851 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.770 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.764 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.794 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.956 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.963 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.768 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.868 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.818 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.908 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.813 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.853 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.835 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.739 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.748 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.791 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.794 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.841 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.852 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.791 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.831 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.782 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.586 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.824 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.971 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.789 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.850 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.791 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.731 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.777 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.669 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.648 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.606 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.594 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.537 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.703 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.4900 | best=0.4900 @ epoch 1
[Step 750] CE/token (EMA): 1.685 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.565 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.645 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.660 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.621 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.773 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.693 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.651 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.715 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.715 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.713 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.671 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.609 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.537 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.585 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.665 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.603 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.674 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.643 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.656 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.598 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.575 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.543 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.513 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.560 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.644 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.706 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.561 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.536 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.491 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.459 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.409 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.585 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.583 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.633 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.571 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.555 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.548 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.408 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.405 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.436 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.394 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.346 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.375 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.421 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.394 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.404 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.473 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.470 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.411 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.464 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.480 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.502 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.603 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.515 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.450 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.466 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.409 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.448 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.321 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.607 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.560 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.578 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.462 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.501 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.494 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.451 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.613 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.631 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.532 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.499 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.396 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.509 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.584 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.510 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified, terrified afraid, terrified | terrified, afraid, afraid, | excited, prepared for the adventure | embarrassed, ashamed, embarrassed,
[ValMetric epoch 2] accuracy=0.5850 | best=0.5850 @ epoch 2
[Step 1500] CE/token (EMA): 1.432 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.440 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.516 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.514 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.501 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.405 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.211 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.305 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.304 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.298 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.183 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.391 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.376 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.376 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.396 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.355 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.391 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.383 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.402 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.474 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.504 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.467 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.433 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.318 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.410 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.406 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.342 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.328 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.322 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.420 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.346 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.369 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.415 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.432 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.480 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.428 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.312 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.184 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.252 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.207 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.226 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.279 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.365 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.287 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.256 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.385 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.428 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.533 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.481 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.392 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.336 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.287 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.405 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.412 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.441 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.509 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.446 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.339 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.475 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.444 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.464 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.373 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.302 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.370 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.274 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.258 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.285 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.438 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.316 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.284 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.308 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.233 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.159 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.120 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.188 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified, terrified afraid afraid afraid | angry angry angry angry angry angry | excited, anticipating the exciting journey | embarrassed and ashamed.

 embarrassed and
[ValMetric epoch 3] accuracy=0.5500 | best=0.5850 @ epoch 2
[Step 2250] CE/token (EMA): 1.313 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9700.83it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 3.873e-05
[RL sample] REF: 'prepared'
[RL sample] GEN: '14\n 8'
[RL step 0] reward=0.0391 adv=+0.0391 gamma=3.87e-05
[Step 0] CE/token (EMA): 10.206 | Contrast[mask]: 0.000 | RL: -3.062 | Reward: 0.0391

[Step 10] CE/token (EMA): 9.949 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 9.371 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 8.291 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.346 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'fat.\n\nThe way to be'
[RL step 50] reward=0.2109 adv=+0.2070 gamma=3.87e-05
[Step 50] CE/token (EMA): 6.410 | Contrast[mask]: 0.000 | RL: -16.228 | Reward: 0.2109
[Step 60] CE/token (EMA): 5.453 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 4.758 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.229 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.625 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: "sad\n\nGiven the user's"
[RL step 100] reward=0.3906 adv=+0.3660 gamma=3.87e-05
[Step 100] CE/token (EMA): 3.356 | Contrast[mask]: 0.000 | RL: -28.676 | Reward: 0.3906
[Step 110] CE/token (EMA): 3.218 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 3.163 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 3.085 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.912 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'grieving.\nTask: writing a'
[RL step 150] reward=0.3359 adv=+0.2747 gamma=3.87e-05
[Step 150] CE/token (EMA): 2.871 | Contrast[mask]: 0.000 | RL: -21.535 | Reward: 0.3359
[Step 160] CE/token (EMA): 2.720 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.540 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.248 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.291 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'annoyed, annoyed, annoyed,'
[RL step 200] reward=0.3672 adv=+0.2785 gamma=3.87e-05
[Step 200] CE/token (EMA): 2.207 | Contrast[mask]: 0.000 | RL: -21.825 | Reward: 0.3672
[Step 210] CE/token (EMA): 2.181 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.254 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.153 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.080 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'relieved and hopeful about the possibility'
[RL step 250] reward=0.3594 adv=+0.2428 gamma=3.87e-05
[Step 250] CE/token (EMA): 2.071 | Contrast[mask]: 0.000 | RL: -19.037 | Reward: 0.3594
[Step 260] CE/token (EMA): 2.086 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 2.021 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.857 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.770 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'terrified, terrified, terrified,'
[RL step 300] reward=0.5078 adv=+0.3670 gamma=3.87e-05
[Step 300] CE/token (EMA): 1.884 | Contrast[mask]: 0.000 | RL: -28.774 | Reward: 0.5078
[Step 310] CE/token (EMA): 1.987 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 2.076 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.917 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.905 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'surprised'
[RL sample] GEN: 'disappointed, disappointed, disappointed,'
[RL step 350] reward=0.5469 adv=+0.3694 gamma=3.87e-05
[Step 350] CE/token (EMA): 1.908 | Contrast[mask]: 0.000 | RL: -28.949 | Reward: 0.5469
[Step 360] CE/token (EMA): 1.938 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.814 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.936 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.870 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'hopeful'
[RL sample] GEN: 'hopeful, hopeful, hopeful,'
[RL step 400] reward=0.4141 adv=+0.1996 gamma=3.87e-05
[Step 400] CE/token (EMA): 1.800 | Contrast[mask]: 0.000 | RL: -15.647 | Reward: 0.4141
[Step 410] CE/token (EMA): 1.788 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.771 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.900 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.935 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'prepared'
[RL sample] GEN: 'prepared, anticipating the trip,'
[RL step 450] reward=0.5000 adv=+0.2656 gamma=3.87e-05
[Step 450] CE/token (EMA): 1.767 | Contrast[mask]: 0.000 | RL: -20.819 | Reward: 0.5000
[Step 460] CE/token (EMA): 1.914 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.857 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.865 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.826 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited for the fun-filled experience'
[RL step 500] reward=0.4922 adv=+0.2312 gamma=3.87e-05
[Step 500] CE/token (EMA): 1.855 | Contrast[mask]: 0.000 | RL: -18.117 | Reward: 0.4922
[Step 510] CE/token (EMA): 1.859 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.760 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.748 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.841 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anticipating'
[RL sample] GEN: 'excited, joyful, joyful,'
[RL step 550] reward=0.5469 adv=+0.2628 gamma=3.87e-05
[Step 550] CE/token (EMA): 1.771 | Contrast[mask]: 0.000 | RL: -20.589 | Reward: 0.5469
[Step 560] CE/token (EMA): 1.836 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.844 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.788 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.808 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'lonely'
[RL sample] GEN: 'jealous, jealous, jealous,'
[RL step 600] reward=0.5859 adv=+0.2756 gamma=3.87e-05
[Step 600] CE/token (EMA): 1.752 | Contrast[mask]: 0.000 | RL: -21.586 | Reward: 0.5859
[Step 610] CE/token (EMA): 1.596 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.818 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.933 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.812 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anxious, prepared, prepared for'
[RL step 650] reward=0.4688 adv=+0.1308 gamma=3.87e-05
[Step 650] CE/token (EMA): 1.828 | Contrast[mask]: 0.000 | RL: -10.254 | Reward: 0.4688
[Step 660] CE/token (EMA): 1.778 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.713 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.788 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.655 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'excited, excited to return to'
[RL step 700] reward=0.4453 adv=+0.0943 gamma=3.87e-05
[Step 700] CE/token (EMA): 1.627 | Contrast[mask]: 0.000 | RL: -7.391 | Reward: 0.4453
[Step 710] CE/token (EMA): 1.549 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.545 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.501 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.640 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5000 | best=0.5000 @ epoch 1
[RL sample] REF: 'jealous'
[RL sample] GEN: 'annoyed, jealous, jealous,'
[RL step 750] reward=0.5156 adv=+0.1552 gamma=3.87e-05
[Step 750] CE/token (EMA): 1.692 | Contrast[mask]: 0.000 | RL: -12.158 | Reward: 0.5156
[Step 760] CE/token (EMA): 1.562 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.673 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.686 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.632 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'disappointed.\n\nI missed my friend'
[RL step 800] reward=0.6250 adv=+0.2490 gamma=3.87e-05
[Step 800] CE/token (EMA): 1.791 | Contrast[mask]: 0.000 | RL: -19.521 | Reward: 0.6250
[Step 810] CE/token (EMA): 1.705 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.666 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.695 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.720 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty, guilty, guilty.'
[RL step 850] reward=0.4922 adv=+0.0913 gamma=3.87e-05
[Step 850] CE/token (EMA): 1.731 | Contrast[mask]: 0.000 | RL: -7.157 | Reward: 0.4922
[Step 860] CE/token (EMA): 1.677 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.611 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.543 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.594 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty, ashamed, guilty,'
[RL step 900] reward=0.4297 adv=+0.0197 gamma=3.87e-05
[Step 900] CE/token (EMA): 1.644 | Contrast[mask]: 0.000 | RL: -1.543 | Reward: 0.4297
[Step 910] CE/token (EMA): 1.541 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.645 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.603 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.616 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'devastated, devastated, devastated.'
[RL step 950] reward=0.4297 adv=+0.0177 gamma=3.87e-05
[Step 950] CE/token (EMA): 1.555 | Contrast[mask]: 0.000 | RL: -1.389 | Reward: 0.4297
[Step 960] CE/token (EMA): 1.528 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.501 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.558 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud.\n\n| proud\n\n|'
[RL step 1000] reward=0.5781 adv=+0.1644 gamma=3.87e-05
[Step 1000] CE/token (EMA): 1.646 | Contrast[mask]: 0.000 | RL: -12.891 | Reward: 0.5781
[Step 1010] CE/token (EMA): 1.682 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.548 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.518 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.479 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disgusted'
[RL sample] GEN: 'disgusted, disgusted.\n\n| disgust'
[RL step 1050] reward=0.6484 adv=+0.2183 gamma=3.87e-05
[Step 1050] CE/token (EMA): 1.469 | Contrast[mask]: 0.000 | RL: -17.101 | Reward: 0.6484
[Step 1060] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.563 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.539 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.603 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'nostalgic'
[RL sample] GEN: 'nostalgic, sentimental.\n\n| sentimental'
[RL step 1100] reward=0.4297 adv=-0.0223 gamma=3.87e-05
[Step 1100] CE/token (EMA): 1.572 | Contrast[mask]: 0.000 | RL: 1.749 | Reward: 0.4297
[Step 1110] CE/token (EMA): 1.546 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.524 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.381 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.390 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sentimental'
[RL sample] GEN: 'sentimental, sentimental, sentimental.'
[RL step 1150] reward=0.5078 adv=+0.0580 gamma=3.87e-05
[Step 1150] CE/token (EMA): 1.419 | Contrast[mask]: 0.000 | RL: -4.548 | Reward: 0.5078
[Step 1160] CE/token (EMA): 1.382 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.338 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.394 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.436 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'confident'
[RL sample] GEN: 'prepared, prepared for the anticipated'
[RL step 1200] reward=0.4453 adv=-0.0103 gamma=3.87e-05
[Step 1200] CE/token (EMA): 1.386 | Contrast[mask]: 0.000 | RL: 0.804 | Reward: 0.4453
[Step 1210] CE/token (EMA): 1.385 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.455 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.494 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.430 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty, ashamed, guilty,'
[RL step 1250] reward=0.5781 adv=+0.1236 gamma=3.87e-05
[Step 1250] CE/token (EMA): 1.489 | Contrast[mask]: 0.000 | RL: -9.681 | Reward: 0.5781
[Step 1260] CE/token (EMA): 1.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.497 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.587 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.488 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'jealous'
[RL sample] GEN: 'proud and proud enough to proud'
[RL step 1300] reward=0.5391 adv=+0.0722 gamma=3.87e-05
[Step 1300] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: -5.652 | Reward: 0.5391
[Step 1310] CE/token (EMA): 1.431 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.363 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.407 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.337 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited for the trip.\n\n|'
[RL step 1350] reward=0.4688 adv=-0.0054 gamma=3.87e-05
[Step 1350] CE/token (EMA): 1.606 | Contrast[mask]: 0.000 | RL: 0.421 | Reward: 0.4688
[Step 1360] CE/token (EMA): 1.547 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.571 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.494 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.515 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'caring, caring enough to save'
[RL step 1400] reward=0.4688 adv=-0.0048 gamma=3.87e-05
[Step 1400] CE/token (EMA): 1.499 | Contrast[mask]: 0.000 | RL: 0.379 | Reward: 0.4688
[Step 1410] CE/token (EMA): 1.437 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.615 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.624 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.546 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'afraid'
[RL sample] GEN: 'afraid.\n\n#11-'
[RL step 1450] reward=0.5156 adv=+0.0425 gamma=3.87e-05
[Step 1450] CE/token (EMA): 1.496 | Contrast[mask]: 0.000 | RL: -3.333 | Reward: 0.5156
[Step 1460] CE/token (EMA): 1.372 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.481 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.577 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.494 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified.

| terrified, terrified | terrified.

| afraid.

| | excited for the exciting adventure. | terrified, embarrassed, and ashamed
[ValMetric epoch 2] accuracy=0.5750 | best=0.5750 @ epoch 2
[RL sample] REF: 'annoyed'
[RL sample] GEN: 'annoyed.\n\nContextually, annoyed'
[RL step 1500] reward=0.6094 adv=+0.1320 gamma=3.87e-05
[Step 1500] CE/token (EMA): 1.505 | Contrast[mask]: 0.000 | RL: -10.345 | Reward: 0.6094
[Step 1510] CE/token (EMA): 1.461 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.492 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.542 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.509 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'joyful'
[RL sample] GEN: 'joyful, joyful, joyful.'
[RL step 1550] reward=0.5469 adv=+0.0563 gamma=3.87e-05
[Step 1550] CE/token (EMA): 1.374 | Contrast[mask]: 0.000 | RL: -4.413 | Reward: 0.5469
[Step 1560] CE/token (EMA): 1.184 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.273 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.332 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.327 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'impressed with the confident and confident'
[RL step 1600] reward=0.4766 adv=-0.0196 gamma=3.87e-05
[Step 1600] CE/token (EMA): 1.220 | Contrast[mask]: 0.000 | RL: 1.538 | Reward: 0.4766
[Step 1610] CE/token (EMA): 1.414 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.429 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.408 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.420 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'caring'
[RL sample] GEN: 'guilty, guilty guilty guilty guilty'
[RL step 1650] reward=0.4453 adv=-0.0489 gamma=3.87e-05
[Step 1650] CE/token (EMA): 1.395 | Contrast[mask]: 0.000 | RL: 3.834 | Reward: 0.4453
[Step 1660] CE/token (EMA): 1.413 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.396 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.397 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.445 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'embarrassed'
[RL sample] GEN: 'embarrassed and ashamed.\n\nContexts'
[RL step 1700] reward=0.5625 adv=+0.0732 gamma=3.87e-05
[Step 1700] CE/token (EMA): 1.504 | Contrast[mask]: 0.000 | RL: -5.731 | Reward: 0.5625
[Step 1710] CE/token (EMA): 1.438 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.415 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.415 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.472 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed and sad disappointed.\n\nWith'

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10561.05it/s]
Map: 100%|██████████| 6000/6000 [00:00<00:00, 9922.06 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 8133.15 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7647.50 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8321.65 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 05B repl n=6000 (s54)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9845.31it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 10.274 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 10.529 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 10.127 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 9.310 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.891 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 6.730 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 5.668 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 5.100 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.377 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.929 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 3.532 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 3.252 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.935 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.757 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.655 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.576 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.538 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.506 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.436 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.329 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.255 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.372 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.166 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.093 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.098 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 2.212 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 2.190 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.989 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.954 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.854 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.829 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.805 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.984 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.999 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 2.003 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.938 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 1.950 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.933 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.799 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.783 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.765 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.774 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.738 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.718 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.733 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.753 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.687 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.789 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.792 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.736 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.751 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.731 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.746 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.833 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.764 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.653 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.707 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.626 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.653 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.549 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.842 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.862 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.840 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.752 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.754 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.764 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.714 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.873 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.883 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.741 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.706 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.559 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.685 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.824 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.743 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.4950 | best=0.4950 @ epoch 1
[Step 750] CE/token (EMA): 1.738 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.711 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.754 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.765 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.701 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.602 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.437 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.514 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.508 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.382 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.657 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.628 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.569 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.601 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.576 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.601 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.599 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.602 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.676 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.741 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.665 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.700 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.559 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.626 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.640 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.575 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.526 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.553 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.627 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.535 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.577 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.590 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.644 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.681 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.595 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.488 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.373 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.421 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.464 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.475 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.563 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.604 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.537 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.506 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.611 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.643 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.756 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.708 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.621 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.540 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.500 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.560 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.557 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.647 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.714 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.657 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.493 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.657 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.625 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.649 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.554 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.490 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.508 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.442 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.456 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.459 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.643 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.520 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.465 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.476 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.459 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.358 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.385 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.440 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified

[害怕

害怕 | angry.

| angry

| | excited

When excited, excited | disgusted.

| disgusted

|
[ValMetric epoch 2] accuracy=0.5350 | best=0.5350 @ epoch 2
[Step 1500] CE/token (EMA): 1.484 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.431 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.449 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.501 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.382 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.489 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.355 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.332 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.379 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.382 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.488 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.600 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.498 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.484 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.419 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.338 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.325 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.358 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.422 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.320 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.402 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.445 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.514 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.445 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.363 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.289 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.401 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.411 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.486 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.434 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.466 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.496 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.455 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.323 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.389 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.324 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.351 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.398 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.408 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.489 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.473 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.358 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.525 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.375 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.332 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.281 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.303 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.407 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.314 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.365 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.286 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.455 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.499 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.470 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.388 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.417 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.381 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.320 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.289 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.361 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.359 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.275 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.276 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.245 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.342 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.370 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.283 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.238 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.251 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.228 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.229 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.291 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.378 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.283 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.300 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified.

## afraid

## | terrified.

### afraid

### | excited

## excited

## | terrified.

### terrified

###
[ValMetric epoch 3] accuracy=0.5500 | best=0.5500 @ epoch 3
[Step 2250] CE/token (EMA): 1.397 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 2260] CE/token (EMA): 1.301 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9778.11it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 10.274 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 10.534 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 10.128 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 9.313 | Contrast[mask]: 0.691 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.906 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 6.748 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 5.677 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 5.109 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.383 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.940 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 100] CE/token (EMA): 3.543 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 3.263 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.960 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.783 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.691 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 150] CE/token (EMA): 2.568 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 160] CE/token (EMA): 2.553 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.536 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.458 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.324 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 200] CE/token (EMA): 2.217 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 210] CE/token (EMA): 2.350 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.158 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.057 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.072 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 250] CE/token (EMA): 2.182 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 260] CE/token (EMA): 2.183 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.978 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.941 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.829 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 300] CE/token (EMA): 1.817 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 310] CE/token (EMA): 1.769 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.956 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.924 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.959 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 350] CE/token (EMA): 1.959 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 360] CE/token (EMA): 2.039 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 2.042 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.897 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.862 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 400] CE/token (EMA): 1.825 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 410] CE/token (EMA): 1.789 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.752 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.714 | Contrast[mask]: 0.667 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.698 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 450] CE/token (EMA): 1.677 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 460] CE/token (EMA): 1.664 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.777 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.778 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.717 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 500] CE/token (EMA): 1.755 | Contrast[mask]: 0.666 | RL: 0.000 | Reward: 0.0000
[Step 510] CE/token (EMA): 1.739 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.756 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.856 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.781 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 550] CE/token (EMA): 1.669 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 560] CE/token (EMA): 1.702 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.610 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.624 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.559 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 600] CE/token (EMA): 1.821 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 610] CE/token (EMA): 1.776 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.825 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.735 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.740 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 650] CE/token (EMA): 1.736 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 660] CE/token (EMA): 1.690 | Contrast[mask]: 0.665 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.844 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.816 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.725 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 700] CE/token (EMA): 1.678 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 710] CE/token (EMA): 1.552 | Contrast[mask]: 0.660 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.660 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.749 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.704 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.4700 | best=0.4700 @ epoch 1
[Step 750] CE/token (EMA): 1.677 | Contrast[mask]: 0.670 | RL: 0.000 | Reward: 0.0000
[Step 760] CE/token (EMA): 1.697 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.722 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.709 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.675 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 800] CE/token (EMA): 1.565 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 810] CE/token (EMA): 1.413 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.467 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.504 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.497 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 850] CE/token (EMA): 1.391 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 860] CE/token (EMA): 1.659 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.612 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.552 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.577 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 900] CE/token (EMA): 1.518 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 910] CE/token (EMA): 1.573 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.562 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.593 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.664 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 950] CE/token (EMA): 1.709 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 960] CE/token (EMA): 1.624 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.633 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.564 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.622 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1000] CE/token (EMA): 1.624 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1010] CE/token (EMA): 1.538 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.506 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.507 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.551 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1050] CE/token (EMA): 1.543 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1060] CE/token (EMA): 1.581 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.620 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.628 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.646 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 1100] CE/token (EMA): 1.557 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1110] CE/token (EMA): 1.440 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.344 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.403 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.431 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1150] CE/token (EMA): 1.427 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1160] CE/token (EMA): 1.527 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.580 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.508 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.461 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 1200] CE/token (EMA): 1.597 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 1210] CE/token (EMA): 1.591 | Contrast[mask]: 0.665 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.685 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.638 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.570 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1250] CE/token (EMA): 1.495 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1260] CE/token (EMA): 1.465 | Contrast[mask]: 0.664 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.558 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.586 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.641 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1300] CE/token (EMA): 1.706 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 1310] CE/token (EMA): 1.638 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.480 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.634 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.606 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1350] CE/token (EMA): 1.620 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1360] CE/token (EMA): 1.480 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.412 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.468 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.426 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1400] CE/token (EMA): 1.442 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1410] CE/token (EMA): 1.433 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.567 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.456 | Contrast[mask]: 0.672 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.421 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1450] CE/token (EMA): 1.444 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1460] CE/token (EMA): 1.414 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.320 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.329 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.416 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified

 embarrassed afraid anxious anxious | angry angry angry angry angry angry | excited anticipating the exciting event | disgusted disgusted disgusted disgusted disgusted disgusted
[ValMetric epoch 2] accuracy=0.5150 | best=0.5150 @ epoch 2
[Step 1500] CE/token (EMA): 1.506 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1510] CE/token (EMA): 1.444 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.443 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.447 | Contrast[mask]: 0.671 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.350 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1550] CE/token (EMA): 1.444 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1560] CE/token (EMA): 1.310 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.302 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.348 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.343 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1600] CE/token (EMA): 1.474 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1610] CE/token (EMA): 1.564 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.482 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.484 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.413 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1650] CE/token (EMA): 1.293 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1660] CE/token (EMA): 1.290 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.327 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.385 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.309 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1700] CE/token (EMA): 1.390 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1710] CE/token (EMA): 1.421 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.453 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.414 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.354 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 1750] CE/token (EMA): 1.292 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1760] CE/token (EMA): 1.401 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1770] CE/token (EMA): 1.394 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1780] CE/token (EMA): 1.458 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1790] CE/token (EMA): 1.400 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1800] CE/token (EMA): 1.428 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1810] CE/token (EMA): 1.444 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 1820] CE/token (EMA): 1.411 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1830] CE/token (EMA): 1.265 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1840] CE/token (EMA): 1.362 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 1850] CE/token (EMA): 1.312 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 1860] CE/token (EMA): 1.376 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1870] CE/token (EMA): 1.395 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1880] CE/token (EMA): 1.429 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 1890] CE/token (EMA): 1.504 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 1900] CE/token (EMA): 1.478 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 1910] CE/token (EMA): 1.350 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1920] CE/token (EMA): 1.500 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 1930] CE/token (EMA): 1.359 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 1940] CE/token (EMA): 1.321 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 1950] CE/token (EMA): 1.285 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 1960] CE/token (EMA): 1.294 | Contrast[mask]: 0.673 | RL: 0.000 | Reward: 0.0000
[Step 1970] CE/token (EMA): 1.371 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 1980] CE/token (EMA): 1.302 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 1990] CE/token (EMA): 1.386 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 2000] CE/token (EMA): 1.294 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2010] CE/token (EMA): 1.421 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 2020] CE/token (EMA): 1.489 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2030] CE/token (EMA): 1.428 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2040] CE/token (EMA): 1.356 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2050] CE/token (EMA): 1.343 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2060] CE/token (EMA): 1.354 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2070] CE/token (EMA): 1.326 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Step 2080] CE/token (EMA): 1.266 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 2090] CE/token (EMA): 1.345 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 2100] CE/token (EMA): 1.339 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2110] CE/token (EMA): 1.262 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2120] CE/token (EMA): 1.264 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2130] CE/token (EMA): 1.218 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2140] CE/token (EMA): 1.329 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 2150] CE/token (EMA): 1.369 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 2160] CE/token (EMA): 1.286 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 2170] CE/token (EMA): 1.244 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 2180] CE/token (EMA): 1.225 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 2190] CE/token (EMA): 1.211 | Contrast[mask]: 0.674 | RL: 0.000 | Reward: 0.0000
[Step 2200] CE/token (EMA): 1.228 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 2210] CE/token (EMA): 1.304 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 2220] CE/token (EMA): 1.398 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 2230] CE/token (EMA): 1.304 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 2240] CE/token (EMA): 1.299 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified anxious prepared prepared prepared prepared | angry angry angry angry angry angry | excited excited excited excited excited excited | disgusted disgusted disgusted disgusted disgusted disgusted
[ValMetric epoch 3] accuracy=0.5350 | best=0.5350 @ epoch 3

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9984.80it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 9.748e-05
[RL sample] REF: 'prepared'
[RL sample] GEN: '1.64'
[RL step 0] reward=0.0156 adv=+0.0156 gamma=9.75e-05
[Step 0] CE/token (EMA): 10.274 | Contrast[mask]: 0.000 | RL: -3.082 | Reward: 0.0156

[Step 10] CE/token (EMA): 10.531 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 10.131 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 9.315 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 40] CE/token (EMA): 7.899 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'fat.\nCiting and not'
[RL step 50] reward=0.2109 adv=+0.2094 gamma=9.75e-05
[Step 50] CE/token (EMA): 6.735 | Contrast[mask]: 0.000 | RL: -41.310 | Reward: 0.2109
[Step 60] CE/token (EMA): 5.666 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 70] CE/token (EMA): 5.092 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 4.377 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 3.929 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'sad.\nVerb: grieve'
[RL step 100] reward=0.3984 adv=+0.3759 gamma=9.75e-05
[Step 100] CE/token (EMA): 3.532 | Contrast[mask]: 0.000 | RL: -74.181 | Reward: 0.3984
[Step 110] CE/token (EMA): 3.273 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.964 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 130] CE/token (EMA): 2.773 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 140] CE/token (EMA): 2.654 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'grieving\nNaei:'
[RL step 150] reward=0.3828 adv=+0.3227 gamma=9.75e-05
[Step 150] CE/token (EMA): 2.578 | Contrast[mask]: 0.000 | RL: -63.660 | Reward: 0.3828
[Step 160] CE/token (EMA): 2.543 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 170] CE/token (EMA): 2.507 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 180] CE/token (EMA): 2.447 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 190] CE/token (EMA): 2.340 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'annoyed\nPresupposed purpose'
[RL step 200] reward=0.3672 adv=+0.2748 gamma=9.75e-05
[Step 200] CE/token (EMA): 2.259 | Contrast[mask]: 0.000 | RL: -54.227 | Reward: 0.3672
[Step 210] CE/token (EMA): 2.370 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 220] CE/token (EMA): 2.163 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 230] CE/token (EMA): 2.079 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 240] CE/token (EMA): 2.092 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'grateful\nEmotion: grateful'
[RL step 250] reward=0.3906 adv=+0.2708 gamma=9.75e-05
[Step 250] CE/token (EMA): 2.188 | Contrast[mask]: 0.000 | RL: -53.410 | Reward: 0.3906
[Step 260] CE/token (EMA): 2.198 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 270] CE/token (EMA): 1.989 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 280] CE/token (EMA): 1.930 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 290] CE/token (EMA): 1.877 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'terrified\nThoughts: terrified'
[RL step 300] reward=0.5234 adv=+0.3765 gamma=9.75e-05
[Step 300] CE/token (EMA): 1.847 | Contrast[mask]: 0.000 | RL: -74.276 | Reward: 0.5234
[Step 310] CE/token (EMA): 1.795 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 320] CE/token (EMA): 1.982 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 330] CE/token (EMA): 1.934 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 340] CE/token (EMA): 1.970 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'surprised'
[RL sample] GEN: 'angry\nReasons for angry'
[RL step 350] reward=0.5078 adv=+0.3232 gamma=9.75e-05
[Step 350] CE/token (EMA): 1.919 | Contrast[mask]: 0.000 | RL: -63.765 | Reward: 0.5078
[Step 360] CE/token (EMA): 1.963 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 370] CE/token (EMA): 1.920 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 380] CE/token (EMA): 1.797 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 390] CE/token (EMA): 1.777 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'hopeful'
[RL sample] GEN: 'hopeful\n\nUsing the context of'
[RL step 400] reward=0.4297 adv=+0.2128 gamma=9.75e-05
[Step 400] CE/token (EMA): 1.767 | Contrast[mask]: 0.000 | RL: -41.974 | Reward: 0.4297
[Step 410] CE/token (EMA): 1.813 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 420] CE/token (EMA): 1.752 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 430] CE/token (EMA): 1.735 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 440] CE/token (EMA): 1.719 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'prepared'
[RL sample] GEN: 'prepared for the trip\nwith'
[RL step 450] reward=0.4609 adv=+0.2228 gamma=9.75e-05
[Step 450] CE/token (EMA): 1.730 | Contrast[mask]: 0.000 | RL: -43.942 | Reward: 0.4609
[Step 460] CE/token (EMA): 1.688 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 470] CE/token (EMA): 1.786 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 480] CE/token (EMA): 1.780 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 490] CE/token (EMA): 1.716 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'anticipating the anticipation of the upcoming'
[RL step 500] reward=0.5391 adv=+0.2786 gamma=9.75e-05
[Step 500] CE/token (EMA): 1.734 | Contrast[mask]: 0.000 | RL: -54.965 | Reward: 0.5391
[Step 510] CE/token (EMA): 1.743 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 520] CE/token (EMA): 1.784 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 530] CE/token (EMA): 1.835 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 540] CE/token (EMA): 1.751 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anticipating'
[RL sample] GEN: 'excited for the pregnancy\nEm'
[RL step 550] reward=0.5234 adv=+0.2351 gamma=9.75e-05
[Step 550] CE/token (EMA): 1.656 | Contrast[mask]: 0.000 | RL: -46.368 | Reward: 0.5234
[Step 560] CE/token (EMA): 1.694 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 570] CE/token (EMA): 1.636 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 580] CE/token (EMA): 1.659 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 590] CE/token (EMA): 1.567 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'lonely'
[RL sample] GEN: 'lonely, lonely, lonely'
[RL step 600] reward=0.5703 adv=+0.2585 gamma=9.75e-05
[Step 600] CE/token (EMA): 1.855 | Contrast[mask]: 0.000 | RL: -50.986 | Reward: 0.5703
[Step 610] CE/token (EMA): 1.821 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 620] CE/token (EMA): 1.814 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 630] CE/token (EMA): 1.727 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 640] CE/token (EMA): 1.726 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'anxious and nervous\nReasoning'
[RL step 650] reward=0.4141 adv=+0.0764 gamma=9.75e-05
[Step 650] CE/token (EMA): 1.743 | Contrast[mask]: 0.000 | RL: -15.066 | Reward: 0.4141
[Step 660] CE/token (EMA): 1.684 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 670] CE/token (EMA): 1.861 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 680] CE/token (EMA): 1.861 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 690] CE/token (EMA): 1.760 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'anxious'
[RL sample] GEN: 'excited, anticipating the new place'
[RL step 700] reward=0.4688 adv=+0.1234 gamma=9.75e-05
[Step 700] CE/token (EMA): 1.702 | Contrast[mask]: 0.000 | RL: -24.364 | Reward: 0.4688
[Step 710] CE/token (EMA): 1.556 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 720] CE/token (EMA): 1.664 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 730] CE/token (EMA): 1.790 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 740] CE/token (EMA): 1.701 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.5050 | best=0.5050 @ epoch 1
[RL sample] REF: 'jealous'
[RL sample] GEN: 'angry, jealous, jealous,'
[RL step 750] reward=0.4922 adv=+0.1345 gamma=9.75e-05
[Step 750] CE/token (EMA): 1.687 | Contrast[mask]: 0.000 | RL: -26.543 | Reward: 0.4922
[Step 760] CE/token (EMA): 1.691 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 770] CE/token (EMA): 1.733 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 780] CE/token (EMA): 1.757 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 790] CE/token (EMA): 1.698 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sad'
[RL sample] GEN: 'anxious, afraid of the illness'
[RL step 800] reward=0.6250 adv=+0.2539 gamma=9.75e-05
[Step 800] CE/token (EMA): 1.599 | Contrast[mask]: 0.000 | RL: -50.094 | Reward: 0.6250
[Step 810] CE/token (EMA): 1.412 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 820] CE/token (EMA): 1.479 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 830] CE/token (EMA): 1.475 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 840] CE/token (EMA): 1.473 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty and ashamed.\nEmotion'
[RL step 850] reward=0.4922 adv=+0.0957 gamma=9.75e-05
[Step 850] CE/token (EMA): 1.350 | Contrast[mask]: 0.000 | RL: -18.877 | Reward: 0.4922
[Step 860] CE/token (EMA): 1.629 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 870] CE/token (EMA): 1.620 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 880] CE/token (EMA): 1.558 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 890] CE/token (EMA): 1.573 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'jealous, jealous jealous jealous jealous'
[RL step 900] reward=0.4688 adv=+0.0627 gamma=9.75e-05
[Step 900] CE/token (EMA): 1.537 | Contrast[mask]: 0.000 | RL: -12.367 | Reward: 0.4688
[Step 910] CE/token (EMA): 1.573 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 920] CE/token (EMA): 1.579 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 930] CE/token (EMA): 1.599 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 940] CE/token (EMA): 1.699 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'terrified'
[RL sample] GEN: 'angry, furious, furious,'
[RL step 950] reward=0.4219 adv=+0.0095 gamma=9.75e-05
[Step 950] CE/token (EMA): 1.743 | Contrast[mask]: 0.000 | RL: -1.881 | Reward: 0.4219
[Step 960] CE/token (EMA): 1.649 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 970] CE/token (EMA): 1.640 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 980] CE/token (EMA): 1.549 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 990] CE/token (EMA): 1.630 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'proud\n\nWith affection, caring'
[RL step 1000] reward=0.5078 adv=+0.0945 gamma=9.75e-05
[Step 1000] CE/token (EMA): 1.621 | Contrast[mask]: 0.000 | RL: -18.646 | Reward: 0.5078
[Step 1010] CE/token (EMA): 1.524 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1020] CE/token (EMA): 1.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1030] CE/token (EMA): 1.562 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1040] CE/token (EMA): 1.593 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disgusted'
[RL sample] GEN: 'disgusted, disgusted, disgusted,'
[RL step 1050] reward=0.5547 adv=+0.1319 gamma=9.75e-05
[Step 1050] CE/token (EMA): 1.523 | Contrast[mask]: 0.000 | RL: -26.017 | Reward: 0.5547
[Step 1060] CE/token (EMA): 1.568 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1070] CE/token (EMA): 1.594 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1080] CE/token (EMA): 1.678 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1090] CE/token (EMA): 1.702 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'nostalgic'
[RL sample] GEN: 'nostalgic.\n\nthinking nostalgic\n\nthinking'
[RL step 1100] reward=0.4844 adv=+0.0484 gamma=9.75e-05
[Step 1100] CE/token (EMA): 1.615 | Contrast[mask]: 0.000 | RL: -9.556 | Reward: 0.4844
[Step 1110] CE/token (EMA): 1.503 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1120] CE/token (EMA): 1.361 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1130] CE/token (EMA): 1.392 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1140] CE/token (EMA): 1.409 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'sentimental'
[RL sample] GEN: 'sentimental.\n\n sentimental\n\n sentimental'
[RL step 1150] reward=0.4766 adv=+0.0358 gamma=9.75e-05
[Step 1150] CE/token (EMA): 1.410 | Contrast[mask]: 0.000 | RL: -7.058 | Reward: 0.4766
[Step 1160] CE/token (EMA): 1.496 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1170] CE/token (EMA): 1.554 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1180] CE/token (EMA): 1.482 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1190] CE/token (EMA): 1.499 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'confident'
[RL sample] GEN: 'anxious and apprehensive.\nI'
[RL step 1200] reward=0.5078 adv=+0.0635 gamma=9.75e-05
[Step 1200] CE/token (EMA): 1.641 | Contrast[mask]: 0.000 | RL: -12.520 | Reward: 0.5078
[Step 1210] CE/token (EMA): 1.638 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1220] CE/token (EMA): 1.748 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1230] CE/token (EMA): 1.680 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1240] CE/token (EMA): 1.616 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'guilty'
[RL sample] GEN: 'guilty guilty guilty guilty guilty guilty'
[RL step 1250] reward=0.5547 adv=+0.1040 gamma=9.75e-05
[Step 1250] CE/token (EMA): 1.535 | Contrast[mask]: 0.000 | RL: -20.514 | Reward: 0.5547
[Step 1260] CE/token (EMA): 1.478 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1270] CE/token (EMA): 1.578 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1280] CE/token (EMA): 1.578 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1290] CE/token (EMA): 1.653 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'jealous'
[RL sample] GEN: 'confident and proud.\n\nI was'
[RL step 1300] reward=0.5703 adv=+0.1092 gamma=9.75e-05
[Step 1300] CE/token (EMA): 1.738 | Contrast[mask]: 0.000 | RL: -21.541 | Reward: 0.5703
[Step 1310] CE/token (EMA): 1.651 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1320] CE/token (EMA): 1.493 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1330] CE/token (EMA): 1.638 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1340] CE/token (EMA): 1.649 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'excited\n\nthinking excited\n\nthinking'
[RL step 1350] reward=0.4688 adv=-0.0033 gamma=9.75e-05
[Step 1350] CE/token (EMA): 1.631 | Contrast[mask]: 0.000 | RL: 0.645 | Reward: 0.4688
[Step 1360] CE/token (EMA): 1.523 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1370] CE/token (EMA): 1.451 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1380] CE/token (EMA): 1.494 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1390] CE/token (EMA): 1.423 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'proud'
[RL sample] GEN: 'caring for an elderly person caring'
[RL step 1400] reward=0.4609 adv=-0.0108 gamma=9.75e-05
[Step 1400] CE/token (EMA): 1.446 | Contrast[mask]: 0.000 | RL: 2.121 | Reward: 0.4609
[Step 1410] CE/token (EMA): 1.450 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1420] CE/token (EMA): 1.622 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1430] CE/token (EMA): 1.486 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1440] CE/token (EMA): 1.462 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'afraid'
[RL sample] GEN: 'afraid of death.\n\nafraid'
[RL step 1450] reward=0.4453 adv=-0.0253 gamma=9.75e-05
[Step 1450] CE/token (EMA): 1.465 | Contrast[mask]: 0.000 | RL: 4.994 | Reward: 0.4453
[Step 1460] CE/token (EMA): 1.414 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1470] CE/token (EMA): 1.319 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1480] CE/token (EMA): 1.309 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1490] CE/token (EMA): 1.389 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified, terrified, terrified. | angry and furious with my son | excited for the exciting upcoming destination | angry and furious with angry and
[ValMetric epoch 2] accuracy=0.5200 | best=0.5200 @ epoch 2
[RL sample] REF: 'annoyed'
[RL sample] GEN: 'annoyed and angry.\n\nAngry'
[RL step 1500] reward=0.6250 adv=+0.1569 gamma=9.75e-05
[Step 1500] CE/token (EMA): 1.447 | Contrast[mask]: 0.000 | RL: -30.938 | Reward: 0.6250
[Step 1510] CE/token (EMA): 1.452 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1520] CE/token (EMA): 1.434 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1530] CE/token (EMA): 1.465 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1540] CE/token (EMA): 1.352 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'joyful'
[RL sample] GEN: 'joyful and joyful.\n\nOn the'
[RL step 1550] reward=0.5625 adv=+0.0787 gamma=9.75e-05
[Step 1550] CE/token (EMA): 1.435 | Contrast[mask]: 0.000 | RL: -15.535 | Reward: 0.5625
[Step 1560] CE/token (EMA): 1.313 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1570] CE/token (EMA): 1.303 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1580] CE/token (EMA): 1.344 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1590] CE/token (EMA): 1.341 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'excited'
[RL sample] GEN: 'impressed with the game\n\nI'
[RL step 1600] reward=0.4453 adv=-0.0463 gamma=9.75e-05
[Step 1600] CE/token (EMA): 1.440 | Contrast[mask]: 0.000 | RL: 9.144 | Reward: 0.4453
[Step 1610] CE/token (EMA): 1.585 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1620] CE/token (EMA): 1.474 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1630] CE/token (EMA): 1.479 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1640] CE/token (EMA): 1.400 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'caring'
[RL sample] GEN: 'grateful\n\nWith grateful for the'
[RL step 1650] reward=0.4375 adv=-0.0495 gamma=9.75e-05
[Step 1650] CE/token (EMA): 1.284 | Contrast[mask]: 0.000 | RL: 9.765 | Reward: 0.4375
[Step 1660] CE/token (EMA): 1.291 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1670] CE/token (EMA): 1.310 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1680] CE/token (EMA): 1.358 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1690] CE/token (EMA): 1.302 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'embarrassed'
[RL sample] GEN: 'embarrassed and ashamed.\n\n embarrassed and'
[RL step 1700] reward=0.5469 adv=+0.0648 gamma=9.75e-05
[Step 1700] CE/token (EMA): 1.390 | Contrast[mask]: 0.000 | RL: -12.785 | Reward: 0.5469
[Step 1710] CE/token (EMA): 1.419 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1720] CE/token (EMA): 1.467 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1730] CE/token (EMA): 1.404 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 1740] CE/token (EMA): 1.310 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed.\n\nSad, disappointed,'

In [12]:
# ============================================================
# PREFIX-DRIFT ДИАГНОСТИКА: ||P_best - P_0|| / ||P_0|| (критика-4 §35)
# Вопрос: «вспомогательная цель не даёт сигнала» или «даёт чрезмерный
# дрейф промпта»? Считаем относительное смещение обученного промпта
# от стартового. P_0: shared_init.pt (3B-серии) или воспроизведённый
# случайный старт (0.5B-sweep). CPU-часть (3B) выполняется без
# загрузки моделей; 0.5B требует коротких загрузок (~15 с x сид).
# ============================================================
import glob

def _drift(P0, Pb):
    num = sum(float((Pb[k].float() - P0[k].float()).norm() ** 2)
              for k in P0 if k in Pb) ** 0.5
    den = sum(float(P0[k].float().norm() ** 2) for k in P0) ** 0.5
    return num / max(den, 1e-12)

DEGRAD = {("gen_d2_incoherent_d21_seed42",): "incoherent s42 (0.128)",
          ("gen_d2_mask_d21_seed48",): "mask s48 (0.136)",
          ("gen_dialogue_ed_contrast_wl_d16_seed48",): "wl s48 (0.300)"}

def group_drift(name, run_dirs, start_of):
    vals, notes = [], []
    for d in run_dirs:
        bp = os.path.join(d, "best_prefix.pt")
        P0p = start_of(d)
        if not (os.path.exists(bp) and P0p and os.path.exists(P0p)):
            continue
        P0, Pb = torch.load(P0p, map_location="cpu"), torch.load(bp, map_location="cpu")
        vals.append(_drift(P0, Pb))
        tag = DEGRAD.get((d.replace("./", ""),), DEGRAD.get((d,), ""))
        if tag:
            notes.append(f"  ! {os.path.basename(d)}: {tag} -> drift {vals[-1]:.3f}")
    if vals:
        print(f"{name:<42} {np.mean(vals):.3f} ± {np.std(vals):.3f} "
              f"(n={len(vals)})")
        for nt in notes:
            print(nt)
    return vals

results = {}

# --- D2 (3B): старт из mle-папки того же сида ---
for cfg, bdir, wave, seeds in [
        ("D2 MLE", "gen_d2_mle", "d21", range(42, 49)),
        ("D2 маска", "gen_d2_mask", "d21", range(42, 49)),
        ("D2 неуместный", "gen_d2_offtopic", "d21", range(42, 49)),
        ("D2 переставленный", "gen_d2_incoherent", "d21", range(42, 49)),
        ("D2 CE+RL", "gen_d2_rl_only", "d22", range(42, 49)),
        ("D2 GRPO", "gen_d2_grpo", "d24", (42, 43, 44))]:
    dirs = [f"{bdir}_{wave}_seed{s}" for s in seeds]
    results[cfg] = group_drift(
        cfg, dirs,
        lambda d: os.path.join(f"gen_d2_mle_d21_seed{d.split('seed')[-1]}",
                               "shared_init.pt"))

# --- D1 (3B): старт из mle-папки того же сида ---
for cfg, bdir, seeds in [
        ("D1 MLE", "gen_crl_mle_baseline_d16", range(42, 49)),
        ("D1 маска", "gen_dialogue_ed_contrast_mask_d16", range(42, 49)),
        ("D1 путаемая метка", "gen_dialogue_ed_contrast_wl_d16", range(42, 49)),
        ("D1 CE+RL", "gen_dialogue_ed_rl_only_d16", range(42, 49)),
        ("D1 полный CRL", "gen_dialogue_ed_full_crl_d16", range(42, 49))]:
    dirs = [f"{bdir}_seed{s}" for s in seeds]
    results[cfg] = group_drift(
        cfg, dirs,
        lambda d: os.path.join(f"gen_crl_mle_baseline_d16_seed{d.split('seed')[-1]}",
                               "shared_init.pt"))

# --- 0.5B×6000 (sweep): старт воспроизводится make_shared_start ---
zs_dirs = {"MLE": "MLE", "mask": "mask", "RL": "RL"}
for label, key in zs_dirs.items():
    vals = []
    for seed in sorted({r["seed"] for r in ld_rows
                        if r["model"] == "05B" and r["size"] == 6000}):
        d = f"sweep_ld/05B_{key}_s{seed}_n6000"
        bp = os.path.join(d, "best_prefix.pt")
        if not os.path.exists(bp):
            continue
        P0 = make_shared_start("Qwen/Qwen2.5-0.5B", seed)
        Pb = torch.load(bp, map_location="cpu")
        vals.append(_drift(P0, Pb))
        del P0
    if vals:
        results[f"0.5B {label}"] = vals
        print(f"{'0.5B x6000 ' + label:<42} {np.mean(vals):.3f} ± {np.std(vals):.3f} "
              f"(n={len(vals)})")

json.dump({k: [float(x) for x in v] for k, v in results.items()},
          open("sweep_ld/prefix_drift.json", "w"), indent=2)
print("\nСохранено: sweep_ld/prefix_drift.json")
print("\nИнтерпретация: деградации <-> большой дрейф? 0.5B: RL > MLE")
print("(цель реально двигает промпт)? D2 3B: одинаковый дрейф ->")
print("«нет сигнала», а не «нет движения».")

D2 MLE                                     0.275 ± 0.045 (n=7)
D2 маска                                   0.266 ± 0.047 (n=7)
  ! gen_d2_mask_d21_seed48: mask s48 (0.136) -> drift 0.296
D2 неуместный                              0.267 ± 0.051 (n=7)
D2 переставленный                          0.278 ± 0.040 (n=7)
  ! gen_d2_incoherent_d21_seed42: incoherent s42 (0.128) -> drift 0.228
D2 CE+RL                                   0.260 ± 0.042 (n=7)
D2 GRPO                                    0.281 ± 0.045 (n=3)
D1 MLE                                     0.292 ± 0.011 (n=7)
D1 маска                                   0.294 ± 0.016 (n=7)
D1 путаемая метка                          0.268 ± 0.039 (n=7)
  ! gen_dialogue_ed_contrast_wl_d16_seed48: wl s48 (0.300) -> drift 0.237
D1 CE+RL                                   0.295 ± 0.010 (n=7)
D1 полный CRL                              0.300 ± 0.010 (n=7)

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9178.53it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10050.06it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9864.47it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9208.90it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9452.65it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10182.22it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10229.58it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9269.32it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10192.80it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9277.88it/s]

0.5B x6000 MLE                             0.234 ± 0.006 (n=10)

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9975.38it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9706.87it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10609.88it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9842.28it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9831.94it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9136.00it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10261.42it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9930.75it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9843.15it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9994.23it/s]

0.5B x6000 mask                            0.231 ± 0.008 (n=10)

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10227.17it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9793.86it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10367.69it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9745.75it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9494.34it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10093.67it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10048.56it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9896.25it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10238.28it/s]
Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9767.98it/s]

0.5B x6000 RL                              0.231 ± 0.006 (n=10)

Сохранено: sweep_ld/prefix_drift.json

Интерпретация: деградации <-> большой дрейф? 0.5B: RL > MLE
(цель реально двигает промпт)? D2 3B: одинаковый дрейф ->
«нет сигнала», а не «нет движения».

In [14]:
# ============================================================
# РЕПЛИКАЦИЯ mask x 250 (сиды 52–54) — последний непроверенный
# разведочный результат (§10.3). Протокол sw_ext05b без изменений:
# общий случайный старт на сид, все 3 конфигурации (для полноты),
# все сиды в отчёт. 250 примеров -> самые быстрые прогоны (~1 мин),
# итого ~15 мин.
# ============================================================
import copy
import math
from math import sqrt, comb

REPL250_SIZE = 250

# tokenize_gen читает ГЛОБАЛЬНЫЙ cfg (ячейка данных замыкается на модуль
# ноутбука). В прошлой сессии в ядре глобальный cfg оказался затёрт
# строкой — отсюда AttributeError: 'str' object has no attribute
# 'max_total_len' на первом же map(). Восстанавливаем базовый конфиг
# свипа: значения идентичны CFG(), на числовой путь не влияет.
cfg = cfg_sweep_base

for seed in (52, 53, 54):
    if any(r["model"] == "05B" and r["seed"] == seed and r["size"] == REPL250_SIZE
           and all(k in r for k in SWEEP_CONFIGS) for r in ld_rows):
        print(f"[Resume] 05B s{seed} n=250 готов")
        continue
    shared = make_shared_start("Qwen/Qwen2.5-0.5B", seed)
    rebuild_d1_datasets(REPL250_SIZE)
    steps = math.ceil(REPL250_SIZE / cfg_sweep_base.batch_size) * \
        cfg_sweep_base.total_epochs
    row = {"model": "05B", "seed": seed, "size": REPL250_SIZE, "replication": True}
    for cname in SWEEP_CONFIGS:
        c = copy.copy(cfg_sweep_base)
        c.model_name = "Qwen/Qwen2.5-0.5B"
        c.seed = seed
        c.train_size = REPL250_SIZE
        c.init_selection_inits = 0
        c.warmup_steps = min(200, max(10, steps // 10))
        c.output_dir = f"./sweep_ld/05B_{cname}_s{seed}_n{REPL250_SIZE}"
        if cname == "MLE":
            c.beta = 0.0; c.gamma = 0.0; c.gamma_auto = False
        elif cname == "mask":
            c.beta = 0.1; c.contrast_mode = "mask"
            c.gamma = 0.0; c.gamma_auto = False
        else:
            c.beta = 0.0; c.gamma = 2e-5; c.gamma_auto = True
        rj = os.path.join(c.output_dir, "results.json")
        if os.path.exists(rj):
            with open(rj) as f:
                sc = json.load(f)["test_scores"]
        else:
            sc = run_experiment(c, f"{cname} 05B repl n={REPL250_SIZE} (s{seed})",
                                init_state=shared)
        row[cname] = sc["accuracy"]
        row[f"{cname}-verb"] = sc["verb_accuracy"]
        gc.collect(); torch.cuda.empty_cache()
    ld_rows = [r for r in ld_rows
               if not (r["model"] == "05B" and r["seed"] == seed
                       and r["size"] == REPL250_SIZE)] + [row]
    with open(_summary_ld, "w") as f:
        json.dump({"rows": ld_rows}, f, indent=2)
    print(f">>> repl 05B s{seed} n=250: "
          f"{ {k: round(row[k], 4) for k in SWEEP_CONFIGS} }\n")
    del shared
    gc.collect(); torch.cuda.empty_cache()

# ---------- агрегация n=10 ----------
rs = sorted([r for r in ld_rows if r["model"] == "05B" and r["size"] == 250],
            key=lambda r: r["seed"])
print("\n" + "=" * 88)
print(f"РЕПЛИКАЦИЯ mask x 250: n={len(rs)} сидов (42-48 исходные + 52-54)")
print("=" * 88)
for a in ("mask", "RL"):
    d = [r[a] - r["MLE"] for r in rs]
    n = len(d)
    se = np.std(d, ddof=1) / sqrt(n)
    t = np.mean(d) / se if se > 0 else float("nan")
    crit = {7: 2.447, 8: 2.365, 9: 2.306, 10: 2.262}.get(n, 2.262)  # t.975, df=n-1
    k = sum(1 for x in d if x > 0)
    nz = sum(1 for x in d if abs(x) > 1e-12)
    psign = 2 * sum(comb(nz, i) for i in range(k, nz + 1)) / 2**nz if nz else 1.0
    orig = [x for x, r in zip(d, rs) if r["seed"] <= 48]
    repl = [x for x, r in zip(d, rs) if r["seed"] >= 52]
    print(f"{a}-MLE: {np.mean(d):+.4f} ± {np.std(d, ddof=1):.4f} | "
          f"t={t:+.2f} (крит {crit}) | {k}/{n} в плюс, p_sign={psign:.4f}")
    print(f"   исходные (n={len(orig)}): {np.mean(orig):+.4f} | "
          f"репликация (n={len(repl)}): {np.mean(repl):+.4f} "
          f"{[f'{x:+.4f}' for x in repl]}")
print("\nИсход (s52-54 x 6000): CE+RL репликация была -0.006 — эффект")
print("не воспроизвёлся. Здесь последний непроверенный результат работы.")

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9548.67it/s]
Map: 100%|██████████| 250/250 [00:00<00:00, 7548.60 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 7916.62 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7705.36 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8308.49 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 05B repl n=250 (s52)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9394.46it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 11.382 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 9.715 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 7.487 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 6.100 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2750 | best=0.2750 @ epoch 1
[Step 40] CE/token (EMA): 3.782 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.390 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 2.984 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified
description: terrified | afraid
Description: afraid | excited
 Descriptor: excited | disgusted
description: disgusted
[ValMetric epoch 2] accuracy=0.3950 | best=0.3950 @ epoch 2
[Step 70] CE/token (EMA): 2.509 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.353 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.287 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified
description: terrified | afraid
Description: afraid | excited
 Descriptor: excited | disgusted disgusted disgusted disgusted disgusted disgusted
[ValMetric epoch 3] accuracy=0.3800 | best=0.3950 @ epoch 2
[Step 100] CE/token (EMA): 2.277 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 1.991 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 1.954 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified
description: terrified | terrified
Description: terrified | excited
 Descriptor: excited | disgusted disgusted disgusted disgusted disgusted disgusted
[ValMetric epoch 4] accuracy=0.3900 | best=0.3950 @ epoch 2

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3950 @ epoch 2 -> best_prefix.pt

MLE 05B repl n=250 (s52) completed in 0.4 min
Loaded best adapter: val accuracy=0.3950 @ epoch 2 (история: [0.275, 0.395, 0.38, 0.39])

Evaluating MLE 05B repl n=250 (s52) on test set (clean protocol)...

======================================================================
RESULTS: MLE 05B repl n=250 (s52)
======================================================================
accuracy: 0.3880
verb_accuracy: 0.4180
======================================================================

Примеры ошибок (ref -> pred | генерация):
  guilty         -> annoyed        | 'annoyed\ndescription: annoyed'
  caring         -> None           | 'very hungry_comma_ and'
  lonely         -> None           | 'empty\n\nThe answer is:'
  excited        -> None           | 'expecting a present\nHypo'
  caring         -> hopeful        | 'hopeful\n Descriptor: hopeful'
  angry          -> guilty         | 'guilty\n Descriptor: guilty'
Results saved to ./sweep_ld/05B_MLE_s52_n250/results.json

======================================================================
STARTING EXPERIMENT: mask 05B repl n=250 (s52)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9186.71it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 11.382 | Contrast[mask]: 0.690 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 9.702 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 7.477 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 6.098 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2750 | best=0.2750 @ epoch 1
[Step 40] CE/token (EMA): 3.803 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.429 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.010 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified

the situation: i | afraid
Description: afraid | excited
 Descriptor: excited | disgusted disgusted disgusted disgusted disgusted disgusted
[ValMetric epoch 2] accuracy=0.3700 | best=0.3700 @ epoch 2
[Step 70] CE/token (EMA): 2.486 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.339 | Contrast[mask]: 0.675 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.299 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified
description: terrified | afraid
Description: afraid | excited
 Descriptor: excited | disgusted disgusted disgusted disgusted disgusted disgusted
[ValMetric epoch 3] accuracy=0.3850 | best=0.3850 @ epoch 3
[Step 100] CE/token (EMA): 2.282 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.017 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 1.977 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified
description: terrified | afraid
Description: afraid | excited
 Descriptor: excited | disgusted disgusted disgusted disgusted disgusted disgusted
[ValMetric epoch 4] accuracy=0.3650 | best=0.3850 @ epoch 3

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3850 @ epoch 3 -> best_prefix.pt

mask 05B repl n=250 (s52) completed in 0.5 min
Loaded best adapter: val accuracy=0.3850 @ epoch 3 (история: [0.275, 0.37, 0.385, 0.365])

Evaluating mask 05B repl n=250 (s52) on test set (clean protocol)...

======================================================================
RESULTS: mask 05B repl n=250 (s52)
======================================================================
accuracy: 0.3760
verb_accuracy: 0.4000
======================================================================

Примеры ошибок (ref -> pred | генерация):
  caring         -> afraid         | 'hungry and they were afraid_co'
  lonely         -> None           | 'empty\n\ndescribing the emotiona'
  excited        -> None           | 'expecting a present\nHypo'
  caring         -> sad            | 'sad\nanticipating sad'
  angry          -> guilty         | 'guilty\nanticipating guilty'
  joyful         -> anticipating   | 'anticipating a happy reunion\nD'
Results saved to ./sweep_ld/05B_mask_s52_n250/results.json

======================================================================
STARTING EXPERIMENT: RL 05B repl n=250 (s52)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 10130.92it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 2.160e-04
[RL sample] REF: 'prepared'
[RL sample] GEN: 'Happiness\nSobibof'
[RL step 0] reward=0.0078 adv=+0.0078 gamma=2.16e-04
[Step 0] CE/token (EMA): 11.382 | Contrast[mask]: 0.000 | RL: -3.415 | Reward: 0.0078

[Step 10] CE/token (EMA): 9.709 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 7.487 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 6.104 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2750 | best=0.2750 @ epoch 1
[Step 40] CE/token (EMA): 3.803 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'comfortable\nAdaptive or not'
[RL step 50] reward=0.3281 adv=+0.3273 gamma=2.16e-04
[Step 50] CE/token (EMA): 3.403 | Contrast[mask]: 0.000 | RL: -143.029 | Reward: 0.3281
[Step 60] CE/token (EMA): 2.992 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified
description: terrified | afraid
Description: afraid | excited
 Descriptor: excited | disgusted

the disgusted
the
[ValMetric epoch 2] accuracy=0.3750 | best=0.3750 @ epoch 2
[Step 70] CE/token (EMA): 2.520 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.348 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.275 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified
description: terrified | terrified
Description: the child | excited
 Descriptor: excited | disgusted disgusted disgusted disgusted disgusted disgusted
[ValMetric epoch 3] accuracy=0.3750 | best=0.3750 @ epoch 2
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed\n\nconsistent\ngiving'
[RL step 100] reward=0.4531 adv=+0.4196 gamma=2.16e-04
[Step 100] CE/token (EMA): 2.279 | Contrast[mask]: 0.000 | RL: -183.465 | Reward: 0.4531
[Step 110] CE/token (EMA): 1.991 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 1.944 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified
description: terrified | terrified
Description: the scene | excited
 Descriptor: excited | disgusted

the disgusted
the
[ValMetric epoch 4] accuracy=0.3700 | best=0.3750 @ epoch 2

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3750 @ epoch 2 -> best_prefix.pt

RL 05B repl n=250 (s52) completed in 0.5 min
Loaded best adapter: val accuracy=0.3750 @ epoch 2 (история: [0.275, 0.375, 0.375, 0.37])

Evaluating RL 05B repl n=250 (s52) on test set (clean protocol)...

======================================================================
RESULTS: RL 05B repl n=250 (s52)
======================================================================
accuracy: 0.3840
verb_accuracy: 0.4040
======================================================================

Примеры ошибок (ref -> pred | генерация):
  caring         -> None           | 'hungry_comma_ and they'
  lonely         -> None           | 'empty\nHerself:'
  excited        -> None           | 'expecting a present\nHers'
  caring         -> hopeful        | 'hopeful\n Descriptor: hopeful'
  joyful         -> anticipating   | 'anticipating a happy and joyfu'
  angry          -> furious        | 'furious\ndescription: furious'
Results saved to ./sweep_ld/05B_RL_s52_n250/results.json
>>> repl 05B s52 n=250: {'MLE': 0.388, 'mask': 0.376, 'RL': 0.384}

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9927.10it/s]
Map: 100%|██████████| 250/250 [00:00<00:00, 7323.28 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 8010.05 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7814.49 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8406.32 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 05B repl n=250 (s53)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9485.90it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 10.408 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 9.373 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 7.325 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.862 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2900 | best=0.2900 @ epoch 1
[Step 40] CE/token (EMA): 3.686 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.276 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.130 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified.

What is something that | terrified

Hoping to be | excited

the feelings of excitement | surprised

The feeling of surprise
[ValMetric epoch 2] accuracy=0.3400 | best=0.3400 @ epoch 2
[Step 70] CE/token (EMA): 2.584 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.380 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.323 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified.

Please and terrified. | terrified

Hoping my son | excited.

the feelings of excitement | embarrassed
Numb, embarrassed
[ValMetric epoch 3] accuracy=0.3650 | best=0.3650 @ epoch 3
[Step 100] CE/token (EMA): 2.254 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.171 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.013 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified.

Please and terrified. | terrified
narrweaves | excited

in the excitement of | embarrassed
Numb, embarrassed
[ValMetric epoch 4] accuracy=0.3700 | best=0.3700 @ epoch 4

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3700 @ epoch 4 -> best_prefix.pt

MLE 05B repl n=250 (s53) completed in 0.4 min
Loaded best adapter: val accuracy=0.3700 @ epoch 4 (история: [0.29, 0.34, 0.365, 0.37])

Evaluating MLE 05B repl n=250 (s53) on test set (clean protocol)...

======================================================================
RESULTS: MLE 05B repl n=250 (s53)
======================================================================
accuracy: 0.3780
verb_accuracy: 0.4060
======================================================================

Примеры ошибок (ref -> pred | генерация):
  guilty         -> afraid         | 'afraid.\n\nhorrific'
  caring         -> None           | 'in a state of hunger.'
  lonely         -> None           | 'empty\n\nThe feeling of being'
  excited        -> joyful         | 'joyful anticipation.\nperceivin'
  sad            -> afraid         | 'afraid of the unknown\n1'
  caring         -> sad            | "sad\n\nthe friend's friend"
Results saved to ./sweep_ld/05B_MLE_s53_n250/results.json

======================================================================
STARTING EXPERIMENT: mask 05B repl n=250 (s53)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9667.98it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 10.408 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 9.369 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 7.326 | Contrast[mask]: 0.678 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.870 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2900 | best=0.2900 @ epoch 1
[Step 40] CE/token (EMA): 3.689 | Contrast[mask]: 0.687 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.294 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.185 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified.

Hoping to be | terrified.

What is the most | excited.

the feelings of excitement | surprised surprised surprised surprised surprised surprised
[ValMetric epoch 2] accuracy=0.3350 | best=0.3350 @ epoch 2
[Step 70] CE/token (EMA): 2.686 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.477 | Contrast[mask]: 0.680 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.401 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified.

Based on the description | terrified.

Based on the description | excited.

the feelings of excitement | annoyed.
12- to
[ValMetric epoch 3] accuracy=0.3500 | best=0.3500 @ epoch 3
[Step 100] CE/token (EMA): 2.319 | Contrast[mask]: 0.677 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.205 | Contrast[mask]: 0.679 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.053 | Contrast[mask]: 0.676 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified.

Based on the text | terrified.

Based on the description | excited.

the feelings of excitement | annoyed.
12- to
[ValMetric epoch 4] accuracy=0.3750 | best=0.3750 @ epoch 4

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3750 @ epoch 4 -> best_prefix.pt

mask 05B repl n=250 (s53) completed in 0.5 min
Loaded best adapter: val accuracy=0.3750 @ epoch 4 (история: [0.29, 0.335, 0.35, 0.375])

Evaluating mask 05B repl n=250 (s53) on test set (clean protocol)...

======================================================================
RESULTS: mask 05B repl n=250 (s53)
======================================================================
accuracy: 0.3640
verb_accuracy: 0.4000
======================================================================

Примеры ошибок (ref -> pred | генерация):
  guilty         -> jealous        | 'jealous. The jealous.\n\nWhat'
  caring         -> None           | 'hungry. Comma_ and'
  lonely         -> None           | 'empty\n\nBased on the descriptio'
  excited        -> joyful         | 'joyful anticipation.\nDescripti'
  sad            -> afraid         | 'afraid of the unknown\ndescript'
  caring         -> sad            | 'sad\n\nthe sad, disappointed'
Results saved to ./sweep_ld/05B_mask_s53_n250/results.json

======================================================================
STARTING EXPERIMENT: RL 05B repl n=250 (s53)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9454.41it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 3.949e-05
[RL sample] REF: 'prepared'
[RL sample] GEN: '14\n 8'
[RL step 0] reward=0.0391 adv=+0.0391 gamma=3.95e-05
[Step 0] CE/token (EMA): 10.408 | Contrast[mask]: 0.000 | RL: -3.122 | Reward: 0.0391

[Step 10] CE/token (EMA): 9.376 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 7.322 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 5.868 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2800 | best=0.2800 @ epoch 1
[Step 40] CE/token (EMA): 3.693 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'comfortable\n \nnarrwe'
[RL step 50] reward=0.3906 adv=+0.3867 gamma=3.95e-05
[Step 50] CE/token (EMA): 3.298 | Contrast[mask]: 0.000 | RL: -30.911 | Reward: 0.3906
[Step 60] CE/token (EMA): 3.132 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified

frantic

fr | terrified
narrweas | excited.

the feelings of excitement | surprised

the surprise surprised
[ValMetric epoch 2] accuracy=0.3500 | best=0.3500 @ epoch 2
[Step 70] CE/token (EMA): 2.614 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.430 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.359 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified.

initials: i | terrified
narrweas | excited

the excitement of the | disgusted

The way the disgusted
[ValMetric epoch 3] accuracy=0.3450 | best=0.3500 @ epoch 2
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'disappointed.\n\nclothes: disappointed'
[RL step 100] reward=0.4844 adv=+0.4418 gamma=3.95e-05
[Step 100] CE/token (EMA): 2.280 | Contrast[mask]: 0.000 | RL: -35.296 | Reward: 0.4844
[Step 110] CE/token (EMA): 2.182 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 2.032 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified.

Hoping to be | terrified
narrate the | excited

in the excitement of | scared

The way the scared
[ValMetric epoch 4] accuracy=0.3700 | best=0.3700 @ epoch 4

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3700 @ epoch 4 -> best_prefix.pt

RL 05B repl n=250 (s53) completed in 0.5 min
Loaded best adapter: val accuracy=0.3700 @ epoch 4 (история: [0.28, 0.35, 0.345, 0.37])

Evaluating RL 05B repl n=250 (s53) on test set (clean protocol)...

======================================================================
RESULTS: RL 05B repl n=250 (s53)
======================================================================
accuracy: 0.3700
verb_accuracy: 0.3980
======================================================================

Примеры ошибок (ref -> pred | генерация):
  guilty         -> afraid         | "afraid.\n\nHow does one's"
  caring         -> None           | 'in a state of hunger.'
  lonely         -> None           | 'empty\n\nThe feeling of being'
  excited        -> joyful         | 'joyful anticipation\nConceiving'
  sad            -> afraid         | 'afraid of the unknown\nDescript'
  caring         -> sad            | 'sad\n\nfriendly, sad'
Results saved to ./sweep_ld/05B_RL_s53_n250/results.json
>>> repl 05B s53 n=250: {'MLE': 0.378, 'mask': 0.364, 'RL': 0.37}

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9179.43it/s]
Map: 100%|██████████| 250/250 [00:00<00:00, 7615.48 examples/s]
Map: 100%|██████████| 200/200 [00:00<00:00, 7893.82 examples/s]
Map: 100%|██████████| 500/500 [00:00<00:00, 7753.62 examples/s]
Map: 100%|██████████| 600/600 [00:00<00:00, 8421.00 examples/s]

======================================================================
STARTING EXPERIMENT: MLE 05B repl n=250 (s54)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9507.33it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[Step 0] CE/token (EMA): 10.793 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 10.007 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 7.845 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 6.139 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2850 | best=0.2850 @ epoch 1
[Step 40] CE/token (EMA): 3.633 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.351 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.098 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified
fill in the blank | terrified.
description: terrified | excited.

The situation: I | scared

The situation: I
[ValMetric epoch 2] accuracy=0.3350 | best=0.3350 @ epoch 2
[Step 70] CE/token (EMA): 2.645 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.473 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.266 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified
R1: terrified | terrified.
to see my son | excited.

- excited
- | scared

The situation: I
[ValMetric epoch 3] accuracy=0.3500 | best=0.3500 @ epoch 3
[Step 100] CE/token (EMA): 2.297 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.079 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 1.898 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified

  • terrified | terrified.
to see my son | excited.

- excited (w | scared

The situation: I
[ValMetric epoch 4] accuracy=0.3600 | best=0.3600 @ epoch 4

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3600 @ epoch 4 -> best_prefix.pt

MLE 05B repl n=250 (s54) completed in 0.4 min
Loaded best adapter: val accuracy=0.3600 @ epoch 4 (история: [0.285, 0.335, 0.35, 0.36])

Evaluating MLE 05B repl n=250 (s54) on test set (clean protocol)...

======================================================================
RESULTS: MLE 05B repl n=250 (s54)
======================================================================
accuracy: 0.3980
verb_accuracy: 0.4300
======================================================================

Примеры ошибок (ref -> pred | генерация):
  caring         -> None           | 'in the process of dying.'
  excited        -> None           | 'expecting\ndesponding'
  sad            -> afraid         | 'afraid\nnarrator:'
  caring         -> hopeful        | 'hopeful\ncontemplating'
  angry          -> guilty         | 'guilty\ncontemplating the'
  joyful         -> anticipating   | 'anticipating\nNurturing'
Results saved to ./sweep_ld/05B_MLE_s54_n250/results.json

======================================================================
STARTING EXPERIMENT: mask 05B repl n=250 (s54)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9583.13it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.1
[Step 0] CE/token (EMA): 10.793 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000

[Step 10] CE/token (EMA): 10.005 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 7.847 | Contrast[mask]: 0.689 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 6.129 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2850 | best=0.2850 @ epoch 1
[Step 40] CE/token (EMA): 3.740 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Step 50] CE/token (EMA): 3.425 | Contrast[mask]: 0.682 | RL: 0.000 | Reward: 0.0000
[Step 60] CE/token (EMA): 3.135 | Contrast[mask]: 0.688 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified
contemplate
poss | terrified
description: terrified | excited

desires: anxious | terrified
description: terrified
[ValMetric epoch 2] accuracy=0.3250 | best=0.3250 @ epoch 2
[Step 70] CE/token (EMA): 2.637 | Contrast[mask]: 0.685 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.479 | Contrast[mask]: 0.683 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.318 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified
  1. | terrified
herself | excited

desires: excited | terrified
  (in the
[ValMetric epoch 3] accuracy=0.3700 | best=0.3700 @ epoch 3
[Step 100] CE/token (EMA): 2.337 | Contrast[mask]: 0.686 | RL: 0.000 | Reward: 0.0000
[Step 110] CE/token (EMA): 2.117 | Contrast[mask]: 0.684 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 1.955 | Contrast[mask]: 0.681 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified
  1. | terrified
herself | excited

desires: excited | terrified
  (in the
[ValMetric epoch 4] accuracy=0.3600 | best=0.3700 @ epoch 3

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3700 @ epoch 3 -> best_prefix.pt

mask 05B repl n=250 (s54) completed in 0.5 min
Loaded best adapter: val accuracy=0.3700 @ epoch 3 (история: [0.285, 0.325, 0.37, 0.36])

Evaluating mask 05B repl n=250 (s54) on test set (clean protocol)...

======================================================================
RESULTS: mask 05B repl n=250 (s54)
======================================================================
accuracy: 0.3920
verb_accuracy: 0.4140
======================================================================

Примеры ошибок (ref -> pred | генерация):
  caring         -> None           | 'in the process of being abando'
  excited        -> None           | 'expecting the concert tickets '
  sad            -> afraid         | 'afraid\nnarrator:'
  caring         -> hopeful        | 'hopeful\nnurturing'
  angry          -> guilty         | 'guilty\n  (or terrified'
  joyful         -> anticipating   | 'anticipating the future.\n\ndesc'
Results saved to ./sweep_ld/05B_mask_s54_n250/results.json

======================================================================
STARTING EXPERIMENT: RL 05B repl n=250 (s54)
======================================================================

Loading weights: 100%|██████████| 290/290 [00:00<00:00, 9489.01it/s]

[PairedStart] загружен ОБЩИЙ старт (5 тензоров префикса) — probe пропущен

Trainable parameters:
trainable params: 811,648 || all params: 494,844,416 || trainable%: 0.1640
[Trainer] Prefix params collected: 5
[Trainer] Contrast: mode=mask, from_start=True, beta=0.0
[RL] gamma auto-calibrated to 1.024e-04
[RL sample] REF: 'prepared'
[RL sample] GEN: '1.64'
[RL step 0] reward=0.0156 adv=+0.0156 gamma=1.02e-04
[Step 0] CE/token (EMA): 10.793 | Contrast[mask]: 0.000 | RL: -3.238 | Reward: 0.0156

[Step 10] CE/token (EMA): 10.004 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 20] CE/token (EMA): 7.847 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 30] CE/token (EMA): 6.143 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[ValMetric epoch 1] accuracy=0.2800 | best=0.2800 @ epoch 1
[Step 40] CE/token (EMA): 3.654 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[RL sample] REF: 'content'
[RL sample] GEN: 'comfortable.\nbelief: I have'
[RL step 50] reward=0.3906 adv=+0.3891 gamma=1.02e-04
[Step 50] CE/token (EMA): 3.382 | Contrast[mask]: 0.000 | RL: -80.641 | Reward: 0.3906
[Step 60] CE/token (EMA): 3.125 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 2] terrified.
Fill in the blank | terrified. 201 | excited.

in the situation, | scared
to gushing
[ValMetric epoch 2] accuracy=0.3150 | best=0.3150 @ epoch 2
[Step 70] CE/token (EMA): 2.645 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 80] CE/token (EMA): 2.488 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 90] CE/token (EMA): 2.297 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 3] terrified. terrified.

create a | terrified. anxious. afraid. | excited.

• filled with anticipation | terrified. The face of terror
[ValMetric epoch 3] accuracy=0.3500 | best=0.3500 @ epoch 3
[RL sample] REF: 'disappointed'
[RL sample] GEN: 'sad.\n\nmaking a sad face'
[RL step 100] reward=0.4766 adv=+0.4361 gamma=1.02e-04
[Step 100] CE/token (EMA): 2.436 | Contrast[mask]: 0.000 | RL: -90.399 | Reward: 0.4766
[Step 110] CE/token (EMA): 2.176 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Step 120] CE/token (EMA): 1.975 | Contrast[mask]: 0.000 | RL: 0.000 | Reward: 0.0000
[Canary epoch 4] terrified.

on the inside, | terrified. anxious. afraid. | excited.

• filled with anticipation | terrified. The face of terror
[ValMetric epoch 4] accuracy=0.3500 | best=0.3500 @ epoch 3

[Phase 2] LR reset to 0.0001, new cosine over remaining 1 steps

[ValMetric] Итог: best accuracy=0.3500 @ epoch 3 -> best_prefix.pt

RL 05B repl n=250 (s54) completed in 0.5 min
Loaded best adapter: val accuracy=0.3500 @ epoch 3 (история: [0.28, 0.315, 0.35, 0.35])

Evaluating RL 05B repl n=250 (s54) on test set (clean protocol)...

======================================================================
RESULTS: RL 05B repl n=250 (s54)
======================================================================
accuracy: 0.3760
verb_accuracy: 0.4040
======================================================================

Примеры ошибок (ref -> pred | генерация):
  caring         -> None           | 'in the process of dying.'
  lonely         -> sad            | 'sad\nto feel empty'
  excited        -> surprised      | 'surprised.\n\nAssistant in antic'
  sad            -> afraid         | "afraid\nnarrator's"
  caring         -> hopeful        | 'hopeful\nnurturing'
  angry          -> terrified      | 'terrified\n\nattaching to the'
Results saved to ./sweep_ld/05B_RL_s54_n250/results.json
>>> repl 05B s54 n=250: {'MLE': 0.398, 'mask': 0.392, 'RL': 0.376}


========================================================================================
РЕПЛИКАЦИЯ mask x 250: n=10 сидов (42-48 исходные + 52-54)
========================================================================================
mask-MLE: +0.0054 ± 0.0138 | t=+1.24 (крит 2.262) | 7/10 в плюс, p_sign=0.3438
   исходные (n=7): +0.0123 | репликация (n=3): -0.0107 ['-0.0120', '-0.0140', '-0.0060']
RL-MLE: +0.0044 ± 0.0183 | t=+0.76 (крит 2.262) | 5/10 в плюс, p_sign=1.0000
   исходные (n=7): +0.0111 | репликация (n=3): -0.0113 ['-0.0040', '-0.0080', '-0.0220']

Исход (s52-54 x 6000): CE+RL репликация была -0.006 — эффект
не воспроизвёлся. Здесь последний непроверенный результат работы.